/* Generated by tools/ida_headstart.py -- Hex-Rays (IDA Pro 9.4) pseudocode.
 *
 * REFERENCE ONLY. This is not valid C and is never compiled: IDA's pseudo
 * types (__int64, _DWORD, _$F0 register aliases) are not MWCC input, and a
 * raw `__asm { ... }` block below is Hex-Rays declining to model an Emotion
 * Engine instruction it does not understand (FPU multiply-accumulate chains,
 * or a rare single op like mfthc1/pcpyld). Everything else in a function
 * usually decompiles correctly -- control flow, hardware MMIO addresses
 * (rendered as MEMORY[0x...]), struct layout. Translate an asm island by
 * hand using the measured b210 rules in docs/matching.md; do not guess.
 *
 * Regenerate: python3 tools/ida_headstart.py --report <verify.json>
 */

// func_00105010  addr 0x00105010  window 400B
__int64 __usercall sub_105010@<$v0>(__int64 a1@<$a0>, float a2@<$f12>)
{
  __int16 v7; // $s1
  __int64 v8; // $a1
  __int64 i; // $s0
  __int64 result; // $v0

  __asm
  {
    sq      $s2, 0x40+var_10($sp)
    sq      $s1, 0x40+var_20($sp)
    sq      $s0, 0x40+var_30($sp)
  }
  v7 = *((_WORD *)dword_7973F4 + (__int16)a1);
  LODWORD(v8) = 0;
  for ( i = 0; i < 5; i = (int)i + 1 )
  {
    v8 = (__int16)sub_246A50(a1, (__int16)(i + 1));
    if ( v7 < v8 )
      break;
    v7 -= v8;
  }
  if ( i >= 5 )
    LOWORD(i) = 4;
  result = (__int16)(int)(float)(100.0
                               * (float)((float)(100
                                               * (__int16)(100 * (i + 1)
                                                         + (int)(float)((float)(100 * v7) / (float)(int)v8)))
                                       / a2));
  __asm
  {
    lq      $s2, 0x40+var_10($sp)
    lq      $s1, 0x40+var_20($sp)
    lq      $s0, 0x40+var_30($sp)
  }
  return result;
}


// func_00105a50  addr 0x00105a50  window 576B
__int64 __fastcall sub_105A50(unsigned __int16 a1)
{
  __int64 v5; // $s0
  __int64 v6; // $v0
  __int64 v7; // $s2
  char v8; // $a1
  unsigned __int8 i; // $a2
  char v10; // $v0
  __int64 result; // $v0
  __int64 v12; // $v0
  __int64 v13; // $s2
  char v14; // $a1
  unsigned __int8 j; // $a2
  char v16; // $v0
  int v17; // $s2
  int v18; // $v0
  __int64 v19; // $s0

  __asm
  {
    sq      $s2, 0x30+var_10($sp)
    sq      $s1, 0x30+var_20($sp)
    sq      $s0, 0x30+var_30($sp)
  }
  v5 = (__int16)a1;
  if ( a1 == 1 )
  {
    v6 = dword_797400;
  }
  else
  {
    v7 = sub_10A900(a1);
    if ( v7 == 0 )
      nullsub_8((unsigned int)aGDataC, 440);
    v6 = sub_109430(v7);
  }
  v8 = 0;
  for ( i = 0; i < 0x63uLL; ++i )
  {
    if ( v6 < dword_5DD6E0[i] )
    {
      v10 = v8;
      goto LABEL_12;
    }
    ++v8;
  }
  v10 = 99;
LABEL_12:
  if ( v10 == 99 )
  {
    result = 0;
  }
  else
  {
    if ( v5 == 1 )
    {
      v12 = dword_797400;
    }
    else
    {
      v13 = sub_10A900(a1);
      if ( v13 == 0 )
        nullsub_8((unsigned int)aGDataC, 440);
      v12 = sub_109430(v13);
    }
    v14 = 0;
    for ( j = 0; j < 0x63uLL; ++j )
    {
      if ( v12 < dword_5DD6E0[j] )
      {
        v16 = v14;
        goto LABEL_25;
      }
      ++v14;
    }
    v16 = 99;
LABEL_25:
    v17 = dword_5DD6DC[(unsigned __int8)(v16 + 1)];
    if ( v5 == 1 )
    {
      v18 = dword_797400;
    }
    else
    {
      v19 = sub_10A900(a1);
      if ( v19 == 0 )
        nullsub_8((unsigned int)aGDataC, 440);
      v18 = sub_109430(v19);
    }
    result = v17 - v18;
  }
  __asm
  {
    lq      $s2, 0x30+var_10($sp)
    lq      $s1, 0x30+var_20($sp)
    lq      $s0, 0x30+var_30($sp)
  }
  return result;
}


// func_0010d7c0  addr 0x0010d7c0  window 3920B
__int64 __fastcall sub_10D7C0(int a1, _DWORD *a2, __int64 a3)
{
  int v11; // $gp
  __int64 v12; // $ra
  int *v15; // $a0
  __int64 v16; // $s2
  unsigned __int64 i; // $a1
  unsigned __int64 j; // $a1
  _DWORD *v19; // $v1
  char v20; // $a1
  unsigned __int8 k; // $a2
  char v22; // $v0
  unsigned __int8 v23; // $a1
  unsigned __int64 m; // $a0
  __int64 v25; // $s1
  int v26; // $s0
  __int64 v27; // $s1
  int v28; // $s3
  __int64 v29; // $s0
  __int64 v30; // $v0
  __int64 v31; // $s1
  int v32; // $s0
  unsigned __int64 n; // $s5
  int v34; // $s3
  unsigned __int64 ii; // $a1
  __int64 result; // $v0
  _QWORD v45[2]; // [sp+0h] [-E0h] BYREF
  __int64 v53; // [sp+80h] [-60h]
  int v54; // [sp+9Ch] [-44h] BYREF
  _WORD v55[2]; // [sp+A0h] [-40h] BYREF
  int v56; // [sp+A4h] [-3Ch]
  char v57; // [sp+A8h] [-38h]
  char v58; // [sp+A9h] [-37h]
  char v59; // [sp+AAh] [-36h]
  char v60; // [sp+D0h] [-10h]
  char v61; // [sp+D1h] [-Fh]
  __int16 v62; // [sp+D2h] [-Eh]
  int v63; // [sp+D4h] [-Ch] BYREF
  int v64; // [sp+D8h] [-8h] BYREF
  char v65; // [sp+DFh] [-1h] BYREF

  v53 = v12;
  __asm
  {
    sq      $s7, 0xE0+var_70($sp)
    sq      $s6, 0xE0+var_80($sp)
    sq      $s5, 0xE0+var_90($sp)
    sq      $s4, 0xE0+var_A0($sp)
    sq      $s3, 0xE0+var_B0($sp)
    sq      $s2, 0xE0+var_C0($sp)
    sq      $s1, 0xE0+var_D0($sp)
    sq      $s0, 0xE0+var_E0($sp)
  }
  v54 = a1;
  v15 = *(int **)(v11 - 25168);
  dword_79B698 = *v15;
  dword_79B69C = v15[1];
  dword_79B6A0 = sub_15A160();
  nullsub_7((unsigned int)aGDataC, 1825);
  v16 = dword_8873F4(1, 172032, 0x40000);
  v64 = 0;
  sub_43F810(v16, (int)&v54, 4);
  v56 = *(_DWORD *)(v11 - 20068);
  dword_79B67C = v56;
  v55[0] = word_797B7A;
  v55[1] = (unsigned __int8)byte_797B7C;
  for ( i = 0; i < 0x12; i = (int)i + 1 )
    *((_BYTE *)&v45[21] + i + 4) = *((_BYTE *)dword_7973A0 + i);
  for ( j = 0; j < 0x12; j = (int)j + 1 )
    *((_BYTE *)&v45[23] + j + 6) = *((_BYTE *)&dword_7973A0[4] + j + 2);
  v19 = *(_DWORD **)(v11 - 25168);
  v60 = *v19;
  v61 = v19[1];
  v20 = 0;
  for ( k = 0; k < 0x63uLL; ++k )
  {
    if ( dword_797400 < (__int64)dword_5DD6E0[k] )
    {
      v22 = v20;
      goto LABEL_13;
    }
    ++v20;
  }
  v22 = 99;
LABEL_13:
  v57 = v22;
  v59 = sub_110460(dword_797400);
  if ( (dword_79B3CC & 0x10000LL) != 0 )
  {
    v58 = 0;
  }
  else if ( (dword_79B3CC & 0x20000) != 0 )
  {
    v58 = 2;
  }
  else
  {
    v58 = 1;
  }
  v23 = 0;
  for ( m = 0; m < 0x32; m = (int)m + 1 )
    v23 += *((_BYTE *)v55 + m);
  v62 = v23;
  sub_43F810((int)v16 + 4, (int)v55, 52);
  v64 = 1;
  sub_43F810((int)v16 + 56, (int)&v64, 4);
  v63 = 36;
  sub_43F810((int)v16 + 60, (int)&v63, 4);
  sub_43F810((int)v16 + 64, (unsigned int)dword_7973A0, 36);
  v64 = 2;
  sub_43F810((int)v16 + 100, (int)&v64, 4);
  v63 = 72;
  sub_43F810((int)v16 + 104, (int)&v63, 4);
  sub_43F810((int)v16 + 108, (unsigned int)&dword_7973C4, 72);
  v64 = 3;
  sub_43F810((int)v16 + 180, (int)&v64, 4);
  v63 = 344;
  sub_43F810((int)v16 + 184, (int)&v63, 4);
  sub_43F810((int)v16 + 188, (unsigned int)&word_79740C, 344);
  v64 = 4;
  sub_43F810((int)v16 + 532, (int)&v64, 4);
  v63 = 16;
  sub_43F810((int)v16 + 536, (int)&v63, 4);
  sub_43F810((int)v16 + 540, (unsigned int)dword_797564, 16);
  v64 = 5;
  sub_43F810((int)v16 + 556, (int)&v64, 4);
  v63 = 6;
  sub_43F810((int)v16 + 560, (int)&v63, 4);
  sub_43F810((int)v16 + 564, (unsigned int)&dword_797574, 6);
  v64 = 6;
  sub_43F810((int)v16 + 570, (int)&v64, 4);
  v63 = 1536;
  sub_43F810((int)v16 + 574, (int)&v63, 4);
  sub_43F810((int)v16 + 578, (unsigned int)&word_79757A, 1536);
  v64 = 8;
  sub_43F810((int)v16 + 2114, (int)&v64, 4);
  v63 = 2;
  sub_43F810((int)v16 + 2118, (int)&v63, 4);
  sub_43F810((int)v16 + 2122, (unsigned int)&word_797B7A, 2);
  v64 = 9;
  sub_43F810((int)v16 + 2124, (int)&v64, 4);
  v63 = 1;
  sub_43F810((int)v16 + 2128, (int)&v63, 4);
  sub_43F810((int)v16 + 2132, (unsigned int)&byte_797B7C, 1);
  v64 = 10;
  sub_43F810((int)v16 + 2133, (int)&v64, 4);
  v63 = 4;
  sub_43F810((int)v16 + 2137, (int)&v63, 4);
  sub_43F810((int)v16 + 2141, (unsigned int)&dword_797B80, 4);
  v64 = 11;
  sub_43F810((int)v16 + 2145, (int)&v64, 4);
  v63 = 2;
  sub_43F810((int)v16 + 2149, (int)&v63, 4);
  sub_43F810((int)v16 + 2153, (unsigned int)&word_797B84, 2);
  v64 = 12;
  sub_43F810((int)v16 + 2155, (int)&v64, 4);
  v63 = 1;
  sub_43F810((int)v16 + 2159, (int)&v63, 4);
  sub_43F810((int)v16 + 2163, (unsigned int)&byte_797B86, 1);
  v64 = 13;
  sub_43F810((int)v16 + 2164, (int)&v64, 4);
  v63 = 1024;
  sub_43F810((int)v16 + 2168, (int)&v63, 4);
  sub_43F810((int)v16 + 2172, (unsigned int)&byte_797B87, 1024);
  v64 = 14;
  sub_43F810((int)v16 + 3196, (int)&v64, 4);
  v63 = 2;
  sub_43F810((int)v16 + 3200, (int)&v63, 4);
  sub_43F810((int)v16 + 3204, (unsigned int)&word_797F88, 2);
  v64 = 15;
  sub_43F810((int)v16 + 3206, (int)&v64, 4);
  v63 = 576;
  sub_43F810((int)v16 + 3210, (int)&v63, 4);
  sub_43F810((int)v16 + 3214, (unsigned int)byte_797F8C, 576);
  v64 = 16;
  sub_43F810((int)v16 + 3790, (int)&v64, 4);
  v63 = 12288;
  sub_43F810((int)v16 + 3794, (int)&v63, 4);
  sub_43F810((int)v16 + 3798, (unsigned int)dword_7981CC, 12288);
  v64 = 17;
  sub_43F810((int)v16 + 16086, (int)&v64, 4);
  v63 = 704;
  sub_43F810((int)v16 + 16090, (int)&v63, 4);
  sub_43F810((int)v16 + 16094, (unsigned int)dword_79B1CC, 704);
  v64 = 18;
  sub_43F810((int)v16 + 16798, (int)&v64, 4);
  v63 = 4;
  sub_43F810((int)v16 + 16802, (int)&v63, 4);
  sub_43F810((int)v16 + 16806, (unsigned int)&dword_79B68C, 4);
  v64 = 19;
  sub_43F810((int)v16 + 16810, (int)&v64, 4);
  v63 = 8;
  sub_43F810((int)v16 + 16814, (int)&v63, 4);
  sub_43F810((int)v16 + 16818, (unsigned int)dword_79B690, 8);
  v64 = 21;
  sub_43F810((int)v16 + 16826, (int)&v64, 4);
  v63 = 4;
  sub_43F810((int)v16 + 16830, (int)&v63, 4);
  sub_43F810((int)v16 + 16834, (unsigned int)&dword_79B698, 4);
  v64 = 22;
  sub_43F810((int)v16 + 16838, (int)&v64, 4);
  v63 = 4;
  sub_43F810((int)v16 + 16842, (int)&v63, 4);
  sub_43F810((int)v16 + 16846, (unsigned int)&dword_79B69C, 4);
  v64 = 23;
  sub_43F810((int)v16 + 16850, (int)&v64, 4);
  v63 = 4;
  sub_43F810((int)v16 + 16854, (int)&v63, 4);
  sub_43F810((int)v16 + 16858, (unsigned int)&dword_79B6A0, 4);
  v64 = 24;
  sub_43F810((int)v16 + 16862, (int)&v64, 4);
  v63 = 340;
  sub_43F810((int)v16 + 16866, (int)&v63, 4);
  sub_43F810((int)v16 + 16870, (unsigned int)dword_79BCD8, 340);
  v64 = 25;
  sub_43F810((int)v16 + 17210, (int)&v64, 4);
  v63 = 512;
  sub_43F810((int)v16 + 17214, (int)&v63, 4);
  sub_43F810((int)v16 + 17218, (unsigned int)dword_79B48C, 512);
  v64 = 26;
  sub_43F810((int)v16 + 17730, (int)&v64, 4);
  v63 = 1536;
  sub_43F810((int)v16 + 17734, (int)&v63, 4);
  sub_43F810((int)v16 + 17738, (unsigned int)dword_79B6D8, 1536);
  v64 = 27;
  sub_43F810((int)v16 + 19274, (int)&v64, 4);
  v63 = 52;
  sub_43F810((int)v16 + 19278, (int)&v63, 4);
  sub_43F810((int)v16 + 19282, (unsigned int)&word_79B6A4, 52);
  v64 = 34;
  sub_43F810((int)v16 + 19334, (int)&v64, 4);
  v63 = 1;
  sub_43F810((int)v16 + 19338, (int)&v63, 4);
  sub_43F810((int)v16 + 19342, (unsigned int)&byte_797B7C, 1);
  v64 = 35;
  sub_43F810((int)v16 + 19343, (int)&v64, 4);
  v63 = 4;
  sub_43F810((int)v16 + 19347, (int)&v63, 4);
  sub_43F810((int)v16 + 19351, (unsigned int)&dword_79BEF4, 4);
  v25 = (int)v16 + 19355;
  v26 = 19355;
  if ( a3 == 0 )
  {
    v64 = 37;
    sub_43F810((int)v16 + 19355, (int)&v64, 4);
    v63 = 4;
    sub_43F810((int)v16 + 19359, (int)&v63, 4);
    sub_43F810((int)v16 + 19363, v11 - 20044, 4);
    v64 = 38;
    sub_43F810((int)v16 + 19367, (int)&v64, 4);
    v63 = 4;
    sub_43F810((int)v16 + 19371, (int)&v63, 4);
    sub_43F810((int)v16 + 19375, v11 - 20040, 4);
    v64 = 39;
    sub_43F810((int)v16 + 19379, (int)&v64, 4);
    v63 = 86016;
    sub_43F810((int)v16 + 19383, (int)&v63, 4);
    sub_43F810((int)v16 + 19387, (unsigned int)&dword_7BBF00, 86016);
    v25 = (int)v16 + 105403;
    v26 = 105403;
  }
  v64 = 40;
  sub_43F810(v25, (int)&v64, 4);
  v63 = 200;
  sub_43F810((int)v25 + 4, (int)&v63, 4);
  sub_43F810((int)v25 + 8, (unsigned int)dword_79BE2C, 200);
  v64 = 41;
  sub_43F810((int)v25 + 208, (int)&v64, 4);
  v63 = sub_15A6A0();
  sub_43F810((int)v25 + 212, (int)&v63, 4);
  v27 = (int)v25 + 216;
  v28 = v26 + 216;
  v29 = sub_15A690();
  v30 = sub_15A6A0();
  sub_43F810(v27, v29, v30);
  v31 = (int)(v27 + sub_15A6A0());
  v32 = v28 + sub_15A6A0();
  for ( n = 0; n < 0xA; n = (int)n + 1 )
  {
    v64 = ((_DWORD)n << 8) + 256;
    sub_43F810(v31, (int)&v64, 4);
    v63 = 4;
    sub_43F810((int)v31 + 4, (int)&v63, 4);
    v34 = (int)&dword_796E50[34 * n];
    sub_43F810((int)v31 + 8, v34, 4);
    v64 = ((_DWORD)n << 8) + 257;
    sub_43F810((int)v31 + 12, (int)&v64, 4);
    v63 = 72;
    sub_43F810((int)v31 + 16, (int)&v63, 4);
    sub_43F810((int)v31 + 20, v34 + 4, 72);
    v64 = ((_DWORD)n << 8) + 258;
    sub_43F810((int)v31 + 92, (int)&v64, 4);
    v63 = 6;
    sub_43F810((int)v31 + 96, (int)&v63, 4);
    sub_43F810((int)v31 + 100, v34 + 76, 6);
    v64 = ((_DWORD)n << 8) + 261;
    sub_43F810((int)v31 + 106, (int)&v64, 4);
    v63 = 48;
    sub_43F810((int)v31 + 110, (int)&v63, 4);
    sub_43F810((int)v31 + 114, v34 + 84, 48);
    v64 = ((_DWORD)n << 8) + 267;
    sub_43F810((int)v31 + 162, (int)&v64, 4);
    v63 = 4;
    sub_43F810((int)v31 + 166, (int)&v63, 4);
    sub_43F810((int)v31 + 170, v34 + 132, 4);
    v31 = (int)v31 + 174;
    v32 += 174;
  }
  v65 = 0;
  for ( ii = 0; ii < v32 - 56; ii = (int)ii + 1 )
    v65 += *(_BYTE *)(v16 + 56 + ii);
  v64 = 0x2000;
  sub_43F810(v31, (int)&v64, 4);
  v63 = 1;
  sub_43F810((int)v31 + 4, (int)&v63, 4);
  sub_43F810((int)v31 + 8, (int)&v65, 1);
  v64 = -1;
  sub_43F810((int)v31 + 9, (int)&v64, 4);
  *a2 = v32 + 13;
  sub_440B68("save size = %d \n", v32 + 13);
  result = v16;
  __asm
  {
    lq      $s7, 0xE0+var_70($sp)
    lq      $s6, 0xE0+var_80($sp)
    lq      $s5, 0xE0+var_90($sp)
    lq      $s4, 0xE0+var_A0($sp)
    lq      $s3, 0xE0+var_B0($sp)
    lq      $s2, 0xE0+var_C0($sp)
    lq      $s1, 0xE0+var_D0($sp)
    lq      $s0, 0xE0+var_E0($sp)
  }
  return result;
}


// func_0010e9e0  addr 0x0010e9e0  window 2480B
void __fastcall sub_10E9E0(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  int v6; // $gp
  __int64 v9; // $v0

  __asm
  {
    sq      $s1, 0x20+var_10($sp)
    sq      $s0, 0x20+var_20($sp)
  }
  switch ( a2 )
  {
    case 2565LL:
    case 2309LL:
    case 2053LL:
    case 1797LL:
    case 1541LL:
    case 1285LL:
    case 1029LL:
    case 773LL:
    case 517LL:
    case 261LL:
      if ( a3 == 48 )
        sub_43F810((int)&dword_796E50[34 * ((unsigned int)a2 >> 8) - 13], a4, 48);
      break;
    case 2562LL:
    case 2306LL:
    case 2050LL:
    case 1794LL:
    case 1538LL:
    case 1282LL:
    case 1026LL:
    case 770LL:
    case 514LL:
    case 258LL:
      if ( a3 == 6 )
        sub_43F810((int)&dword_796E50[34 * ((unsigned int)a2 >> 8) - 15], a4, 6);
      break;
    case 2561LL:
    case 2305LL:
    case 2049LL:
    case 1793LL:
    case 1537LL:
    case 1281LL:
    case 1025LL:
    case 769LL:
    case 513LL:
    case 257LL:
      if ( a3 == 72 )
        sub_43F810((int)&dword_796E50[34 * ((unsigned int)a2 >> 8) - 33], a4, 72);
      break;
    case 2560LL:
    case 2304LL:
    case 2048LL:
    case 1792LL:
    case 1536LL:
    case 1280LL:
    case 1024LL:
    case 768LL:
    case 512LL:
    case 256LL:
      if ( a3 == 4 )
        sub_43F810((int)&dword_796E50[34 * ((unsigned int)a2 >> 8) - 34], a4, 4);
      break;
    case 41LL:
      if ( a3 == sub_15A6A0() )
      {
        v9 = sub_15A690();
        sub_43F810(v9, a4, a3);
      }
      break;
    case 40LL:
      if ( a3 == 200 )
        sub_43F810((unsigned int)dword_79BE2C, a4, 200);
      break;
    case 39LL:
      if ( a3 == 86016 )
        sub_43F810((unsigned int)&dword_7BBF00, a4, 86016);
      break;
    case 38LL:
      if ( a3 == 4 )
        sub_43F810(v6 - 20040, a4, 4);
      break;
    case 37LL:
      if ( a3 == 4 )
        sub_43F810(v6 - 20044, a4, 4);
      break;
    case 35LL:
      if ( a3 == 4 )
        sub_43F810((unsigned int)&dword_79BEF4, a4, 4);
      break;
    case 34LL:
      if ( a3 != 1 )
        break;
      goto LABEL_89;
    case 32LL:
      break;
    case 27LL:
      if ( a3 == 52 )
        sub_43F810((unsigned int)&word_79B6A4, a4, 52);
      break;
    case 26LL:
      if ( a3 == 1536 )
        sub_43F810((unsigned int)dword_79B6D8, a4, 1536);
      break;
    case 25LL:
      if ( a3 == 512 )
        sub_43F810((unsigned int)dword_79B48C, a4, 512);
      break;
    case 24LL:
      if ( a3 == 340 )
        sub_43F810((unsigned int)dword_79BCD8, a4, 340);
      break;
    case 23LL:
      if ( a3 == 4 )
        sub_43F810((unsigned int)&dword_79B6A0, a4, 4);
      break;
    case 22LL:
      if ( a3 == 4 )
        sub_43F810((unsigned int)&dword_79B69C, a4, 4);
      break;
    case 21LL:
      if ( a3 == 4 )
        sub_43F810((unsigned int)&dword_79B698, a4, 4);
      break;
    case 19LL:
      if ( a3 == 8 )
        sub_43F810((unsigned int)dword_79B690, a4, 8);
      break;
    case 18LL:
      if ( a3 == 4 )
        sub_43F810((unsigned int)&dword_79B68C, a4, 4);
      break;
    case 17LL:
      if ( a3 == 704 )
        sub_43F810((unsigned int)dword_79B1CC, a4, 704);
      break;
    case 16LL:
      if ( a3 == 12288 )
        sub_43F810((unsigned int)dword_7981CC, a4, 12288);
      break;
    case 15LL:
      if ( a3 == 576 )
        sub_43F810((unsigned int)byte_797F8C, a4, 576);
      break;
    case 14LL:
      if ( a3 == 2 )
        sub_43F810((unsigned int)&word_797F88, a4, 2);
      break;
    case 13LL:
      if ( a3 == 1024 )
        sub_43F810((unsigned int)&byte_797B87, a4, 1024);
      break;
    case 12LL:
      if ( a3 == 1 )
        sub_43F810((unsigned int)&byte_797B86, a4, 1);
      break;
    case 11LL:
      if ( a3 == 2 )
        sub_43F810((unsigned int)&word_797B84, a4, 2);
      break;
    case 10LL:
      if ( a3 == 4 )
        sub_43F810((unsigned int)&dword_797B80, a4, 4);
      break;
    case 9LL:
      if ( a3 != 1 )
        break;
LABEL_89:
      sub_43F810((unsigned int)&byte_797B7C, a4, 1);
      break;
    default:
      switch ( a2 )
      {
        case 8LL:
          if ( a3 == 2 )
            sub_43F810((unsigned int)&word_797B7A, a4, 2);
          break;
        case 6LL:
          if ( a3 == 1536 )
            sub_43F810((unsigned int)&word_79757A, a4, 1536);
          break;
        case 5LL:
          if ( a3 == 6 )
            sub_43F810((unsigned int)&dword_797574, a4, 6);
          break;
        case 4LL:
          if ( a3 == 16 )
            sub_43F810((unsigned int)dword_797564, a4, 16);
          break;
        case 3LL:
          if ( a3 == 344 )
            sub_43F810((unsigned int)&word_79740C, a4, 344);
          break;
        case 2LL:
          if ( a3 == 72 )
            sub_43F810((unsigned int)&dword_7973C4, a4, 72);
          break;
        default:
          if ( a2 == 1 && a3 == 36 )
            sub_43F810((unsigned int)dword_7973A0, a4, 36);
          break;
      }
      break;
  }
  __asm
  {
    lq      $s1, 0x20+var_10($sp)
    lq      $s0, 0x20+var_20($sp)
  }
}

