/*
 * Generated by tools/ghidra_headstart.py -- Ghidra decompiler output.
 *
 * REFERENCE ONLY. This is not valid C and is never compiled.
 *
 * Ghidra pseudo-types (`undefined1 [16]`, `undefined4`, `code *`, `uint`,
 * `ulong`) and its `FUN_xxxxxxxx` / `DAT_xxxxxxxx` naming are decompiler
 * artifacts -- translate them into the project's own conventions
 * (s8/u8/s16/u16/s32/u32/s64/u64/f32 and the real func_xxxxxxxx names)
 * before writing any source.
 *
 * Why this corpus exists: Ghidra's Emotion Engine support models the PS2's
 * 128-bit register file and VU0 macro-mode ops (you will see
 * `undefined1 auVar [16]` and intrinsics like `_sqc2(...)`), where Hex-Rays
 * emits an opaque `__asm { }` island that hides the surrounding dataflow.
 * For ordinary integer code the Hex-Rays corpus in docs/ida_headstart is
 * usually the easier read. Use whichever is clean for your target; when both
 * are, cross-check them against each other and against the retail
 * disassembly from build/RECON_dis.py.
 *
 * Regenerate: python3 tools/ghidra_headstart.py --report <verify json>
 */


// func_001f0620  addr 0x001f0620  window 672B
bool FUN_001f0620(int param_1,short param_2)

{
  int iVar1;
  uint uVar2;
  bool bVar3;
  ushort uVar4;
  long lVar5;
  
  uVar4 = *(ushort *)(*(int *)(iGpffffb3ac + 0xc68) + 8);
  if ((uVar4 == 0x215) && (param_2 != 2)) {
    bVar3 = false;
  }
  else {
    switch(param_2) {
    default:
      bVar3 = false;
      break;
    case 1:
      bVar3 = true;
      break;
    case 2:
      lVar5 = FUN_00232710(*(undefined4 *)(*(int *)(param_1 + 0x30) + 0xa64),8);
      bVar3 = lVar5 == 0;
      break;
    case 3:
      lVar5 = FUN_00106330(0x1438);
      bVar3 = lVar5 == 0;
      break;
    case 4:
      if (*(char *)(*(int *)(param_1 + 0x30) + 0xa2) == '\0') {
        if (*(short *)(*(int *)(param_1 + 0x30) + 0xa4) == 1) {
          uVar4 = FUN_001ef720(1,0);
          if (uVar4 < 2) {
            bVar3 = false;
          }
          else {
            lVar5 = FUN_00106330(0x1438);
            bVar3 = lVar5 == 0;
          }
        }
        else {
          bVar3 = false;
        }
      }
      else {
        bVar3 = false;
      }
      break;
    case 5:
      iVar1 = *(int *)(param_1 + 0x30);
      if (*(char *)(iVar1 + 0xa2) == '\0') {
        if (*(short *)(iVar1 + 0xa4) == 1) {
          if ((*(ushort *)(param_1 + 0x18) & 0x400) == 0) {
            bVar3 = false;
          }
          else {
            lVar5 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),8);
            if (lVar5 == 0) {
              lVar5 = FUN_00106330(0x1438);
              bVar3 = lVar5 == 0;
            }
            else {
              bVar3 = false;
            }
          }
        }
        else {
          bVar3 = false;
        }
      }
      else {
        bVar3 = false;
      }
      break;
    case 6:
      uVar2 = *(uint *)(iGpffffb414 + (uint)uVar4 * 0x18);
      if ((uVar2 & 0x20) == 0) {
        if ((uVar2 & 1) == 0) {
          bVar3 = false;
        }
        else {
          lVar5 = FUN_001f5ea0(0);
          bVar3 = lVar5 == 0;
        }
      }
      else {
        bVar3 = false;
      }
      break;
    case 7:
    case 8:
    case 0xb:
    case 0xc:
      bVar3 = true;
      break;
    case 10:
      if (*(char *)(*(int *)(param_1 + 0x30) + 0xa2) == '\0') {
        lVar5 = FUN_00106330(0x1438);
        bVar3 = lVar5 == 0;
      }
      else {
        bVar3 = false;
      }
      break;
    case 0xd:
      bVar3 = true;
    }
  }
  return bVar3;
}


// func_001f0dd0  addr 0x001f0dd0  window 416B
int FUN_001f0dd0(int param_1,long param_2)

{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  uint uVar5;
  uint uVar6;
  
  iVar3 = 0;
  if (param_2 == 0) {
    for (uVar6 = 0; uVar6 < *(ushort *)(param_1 + 0x6a); uVar6 = uVar6 + 1 & 0xffff) {
      iVar1 = *(int *)(param_1 + uVar6 * 4 + 0x38);
      if ((*(ushort *)(iVar1 + 0xdc) & 0x106) != 0) {
        return 1;
      }
      for (uVar5 = 0; uVar5 < *(byte *)(iVar1 + 0xd9); uVar5 = uVar5 + 1 & 0xffff) {
        iVar4 = iVar1 + uVar5 * 0x20;
        iVar2 = *(int *)(iVar4 + 0xf0);
        if (iVar2 == 0) {
          if (*(int *)(iVar4 + 0xf8) != 0) {
            return 1;
          }
        }
        else if (iVar2 < 0) {
          return 1;
        }
      }
    }
  }
  else {
    for (uVar6 = 0; uVar6 < *(ushort *)(param_1 + 0x6a); uVar6 = uVar6 + 1 & 0xffff) {
      iVar1 = *(int *)(param_1 + uVar6 * 4 + 0x38);
      if (*(int *)(iVar1 + 0xe4) != 0) {
        return 0;
      }
      if ((*(ushort *)(iVar1 + 0xdc) & 0x500) != 0) {
        return 0;
      }
      if (iVar3 == 0) {
        for (uVar5 = 0; uVar5 < *(byte *)(iVar1 + 0xd9); uVar5 = uVar5 + 1 & 0xffff) {
          if (*(int *)(iVar1 + uVar5 * 0x20 + 0xf0) < 0) {
            iVar3 = 1;
            break;
          }
        }
      }
    }
  }
  return iVar3;
}


// func_001f1030  addr 0x001f1030  window 432B
undefined4 FUN_001f1030(int param_1)

{
  int iVar1;
  long lVar2;
  uint uVar3;
  uint uVar4;
  char cVar5;
  
  cVar5 = *(char *)(*(int *)(param_1 + 0x30) + 0xa2);
  if ((((*(ushort *)(param_1 + 0x1a) & 1) != 0) &&
      (iVar1 = *(int *)(*(int *)(param_1 + 0x30) + 0xa64), iVar1 != 0)) &&
     (lVar2 = FUN_00232710(iVar1,0x100), lVar2 != 0)) {
    cVar5 = cVar5 == '\0';
  }
  uVar3 = (uint)*(ushort *)(param_1 + 0x6a);
  if (1 < uVar3) {
    uVar4 = 0;
    while( true ) {
      if (uVar3 <= uVar4) {
        return 1;
      }
      iVar1 = *(int *)(param_1 + uVar4 * 4 + 0x38);
      if (((*(ushort *)(iVar1 + 0x1a) & 1) != 0) &&
         (*(char *)(*(int *)(iVar1 + 0x30) + 0xa2) != cVar5)) break;
      uVar4 = uVar4 + 1 & 0xffff;
    }
    return 0;
  }
  if (uVar3 == 1) {
    iVar1 = *(int *)(param_1 + 0x38);
    if ((*(ushort *)(iVar1 + 0x1a) & 1) == 0) {
      return 0;
    }
    if (*(char *)(*(int *)(iVar1 + 0x30) + 0xa2) != cVar5) {
      return 0;
    }
    for (uVar3 = 0; uVar3 < *(byte *)(iVar1 + 0xd9); uVar3 = uVar3 + 1 & 0xffff) {
      if ((*(ushort *)(iVar1 + uVar3 * 0x20 + 0x10e) & 0x20) != 0) {
        return 1;
      }
    }
  }
  return 0;
}


// func_001f14f0  addr 0x001f14f0  window 6096B
/* WARNING: Removing unreachable block (ram,0x001f180c) */

void FUN_001f14f0(int param_1)

{
  char cVar1;
  char cVar2;
  byte bVar3;
  ushort uVar4;
  int iVar5;
  int iVar6;
  bool bVar7;
  bool bVar8;
  char cVar9;
  undefined1 uVar10;
  ushort uVar11;
  undefined2 uVar12;
  short sVar13;
  undefined2 uVar14;
  short sVar15;
  int iVar16;
  uint uVar17;
  uint *puVar18;
  undefined4 uVar19;
  long lVar20;
  ulong uVar21;
  ulong uVar22;
  int iVar23;
  int iVar24;
  uint uVar25;
  int iVar26;
  int iVar27;
  bool bVar28;
  ushort *puVar29;
  float fVar30;
  float fVar31;
  ushort uStack_170;
  int iStack_ec;
  int iStack_e8;
  int iStack_e4;
  undefined1 uStack_e0;
  undefined1 uStack_d0;
  byte bStack_c0;
  byte bStack_b0;
  short sStack_a0;
  short sStack_80;
  undefined4 uStack_70;
  int iStack_60;
  int iStack_50;
  int iStack_40;
  int iStack_2c;
  int iStack_28;
  int iStack_24;
  int iStack_4;
  
  sStack_a0 = 0;
  uVar4 = *(ushort *)(param_1 + 0x6e);
  *(ushort *)(param_1 + 0x72) = uVar4;
  bVar28 = *(short *)(param_1 + 0x6c) == 3;
  iVar16 = (uint)uVar4 * 0x28;
  cVar1 = *(char *)(iVar16 + iGpffffb3b8 + 0x11);
  iVar26 = *(int *)(*(int *)(param_1 + 0x30) + 0xa64);
  *(undefined2 *)(iVar26 + 0x2c) = 0;
  if ((*(short *)(param_1 + 0x6c) == 3) && (*(short *)(param_1 + 0x70) != 0)) {
    bVar28 = true;
  }
  cVar9 = FUN_0023d8e0(iVar26,uVar4);
  *(undefined1 *)(param_1 + 0xd9) = 0;
  *(undefined2 *)(param_1 + 0xdc) = 0;
  *(undefined4 *)(param_1 + 0xe0) = 0;
  *(undefined4 *)(param_1 + 0xe4) = 0;
  *(undefined1 *)(param_1 + 0xdb) = 0;
  *(undefined1 *)(param_1 + 0xda) = 0;
  *(undefined4 *)(param_1 + 0xe8) = 0;
  *(undefined2 *)(param_1 + 0xec) = 0;
  *(undefined2 *)(param_1 + 0xee) = 0xffff;
  if ((bVar28 == false) && (lVar20 = FUN_0023df70(uVar4), lVar20 == 0)) {
    lVar20 = FUN_0023ddc0(iVar26,uVar4);
    if ((lVar20 == 3) || (lVar20 == 4)) {
      *(undefined4 *)(param_1 + 0xe8) = 1;
      if (*(char *)(*(int *)(param_1 + 0x30) + 0xa2) == '\0') {
        uVar14 = 0x3a;
      }
      else {
        uVar14 = 0x3b;
      }
      *(undefined2 *)(param_1 + 0xec) = uVar14;
    }
    else if (lVar20 == 2) {
      *(undefined4 *)(param_1 + 0xe8) = 1;
      if (*(char *)(*(int *)(param_1 + 0x30) + 0xa2) == '\0') {
        uVar14 = 0x38;
      }
      else {
        uVar14 = 0x39;
      }
      *(undefined2 *)(param_1 + 0xec) = uVar14;
    }
    else if (lVar20 == 1) {
      *(undefined4 *)(param_1 + 0xe8) = 1;
      if (*(char *)(*(int *)(param_1 + 0x30) + 0xa2) == '\0') {
        uVar14 = 0x36;
      }
      else {
        uVar14 = 0x37;
      }
      *(undefined2 *)(param_1 + 0xec) = uVar14;
    }
  }
  if (*(int *)(param_1 + 0xe8) == 1) {
    *(undefined1 *)(param_1 + 0xdb) = 0;
  }
  else {
    uVar25 = (uint)*(ushort *)(param_1 + 0x6a);
    if (1 < uVar25) {
      uVar17 = 0;
      while ((uVar17 < uVar25 && (*(int *)(param_1 + uVar17 * 4 + 0x38) != param_1))) {
        uVar17 = uVar17 + 1 & 0xffff;
      }
      if (uVar17 != uVar25) {
        for (; (int)uVar17 < (int)(*(ushort *)(param_1 + 0x6a) - 1); uVar17 = uVar17 + 1 & 0xffff) {
          *(undefined4 *)(param_1 + uVar17 * 4 + 0x38) =
               *(undefined4 *)(param_1 + uVar17 * 4 + 0x3c);
        }
        *(int *)(uVar17 * 4 + param_1 + 0x38) = param_1;
      }
    }
    fVar31 = 1.0;
    if ((*(char *)(*(int *)(param_1 + 0x30) + 0xa2) == '\x01') &&
       (lVar20 = FUN_00243fa0(uVar4), fVar31 = 1.0, lVar20 == 0)) {
      uVar11 = *(ushort *)(*(int *)(param_1 + 0x30) + 0xa4);
      fVar30 = *(float *)(*(int *)(param_1 + 0x30) + 0x2c) /
               ((float)*(ushort *)(((uint)uVar11 * 0x1c + (uint)uVar11) * 8 + iGpffffb3cc + 0x14) /
               100.0);
      fVar31 = fGpffff812c;
      if ((fVar30 <= fGpffff812c) && (fVar31 = fGpffff80d4, fGpffff80d4 <= fVar30)) {
        fVar31 = fVar30;
      }
      fVar31 = fVar31 * 1.0;
    }
    *(undefined2 *)(param_1 + 0x3f4) = 0x240;
    uStack_e0 = 0;
    sStack_80 = 0;
    iStack_40 = 0;
    for (uStack_170 = 0; uStack_170 < *(ushort *)(param_1 + 0x6a); uStack_170 = uStack_170 + 1) {
      iVar5 = *(int *)(param_1 + (uint)uStack_170 * 4 + 0x38);
      iVar6 = *(int *)(*(int *)(iVar5 + 0x30) + 0xa64);
      iStack_50 = 0;
      iStack_60 = 0;
      iStack_ec = 0;
      bVar8 = false;
      *(undefined2 *)(iVar5 + 0x3f4) = 0x240;
      *(undefined2 *)(iVar6 + 0x2c) = 0;
      *(undefined1 *)(iVar5 + 0xd9) = 0;
      *(undefined2 *)(iVar5 + 0xdc) = 0;
      *(undefined4 *)(iVar5 + 0xe0) = 0;
      *(undefined4 *)(iVar5 + 0xe4) = 0;
      *(undefined1 *)(iVar5 + 0xdb) = 0;
      *(undefined1 *)(iVar5 + 0xda) = 0;
      *(undefined4 *)(iVar5 + 0xe8) = 0;
      *(undefined2 *)(iVar5 + 0xec) = 0;
      *(undefined2 *)(iVar5 + 0xee) = 0xffff;
      uVar11 = FUN_0023e6f0(iVar26,iVar6,uVar4,bVar28);
      iStack_24 = iVar6;
      iStack_4 = iVar5;
      if (uVar11 == 0x200) {
        uVar11 = FUN_0023e6f0(iVar26,iVar26,uVar4,bVar28 | 2);
        if ((uVar11 == 4) || (uVar11 == 2)) {
          uVar11 = 1;
        }
        else if (uVar11 == 0x200) {
          uVar11 = 0x100;
        }
        *(undefined4 *)(iVar5 + 0xe4) = 1;
        iStack_24 = iVar26;
        iStack_4 = param_1;
      }
      if (*(int *)(iVar5 + 0xe4) == 0) {
        uVar14 = FUN_002411a0(iVar26,iStack_24,uVar4,uVar11,bVar28);
      }
      else {
        uVar14 = 1;
      }
      lVar20 = FUN_0023df70(uVar4);
      if (lVar20 == 0) {
        bStack_c0 = FUN_00243650(iVar26,uVar4,uVar14);
        uStack_d0 = 1;
      }
      else {
        bStack_c0 = 1;
        FUN_0023e1f0(*(undefined4 *)(*(int *)(param_1 + 0x30) + 0xa64));
        uStack_d0 = FUN_0023e2f0(iVar26,uVar14);
      }
      if (*(int *)(iVar5 + 0xe4) == 0) {
        if ((((uVar11 == 0x100) || (uVar11 == 4)) || (uVar11 == 2)) ||
           ((uVar11 == 0x400 || (uVar11 == 0x200)))) {
          bStack_c0 = 1;
          uStack_d0 = 1;
        }
      }
      else {
        bStack_c0 = 1;
        uStack_d0 = 1;
      }
      if (*(int *)(iVar5 + 0xe4) == 0) {
        iStack_e4 = FUN_00241de0(iVar26,iStack_24,uVar4,uVar11,uVar14,bVar28);
        iStack_e8 = FUN_00241f00(iVar26,iVar6,uVar4,uVar11,uVar14,bVar28);
        if ((iStack_e4 != 0) || (lVar20 = FUN_00232710(iVar6,0x100000), lVar20 != 0)) {
          iStack_ec = FUN_00242360(iVar26,iVar6,uVar4,uVar11,uVar14,bVar28);
        }
      }
      else {
        iStack_e4 = 0;
        iStack_e8 = 0;
      }
      uVar21 = FUN_002397d0(uVar4,iVar26,iStack_24,uVar11,uVar14,bVar28);
      uVar22 = FUN_00239e40(uVar4,iVar26,iStack_24,uVar11,uVar14,bVar28);
      iVar27 = iVar16 + iGpffffb3b8;
      if ((((*(char *)(iVar27 + 0x18) == '\x01') && ((*(uint *)(iVar27 + 0x1c) & 0x80000) != 0)) &&
          (*(char *)(iVar27 + 0x24) != '\t')) && ((uVar21 & 0x80000) == 0)) {
        iStack_e4 = 0;
      }
      if (uVar21 == 0x80000) {
        *(undefined4 *)(iVar5 + 0xe0) = 1;
      }
      sVar15 = FUN_001fb360(iVar5,uVar4,bVar28);
      if (((uVar11 == 1) && (*(int *)(iVar5 + 0xe4) == 0)) && (sVar15 == 0)) {
        uStack_70 = *(undefined4 *)(iVar16 + iGpffffb3b8 + 0x20);
      }
      else {
        uStack_70 = 0;
      }
      *(ushort *)(iVar5 + 0xdc) = uVar11;
      *(undefined2 *)(iVar5 + 0xde) = uVar14;
      bVar7 = (uVar22 & 0x80000) == 0;
      for (bStack_b0 = 0; (uint)bStack_b0 < (uint)bStack_c0; bStack_b0 = bStack_b0 + 1) {
        iVar27 = iVar5 + (uint)bStack_b0 * 0x20;
        puVar29 = (ushort *)(iVar27 + 0x10e);
        *(undefined2 *)(iVar27 + 0x10e) = 0;
        *(undefined2 *)(iVar27 + 0x108) = 0;
        *(undefined2 *)(iVar27 + 0x10a) = 0;
        iStack_28 = FUN_00235520(uVar4,iVar26,iStack_24,1,uVar11,uVar14,bVar28,1);
        iStack_2c = FUN_00235520(uVar4,iVar26,iStack_24,1,uVar11,uVar14,bVar28,2);
        if ((int)((float)iStack_28 * fVar31) != 0) {
          iStack_28 = (int)((float)iStack_28 * fVar31);
        }
        if ((int)((float)iStack_2c * 1.0) != 0) {
          iStack_2c = (int)((float)iStack_2c * 1.0);
        }
        iVar23 = iVar5 + (uint)bStack_b0 * 0x20;
        puVar18 = (uint *)(iVar23 + 0xf8);
        *(int *)(iVar23 + 0xf8) = (int)uVar21;
        *(int *)(iVar23 + 0xfc) = (int)uVar22;
        uVar19 = FUN_002384b0(uVar4,iVar26,iStack_24,bVar28);
        cVar2 = *(char *)(iVar16 + iGpffffb3b8 + 0x11);
        if ((cVar2 == '\r') || (cVar2 == '\f')) {
          uVar12 = FUN_0043c6a0(iStack_28);
          *(undefined2 *)(iVar27 + 0x108) = uVar12;
        }
        cVar2 = *(char *)(iVar16 + iGpffffb3b8 + 0x14);
        if ((cVar2 == '\r') || (cVar2 == '\f')) {
          uVar12 = FUN_0043c6a0(iStack_2c);
          *(undefined2 *)(iVar27 + 0x10a) = uVar12;
        }
        iVar24 = iVar5 + (uint)bStack_b0 * 0x20;
        *(undefined4 *)(iVar24 + 0x100) = uStack_70;
        *(undefined4 *)(iVar24 + 0x104) = uVar19;
        iVar23 = iVar24 + 0xf0;
        *(int *)(iVar24 + 0xf0) = iStack_28;
        *(int *)(iVar24 + 0xf4) = iStack_2c;
        iStack_50 = iStack_50 + iStack_28;
        iStack_60 = iStack_60 + iStack_2c;
        if (iStack_4 == param_1) {
          iStack_40 = iStack_40 + iStack_28;
        }
        if (*(char *)(iVar16 + iGpffffb3b8 + 0x24) == '\x02') {
          *puVar29 = *puVar29 | 0x20;
        }
        if ((*(byte *)(iVar16 + iGpffffb3b8) & 1) != 0) {
          *puVar29 = *puVar29 | 0x40;
        }
        if (cVar1 == '\x10') {
          *puVar29 = *puVar29 | 8;
        }
        if (iStack_4 == param_1) {
          lVar20 = FUN_002428f0(iStack_24,iStack_40);
          bVar8 = lVar20 != 0;
          if ((lVar20 == 0) && (bVar8 = false, (uVar21 & 0x80000) != 0)) {
            bVar8 = bVar7;
          }
        }
        else {
          lVar20 = FUN_002428f0(iStack_24,iStack_50);
          bVar8 = lVar20 != 0;
          if ((lVar20 == 0) && (bVar8 = false, (uVar21 & 0x80000) != 0)) {
            bVar8 = bVar7;
          }
        }
        if ((bStack_b0 + 1 == (uint)bStack_c0) || (bVar8)) {
          if (iStack_e4 == 0) {
            if ((((((iStack_50 < 0) || (uVar11 == 0x100)) || (uVar11 == 0x400)) &&
                 (lVar20 = FUN_00232710(iStack_24,0x100000), lVar20 != 0)) ||
                ((*(int *)(iVar5 + 0xe4) == 1 &&
                 (lVar20 = FUN_00232710(iVar6,0x100000), lVar20 != 0)))) &&
               ((*puVar29 = *puVar29 | 1, *(int *)(iVar5 + 0xe4) == 1 ||
                ((uVar11 == 0x100 || (uVar11 == 0x400)))))) {
              *puVar29 = *puVar29 | 2;
            }
          }
          else {
            *puVar18 = *puVar18 | 0x100000;
          }
          if (((iStack_ec == 0) || (-1 < iStack_50)) || (uVar21 != 0)) {
            iStack_ec = 0;
          }
          else {
            *puVar18 = *puVar18 | 1;
          }
          if (iStack_e8 != 0) {
            *puVar29 = *puVar29 | 4;
          }
          if (((uVar11 == 1) && (*(int *)(iVar5 + 0xe4) != 1)) && (iStack_e8 != 1)) {
            if (iStack_e4 != 0) {
              sStack_80 = sStack_80 + 1;
            }
          }
          else {
            uStack_e0 = 2;
          }
        }
        if (bVar8) {
          sVar13 = *(short *)(iStack_4 + 0x3f4);
          if (sVar13 == 0x240) {
            sVar13 = FUN_00242990(*(undefined4 *)(*(int *)(iStack_4 + 0x30) + 0xa64),uVar4);
          }
          if (sVar13 < 0) {
            uVar10 = FUN_001f12b0(iStack_4,iVar23,uVar11,uVar14,1);
            *(undefined1 *)(iVar5 + (uint)bStack_b0 * 0x20 + 0x10c) = uVar10;
            *(undefined4 *)(iVar5 + 0xe0) = 1;
            if (param_1 == iStack_4) {
              *(undefined2 *)(iVar27 + 0x108) = 0;
            }
          }
          else {
            *(short *)(iStack_4 + 0x3f4) = sVar13;
            *puVar29 = *puVar29 | 0x10;
            uVar10 = FUN_001f12b0(iStack_4,iVar23,uVar11,uVar14,0);
            *(undefined1 *)(iVar5 + (uint)bStack_b0 * 0x20 + 0x10c) = uVar10;
          }
          bStack_c0 = (byte)(bStack_b0 + 1);
          break;
        }
        uVar10 = FUN_001f12b0(iStack_4,iVar23,uVar11,uVar14,0);
        *(undefined1 *)(iVar5 + (uint)bStack_b0 * 0x20 + 0x10c) = uVar10;
      }
      if (((*(int *)(iVar5 + 0xe4) == 1) || ((uVar11 & 0x700) != 0)) ||
         ((iStack_50 != 0 || (((iStack_60 != 0 || (uVar21 != 0)) || (uVar22 != 0)))))) {
        if ((*(int *)(iVar5 + 0xe4) == 1) || ((uVar11 & 0x500) != 0)) {
          FUN_001f9cd0(param_1,iVar5,uVar4);
        }
        if (((*(char *)(*(int *)(iVar5 + 0x30) + 0xa2) == '\x01') &&
            (CONCAT44((int)(((long)cVar9 << 0x38) >> 0x3f),(int)cVar9) < 8)) && ((uVar11 & 6) == 0))
        {
          FUN_0010f3d0(*(undefined2 *)(*(int *)(iVar5 + 0x30) + 0xa4),cVar9);
        }
      }
      sVar13 = *(short *)(iVar26 + 0x2c);
      if ((*(short *)(iVar26 + 0x2c) == 0) && (sVar13 = sStack_a0, *(short *)(iVar6 + 0x2c) != 0)) {
        sVar13 = *(short *)(iVar6 + 0x2c);
      }
      sStack_a0 = sVar13;
      if (sVar15 == 0) {
        if ((uVar11 & 6) == 0) {
          sVar15 = FUN_001f0260(uVar4);
        }
        else {
          sVar15 = 0;
        }
      }
      else {
        sVar15 = FUN_001fb170(sVar15);
        *(byte *)(param_1 + 0xd8) = *(byte *)(param_1 + 0xd8) | 1;
      }
      if (sVar15 == 0) {
        if (sStack_a0 == 0) {
          if (!bVar8) {
            if ((iStack_ec == 0) && ((uVar21 & 1) == 0)) {
              if (uVar21 != 0) {
                if ((uVar21 & 2) == 0) {
                  if ((uVar21 & 4) == 0) {
                    if ((uVar21 & 8) == 0) {
                      if ((uVar21 & 0x10) == 0) {
                        if ((uVar21 & 0x20) == 0) {
                          if ((uVar21 & 0x40) == 0) {
                            if ((uVar21 & 0x80) != 0) {
                              if (*(char *)(*(int *)(iVar5 + 0x30) + 0xa2) == '\0') {
                                uVar14 = 0xe;
                              }
                              else {
                                uVar14 = 0xf;
                              }
                              *(undefined2 *)(iVar5 + 0xec) = uVar14;
                            }
                          }
                          else {
                            if (*(char *)(*(int *)(iVar5 + 0x30) + 0xa2) == '\0') {
                              uVar14 = 0x1a;
                            }
                            else {
                              uVar14 = 0x1b;
                            }
                            *(undefined2 *)(iVar5 + 0xec) = uVar14;
                          }
                        }
                        else {
                          if (*(char *)(*(int *)(iVar5 + 0x30) + 0xa2) == '\0') {
                            uVar14 = 0x10;
                          }
                          else {
                            uVar14 = 0x11;
                          }
                          *(undefined2 *)(iVar5 + 0xec) = uVar14;
                        }
                      }
                      else {
                        if (*(char *)(*(int *)(iVar5 + 0x30) + 0xa2) == '\0') {
                          uVar14 = 0x12;
                        }
                        else {
                          uVar14 = 0x13;
                        }
                        *(undefined2 *)(iVar5 + 0xec) = uVar14;
                      }
                    }
                    else {
                      if (*(char *)(*(int *)(iVar5 + 0x30) + 0xa2) == '\0') {
                        uVar14 = 0x1c;
                      }
                      else {
                        uVar14 = 0x1d;
                      }
                      *(undefined2 *)(iVar5 + 0xec) = uVar14;
                    }
                  }
                  else {
                    if (*(char *)(*(int *)(iVar5 + 0x30) + 0xa2) == '\0') {
                      uVar14 = 0x14;
                    }
                    else {
                      uVar14 = 0x15;
                    }
                    *(undefined2 *)(iVar5 + 0xec) = uVar14;
                  }
                }
                else {
                  if (*(char *)(*(int *)(iVar5 + 0x30) + 0xa2) == '\0') {
                    uVar14 = 0x16;
                  }
                  else {
                    uVar14 = 0x17;
                  }
                  *(undefined2 *)(iVar5 + 0xec) = uVar14;
                }
              }
            }
            else {
              if (*(char *)(*(int *)(iVar5 + 0x30) + 0xa2) == '\0') {
                uVar14 = 0x18;
              }
              else {
                uVar14 = 0x19;
              }
              *(undefined2 *)(iVar5 + 0xec) = uVar14;
            }
          }
        }
        else {
          *(short *)(iVar5 + 0xec) = sStack_a0;
        }
      }
      else {
        *(short *)(iVar5 + 0xec) = sVar15;
      }
      *(byte *)(iVar5 + 0xd9) = bStack_c0;
      *(undefined1 *)(iVar5 + 0xda) = uStack_d0;
    }
    if (sStack_80 != 0) {
      uStack_e0 = 1;
    }
    if (*(short *)(param_1 + 0xee) == -1) {
      uVar14 = FUN_001f0610(uVar4);
      *(undefined2 *)(param_1 + 0xee) = uVar14;
    }
    if (*(char *)(iVar16 + iGpffffb3b8 + 0x24) == '\x06') {
      *(ushort *)(param_1 + 0x1a) = *(ushort *)(param_1 + 0x1a) | 0x4000;
    }
    sVar15 = FUN_001fb1f0(param_1,uVar4,bVar28);
    if ((sVar15 != 0) && (*(int *)(param_1 + 0xe8) != 1)) {
      uVar14 = FUN_001fb170();
      *(undefined2 *)(param_1 + 0xec) = uVar14;
    }
    *(undefined1 *)(param_1 + 0xdb) = uStack_e0;
    cVar1 = *(char *)(*(int *)(param_1 + 0x30) + 0xa2);
    if ((((cVar1 == '\x01') && (*(short *)(param_1 + 0x6a) == 1)) &&
        (*(int *)(param_1 + 0x38) == *(int *)(iGpffffb3ac + 0x170))) &&
       (*(int *)(*(int *)(param_1 + 0x38) + 0xe0) == 1)) {
      bVar28 = false;
      while (!bVar28) {
        if (*(int *)(*(int *)(param_1 + 0x38) + 0xe4) != 0) {
          bVar28 = true;
          goto LAB_001f27e8;
        }
        bVar28 = true;
      }
      bVar28 = false;
LAB_001f27e8:
      if (!bVar28) {
        lVar20 = FUN_001efd50(param_1);
        iVar26 = (int)lVar20;
        *(int *)(param_1 + 0x88) = iVar26;
        if (lVar20 == 0) {
          return;
        }
        iVar5 = *(int *)(param_1 + 0x38);
        uVar19 = *(undefined4 *)(*(int *)(iVar26 + 0x30) + 0xa64);
        if (*(char *)(iVar16 + iGpffffb3b8 + 0x24) == '\r') {
          *(undefined2 *)(iVar26 + 0xec) = *(undefined2 *)(iVar5 + 0xec);
        }
        else {
          *(undefined2 *)(iVar26 + 0xec) = 0;
        }
        *(undefined1 *)(param_1 + 0xdb) = 0;
        *(undefined1 *)(iVar5 + 0xdb) = 0;
        *(undefined2 *)(iVar5 + 0xdc) = 1;
        *(undefined2 *)(iVar5 + 0xde) = 1;
        *(undefined4 *)(iVar5 + 0xe0) = 0;
        *(undefined4 *)(iVar5 + 0xe4) = 0;
        *(undefined4 *)(iVar5 + 0xe8) = 0;
        *(undefined2 *)(iVar5 + 0xec) = 0;
        *(undefined2 *)(iVar5 + 0xee) = 0xffff;
        bVar28 = false;
        iVar26 = 0;
        bVar3 = *(byte *)(iVar5 + 0xd9);
        uVar25 = 0;
        while( true ) {
          if (bVar3 <= uVar25) {
            return;
          }
          iVar27 = iVar5 + uVar25 * 0x20;
          iVar6 = *(int *)(iVar27 + 0xf0);
          iVar26 = iVar26 + iVar6;
          lVar20 = FUN_002428f0(uVar19,iVar26);
          if ((lVar20 != 0) ||
             (((*(uint *)(iVar27 + 0xf8) & 0x80000) != 0 &&
              ((*(uint *)(iVar27 + 0xfc) & 0x80000) == 0)))) {
            bVar28 = true;
          }
          iVar27 = iVar5 + uVar25 * 0x20;
          FUN_0043f9c8((int *)(iVar27 + 0xf0),0,0x20);
          *(int *)(iVar27 + 0xf0) = iVar6;
          *(undefined1 *)(iVar27 + 0x10c) = 2;
          *(ushort *)(iVar27 + 0x10e) = *(ushort *)(iVar27 + 0x10e) | 0x200;
          if (*(char *)(iVar16 + iGpffffb3b8 + 0x24) == '\r') break;
          if (bVar28) {
            iVar26 = uVar25 * 0x20 + iVar5;
            *(uint *)(iVar26 + 0xf8) = *(uint *)(iVar26 + 0xf8) | 0x80000;
            *(undefined2 *)(*(int *)(param_1 + 0x88) + 0x3f4) = 0;
            *(ushort *)(iVar27 + 0x10e) = *(ushort *)(iVar27 + 0x10e) | 0x10;
            *(char *)(iVar5 + 0xd9) = (char)uVar25 + '\x01';
            return;
          }
          uVar25 = uVar25 + 1 & 0xff;
        }
        iVar26 = uVar25 * 0x20 + iVar5;
        *(uint *)(iVar26 + 0xf8) = *(uint *)(iVar26 + 0xf8) | 0x80000;
        *(uint *)(iVar26 + 0xfc) = *(uint *)(iVar26 + 0xfc) & 0xfff7ffff;
        *(char *)(iVar5 + 0xd9) = (char)uVar25 + '\x01';
        return;
      }
    }
    if ((((*(byte *)(param_1 + 0xdb) & 1) != 0) && ((*(ushort *)(param_1 + 0x18) & 4) == 0)) &&
       ((cVar1 == '\0' && (*(short *)(param_1 + 0x6a) != 0)))) {
      sVar15 = 0;
      for (uVar25 = 0; uVar25 < *(ushort *)(param_1 + 0x6a); uVar25 = uVar25 + 1 & 0xffff) {
        iVar26 = *(int *)(param_1 + uVar25 * 4 + 0x38);
        if ((*(int *)(iVar26 + 0xe0) == 1) &&
           (lVar20 = FUN_00232710(*(undefined4 *)(*(int *)(iVar26 + 0x30) + 0xa64),0x100000),
           lVar20 == 0)) {
          sVar15 = sVar15 + 1;
        }
        else {
          for (uVar17 = 0; uVar17 < *(byte *)(iVar26 + 0xd9); uVar17 = uVar17 + 1 & 0xff) {
            if ((*(char *)(*(int *)(iVar26 + 0x30) + 0xa2) == '\x01') &&
               ((*(uint *)(iVar26 + uVar17 * 0x20 + 0xf8) & 0x100000) != 0)) {
              sVar15 = sVar15 + 1;
              break;
            }
          }
        }
      }
      for (iVar26 = *(int *)(iGpffffb3ac + 0x174); iVar26 != 0; iVar26 = *(int *)(iVar26 + 0x450)) {
        if (((((*(ushort *)(iVar26 + 0x1a) & 1) != 0) &&
             (iVar16 = *(int *)(iVar26 + 0x30), *(char *)(iVar16 + 0xa2) == '\x01')) &&
            ((*(uint *)(iVar16 + 0x9c) & 8) != 0)) &&
           ((lVar20 = FUN_002428f0(*(undefined4 *)(iVar16 + 0xa64),0), lVar20 == 0 &&
            (lVar20 = FUN_00232710(*(undefined4 *)(*(int *)(iVar26 + 0x30) + 0xa64),0x100000),
            lVar20 == 0)))) {
          sVar15 = sVar15 + -1;
        }
      }
      if ((*(int *)(iGpffffb3ac + 0x170) != 0) &&
         (lVar20 = FUN_00232710(*(undefined4 *)
                                 (*(int *)(*(int *)(iGpffffb3ac + 0x170) + 0x30) + 0xa64),0x100117),
         lVar20 != 0)) {
        sVar15 = 1;
      }
      if (sVar15 != 0) {
        lVar20 = FUN_001eff50(param_1);
        if (lVar20 == 0) {
          lVar20 = FUN_001ef9c0(param_1);
          if (lVar20 != 0) {
            *(undefined2 *)(param_1 + 0x16) = 0xc;
            FUN_001b0e30(param_1);
          }
        }
        else {
          iVar26 = (int)lVar20;
          if (*(ushort *)(param_1 + 0x6a) < 2) {
            *(undefined4 *)(iVar26 + 0x90) = *(undefined4 *)(param_1 + 0x38);
          }
          else {
            iVar16 = FUN_00231d70();
            *(undefined4 *)(iVar26 + 0x90) = *(undefined4 *)(iVar16 * 4 + param_1 + 0x38);
          }
          if (*(int *)(*(int *)(iVar26 + 0x90) + 0xe0) == 0) {
            *(int *)(param_1 + 0x8c) = iVar26;
            *(undefined2 *)(iVar26 + 0x16) = 0xd;
            FUN_001b0e30(lVar20);
          }
        }
      }
    }
  }
  return;
}


// func_001f2cc0  addr 0x001f2cc0  window 496B
void FUN_001f2cc0(int param_1)

{
  bool bVar1;
  byte bVar2;
  short sVar3;
  int iVar4;
  int iVar5;
  uint uVar6;
  int iStack_4;
  
  if (((*(ushort *)(param_1 + 0x1a) & 1) != 0) &&
     (iVar5 = *(int *)(param_1 + 0x30), *(char *)(iVar5 + 0xa2) == '\x01')) {
    if (0x14f < *(ushort *)(iVar5 + 0xa4)) {
      FUN_0046d730(0x60ab08,0x4f5);
    }
    if ((*(ushort *)(param_1 + 0x1a) & 0x20) == 0) {
      *(ushort *)(param_1 + 0x1a) = *(ushort *)(param_1 + 0x1a) | 0x20;
      iVar4 = func_0x00243950(*(undefined4 *)(iVar5 + 0xa64));
      *(int *)(iGpffffb3ac + 0xcb0) = *(int *)(iGpffffb3ac + 0xcb0) + iVar4;
      iVar4 = FUN_002439c0(*(undefined4 *)(iVar5 + 0xa64));
      *(int *)(iGpffffb3ac + 0xcb4) = *(int *)(iGpffffb3ac + 0xcb4) + iVar4;
      sVar3 = FUN_00243a30(*(undefined4 *)(iVar5 + 0xa64),&iStack_4);
      if (((iStack_4 != 1) && (*(short *)(param_1 + 0x80) != 0)) &&
         (bVar2 = FUN_00231d70(100), bVar2 < *(byte *)(param_1 + 0x82))) {
        sVar3 = *(short *)(param_1 + 0x80);
      }
      if (sVar3 != 0) {
        bVar1 = false;
        for (uVar6 = 0; uVar6 < 3; uVar6 = uVar6 + 1 & 0xffff) {
          iVar5 = iGpffffb3ac + uVar6 * 4;
          if (*(short *)(iVar5 + 0xcd0) == sVar3) {
            *(short *)(iVar5 + 0xcd2) = *(short *)(iVar5 + 0xcd2) + 1;
            bVar1 = true;
            break;
          }
        }
        if (!bVar1) {
          for (uVar6 = 0; uVar6 < 3; uVar6 = uVar6 + 1 & 0xffff) {
            iVar5 = iGpffffb3ac + uVar6 * 4;
            if (*(short *)(iVar5 + 0xcd0) == 0) {
              *(short *)(iVar5 + 0xcd0) = sVar3;
              *(undefined2 *)(uVar6 * 4 + iGpffffb3ac + 0xcd2) = 1;
              *(uint *)(iGpffffb3ac + 0xcdc) = uVar6 + 1;
              return;
            }
          }
        }
      }
    }
  }
  return;
}


// func_001f39d0  addr 0x001f39d0  window 304B
undefined4 FUN_001f39d0(int *param_1)

{
  undefined2 uVar1;
  short sVar2;
  ushort uVar3;
  int iVar4;
  int iVar5;
  char cVar6;
  long lVar7;
  
  iVar4 = *param_1;
  iVar5 = *(int *)(iVar4 + 0x30);
  sVar2 = *(short *)(iVar4 + 0x6c);
  if ((sVar2 != 1) && (sVar2 != 9)) {
    if (sVar2 == 3) {
      if (*(char *)(iVar5 + 0xa2) == '\0') {
        uVar1 = *(undefined2 *)(iVar4 + 0x70);
        cVar6 = FUN_00106600(uVar1);
        FUN_00106620(uVar1,cVar6 + -1);
      }
    }
    else if (sVar2 == 2) {
      uVar3 = *(ushort *)(iVar4 + 0x6e);
      lVar7 = FUN_0023d9b0(*(undefined4 *)(iVar5 + 0xa64),uVar3);
      if (lVar7 != 0) {
        cVar6 = *(char *)((uint)uVar3 * 0x28 + iGpffffb3b8 + 3);
        if (cVar6 == '\x02') {
          FUN_00232610(*(undefined4 *)(iVar5 + 0xa64),-(int)lVar7);
        }
        else if (cVar6 == '\x01') {
          FUN_002325a0(*(undefined4 *)(iVar5 + 0xa64),-(int)lVar7);
        }
      }
    }
  }
  return 1;
}


// func_001f3bb0  addr 0x001f3bb0  window 944B
int FUN_001f3bb0(void)

{
  ushort uVar1;
  short sVar2;
  uint uVar3;
  undefined4 uVar4;
  uint uVar5;
  uint uVar6;
  int iVar7;
  long lVar8;
  undefined8 uVar9;
  ulong uVar10;
  int iVar11;
  int iVar12;
  int iVar13;
  
  uVar3 = FUN_001ef720(2,0x80000);
  uVar3 = uVar3 & 0xffff;
  if (uVar3 < 6) {
    lVar8 = FUN_00106330(0x38);
    if (lVar8 == 0) {
      uVar4 = 8;
    }
    else {
      uVar4 = 5;
    }
    uVar9 = FUN_0010a900(uVar4);
    lVar8 = FUN_0010ce10(uVar9,0x10d);
    uVar5 = func_0x001ef4d0(2,0x80000);
    uVar6 = FUN_00231e20(*(undefined4 *)(*(int *)(*(int *)(iGpffffb3ac + 0x170) + 0x30) + 0xa64));
    iVar7 = *(int *)(iGpffffb3ac + 0x180);
    for (iVar11 = iVar7; iVar11 != 0; iVar11 = *(int *)(iVar11 + 0xa6c)) {
      uVar1 = *(ushort *)(iGpffffb3c4 + (uint)*(ushort *)(iVar11 + 0xa4) * 0x3c);
      if ((uVar1 & 0x40) != 0) {
        return 1;
      }
      if ((uVar1 & 0x80) != 0) {
        return 0;
      }
    }
    if (lVar8 != -1) {
      iVar12 = -1;
      iVar11 = -1;
      for (; iVar7 != 0; iVar7 = *(int *)(iVar7 + 0xa6c)) {
        for (iVar13 = 0; iVar13 < 8; iVar13 = iVar13 + 1) {
          uVar10 = FUN_00242800(*(undefined4 *)(iVar7 + 0xa64),(short)iVar13);
          if ((uVar10 & 0x7000000) != 0) {
            switch(iVar13) {
            case 0:
              iVar11 = 0x17;
              break;
            case 1:
              iVar11 = 0x18;
              break;
            case 2:
              iVar11 = 0x19;
              break;
            case 3:
              iVar11 = 0x1b;
              break;
            case 4:
              iVar11 = 0x1a;
              break;
            case 6:
              iVar11 = 0x1c;
              break;
            case 7:
              iVar11 = 0x1d;
            }
          }
        }
      }
      for (iVar7 = *(int *)(iGpffffb3ac + 0x180); iVar7 != 0; iVar7 = *(int *)(iVar7 + 0xa6c)) {
        for (iVar13 = 0; iVar13 < 8; iVar13 = iVar13 + 1) {
          uVar10 = FUN_00242800(*(undefined4 *)(iVar7 + 0xa64),(short)iVar13);
          if ((uVar10 & 0x8000000) != 0) {
            switch(iVar13) {
            case 0:
              iVar12 = 0x1e;
              break;
            case 1:
              iVar12 = 0x1f;
              break;
            case 2:
              iVar12 = 0x20;
              break;
            case 3:
              iVar12 = 0x22;
              break;
            case 4:
              iVar12 = 0x21;
              break;
            case 6:
              iVar12 = 0x23;
              break;
            case 7:
              iVar12 = 0x24;
            }
          }
        }
      }
      if (iVar11 != -1) {
        return iVar11;
      }
      if (iVar12 != -1) {
        return iVar12;
      }
    }
    if ((int)((uVar5 & 0xffff) - (uVar6 & 0xff)) < 4) {
      sVar2 = *(short *)(iGpffffb3ac + 0x1a);
      if (sVar2 == 2) {
        iVar7 = uVar3 + 0xc;
      }
      else if (sVar2 == 1) {
        iVar7 = uVar3 + 7;
      }
      else if (sVar2 == 0) {
        iVar7 = uVar3 + 2;
      }
      else {
        iVar7 = -1;
      }
    }
    else {
      iVar7 = 2;
    }
  }
  else {
    iVar7 = -1;
  }
  return iVar7;
}


// func_001f4e50  addr 0x001f4e50  window 1888B
short FUN_001f4e50(int param_1)

{
  int iVar1;
  ushort uVar2;
  uint uVar3;
  long lVar4;
  ulong uVar5;
  short sVar6;
  short asStack_100 [128];
  
  if (*(char *)(*(int *)(param_1 + 0x30) + 0xa2) == '\0') {
    uVar3 = 0;
    uVar2 = 0;
    for (iVar1 = *(int *)(iGpffffb3ac + 0x178); iVar1 != 0; iVar1 = *(int *)(iVar1 + 0xa6c)) {
      lVar4 = FUN_002428f0(*(undefined4 *)(iVar1 + 0xa64),0);
      if ((lVar4 == 0) &&
         ((lVar4 = FUN_001b0c80(iVar1), lVar4 == 0 || ((*(ushort *)((int)lVar4 + 0x18) & 0x20) == 0)
          ))) {
        lVar4 = FUN_00242930(*(undefined4 *)(iVar1 + 0xa64));
        if (lVar4 != 0) {
          asStack_100[uVar3 * 2] = 0x8a;
          asStack_100[uVar3 * 2 + 1] = *(short *)(iVar1 + 0xa4);
          uVar3 = uVar3 + 1 & 0xffff;
          uVar2 = uVar2 + 1;
        }
        if (*(short *)(iVar1 + 0xa4) != 1) {
          lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),0x10);
          if (lVar4 == 0) {
            lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),0x20);
            if (lVar4 == 0) {
              lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),4);
              if (lVar4 == 0) {
                lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),2);
                if (lVar4 == 0) {
                  lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),1);
                  if (lVar4 == 0) {
                    lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),0x40);
                    if (lVar4 == 0) {
                      lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),0x80);
                      if (lVar4 == 0) {
                        lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),8);
                        if (lVar4 != 0) {
                          asStack_100[uVar3 * 2] = 0xc3;
                          asStack_100[uVar3 * 2 + 1] = *(short *)(iVar1 + 0xa4);
                          uVar3 = uVar3 + 1 & 0xffff;
                        }
                      }
                      else {
                        asStack_100[uVar3 * 2] = 0xbd;
                        asStack_100[uVar3 * 2 + 1] = *(short *)(iVar1 + 0xa4);
                        uVar3 = uVar3 + 1 & 0xffff;
                      }
                    }
                    else {
                      asStack_100[uVar3 * 2] = 0xb7;
                      asStack_100[uVar3 * 2 + 1] = *(short *)(iVar1 + 0xa4);
                      uVar3 = uVar3 + 1 & 0xffff;
                    }
                  }
                  else {
                    asStack_100[uVar3 * 2] = 0xb1;
                    asStack_100[uVar3 * 2 + 1] = *(short *)(iVar1 + 0xa4);
                    uVar3 = uVar3 + 1 & 0xffff;
                  }
                }
                else {
                  asStack_100[uVar3 * 2] = 0xab;
                  asStack_100[uVar3 * 2 + 1] = *(short *)(iVar1 + 0xa4);
                  uVar3 = uVar3 + 1 & 0xffff;
                }
              }
              else {
                asStack_100[uVar3 * 2] = 0xa5;
                asStack_100[uVar3 * 2 + 1] = *(short *)(iVar1 + 0xa4);
                uVar3 = uVar3 + 1 & 0xffff;
              }
            }
            else {
              asStack_100[uVar3 * 2] = 0x9f;
              asStack_100[uVar3 * 2 + 1] = *(short *)(iVar1 + 0xa4);
              uVar3 = uVar3 + 1 & 0xffff;
            }
          }
          else {
            asStack_100[uVar3 * 2] = 0x99;
            asStack_100[uVar3 * 2 + 1] = *(short *)(iVar1 + 0xa4);
            uVar3 = uVar3 + 1 & 0xffff;
          }
        }
        lVar4 = FUN_002340c0(*(undefined4 *)(iVar1 + 0xa64),10);
        if (lVar4 != 0) {
          asStack_100[uVar3 * 2] = 0x6f;
          asStack_100[uVar3 * 2 + 1] = *(short *)(iVar1 + 0xa4);
          uVar3 = uVar3 + 1 & 0xffff;
        }
        lVar4 = FUN_002340c0(*(undefined4 *)(iVar1 + 0xa64),0x80);
        if (lVar4 != 0) {
          asStack_100[uVar3 * 2] = 0x76;
          asStack_100[uVar3 * 2 + 1] = *(short *)(iVar1 + 0xa4);
          uVar3 = uVar3 + 1 & 0xffff;
        }
        lVar4 = FUN_002340c0(*(undefined4 *)(iVar1 + 0xa64),0x220);
        if (lVar4 != 0) {
          asStack_100[uVar3 * 2] = 0x7d;
          asStack_100[uVar3 * 2 + 1] = *(short *)(iVar1 + 0xa4);
          uVar3 = uVar3 + 1 & 0xffff;
        }
      }
    }
    iVar1 = *(int *)(param_1 + 0x30);
    if (*(short *)(iVar1 + 0xa4) == 1) {
      lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),0x20);
      if (lVar4 == 0) {
        lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),2);
        if (lVar4 == 0) {
          lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),1);
          if (lVar4 == 0) {
            lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),0x40);
            if (lVar4 == 0) {
              lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),0x80);
              if (lVar4 == 0) {
                lVar4 = FUN_00232710(*(undefined4 *)(iVar1 + 0xa64),8);
                if (lVar4 != 0) {
                  asStack_100[uVar3 * 2] = 0x98;
                  asStack_100[uVar3 * 2 + 1] = -1;
                  uVar3 = uVar3 + 1 & 0xffff;
                }
              }
              else {
                asStack_100[uVar3 * 2] = 0x97;
                asStack_100[uVar3 * 2 + 1] = -1;
                uVar3 = uVar3 + 1 & 0xffff;
              }
            }
            else {
              asStack_100[uVar3 * 2] = 0x96;
              asStack_100[uVar3 * 2 + 1] = -1;
              uVar3 = uVar3 + 1 & 0xffff;
            }
          }
          else {
            asStack_100[uVar3 * 2] = 0x95;
            asStack_100[uVar3 * 2 + 1] = -1;
            uVar3 = uVar3 + 1 & 0xffff;
          }
        }
        else {
          asStack_100[uVar3 * 2] = 0x94;
          asStack_100[uVar3 * 2 + 1] = -1;
          uVar3 = uVar3 + 1 & 0xffff;
        }
      }
      else {
        asStack_100[uVar3 * 2] = 0x92;
        asStack_100[uVar3 * 2 + 1] = -1;
        uVar3 = uVar3 + 1 & 0xffff;
      }
    }
    if (1 < uVar2) {
      asStack_100[uVar3 * 2] = 0x89;
      asStack_100[uVar3 * 2 + 1] = -1;
      uVar3 = uVar3 + 1 & 0xffff;
    }
    uVar2 = FUN_001ef720(2,0x80000);
    uVar5 = (ulong)uVar2;
    if ((long)*(short *)(iGpffffb3ac + 0xa6c) == uVar5) {
      if ((uVar5 < 6) && (uVar5 != 0)) {
        asStack_100[uVar3 * 2] = 0x89 - uVar2;
        asStack_100[uVar3 * 2 + 1] = -1;
        uVar3 = uVar3 + 1 & 0xffff;
      }
    }
    else {
      *(ushort *)(iGpffffb3ac + 0xa6c) = uVar2;
    }
    if (uVar3 == 0) {
      sVar6 = -1;
    }
    else {
      uVar3 = FUN_00231d70();
      sVar6 = asStack_100[(uVar3 & 0xffff) * 2];
      if ((long)*(int *)(iGpffffb3ac + 0xa68) == (long)sVar6) {
        sVar6 = -1;
      }
      else {
        *(int *)(iGpffffb3ac + 0xa68) = (int)sVar6;
        switch(asStack_100[(uVar3 & 0xffff) * 2 + 1]) {
        case 2:
          sVar6 = sVar6 + 1;
          break;
        case 3:
          sVar6 = sVar6 + 2;
          break;
        case 4:
          sVar6 = sVar6 + 3;
          break;
        case 6:
          sVar6 = sVar6 + 4;
          break;
        case 7:
          sVar6 = sVar6 + 5;
          break;
        case 8:
          sVar6 = sVar6 + 6;
        }
      }
    }
  }
  else {
    sVar6 = -1;
  }
  return sVar6;
}


// func_001f5a00  addr 0x001f5a00  window 464B
/* WARNING: Removing unreachable block (ram,0x001f5a50) */

void FUN_001f5a00(long param_1)

{
  bool bVar1;
  bool bVar2;
  long lVar3;
  
  bVar1 = false;
  bVar2 = false;
  while ((!bVar2 && (!bVar1))) {
    if (((((*(ushort *)(iGpffffb3ac + 0xa48) & 1) != 0) && (lVar3 = FUN_001b1540(), lVar3 != 0)) &&
        ((*(ushort *)((int)lVar3 + 0x1a) & 1) != 0)) &&
       ((param_1 != 0 && (*(char *)(*(int *)((int)lVar3 + 0x30) + 0xa2) == '\0')))) {
      *(short *)(iGpffffb3ac + 0xa44) = *(short *)(iGpffffb3ac + 0xa44) + 1;
      if ((param_1 == 0) ||
         ((*(ushort *)(iGpffffb3ac + 0xa46) < 4 ||
          ((uint)*(ushort *)(iGpffffb3ac + 0xa44) !=
           (int)(uint)*(ushort *)(iGpffffb3ac + 0xa46) >> 1)))) {
        if (((*(ushort *)(iGpffffb3ac + 0xa46) <= *(ushort *)(iGpffffb3ac + 0xa44)) &&
            (lVar3 = FUN_00232710(*(undefined4 *)
                                   (*(int *)(*(int *)(iGpffffb3ac + 0x170) + 0x30) + 0xa64),0x180010
                                 ), lVar3 == 0)) && (lVar3 = func_0x001b1550(), lVar3 == 0)) {
          *(undefined2 *)(*(int *)(iGpffffb3ac + 0x170) + 0x16) = 0x1c;
          FUN_001b0e30(*(undefined4 *)(iGpffffb3ac + 0x170));
          bVar1 = true;
          *(ushort *)(iGpffffb3ac + 0xa48) = *(ushort *)(iGpffffb3ac + 0xa48) & 0xfffe;
        }
      }
      else {
        FUN_001f56d0(*(undefined4 *)(iGpffffb3ac + 0x170),4,0,0,4);
      }
    }
    bVar2 = true;
  }
  return;
}


// func_001f5bd0  addr 0x001f5bd0  window 720B
void FUN_001f5bd0(uint param_1)

{
  int iVar1;
  ulong uVar2;
  float fVar3;
  undefined2 uVar4;
  float fVar5;
  float fVar6;
  float fVar7;
  float fVar8;
  
  *(ushort *)(iGpffffb3ac + 0xa48) =
       *(ushort *)(iGpffffb3ac + 0xa48) | (ushort)(1 << (param_1 & 0x1f));
  if ((param_1 & 0xffff) == 0) {
    uVar2 = func_0x001ef5f0(1,3,0x80000);
    if ((long)uVar2 < 0) {
      fVar5 = (float)(uVar2 & 0xffffffff);
    }
    else {
      fVar5 = (float)(int)uVar2;
    }
    uVar2 = func_0x001ef5f0(2,3,0x80000);
    if ((long)uVar2 < 0) {
      fVar6 = (float)(uVar2 & 0xffffffff);
    }
    else {
      fVar6 = (float)(int)uVar2;
    }
    uVar2 = func_0x001ef5f0(1,4,0x80000);
    if ((long)uVar2 < 0) {
      fVar7 = (float)(uVar2 & 0xffffffff);
    }
    else {
      fVar7 = (float)(int)uVar2;
    }
    uVar2 = func_0x001ef5f0(2,4,0x80000);
    if ((long)uVar2 < 0) {
      fVar8 = (float)(uVar2 & 0xffffffff);
    }
    else {
      fVar8 = (float)(int)uVar2;
    }
    iVar1 = FUN_00231d70(0xf);
    fVar3 = 10.0;
    fVar5 = ((float)(iVar1 + 5) / 10.0) * (fVar5 / fVar6) * (fVar7 / fVar8) * 30.0;
    if (50.0 < fVar5) {
      fVar3 = 50.0;
    }
    else if (10.0 <= fVar5) {
      fVar3 = fVar5;
    }
    iVar1 = (param_1 & 0xffff) * 4;
    *(undefined2 *)(iVar1 + iGpffffb3ac + 0xa44) = 0;
    fVar3 = 100.0 / fVar3;
    if (fVar3 < 2.1474836e+09) {
      uVar4 = (undefined2)(int)fVar3;
    }
    else {
      uVar4 = (undefined2)(int)(fVar3 - 2.1474836e+09);
    }
    *(undefined2 *)(iVar1 + iGpffffb3ac + 0xa46) = uVar4;
  }
  return;
}


// func_001f62f0  addr 0x001f62f0  window 736B
short FUN_001f62f0(int param_1)

{
  ushort uVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  long lVar5;
  ulong uVar6;
  short sVar7;
  ulong unaff_s3;
  short sVar8;
  short sVar9;
  short asStack_10 [8];
  
  lVar5 = FUN_00106330(0x38);
  if (lVar5 == 0) {
    sVar7 = 200;
  }
  else {
    sVar7 = 0xfa;
  }
  uVar2 = func_0x001ef4d0(2,0x80000);
  uVar3 = FUN_00231e20(*(undefined4 *)(*(int *)(*(int *)(iGpffffb3ac + 0x170) + 0x30) + 0xa64));
  if ((*(uint *)(iGpffffb3ac + 0xc) & 0x200000) == 0) {
    if ((int)((uVar2 & 0xffff) - (uVar3 & 0xff)) < 4) {
      if ((int)((uVar3 & 0xff) - (uVar2 & 0xffff)) < 4) {
        sVar9 = 1;
      }
      else {
        sVar9 = 2;
      }
    }
    else {
      sVar9 = 0;
    }
  }
  else {
    sVar9 = 0;
  }
  uVar2 = 0;
  sVar9 = sVar9 * 0x1e;
  for (sVar8 = 0; sVar8 < 7; sVar8 = sVar8 + 1) {
    switch(sVar8) {
    case 0:
      unaff_s3 = 0;
      break;
    case 1:
      unaff_s3 = 1;
      break;
    case 2:
      unaff_s3 = 2;
      break;
    case 3:
      unaff_s3 = 4;
      break;
    case 4:
      unaff_s3 = 3;
      break;
    case 5:
      unaff_s3 = 6;
      break;
    case 6:
      unaff_s3 = 7;
    }
    if ((*(char *)(param_1 + 0xa2) != '\x01') ||
       (lVar5 = FUN_001f0950(*(undefined2 *)(param_1 + 0xa4),unaff_s3 & 0xffff), lVar5 != 0)) {
      uVar6 = FUN_0023a6b0(*(undefined4 *)(param_1 + 0xa64),unaff_s3);
      if ((uVar6 & 0x8000000) == 0) {
        if ((uVar6 & 0x7000000) != 0) {
          uVar1 = FUN_004bd050(0);
          asStack_10[uVar2] = sVar7 + sVar8 * 2 + sVar9 + (uVar1 & 1) + 0x10;
          uVar2 = uVar2 + 1 & 0xffff;
        }
      }
      else {
        uVar1 = FUN_004bd050(0);
        asStack_10[uVar2] = sVar7 + sVar8 * 2 + sVar9 + 2 + (uVar1 & 1);
        uVar2 = uVar2 + 1 & 0xffff;
      }
    }
  }
  if (uVar2 == 0) {
    uVar1 = FUN_004bd050(0);
    sVar9 = sVar9 + sVar7 + (uVar1 & 1);
  }
  else {
    iVar4 = FUN_00231d70();
    sVar9 = asStack_10[iVar4];
  }
  return sVar9;
}


// func_001f6930  addr 0x001f6930  window 704B
uint FUN_001f6930(int param_1)

{
  int iVar1;
  bool bVar2;
  uint uVar3;
  long lVar4;
  uint uVar5;
  uint uVar6;
  long lVar7;
  uint uVar8;
  uint uVar9;
  
  iVar1 = *(int *)(param_1 + 0x30);
  uVar3 = FUN_002326e0(*(undefined4 *)(iVar1 + 0xa64));
  uVar9 = 0;
  for (uVar8 = 0; uVar8 < 0x18; uVar8 = uVar8 + 1) {
    uVar5 = 1 << (uVar8 & 0x1f);
    if ((uVar3 & uVar5) != 0) {
      if (uVar5 == 8) {
        lVar7 = FUN_00244f60(8,*(undefined4 *)(iVar1 + 0xa64),*(undefined4 *)(iVar1 + 0xa64),0xffff,
                             8);
        uVar6 = 6;
        bVar2 = true;
      }
      else if (uVar5 == 0x80) {
        lVar7 = FUN_00244f60(8,*(undefined4 *)(iVar1 + 0xa64),*(undefined4 *)(iVar1 + 0xa64),0xffff)
        ;
        uVar6 = 6;
        bVar2 = true;
      }
      else if (uVar5 == 0x40) {
        lVar7 = FUN_00244f60(8,*(undefined4 *)(iVar1 + 0xa64),*(undefined4 *)(iVar1 + 0xa64),0xffff)
        ;
        uVar6 = 3;
        bVar2 = true;
      }
      else if (uVar5 == 2) {
        lVar7 = FUN_00244f60(8,*(undefined4 *)(iVar1 + 0xa64),*(undefined4 *)(iVar1 + 0xa64),0xffff)
        ;
        uVar6 = 3;
        bVar2 = true;
      }
      else if (uVar5 == 4) {
        lVar7 = FUN_00244f60(8,*(undefined4 *)(iVar1 + 0xa64),*(undefined4 *)(iVar1 + 0xa64),0xffff)
        ;
        uVar6 = 3;
        bVar2 = true;
      }
      else if (uVar5 == 0x10) {
        lVar7 = FUN_00244f60(8,*(undefined4 *)(iVar1 + 0xa64),*(undefined4 *)(iVar1 + 0xa64),0xffff)
        ;
        uVar6 = 3;
        bVar2 = true;
      }
      else {
        lVar7 = 0;
        uVar6 = 0;
        bVar2 = false;
      }
      if ((bVar2) && (uVar6 != 0)) {
        lVar4 = FUN_00232730(*(undefined4 *)(iVar1 + 0xa64),0x22f);
        if ((lVar4 != 0) && (uVar6 = (int)uVar6 >> 1, uVar6 == 0)) {
          uVar6 = 1;
        }
        lVar4 = FUN_00232730(*(undefined4 *)(iVar1 + 0xa64),0x230);
        if (lVar4 != 0) {
          uVar6 = 1;
        }
      }
      if (1 < *(byte *)(param_1 + uVar8 + 0x3f6)) {
        if ((*(byte *)(param_1 + uVar8 + 0x3f6) < uVar6) || (uVar6 == 0)) {
          lVar4 = FUN_00231d70(100);
          if (lVar4 < lVar7) {
            uVar9 = uVar9 | uVar5;
          }
        }
        else {
          uVar9 = uVar9 | uVar5;
        }
      }
    }
  }
  return uVar9;
}


// func_001f8480  addr 0x001f8480  window 528B
void FUN_001f8480(void)

{
  undefined8 uVar1;
  long lVar2;
  undefined1 auStack_100 [256];
  
  FUN_0044ea90(0x624f50,0x3a);
  uVar1 = (*DAT_008873e8)(0xbe4,0x40000);
  FUN_00442088(auStack_100,0x624f60);
  func_0x00456250(3,auStack_100,0,uVar1);
  while (lVar2 = func_0x004c7ef8(3), lVar2 != 3) {
    if (lVar2 == 4) {
      func_0x00456250(3,auStack_100,0,uVar1);
    }
  }
  uGpffffb460 = 1;
  FUN_0044ea90(0x624f50,0x3a);
  uVar1 = (*DAT_008873e8)(0x630,0x40000);
  FUN_00442088(auStack_100,0x624f80);
  func_0x00456250(4,auStack_100,0,uVar1);
  while (lVar2 = func_0x004c7ef8(4), lVar2 != 3) {
    if (lVar2 == 4) {
      func_0x00456250(4,auStack_100,0,uVar1);
    }
  }
  FUN_0044ea90(0x624f50,0x3a);
  uVar1 = (*DAT_008873e8)(0x4a0,0x40000);
  FUN_00442088(auStack_100,0x624fa0);
  func_0x00456250(5,auStack_100,0,uVar1);
  while (lVar2 = func_0x004c7ef8(5), lVar2 != 3) {
    if (lVar2 == 4) {
      func_0x00456250(5,auStack_100,0,uVar1);
    }
  }
  uGpffffb464 = 1;
  return;
}


// func_001f90e0  addr 0x001f90e0  window 480B
int FUN_001f90e0(int param_1)

{
  ushort uVar1;
  int iVar2;
  long lVar3;
  uint uVar4;
  int iVar5;
  int aiStack_30 [12];
  
  lVar3 = FUN_0045af90(3);
  if (lVar3 == 1) {
    iVar2 = -1;
  }
  else if (*(char *)(*(int *)(param_1 + 0x30) + 0xa2) == '\0') {
    lVar3 = FUN_00232710(*(undefined4 *)(*(int *)(param_1 + 0x30) + 0xa64),0x110);
    if (lVar3 == 0) {
      uVar4 = 0;
      for (iVar2 = *(int *)(iGpffffb3ac + 0x178); iVar2 != 0; iVar2 = *(int *)(iVar2 + 0xa6c)) {
        lVar3 = FUN_002428f0(*(undefined4 *)(iVar2 + 0xa64),0);
        if ((((lVar3 == 0) &&
             (lVar3 = FUN_00232710(*(undefined4 *)(iVar2 + 0xa64),0x1001d7), lVar3 == 0)) &&
            (*(short *)(iVar2 + 0xa4) != 1)) && (iVar2 != *(int *)(param_1 + 0x30))) {
          aiStack_30[uVar4] = iVar2;
          uVar4 = uVar4 + 1 & 0xffff;
        }
      }
      if (uVar4 == 0) {
        iVar2 = -1;
      }
      else {
        iVar2 = FUN_00231d70();
        iVar2 = aiStack_30[iVar2];
        if (iVar2 == 0) {
          iVar2 = -1;
        }
        else {
          iVar5 = 0x32;
          uVar4 = 1;
          while( true ) {
            if ((8 < (int)uVar4) || (uVar4 == *(ushort *)(*(int *)(param_1 + 0x30) + 0xa4))) break;
            if ((uVar4 != 5) && (uVar4 != *(ushort *)(iVar2 + 0xa4))) {
              iVar5 = iVar5 + 3;
            }
            uVar4 = uVar4 + 1;
          }
          uVar1 = *(ushort *)((uint)*(ushort *)(iVar2 + 0xa4) * 2 + 0x624fc0);
          iVar2 = FUN_00231d70(3);
          iVar2 = iVar5 + (uint)uVar1 + iVar2;
        }
      }
    }
    else {
      iVar2 = -1;
    }
  }
  else {
    iVar2 = -1;
  }
  return iVar2;
}


// func_001faf70  addr 0x001faf70  window 512B
undefined4 FUN_001faf70(int param_1,ulong param_2,undefined8 param_3)

{
  undefined4 uVar1;
  long lVar2;
  byte *pbVar3;
  uint uVar4;
  uint uVar5;
  uint uVar6;
  uint uVar7;
  
  if ((long)param_2 < 1) {
    uVar1 = 0;
  }
  else {
    pbVar3 = (byte *)(iGpffffb3b8 + (int)param_2 * 0x28);
    if ((*pbVar3 & 8) == 0) {
      uVar1 = 0;
    }
    else {
      uVar4 = *(uint *)(pbVar3 + 0x20);
      if (((uVar4 & 0x7f7fffff) != 0) && ((uVar4 & 0x80800000) == 0)) {
        for (uVar7 = 0; uVar7 < 0x20; uVar7 = uVar7 + 1) {
          uVar5 = 1 << (uVar7 & 0x1f);
          if ((uVar4 & uVar5) != 0) {
            uVar6 = 0;
            while ((uVar6 < *(ushort *)(param_1 + 0x6a) &&
                   (lVar2 = FUN_002340c0(*(undefined4 *)
                                          (*(int *)(*(int *)(param_1 + uVar6 * 4 + 0x38) + 0x30) +
                                          0xa64),uVar5), lVar2 != 0))) {
              uVar6 = uVar6 + 1;
            }
            if (uVar6 != *(ushort *)(param_1 + 0x6a)) break;
          }
        }
        if (uVar7 == 0x20) {
          if ((uVar4 & 0x3000) != 0) {
            return 5;
          }
          return 3;
        }
      }
      uVar4 = 0;
      while (((uVar4 < *(ushort *)(param_1 + 0x6a) &&
              (lVar2 = FUN_0023a1e0(param_2 & 0xffff,
                                    *(undefined4 *)(*(int *)(param_1 + 0x30) + 0xa64),
                                    *(undefined4 *)
                                     (*(int *)(*(int *)(param_1 + uVar4 * 4 + 0x38) + 0x30) + 0xa64)
                                    ,param_3), lVar2 != 0)) && (lVar2 != 0xffff))) {
        uVar4 = uVar4 + 1;
      }
      if (uVar4 == *(ushort *)(param_1 + 0x6a)) {
        uVar1 = 4;
      }
      else {
        uVar1 = 0;
      }
    }
  }
  return uVar1;
}


// func_001fb480  addr 0x001fb480  window 1744B
/* WARNING: Removing unreachable block (ram,0x001fba60) */
/* WARNING: Removing unreachable block (ram,0x001fb9e0) */
/* WARNING: Removing unreachable block (ram,0x001fb948) */
/* WARNING: Removing unreachable block (ram,0x001fb8c8) */
/* WARNING: Removing unreachable block (ram,0x001fb830) */
/* WARNING: Removing unreachable block (ram,0x001fb7b0) */
/* WARNING: Removing unreachable block (ram,0x001fb718) */
/* WARNING: Removing unreachable block (ram,0x001fb698) */
/* WARNING: Removing unreachable block (ram,0x001fb6d8) */
/* WARNING: Removing unreachable block (ram,0x001fb758) */
/* WARNING: Removing unreachable block (ram,0x001fb7f0) */
/* WARNING: Removing unreachable block (ram,0x001fb870) */
/* WARNING: Removing unreachable block (ram,0x001fb908) */
/* WARNING: Removing unreachable block (ram,0x001fb988) */
/* WARNING: Removing unreachable block (ram,0x001fba20) */
/* WARNING: Removing unreachable block (ram,0x001fbaa0) */

void FUN_001fb480(float param_1,byte *param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5)

{
  int iVar1;
  undefined8 uVar2;
  float fVar3;
  float fVar4;
  float fStack_100;
  float fStack_fc;
  undefined4 uStack_f8;
  undefined4 uStack_f0;
  undefined4 uStack_ec;
  float fStack_e8;
  float fStack_e0;
  float fStack_dc;
  float fStack_d8;
  float fStack_d4;
  float fStack_c0;
  float fStack_bc;
  undefined4 uStack_b8;
  undefined4 uStack_b0;
  float fStack_ac;
  float fStack_a8;
  float fStack_a0;
  float fStack_9c;
  float fStack_98;
  float fStack_94;
  float fStack_80;
  float fStack_7c;
  undefined4 uStack_78;
  float fStack_70;
  undefined4 uStack_6c;
  float fStack_68;
  float fStack_60;
  float fStack_5c;
  float fStack_58;
  float fStack_54;
  float fStack_40;
  float fStack_3c;
  undefined4 uStack_38;
  float fStack_30;
  float fStack_2c;
  float fStack_28;
  float fStack_20;
  float fStack_1c;
  float fStack_18;
  float fStack_14;
  
  iVar1 = FUN_00457120();
  uVar2 = FUN_00401b80();
  fStack_80 = 640.0;
  fStack_70 = 640.0 / (float)*(int *)((int)uVar2 + 0xc);
  fStack_bc = 448.0;
  fStack_ac = 448.0 / (float)*(int *)((int)uVar2 + 0x10);
  if (param_1 == 0.0) {
    fVar3 = 0.0;
    fVar4 = 0.0;
  }
  else {
    fVar3 = param_1 * -320.0 + fGpffff82e8 + 0.0;
    fVar4 = param_1 * -224.0 + fGpffff82ec + 0.0;
    fStack_80 = param_1 * 320.0 + fGpffff82e8 + 0.0;
    fStack_bc = param_1 * 224.0 + fGpffff82ec + 0.0;
  }
  (*DAT_00887300)(7,2);
  (*DAT_00887300)(0x14,1);
  (*DAT_00887300)(0xe,0);
  (*DAT_00887300)(6,0);
  (*DAT_00887300)(8,0);
  (*DAT_00887300)(9,param_5);
  (*DAT_00887300)(0xc,1);
  (*DAT_00887300)(1,uVar2);
  FUN_003f6440(2,param_3);
  FUN_003f6440(3,param_4);
  fStack_e8 = 1.0 / *(float *)(iVar1 + 0x84);
  uStack_f8 = DAT_008872fc;
  fStack_e0 = (float)*param_2;
  fStack_dc = (float)param_2[1];
  fStack_d8 = (float)param_2[2];
  fStack_d4 = (float)param_2[3];
  uStack_f0 = 0;
  uStack_ec = 0;
  uStack_b8 = DAT_008872fc;
  fStack_a0 = (float)*param_2;
  fStack_9c = (float)param_2[1];
  fStack_98 = (float)param_2[2];
  fStack_94 = (float)param_2[3];
  uStack_b0 = 0;
  uStack_78 = DAT_008872fc;
  fStack_60 = (float)*param_2;
  fStack_5c = (float)param_2[1];
  fStack_58 = (float)param_2[2];
  fStack_54 = (float)param_2[3];
  uStack_6c = 0;
  uStack_38 = DAT_008872fc;
  fStack_20 = (float)*param_2;
  fStack_1c = (float)param_2[1];
  fStack_18 = (float)param_2[2];
  fStack_14 = (float)param_2[3];
  fStack_100 = fVar3;
  fStack_fc = fVar4;
  fStack_c0 = fVar3;
  fStack_a8 = fStack_e8;
  fStack_7c = fVar4;
  fStack_68 = fStack_e8;
  fStack_40 = fStack_80;
  fStack_3c = fStack_bc;
  fStack_30 = fStack_70;
  fStack_2c = fStack_ac;
  fStack_28 = fStack_e8;
  (*DAT_00887310)(4,&fStack_100,4);
  (*DAT_00887300)(1,0);
  return;
}


// func_001fbb50  addr 0x001fbb50  window 1632B
/* WARNING: Removing unreachable block (ram,0x001fbc58) */
/* WARNING: Removing unreachable block (ram,0x001fbe80) */

undefined4 FUN_001fbb50(int param_1)

{
  char cVar1;
  char *pcVar2;
  undefined8 uVar3;
  long lVar4;
  uint uVar5;
  undefined4 uVar6;
  float fVar7;
  undefined1 uVar8;
  float fVar9;
  undefined4 uVar10;
  undefined4 auStack_30 [10];
  undefined4 uStack_8;
  undefined1 uStack_4;
  undefined1 uStack_3;
  undefined1 uStack_2;
  undefined1 uStack_1;
  
  uVar3 = FUN_00457120();
  lVar4 = FUN_003e8120(uVar3);
  if (lVar4 == 0) {
    return 0;
  }
  uVar6 = 0;
  for (uVar5 = 0; uVar5 < 7; uVar5 = uVar5 + 1) {
    (*DAT_00887304)(*(undefined4 *)(&DAT_00625210 + uVar5 * 4),auStack_30 + uVar5);
  }
  pcVar2 = *(char **)(param_1 + 0x38);
  cVar1 = *pcVar2;
  if (cVar1 == '\x03') {
    lVar4 = FUN_00122720();
    if (lVar4 != 0) {
      FUN_00122640(1,0x1e);
      uGpffffb468 = 0;
      uVar6 = 0xffffffff;
    }
    goto LAB_001fc0e4;
  }
  if (cVar1 != '\x02') {
    if (cVar1 != '\x01') goto LAB_001fc0e4;
    if (sGpffffb46c == 0) {
      uGpffffb46a = uGpffffb46a + 1;
      fVar9 = (float)uGpffffb46a / 20.0;
      (*DAT_00887300)(7,2);
      (*DAT_00887300)(0x14,1);
      (*DAT_00887300)(0xe,0);
      (*DAT_00887300)(6,0);
      (*DAT_00887300)(8,0);
      (*DAT_00887300)(0xc,1);
      (*DAT_00887300)(1,0);
      FUN_003f6440(2,0x44);
      FUN_003f6440(3,0x31801);
      FUN_00489f80();
      uStack_4 = 0xff;
      uStack_3 = 0xff;
      uStack_2 = 0xff;
      fVar7 = (1.0 - fVar9 * fVar9 * fVar9 * fVar9 * fVar9 * fVar9) * 255.0;
      if (fVar7 < 2.1474836e+09) {
        uStack_1 = (undefined1)(int)fVar7;
      }
      else {
        uStack_1 = (undefined1)(int)(fVar7 - 2.1474836e+09);
      }
      FUN_0045c870(&uStack_4,0);
      fVar7 = (1.0 - fVar9 * fVar9) * 160.0;
      if (fVar7 < 2.1474836e+09) {
        uVar8 = (undefined1)(int)fVar7;
      }
      else {
        uVar8 = (undefined1)(int)(fVar7 - 2.1474836e+09);
      }
      uStack_8 = CONCAT13(uVar8,0xffffff);
      fVar7 = ((float)uGpffffb46a / 20.0) * 1.5;
      FUN_00457120();
      (*DAT_00887300)(7,2);
      (*DAT_00887300)(0x14,1);
      (*DAT_00887300)(0xe,0);
      (*DAT_00887300)(6,0);
      (*DAT_00887300)(8,0);
      (*DAT_00887300)(0xc,1);
      (*DAT_00887300)(1,0);
      FUN_003f6440(2,0x44);
      FUN_003f6440(3,0x31801);
      FUN_00204690(fVar7,fVar7,DAT_008872fc,0,uStack_8);
      FUN_0048a000();
      FUN_001fb480(0x3f800000,&gp0xffffa4d8,0x54,0x31801,1);
      if (0x13 < uGpffffb46a) {
        *pcVar2 = '\x03';
      }
      goto LAB_001fc0e4;
    }
    sGpffffb46c = sGpffffb46c + -1;
  }
  if (cGpffffb469 == '\0') {
    FUN_001fb480(0x3f800000,&gp0xffffa4d8,0x44,0x31801,1);
    uVar10 = uGpffff82f4;
    if (*(short *)(pcVar2 + 6) == 1) {
      uVar10 = uGpffff82f0;
    }
    uStack_4 = 0xff;
    uStack_3 = 0xff;
    uStack_2 = 0xff;
    if (*(short *)(pcVar2 + 6) == 1) {
      uStack_1 = 6;
    }
    else {
      uStack_1 = 10;
    }
    FUN_001fb480(uVar10,&uStack_4,0x44,0x31801,2);
    uStack_1 = 5;
    FUN_001fb480(uVar10,&uStack_4,0x48,0x31801,2);
  }
LAB_001fc0e4:
  for (uVar5 = 0; uVar5 < 7; uVar5 = uVar5 + 1) {
    (*DAT_00887300)(*(undefined4 *)(&DAT_00625210 + uVar5 * 4),auStack_30[uVar5]);
  }
  (*DAT_00887300)(1,0);
  FUN_003f6440(2,0x44);
  FUN_003f6440(3,0x717fb);
  uVar3 = FUN_00457120();
  FUN_003e8110(uVar3);
  return uVar6;
}


// func_001fc300  addr 0x001fc300  window 416B
bool FUN_001fc300(int param_1,char *param_2)

{
  char cVar1;
  uint uVar2;
  
  if (param_2[3] != '\0') {
    return true;
  }
  for (uVar2 = 0; (uVar2 < 3 && ((&DAT_00881448)[uVar2] != 0)); uVar2 = uVar2 + 1 & 0xffff) {
    if ((((uint)(byte)param_2[2] & 1 << (uVar2 & 0x1f)) != 0) && ((&DAT_00881448)[uVar2] == param_1)
       ) {
      return true;
    }
  }
  if ((DAT_00881440 != 0) && (*(char *)(param_1 + 0xa2) == *(char *)(DAT_00881440 + 0xa2))) {
    cVar1 = *param_2;
    if (cVar1 == '\x02') {
      return true;
    }
    if (cVar1 == '\x01') {
      return DAT_00881440 == param_1;
    }
    if (cVar1 == '\0') {
      return false;
    }
  }
  if ((DAT_00881444 != 0) && (*(char *)(param_1 + 0xa2) == *(char *)(DAT_00881444 + 0xa2))) {
    cVar1 = param_2[1];
    if (cVar1 == '\x02') {
      return true;
    }
    if (cVar1 == '\x01') {
      return DAT_00881444 == param_1;
    }
    if (cVar1 == '\0') {
      return false;
    }
  }
  return false;
}

