/*
 * W53SdkWrap archive for func_00466c60 @ 0x00466c60.
 * Best measured source floor (kept out of production): object 544B,
 * retail window 544B, normalized_diff 94 (reloc-masked).
 *
 * Shape probes included: faithful Ghidra do/while reconstruction; direct
 * nested state dispatch; inverted nested dispatch; switch dispatch; explicit
 * labels/gotos; direct versus block-scoped queue-base expressions; signed
 * short versus s32 retry counters; and direct versus temporary call results.
 * The body below is the best direct nested-dispatch result.
 *
 * Residual floor: MWCC emits the state load before the state-3 constant,
 * chooses the opposite state-0 branch layout, and materializes the queue and
 * call-table GPREL expressions with different bases/addends. It also omits
 * the retail sign-extension pair before the retry threshold and chooses a
 * different linked-list/outer-loop branch layout. These are real instruction
 * differences, not relocation-only noise. The retail sq/lq operations are
 * callee-save operations generated by the compiler; cvt.w.s is expressible
 * with the explicit float-to-s32 conversion used below. Production therefore
 * intentionally retains INCLUDE_ASM.
 */
void func_00466c60(void)
{
    s16 i;
    u8 *work;
    s32 lock;
    s32 count;

    for (i = 0; i <= 0; i++) {
        work = *(u8 **)(D_008E4B50 + i * 0x1D8);
        if (work != NULL) {
            do {
                if (3 != *(s32 *)(work + 0x1A4)) {
                    if (2 != *(s32 *)(work + 0x1A4)) {
                        if (1 != *(s32 *)(work + 0x1A4)) {
                            if (0 == *(s32 *)(work + 0x1A4)) {
                                if (*(s8 *)(work + 0xA4) != 0) {
                                    lock = func_0042ba20();
                                    func_00440b68((u8 *)&D_00724BC8 - 0xAC8,
                                                   D_00712978, 0x233);
                                    *(s32 *)(work + 0x1B0) =
                                        func_00454a60(work + 0xA4,
                                                      *(s32 *)(work + 0x1A8));
                                    if (lock != 0) {
                                        func_0042ba70();
                                    }
                                    *(s32 *)(work + 0x1A4) = 1;
                                    break;
                                }
                                *(s32 *)(work + 0x1B0) = 0;
                                lock = 0;
                                goto enqueue;
                            }
                            break;
                        }
                        lock = func_0042ba20();
                        if (func_004553c0(*(s32 *)(work + 0x1B0)) != 0) {
                            if (lock != 0) {
                                func_0042ba70();
                            }
                            lock = 0;
                            goto enqueue;
                        }
                        if (lock != 0) {
                            func_0042ba70();
                        }
                        break;
 enqueue:
                        *(s16 *)((u8 *)&D_00724BC8 + 8 + i * 8) = 1;
                        *(u8 **)((u8 *)&D_00724BC8 + 12 + i * 8) = work;
                        *(s32 *)(work + 0x1A4) = 2;
                        func_00421710(
                            *(s32 *)((u8 *)&D_00724BC8 + i * 4));
                        if (lock != 0) {
                            func_0042ba70();
                        }
                        break;
                    }
                    count = *(s16 *)(work + 0x1D4) + 1;
                    *(s16 *)(work + 0x1D4) = count;
                    if (count >= 6) {
                        func_00440b68(
                            D_00712990,
                            (s32)*(f32 *)((u8 *)&D_00724BC8 + 0x4C));
                    }
                    break;
                }
                work = *(u8 **)work;
                if (work == NULL) {
                    return;
                }
            } while (work != NULL);
        }
    }
}
