/* Generated by tools/ida_headstart.py -- Hex-Rays (IDA Pro 9.4) pseudocode.
 *
 * REFERENCE ONLY. This is not valid C and is never compiled: IDA's pseudo
 * types (__int64, _DWORD, _$F0 register aliases) are not MWCC input, and a
 * raw `__asm { ... }` block below is Hex-Rays declining to model an Emotion
 * Engine instruction it does not understand (FPU multiply-accumulate chains,
 * or a rare single op like mfthc1/pcpyld). Everything else in a function
 * usually decompiles correctly -- control flow, hardware MMIO addresses
 * (rendered as MEMORY[0x...]), struct layout. Translate an asm island by
 * hand using the measured b210 rules in docs/matching.md; do not guess.
 *
 * Regenerate: python3 tools/ida_headstart.py --report <verify.json>
 */

// func_00269c70  addr 0x00269c70  window 320B
void __fastcall sub_269C70(float *a1, float *a2, float a3)
{
  _BYTE v6[64]; // [sp+40h] [-70h] BYREF
  __int64 v7; // [sp+80h] [-30h] BYREF
  float v8; // [sp+88h] [-28h]
  __int64 v9; // [sp+90h] [-20h] BYREF
  float v10; // [sp+98h] [-18h]
  float v11; // [sp+A0h] [-10h] BYREF
  float v12; // [sp+A4h] [-Ch]
  float v13; // [sp+A8h] [-8h]

  v9 = qword_63B0F0;
  v10 = flt_63B0F8;
  v7 = qword_63B100;
  v8 = flt_63B108;
  sub_3E0870((int)v6, (int)&v7, 0);
  sub_3E4320((int)&v9, (int)&v9, (int)v6);
  v7 = 0x3F80000000000000LL;
  v8 = 0.0;
  sub_3E0870((int)v6, (int)&v7, 0);
  sub_3E4320((int)&v11, (int)&v9, (int)v6);
  sub_3E40B0((int)&v11, (int)&v11);
  v11 = v11 * a3;
  v12 = v12 * a3;
  v13 = v13 * a3;
  *a1 = v11 + *a2;
  a1[1] = v12 + a2[1];
  a1[2] = v13 + a2[2];
}


// func_0026a020  addr 0x0026a020  window 6720B
void __fastcall sub_26A020(__int64 a1)
{
  int v2; // $a0
  __int64 v3; // $s3
  int v4; // $a0
  float v5; // $f1
  float v6; // $f0
  float v7; // $f1
  float v8; // $f0
  float v9; // $f1
  float v10; // $f0
  float v11; // $f1
  float v12; // $f0
  float v13; // $f20
  __int64 v14; // $a1
  float v15; // $f23
  __int64 v16; // $a2
  float v17; // $f1
  float v18; // $f0
  unsigned int v19; // $a0
  __int64 v20; // $v0
  float v21; // $f1
  float v22; // $f0
  float v23; // $f1
  float v24; // $f0
  float v25; // $f1
  float v26; // $f0
  float v27; // $f0
  float v28; // $f23
  __int64 v29; // $v0
  float v30; // $f1
  float v31; // $f1
  float v32; // $f0
  float v33; // $f1
  float v34; // $f0
  unsigned __int64 v35; // $a0
  float v36; // $f1
  float v37; // $f0
  __int64 v38; // $a1
  float v39; // $f1
  float v40; // $f0
  __int64 v41; // $a0
  float v42; // $f20
  __int64 v43; // $s1
  float v44; // $f1
  float v45; // $f0
  __int64 v46; // $v0
  float v47; // $f1
  float v48; // $f0
  float v49; // $f1
  __int64 v50; // $v0
  float v51; // $f1
  __int64 v52; // $v0
  float v53; // $f1
  __int64 v54; // $v0
  float v55; // $f3
  __int64 v56; // $v0
  float v57; // $f3
  __int64 v58; // $v0
  float v59; // $f3
  float v60; // $f0
  unsigned __int64 v61; // $v1
  float v62; // $f1
  float v63; // $f0
  float v64; // $f1
  float v65; // $f0
  int v66; // $v1
  float v67; // $f1
  float v68; // $f0
  __int64 i; // $v1
  float v70; // $f1
  float v71; // $f0
  float v72; // $f1
  float v73; // $f0
  __int64 v74; // $a2
  float v75; // $f1
  float v76; // $f22
  float v77; // $f20
  __int64 v78; // $a1
  float v79; // $f2
  float v80; // $f2
  float v81; // $f2
  float v82; // $f0
  float v83; // $f21
  unsigned __int64 v84; // $a0
  float v85; // $f1
  float v86; // $f0
  __int64 v87; // $v1
  float v88; // $f1
  float v89; // $f0
  float v90; // $f4
  __int64 v91; // $a1
  float v92; // $f1
  float v93; // $f1
  float v94; // $f3
  float v95; // $f2
  float v96; // $f1
  unsigned __int64 v97; // $a0
  float v98; // $f1
  float v99; // $f0
  int v100; // $a0
  __int64 v101; // $a2
  unsigned __int8 v102; // $s1
  __int64 v103; // $a1
  float v104; // $f0
  float v105; // $f1
  float v106; // $f1
  unsigned __int8 v107; // $a0
  __int64 v108; // $a0
  unsigned int v109; // $v0
  char v110; // $a0
  char v111; // $v1
  __int64 v112; // $a2
  float v113; // $f3
  __int64 v114; // $a1
  __int64 v115; // $v1
  float v116; // $f1
  __int64 v117; // $a0
  __int64 j; // $s1
  int v119; // $v1
  __int64 k; // $s1
  int v121; // $v1
  __int64 v122; // $v1
  int v123; // $a2
  __int64 v124; // $a1
  __int64 v125; // $a1
  _BYTE *v126; // $s2
  __int64 v127; // $a0
  __int16 v128; // $v0
  __int16 v129; // $v0
  __int16 v130; // $v0
  float v131; // [sp+78h] [-108h]
  float v132; // [sp+7Ch] [-104h]
  float v133; // [sp+88h] [-F8h]
  float v134; // [sp+8Ch] [-F4h]
  float v135; // [sp+90h] [-F0h]
  float v136[4]; // [sp+98h] [-E8h] BYREF
  float v137[4]; // [sp+A8h] [-D8h] BYREF
  float v138[4]; // [sp+B8h] [-C8h] BYREF
  float v139[4]; // [sp+C8h] [-B8h] BYREF
  float v140; // [sp+D8h] [-A8h] BYREF
  float v141; // [sp+DCh] [-A4h]
  float v142; // [sp+E0h] [-A0h]
  float v143; // [sp+E8h] [-98h]
  float v144; // [sp+ECh] [-94h]
  float v145; // [sp+F0h] [-90h]
  float v146; // [sp+F8h] [-88h]
  float v147; // [sp+FCh] [-84h]
  float v148; // [sp+100h] [-80h]
  float v149; // [sp+108h] [-78h] BYREF
  float v150; // [sp+10Ch] [-74h]
  float v151; // [sp+110h] [-70h]
  float v152; // [sp+118h] [-68h] BYREF
  float v153; // [sp+11Ch] [-64h]
  float v154; // [sp+120h] [-60h]
  float v155; // [sp+128h] [-58h] BYREF
  float v156; // [sp+12Ch] [-54h]
  float v157; // [sp+130h] [-50h]
  float v158[4]; // [sp+138h] [-48h] BYREF
  float v159; // [sp+148h] [-38h] BYREF
  float v160; // [sp+14Ch] [-34h]
  float v161; // [sp+150h] [-30h]
  float v162; // [sp+158h] [-28h] BYREF
  float v163; // [sp+15Ch] [-24h]
  float v164; // [sp+160h] [-20h]
  float v165; // [sp+168h] [-18h] BYREF
  float v166; // [sp+16Ch] [-14h]
  float v167; // [sp+170h] [-10h]
  _BYTE v168[4]; // [sp+178h] [-8h] BYREF
  _BYTE v169[4]; // [sp+17Ch] [-4h] BYREF

  if ( a1 != 0 )
  {
    v2 = *(_DWORD *)(a1 + 40);
    if ( (v2 & 0x20) != 0 )
    {
      v3 = *(int *)(a1 + 308);
      *(_DWORD *)(a1 + 40) = v2 & 0xFFFFFFDF;
      *(_DWORD *)(a1 + 308) = 0;
    }
    else
    {
      v3 = (v2 & 8) == 0;
    }
    if ( v3 < 0 )
      v3 = 0;
    v4 = *(_DWORD *)(a1 + 40);
    if ( (v4 & 0x10) != 0 )
    {
      *(_DWORD *)(a1 + 40) = v4 | 0x8000000;
      v5 = *(float *)(a1 + 148);
      v6 = *(float *)(a1 + 152);
      v165 = *(float *)(a1 + 144);
      v166 = v5;
      v167 = v6;
      sub_269C70(v158, &v165, *(float *)(a1 + 184));
      v7 = v158[1];
      v8 = v158[2];
      *(float *)(a1 + 4) = v158[0];
      *(float *)(a1 + 8) = v7;
      *(float *)(a1 + 12) = v8;
      v9 = *(float *)(a1 + 148);
      v10 = *(float *)(a1 + 152);
      *(_DWORD *)(a1 + 16) = *(_DWORD *)(a1 + 144);
      *(float *)(a1 + 20) = v9;
      *(float *)(a1 + 24) = v10;
      v11 = *(float *)(a1 + 160);
      v12 = *(float *)(a1 + 164);
      v162 = *(float *)(a1 + 156);
      v163 = v11;
      v164 = v12;
      v13 = *(float *)(a1 + 188);
      sub_269C70(&v155, &v162, v13);
      v149 = *(float *)(a1 + 156) - *(float *)(a1 + 144);
      v150 = *(float *)(a1 + 160) - *(float *)(a1 + 148);
      v151 = *(float *)(a1 + 164) - *(float *)(a1 + 152);
      v16 = *(int *)(a1 + 192);
      if ( *(_DWORD *)(a1 + 192) == 0 )
        goto LABEL_9;
      switch ( *(_BYTE *)(a1 + 140) )
      {
        case 0:
          v20 = *(int *)(a1 + 196);
          if ( v20 < 0 )
            v21 = (float)((*(_DWORD *)(a1 + 196) >> 1) | *(_DWORD *)(a1 + 196) & 1u)
                + (float)((*(_DWORD *)(a1 + 196) >> 1) | *(_DWORD *)(a1 + 196) & 1u);
          else
            v21 = (float)(int)v20;
          if ( v16 < 0 )
            v22 = (float)((*(_DWORD *)(a1 + 192) >> 1) | *(_DWORD *)(a1 + 192) & 1u)
                + (float)((*(_DWORD *)(a1 + 192) >> 1) | *(_DWORD *)(a1 + 192) & 1u);
          else
            v22 = (float)(int)v16;
          v159 = (float)(v165 + 0.0) + (float)((float)(v21 / v22) * (float)(v162 - v165));
          v160 = (float)(v166 + 0.0) + (float)((float)(v21 / v22) * (float)(v163 - v166));
          v161 = (float)(v167 + 0.0) + (float)((float)(v21 / v22) * (float)(v164 - v167));
          sub_269C70(&v152, &v159, (float)(v15 + 0.0) + (float)((float)(v21 / v22) * (float)(v13 - v15)));
          v23 = v153;
          v24 = v154;
          *(float *)(a1 + 4) = v152;
          *(float *)(a1 + 8) = v23;
          *(float *)(a1 + 12) = v24;
          v25 = v160;
          v26 = v161;
          *(float *)(a1 + 16) = v159;
          *(float *)(a1 + 20) = v25;
          *(float *)(a1 + 24) = v26;
          break;
        case 1:
        case 2:
        case 3:
        case 4:
        case 5:
          v27 = sub_26CBA0(*(unsigned __int8 *)(a1 + 140), v14);
          v29 = *(int *)(a1 + 192);
          if ( v29 < 0 )
            v30 = (float)((*(_DWORD *)(a1 + 192) >> 1) | *(_DWORD *)(a1 + 192) & 1u)
                + (float)((*(_DWORD *)(a1 + 192) >> 1) | *(_DWORD *)(a1 + 192) & 1u);
          else
            v30 = (float)(int)v29;
          v159 = (float)(v165 + 0.0) + (float)((float)(v27 / v30) * (float)(v162 - v165));
          v160 = (float)(v166 + 0.0) + (float)((float)(v27 / v30) * (float)(v163 - v166));
          v161 = (float)(v167 + 0.0) + (float)((float)(v27 / v30) * (float)(v164 - v167));
          sub_269C70(&v152, &v159, (float)(v28 + 0.0) + (float)((float)(v27 / v30) * (float)(v13 - v28)));
          v31 = v153;
          v32 = v154;
          *(float *)(a1 + 4) = v152;
          *(float *)(a1 + 8) = v31;
          *(float *)(a1 + 12) = v32;
          v33 = v160;
          v34 = v161;
          *(float *)(a1 + 16) = v159;
          *(float *)(a1 + 20) = v33;
          *(float *)(a1 + 24) = v34;
          break;
        default:
          break;
      }
      v35 = *(int *)(a1 + 196);
      if ( v35 < *(int *)(a1 + 192) )
      {
        *(_DWORD *)(a1 + 196) = v35 + v3;
      }
      else
      {
LABEL_9:
        v17 = v156;
        v18 = v157;
        *(float *)(a1 + 4) = v155;
        *(float *)(a1 + 8) = v17;
        *(float *)(a1 + 12) = v18;
        v149 = v162 - v155;
        v150 = v163 - v156;
        v151 = v164 - v157;
        sub_269DB0((int)a1 + 16, (int)&v149);
        v19 = *(_DWORD *)(a1 + 40) & 0xFFFFFFEF;
        *(_DWORD *)(a1 + 40) = v19;
        *(_DWORD *)(a1 + 40) = v19 & 0xF7FFFFFF;
      }
    }
    else
    {
      if ( (v4 & 1) != 0 )
      {
        v36 = *(float *)(a1 + 64);
        v37 = *(float *)(a1 + 68);
        v146 = *(float *)(a1 + 60);
        v147 = v36;
        v148 = v37;
        v38 = (int)a1 + 4;
        v39 = *(float *)(a1 + 8);
        v40 = *(float *)(a1 + 12);
        v143 = *(float *)(a1 + 4);
        v144 = v39;
        v145 = v40;
        v41 = *(unsigned __int8 *)(a1 + 84);
        if ( *(_BYTE *)(a1 + 84) != 0 )
        {
          if ( v41 == 1 )
          {
            v140 = v146 - *(float *)(a1 + 48);
            v141 = v147 - *(float *)(a1 + 52);
            v142 = v148 - *(float *)(a1 + 56);
            v46 = *(int *)(a1 + 100);
            if ( *(_DWORD *)(a1 + 100) != 0 )
            {
              if ( v46 < 0 )
                v49 = (float)((*(_DWORD *)(a1 + 100) >> 1) | *(_DWORD *)(a1 + 100) & 1u)
                    + (float)((*(_DWORD *)(a1 + 100) >> 1) | *(_DWORD *)(a1 + 100) & 1u);
              else
                v49 = (float)(int)v46;
              v140 = v140 / v49;
              v50 = *(int *)(a1 + 100);
              if ( v50 < 0 )
                v51 = (float)((*(_DWORD *)(a1 + 100) >> 1) | *(_DWORD *)(a1 + 100) & 1u)
                    + (float)((*(_DWORD *)(a1 + 100) >> 1) | *(_DWORD *)(a1 + 100) & 1u);
              else
                v51 = (float)(int)v50;
              v141 = v141 / v51;
              v52 = *(int *)(a1 + 100);
              if ( v52 < 0 )
                v53 = (float)((*(_DWORD *)(a1 + 100) >> 1) | *(_DWORD *)(a1 + 100) & 1u)
                    + (float)((*(_DWORD *)(a1 + 100) >> 1) | *(_DWORD *)(a1 + 100) & 1u);
              else
                v53 = (float)(int)v52;
              v142 = v142 / v53;
              switch ( *(_BYTE *)(a1 + 44) )
              {
                case 0:
                  v54 = *(int *)(a1 + 96);
                  if ( v54 < 0 )
                    v55 = (float)((*(_DWORD *)(a1 + 96) >> 1) | *(_DWORD *)(a1 + 96) & 1u)
                        + (float)((*(_DWORD *)(a1 + 96) >> 1) | *(_DWORD *)(a1 + 96) & 1u);
                  else
                    v55 = (float)(int)v54;
                  *(float *)(a1 + 4) = (float)(*(float *)(a1 + 48) + 0.0) + (float)(v140 * v55);
                  v56 = *(int *)(a1 + 96);
                  if ( v56 < 0 )
                    v57 = (float)((*(_DWORD *)(a1 + 96) >> 1) | *(_DWORD *)(a1 + 96) & 1u)
                        + (float)((*(_DWORD *)(a1 + 96) >> 1) | *(_DWORD *)(a1 + 96) & 1u);
                  else
                    v57 = (float)(int)v56;
                  *(float *)(a1 + 8) = (float)(*(float *)(a1 + 52) + 0.0) + (float)(v141 * v57);
                  v58 = *(int *)(a1 + 96);
                  if ( v58 < 0 )
                    v59 = (float)((*(_DWORD *)(a1 + 96) >> 1) | *(_DWORD *)(a1 + 96) & 1u)
                        + (float)((*(_DWORD *)(a1 + 96) >> 1) | *(_DWORD *)(a1 + 96) & 1u);
                  else
                    v59 = (float)(int)v58;
                  *(float *)(a1 + 12) = (float)(*(float *)(a1 + 56) + 0.0) + (float)(v142 * v59);
                  break;
                case 1:
                case 2:
                case 3:
                case 4:
                case 5:
                  v60 = sub_26CBA0(*(unsigned __int8 *)(a1 + 44), v38);
                  *(float *)(a1 + 4) = (float)(*(float *)(a1 + 48) + 0.0) + (float)(v140 * v60);
                  *(float *)(a1 + 8) = (float)(*(float *)(a1 + 52) + 0.0) + (float)(v141 * v60);
                  *(float *)(a1 + 12) = (float)(*(float *)(a1 + 56) + 0.0) + (float)(v142 * v60);
                  break;
                default:
                  break;
              }
              v61 = *(int *)(a1 + 96);
              if ( v61 < *(int *)(a1 + 100) )
              {
                *(_DWORD *)(a1 + 96) = v61 + v3;
              }
              else
              {
                v62 = v147;
                v63 = v148;
                *(float *)(a1 + 4) = v146;
                *(float *)(a1 + 8) = v62;
                *(float *)(a1 + 12) = v63;
                *(_DWORD *)(a1 + 40) &= ~1u;
              }
            }
            else
            {
              v47 = v147;
              v48 = v148;
              *(float *)v38 = v146;
              *(float *)(a1 + 8) = v47;
              *(float *)(a1 + 12) = v48;
              *(_DWORD *)(a1 + 40) &= ~1u;
            }
            sub_146A10(a1, (int)a1 + 4, 0, 0);
          }
          else if ( v41 == 2 )
          {
            sub_26CEF0(*(int *)(a1 + 88), (int)v138, (int)v137);
            v64 = *(float *)(a1 + 100);
            v65 = *(float *)(a1 + 96);
            if ( v65 >= v64 )
            {
              v66 = *(_DWORD *)(a1 + 40);
              if ( (v66 & 0x40) != 0 )
                *(float *)(a1 + 96) = v65 - v64;
              else
                *(_DWORD *)(a1 + 40) = v66 & 0xFFFFFFFE;
            }
            v67 = v138[1];
            v68 = v138[2];
            *(float *)(a1 + 4) = v138[0];
            *(float *)(a1 + 8) = v67;
            *(float *)(a1 + 12) = v68;
            for ( i = 0; i < v3; i = (int)i + 1 )
              *(float *)(a1 + 96) = *(float *)(a1 + 96) + *(float *)(a1 + 92);
            sub_146A10(a1, (int)a1 + 4, 0, 0);
            if ( (*(_DWORD *)(a1 + 40) & 8LL) == 0 )
            {
              v70 = v137[1];
              v71 = v137[2];
              *(float *)(a1 + 16) = v137[0];
              *(float *)(a1 + 20) = v70;
              *(float *)(a1 + 24) = v71;
              sub_146A10(a1, 0, (int)a1 + 16, 0);
            }
          }
        }
        else
        {
          v140 = v146 - v143;
          v141 = v147 - v144;
          v142 = v148 - v145;
          v42 = sub_3E4180((int)&v140);
          v43 = v3;
          while ( v42 > *(float *)(a1 + 92) )
          {
            sub_3E40B0((int)v139, (int)&v140);
            if ( v43 > 0 )
            {
              *(float *)(a1 + 4) = (float)(*(float *)(a1 + 4) + 0.0) + (float)(v139[0] * *(float *)(a1 + 92));
              *(float *)(a1 + 8) = (float)(*(float *)(a1 + 8) + 0.0) + (float)(v139[1] * *(float *)(a1 + 92));
              *(float *)(a1 + 12) = (float)(*(float *)(a1 + 12) + 0.0) + (float)(v139[2] * *(float *)(a1 + 92));
            }
            v43 = (int)v43 - 1;
            if ( v43 <= 0 )
              goto LABEL_32;
          }
          v44 = v147;
          v45 = v148;
          *(float *)(a1 + 4) = v146;
          *(float *)(a1 + 8) = v44;
          *(float *)(a1 + 12) = v45;
          *(_DWORD *)(a1 + 40) &= ~1u;
LABEL_32:
          sub_146A10(a1, (int)a1 + 4, 0, 0);
        }
      }
      if ( (*(_DWORD *)(a1 + 40) & 4LL) != 0 )
      {
        if ( *(_DWORD *)(a1 + 132) != 0 )
        {
          if ( *(_DWORD *)(a1 + 136) != 0 )
          {
            sub_26C770((int)a1 + 104, (int)a1 + 116, (int)v136);
            v74 = *(int *)(a1 + 132);
            if ( v74 < 0 )
              v75 = (float)((*(_DWORD *)(a1 + 132) >> 1) | *(_DWORD *)(a1 + 132) & 1u)
                  + (float)((*(_DWORD *)(a1 + 132) >> 1) | *(_DWORD *)(a1 + 132) & 1u);
            else
              v75 = (float)(int)v74;
            v76 = v136[0] / v75;
            v77 = v136[2] / v75;
            switch ( *(_BYTE *)(a1 + 129) )
            {
              case 0:
                v78 = *(int *)(a1 + 136);
                if ( v78 < 0 )
                  v79 = (float)((*(_DWORD *)(a1 + 136) >> 1) | *(_DWORD *)(a1 + 136) & 1u)
                      + (float)((*(_DWORD *)(a1 + 136) >> 1) | *(_DWORD *)(a1 + 136) & 1u);
                else
                  v79 = (float)(int)v78;
                v133 = (float)(*(float *)(a1 + 104) + 0.0) + (float)(v76 * v79);
                if ( v78 < 0 )
                  v80 = (float)((*(_DWORD *)(a1 + 136) >> 1) | *(_DWORD *)(a1 + 136) & 1u)
                      + (float)((*(_DWORD *)(a1 + 136) >> 1) | *(_DWORD *)(a1 + 136) & 1u);
                else
                  v80 = (float)(int)v78;
                v134 = (float)(*(float *)(a1 + 108) + 0.0) + (float)((float)(v136[1] / v75) * v80);
                if ( v78 < 0 )
                  v81 = (float)((*(_DWORD *)(a1 + 136) >> 1) | *(_DWORD *)(a1 + 136) & 1u)
                      + (float)((*(_DWORD *)(a1 + 136) >> 1) | *(_DWORD *)(a1 + 136) & 1u);
                else
                  v81 = (float)(int)v78;
                v135 = (float)(*(float *)(a1 + 112) + 0.0) + (float)(v77 * v81);
                break;
              case 1:
              case 2:
              case 3:
              case 4:
              case 5:
                v82 = sub_26CBA0(*(unsigned __int8 *)(a1 + 129), *(unsigned __int8 *)(a1 + 129));
                v133 = (float)(*(float *)(a1 + 104) + 0.0) + (float)(v76 * v82);
                v134 = (float)(*(float *)(a1 + 108) + 0.0) + (float)(v83 * v82);
                v135 = (float)(*(float *)(a1 + 112) + 0.0) + (float)(v77 * v82);
                break;
              default:
                break;
            }
            *(float *)(a1 + 16) = v133;
            *(float *)(a1 + 20) = v134;
            *(float *)(a1 + 24) = v135;
            v84 = *(int *)(a1 + 136);
            if ( v84 < *(int *)(a1 + 132) )
            {
              *(_DWORD *)(a1 + 136) = v84 + v3;
            }
            else
            {
              v85 = *(float *)(a1 + 120);
              v86 = *(float *)(a1 + 124);
              *(_DWORD *)(a1 + 16) = *(_DWORD *)(a1 + 116);
              *(float *)(a1 + 20) = v85;
              *(float *)(a1 + 24) = v86;
              *(_DWORD *)(a1 + 40) &= ~4u;
            }
            if ( v3 != 0 )
              sub_146A10(a1, 0, (int)a1 + 16, 0);
          }
          else
          {
            *(_DWORD *)(a1 + 136) = v3;
          }
        }
        else
        {
          v72 = *(float *)(a1 + 120);
          v73 = *(float *)(a1 + 124);
          *(_DWORD *)(a1 + 16) = *(_DWORD *)(a1 + 116);
          *(float *)(a1 + 20) = v72;
          *(float *)(a1 + 24) = v73;
          *(_DWORD *)(a1 + 40) &= ~4u;
          sub_146A10(a1, 0, (int)a1 + 16, 0);
        }
      }
      if ( (*(_DWORD *)(a1 + 40) & 0x8000000LL) == 0 )
        sub_26C680((int)a1 + 16);
    }
    if ( (*(_DWORD *)(a1 + 40) & 0x8000LL) != 0 )
    {
      v87 = *(int *)(a1 + 224);
      if ( *(_DWORD *)(a1 + 224) != 0 )
      {
        if ( v87 < 0 )
          v90 = (float)((*(_DWORD *)(a1 + 224) >> 1) | *(_DWORD *)(a1 + 224) & 1u)
              + (float)((*(_DWORD *)(a1 + 224) >> 1) | *(_DWORD *)(a1 + 224) & 1u);
        else
          v90 = (float)(int)v87;
        v91 = *(int *)(a1 + 228);
        if ( v91 < 0 )
          v92 = (float)((*(_DWORD *)(a1 + 228) >> 1) | *(_DWORD *)(a1 + 228) & 1u)
              + (float)((*(_DWORD *)(a1 + 228) >> 1) | *(_DWORD *)(a1 + 228) & 1u);
        else
          v92 = (float)(int)v91;
        v131 = (float)(*(float *)(a1 + 200) + 0.0)
             + (float)((float)((float)(*(float *)(a1 + 212) - *(float *)(a1 + 200)) / v90) * v92);
        if ( v91 < 0 )
          v93 = (float)((*(_DWORD *)(a1 + 228) >> 1) | *(_DWORD *)(a1 + 228) & 1u)
              + (float)((*(_DWORD *)(a1 + 228) >> 1) | *(_DWORD *)(a1 + 228) & 1u);
        else
          v93 = (float)(int)v91;
        v132 = (float)(*(float *)(a1 + 204) + 0.0)
             + (float)((float)((float)(*(float *)(a1 + 216) - *(float *)(a1 + 204)) / v90) * v93);
        v94 = *(float *)(a1 + 208);
        v95 = (float)(*(float *)(a1 + 220) - v94) / v90;
        if ( v91 < 0 )
          v96 = (float)((*(_DWORD *)(a1 + 228) >> 1) | *(_DWORD *)(a1 + 228) & 1u)
              + (float)((*(_DWORD *)(a1 + 228) >> 1) | *(_DWORD *)(a1 + 228) & 1u);
        else
          v96 = (float)(int)v91;
        *(float *)(a1 + 28) = v131;
        *(float *)(a1 + 32) = v132;
        *(float *)(a1 + 36) = (float)(v94 + 0.0) + (float)(v95 * v96);
        v97 = *(int *)(a1 + 228);
        if ( v97 < *(int *)(a1 + 224) )
        {
          *(_DWORD *)(a1 + 228) = v97 + v3;
        }
        else
        {
          v98 = *(float *)(a1 + 216);
          v99 = *(float *)(a1 + 220);
          *(_DWORD *)(a1 + 28) = *(_DWORD *)(a1 + 212);
          *(float *)(a1 + 32) = v98;
          *(float *)(a1 + 36) = v99;
          *(_DWORD *)(a1 + 40) &= ~0x8000u;
        }
        if ( v3 != 0 )
          sub_146A10(a1, 0, 0, (int)a1 + 28);
      }
      else
      {
        v88 = *(float *)(a1 + 216);
        v89 = *(float *)(a1 + 220);
        *(_DWORD *)(a1 + 28) = *(_DWORD *)(a1 + 212);
        *(float *)(a1 + 32) = v88;
        *(float *)(a1 + 36) = v89;
        *(_DWORD *)(a1 + 40) &= ~0x8000u;
        sub_146A10(a1, 0, 0, (int)a1 + 28);
      }
    }
    v100 = *(_DWORD *)(a1 + 40);
    if ( (v100 & 0x4000) != 0 )
    {
      v101 = *(int *)(a1 + 248);
      if ( *(_DWORD *)(a1 + 248) != 0 )
      {
        v103 = *(int *)(a1 + 252);
        if ( v103 < (unsigned __int64)v101 )
        {
          if ( v101 < 0 )
            v104 = (float)((*(_DWORD *)(a1 + 248) >> 1) | *(_DWORD *)(a1 + 248) & 1u)
                 + (float)((*(_DWORD *)(a1 + 248) >> 1) | *(_DWORD *)(a1 + 248) & 1u);
          else
            v104 = (float)(int)v101;
          if ( v103 < 0 )
            v105 = (float)((*(_DWORD *)(a1 + 252) >> 1) | *(_DWORD *)(a1 + 252) & 1u)
                 + (float)((*(_DWORD *)(a1 + 252) >> 1) | *(_DWORD *)(a1 + 252) & 1u);
          else
            v105 = (float)(int)v103;
          v106 = (float)((float)*(unsigned __int8 *)(a1 + 244) + 0.0)
               + (float)((float)((float)((float)*(unsigned __int8 *)(a1 + 245) - (float)*(unsigned __int8 *)(a1 + 244))
                               / v104)
                       * v105);
          if ( v106 >= 2147483600.0 )
            v107 = (int)(float)(v106 - 2147483600.0);
          else
            v107 = (int)v106;
          v102 = v107;
          *(_DWORD *)(a1 + 252) += v3;
        }
        else
        {
          v102 = *(_BYTE *)(a1 + 245);
          *(_DWORD *)(a1 + 40) = v100 & 0xFFFFBFFF;
        }
      }
      else
      {
        v102 = *(_BYTE *)(a1 + 245);
        *(_DWORD *)(a1 + 40) = v100 & 0xFFFFBFFF;
      }
      v108 = (*(_WORD *)a1 & 0xFC00) >> 10;
      if ( v108 == 6 )
      {
        sub_4B14F0(*(int *)(a1 + 324), (int)v168);
        v168[3] = v102;
        sub_4B13F0(*(int *)(a1 + 324), (int)v168);
      }
      else if ( v108 == 3 )
      {
        v109 = sub_47A250(*(int *)(a1 + 356));
        v110 = *(_BYTE *)(v109 + 1);
        v111 = *(_BYTE *)(v109 + 2);
        v169[0] = *(_BYTE *)v109;
        v169[1] = v110;
        v169[2] = v111;
        v169[3] = v102;
        if ( v102 == 255 || *(_BYTE *)(a1 + 256) == 0 )
          sub_47A870(*(int *)(a1 + 356));
        else
          sub_47A850(*(int *)(a1 + 356));
        sub_47A220(*(int *)(a1 + 356), (int)v169);
      }
    }
    if ( (*(_DWORD *)(a1 + 40) & 0x400LL) != 0 && (*(_WORD *)a1 & 0xFC00) >> 10 == 7 )
    {
      v112 = *(int *)(a1 + 268);
      v113 = *(float *)(a1 + 264);
      v114 = *(int *)(a1 + 272);
      if ( v112 > 0 )
      {
        v115 = *(int *)(a1 + 96);
        if ( v115 < 0 )
          v116 = (float)((*(_DWORD *)(a1 + 96) >> 1) | *(_DWORD *)(a1 + 96) & 1u)
               + (float)((*(_DWORD *)(a1 + 96) >> 1) | *(_DWORD *)(a1 + 96) & 1u);
        else
          v116 = (float)(int)v115;
        *(float *)(a1 + 320) = (float)(*(float *)(a1 + 260) + 0.0)
                             + (float)((float)((float)(v113 - *(float *)(a1 + 260)) / (float)(int)v112) * v116);
        if ( v114 < v112 )
        {
          *(_DWORD *)(a1 + 272) += v3;
        }
        else
        {
          *(float *)(a1 + 320) = v113;
          *(_DWORD *)(a1 + 40) &= ~0x400u;
        }
      }
      else
      {
        *(float *)(a1 + 320) = v113;
        *(_DWORD *)(a1 + 40) &= ~0x400u;
      }
    }
    v117 = (*(_WORD *)a1 & 0xFC00) >> 10;
    if ( v117 == 1 )
    {
      for ( j = 0; j < 2; j = (int)j + 1 )
      {
        v119 = a1 + 4 * j;
        if ( *(_DWORD *)(v119 + 320) != 0 )
          sub_4B1190(*(int *)(v119 + 320));
      }
    }
    else if ( v117 == 3 )
    {
      for ( k = 0; k < 2; k = (int)k + 1 )
      {
        v121 = a1 + 4 * k;
        if ( *(_DWORD *)(v121 + 320) != 0 )
          sub_4B1190(*(int *)(v121 + 320));
      }
    }
    else if ( v117 == 6 && *(_DWORD *)(a1 + 324) != 0 )
    {
      sub_4B1190(*(int *)(a1 + 324));
    }
    if ( (*(_DWORD *)(a1 + 40) & 0x2000LL) != 0 )
    {
      v122 = 0;
      v123 = 0;
      v124 = (*(_WORD *)a1 & 0xFC00) >> 10;
      switch ( v124 )
      {
        case 3LL:
          v122 = (int)a1 + 332;
          v123 = *(_DWORD *)(a1 + 356);
          break;
        case 2LL:
          v122 = (int)a1 + 320;
          v123 = *(_DWORD *)(a1 + 344);
          break;
        case 1LL:
          v122 = (int)a1 + 332;
          v123 = *(_DWORD *)(a1 + 356);
          break;
        default:
          break;
      }
      if ( v122 != 0 )
      {
        v125 = *(int *)v122;
        if ( *(_BYTE *)(164 * v125 + v123 + 238) == 1 )
        {
          sub_269820(a1, v125, *(int *)(v122 + 4), *(int *)(v122 + 8), *(int *)(v122 + 12), *(int *)(v122 + 16));
          *(_DWORD *)(a1 + 40) &= ~0x2000u;
        }
      }
    }
    v126 = (_BYTE *)(a1 + 232);
    v127 = *(unsigned __int8 *)(a1 + 232);
    if ( v127 == 2 || v127 == 1 )
    {
      if ( v127 == 1 )
      {
        if ( (*(_DWORD *)(a1 + 40) & 1LL) == 0 )
        {
          *v126 = 0;
          v128 = sub_26BA60((int)a1 + 4);
          if ( *(_BYTE *)(a1 + 234) == 1 )
          {
            sub_45AF60(0, *(unsigned __int8 *)(a1 + 235), 2, (__int16)(*(unsigned __int8 *)(a1 + 233) + 24));
          }
          else if ( *(_BYTE *)(a1 + 234) == 0 )
          {
            sub_45AF60(0, *(unsigned __int8 *)(a1 + 235), 1, (__int16)(*(unsigned __int8 *)(a1 + 233) + 4 * v128));
          }
          if ( (unsigned __int8)++*(_BYTE *)(a1 + 233) >= 4uLL )
            *(_BYTE *)(a1 + 233) = 0;
          return;
        }
        goto LABEL_195;
      }
      if ( (*(_DWORD *)(a1 + 40) & 4LL) != 0 )
      {
LABEL_195:
        if ( v3 != 0 )
        {
          if ( *(_WORD *)(a1 + 240) != 0 )
          {
            --*(_WORD *)(a1 + 240);
          }
          else
          {
            if ( *(_WORD *)(a1 + 236) == 0 )
            {
              v130 = sub_26BA60((int)a1 + 4);
              if ( *(_BYTE *)(a1 + 234) == 1 )
              {
                sub_45AF60(0, *(unsigned __int8 *)(a1 + 235), 2, (__int16)(*(unsigned __int8 *)(a1 + 233) + 24));
              }
              else if ( *(_BYTE *)(a1 + 234) == 0 )
              {
                sub_45AF60(0, *(unsigned __int8 *)(a1 + 235), 1, (__int16)(*(unsigned __int8 *)(a1 + 233) + 4 * v130));
              }
              if ( (unsigned __int8)++*(_BYTE *)(a1 + 233) >= 4uLL )
                *(_BYTE *)(a1 + 233) = 0;
            }
            if ( (unsigned __int16)++*(_WORD *)(a1 + 236) >= (__int64)*(unsigned __int16 *)(a1 + 238) )
            {
              if ( *(_WORD *)(a1 + 238) != 0 )
                *(_WORD *)(a1 + 236) = 0;
              else
                *v126 = 0;
            }
          }
        }
        return;
      }
      *v126 = 0;
      v129 = sub_26BA60((int)a1 + 4);
      if ( *(_BYTE *)(a1 + 234) == 1 )
      {
        sub_45AF60(0, *(unsigned __int8 *)(a1 + 235), 2, (__int16)(*(unsigned __int8 *)(a1 + 233) + 24));
      }
      else if ( *(_BYTE *)(a1 + 234) == 0 )
      {
        sub_45AF60(0, *(unsigned __int8 *)(a1 + 235), 1, (__int16)(*(unsigned __int8 *)(a1 + 233) + 4 * v129));
      }
      if ( (unsigned __int8)++*(_BYTE *)(a1 + 233) >= 4uLL )
        *(_BYTE *)(a1 + 233) = 0;
    }
  }
}


// func_0026ba60  addr 0x0026ba60  window 432B
__int64 __fastcall sub_26BA60(__int64 a1)
{
  int v1; // $gp
  __int64 v3; // $s0
  _DWORD *v4; // $v1
  int v5; // $v0
  __int64 v7; // $s1
  float v8; // $f3
  float v9; // $f2
  float v10; // $f3
  float v11; // $f2
  int v12; // [sp+50h] [-10h] BYREF
  int v13; // [sp+54h] [-Ch]
  int v14; // [sp+58h] [-8h]

  v3 = sub_1452B0(21);
  v4 = *(_DWORD **)(v1 - 25168);
  v5 = dword_5F08B0[*v4];
  if ( v5 == 0 )
    return 0;
  v7 = *(unsigned __int8 *)(v5 + v4[1]);
  while ( v3 != 0 )
  {
    v12 = v3 + 348;
    v13 = v3 + 360;
    v14 = v3 + 372;
    if ( sub_168EC0(a1, (int)&v12) == 1 )
    {
      v8 = *(float *)(v12 + 4);
      v9 = *(float *)(a1 + 4);
      if ( v9 < (float)(v8 + 100.0) && v9 > (float)(v8 - 100.0) )
        return *(int *)(v3 + 396);
    }
    v12 = v3 + 360;
    v13 = v3 + 372;
    v14 = v3 + 384;
    if ( sub_168EC0(a1, (int)&v12) == 1 )
    {
      v10 = *(float *)(v12 + 4);
      v11 = *(float *)(a1 + 4);
      if ( v11 < (float)(v10 + 100.0) && v11 > (float)(v10 - 100.0) )
        return *(int *)(v3 + 396);
    }
    v3 = *(int *)(v3 + 312);
  }
  return v7;
}


// func_0026bfc0  addr 0x0026bfc0  window 464B
__int64 __usercall sub_26BFC0@<$v0>(float *a1@<$a0>, float *a2@<$a1>, float a3@<$f12>)
{
  __int64 result; // $v0
  float v7; // $f1
  float v8; // $f0
  float v9; // $f1
  float v10; // $f0
  _DWORD v11[3]; // [sp+40h] [-B0h] BYREF
  int v12; // [sp+4Ch] [-A4h]
  int v13; // [sp+50h] [-A0h]
  int v14; // [sp+54h] [-9Ch]
  int v15; // [sp+58h] [-98h]
  int v16; // [sp+60h] [-90h]
  int v17; // [sp+64h] [-8Ch]
  int v18; // [sp+68h] [-88h]
  int v19; // [sp+70h] [-80h]
  int v20; // [sp+74h] [-7Ch]
  int v21; // [sp+78h] [-78h]
  __int64 v22; // [sp+80h] [-70h] BYREF
  float v23; // [sp+88h] [-68h]
  __int64 v24; // [sp+90h] [-60h] BYREF
  float v25; // [sp+98h] [-58h]
  __int64 v26; // [sp+A0h] [-50h] BYREF
  float v27; // [sp+A8h] [-48h]
  float v28; // [sp+B0h] [-40h]
  float v29; // [sp+B4h] [-3Ch]
  float v30; // [sp+B8h] [-38h]
  float v31; // [sp+C0h] [-30h]
  float v32[4]; // [sp+D0h] [-20h] BYREF
  __int64 v33; // [sp+E0h] [-10h] BYREF
  float v34; // [sp+E8h] [-8h]

  v33 = qword_63B120;
  v34 = flt_63B128;
  v26 = qword_63B130;
  v27 = flt_63B138;
  v24 = qword_63B140;
  v25 = flt_63B148;
  v22 = qword_63B150;
  v23 = flt_63B158;
  v18 = 1065353216;
  v14 = 1065353216;
  v11[0] = 1065353216;
  v13 = 0;
  v11[2] = 0;
  v11[1] = 0;
  v17 = 0;
  v16 = 0;
  v15 = 0;
  v21 = 0;
  v20 = 0;
  v19 = 0;
  v12 |= 0x20003u;
  sub_3E0870((int)v11, (int)&v24, 1);
  sub_3E0870((int)v11, (int)&v26, 1);
  sub_3E0870((int)v11, (int)&v22, 1);
  result = sub_3E4320((int)v32, (int)&v33, (int)v11);
  v7 = a1[1];
  v8 = a1[2];
  v31 = *a1;
  v28 = (float)(v31 + 0.0) - (float)(v32[0] * a3);
  v29 = (float)(v7 + 0.0) - (float)(v32[1] * a3);
  v30 = (float)(v8 + 0.0) - (float)(v32[2] * a3);
  v9 = v29;
  v10 = v30;
  *a2 = v28;
  a2[1] = v9;
  a2[2] = v10;
  return result;
}


// func_0026c190  addr 0x0026c190  window 384B
__int64 __usercall sub_26C190@<$v0>(float *a1@<$a0>, int a2@<$a1>, float a3@<$f12>)
{
  float v6; // $f1
  float v7; // $f0
  float v8; // $f1
  float v9; // $f0
  __int64 v10; // $v0
  int *v11; // $a2
  __int64 *v12; // $a1
  __int64 v13; // $a0
  int v14; // $v1
  int v15; // $v0
  __int64 result; // $v0
  float v17; // $f1
  float v18; // $f0
  _BYTE v19[64]; // [sp+40h] [-D0h] BYREF
  __int64 v20; // [sp+80h] [-90h] BYREF
  float v21; // [sp+88h] [-88h]
  float v22[4]; // [sp+C0h] [-50h] BYREF
  __int64 v23; // [sp+D0h] [-40h] BYREF
  float v24; // [sp+D8h] [-38h]
  float v25[4]; // [sp+E0h] [-30h] BYREF
  float v26[4]; // [sp+F0h] [-20h] BYREF
  float v27; // [sp+100h] [-10h] BYREF
  float v28; // [sp+104h] [-Ch]
  float v29; // [sp+108h] [-8h]

  v6 = *(float *)(a2 + 8);
  v7 = *(float *)(a2 + 12);
  v27 = *(float *)(a2 + 4);
  v28 = v6;
  v29 = v7;
  v8 = *(float *)(a2 + 20);
  v9 = *(float *)(a2 + 24);
  v26[0] = *(float *)(a2 + 16);
  v26[1] = v8;
  v26[2] = v9;
  if ( *(_WORD *)(a2 + 332) != 0 )
  {
    v10 = sub_145270(*(unsigned __int16 *)(a2 + 332));
    if ( v10 != 0 )
    {
      v27 = *(float *)(v10 + 4);
      v28 = *(float *)(v10 + 8);
      v29 = *(float *)(v10 + 12);
      a3 = *(float *)(a2 + 324);
      sub_146F50((int)v19, (int)&v27, (int)v26);
      v11 = (int *)v19;
      v12 = &v20;
      LODWORD(v13) = 8;
      do
      {
        v14 = *v11;
        v15 = v11[1];
        v11 += 2;
        v13 = (int)v13 - 1;
        *(_DWORD *)v12 = v14;
        *((_DWORD *)v12++ + 1) = v15;
      }
      while ( v13 > 0 );
      v23 = v20;
      v24 = v21;
      sub_3E40B0((int)v22, (int)&v23);
      v27 = (float)(v27 + 0.0) - (float)(15.0 * v22[0]);
      v29 = (float)(v29 + 0.0) - (float)(15.0 * v22[2]);
    }
  }
  result = sub_26BFC0(&v27, v25, a3);
  v17 = v25[1];
  v18 = v25[2];
  *a1 = v25[0];
  a1[1] = v17;
  a1[2] = v18;
  return result;
}

