/*
 * Generated by tools/ghidra_headstart.py -- Ghidra decompiler output.
 *
 * REFERENCE ONLY. This is not valid C and is never compiled.
 *
 * Ghidra pseudo-types (`undefined1 [16]`, `undefined4`, `code *`, `uint`,
 * `ulong`) and its `FUN_xxxxxxxx` / `DAT_xxxxxxxx` naming are decompiler
 * artifacts -- translate them into the project's own conventions
 * (s8/u8/s16/u16/s32/u32/s64/u64/f32 and the real func_xxxxxxxx names)
 * before writing any source.
 *
 * Why this corpus exists: Ghidra's Emotion Engine support models the PS2's
 * 128-bit register file and VU0 macro-mode ops (you will see
 * `undefined1 auVar [16]` and intrinsics like `_sqc2(...)`), where Hex-Rays
 * emits an opaque `__asm { }` island that hides the surrounding dataflow.
 * For ordinary integer code the Hex-Rays corpus in docs/ida_headstart is
 * usually the easier read. Use whichever is clean for your target; when both
 * are, cross-check them against each other and against the retail
 * disassembly from build/RECON_dis.py.
 *
 * Regenerate: python3 tools/ghidra_headstart.py --report <verify json>
 */


// func_00252230  addr 0x00252230  window 1248B
/* WARNING: Removing unreachable block (ram,0x00252640) */
/* WARNING: Removing unreachable block (ram,0x00252368) */
/* WARNING: Removing unreachable block (ram,0x002523ac) */
/* WARNING: Removing unreachable block (ram,0x0025267c) */
/* WARNING: Removing unreachable block (ram,0x00252550) */
/* WARNING: Removing unreachable block (ram,0x00252458) */
/* WARNING: Removing unreachable block (ram,0x0025249c) */
/* WARNING: Removing unreachable block (ram,0x00252594) */

void FUN_00252230(float param_1,int param_2,int param_3,int param_4)

{
  float fVar1;
  
  *(float *)(param_2 + 4) =
       param_1 * (*(float *)(param_4 + 4) - *(float *)(param_3 + 4)) + *(float *)(param_3 + 4) + 0.0
  ;
  *(float *)(param_2 + 8) =
       param_1 * (*(float *)(param_4 + 8) - *(float *)(param_3 + 8)) + *(float *)(param_3 + 8) + 0.0
  ;
  *(float *)(param_2 + 0xc) =
       param_1 * (*(float *)(param_4 + 0xc) - *(float *)(param_3 + 0xc)) +
       *(float *)(param_3 + 0xc) + 0.0;
  *(float *)(param_2 + 0x10) =
       param_1 * (*(float *)(param_4 + 0x10) - *(float *)(param_3 + 0x10)) +
       *(float *)(param_3 + 0x10) + 0.0;
  *(float *)(param_2 + 0x14) =
       param_1 * (*(float *)(param_4 + 0x14) - *(float *)(param_3 + 0x14)) +
       *(float *)(param_3 + 0x14) + 0.0;
  *(float *)(param_2 + 0x1c) =
       param_1 * (*(float *)(param_4 + 0x1c) - *(float *)(param_3 + 0x1c)) +
       *(float *)(param_3 + 0x1c) + 0.0;
  *(short *)(param_2 + 0x20) =
       (short)(int)(param_1 * ((float)(int)*(short *)(param_4 + 0x20) -
                              (float)(int)*(short *)(param_3 + 0x20)) +
                   (float)(int)*(short *)(param_3 + 0x20) + 0.0);
  *(short *)(param_2 + 0x22) =
       (short)(int)(param_1 * ((float)(int)*(short *)(param_4 + 0x22) -
                              (float)(int)*(short *)(param_3 + 0x22)) +
                   (float)(int)*(short *)(param_3 + 0x22) + 0.0);
  fVar1 = (float)(*(uint *)(param_3 + 0x18) >> 0x18);
  fVar1 = param_1 * ((float)(*(uint *)(param_4 + 0x18) >> 0x18) - fVar1) + fVar1 + 0.0;
  if (2.1474836e+09 <= fVar1) {
    fVar1 = fVar1 - 2.1474836e+09;
  }
  *(int *)(param_2 + 0x18) = (int)fVar1 << 0x18;
  fVar1 = (float)(*(uint *)(param_3 + 0x18) >> 0x10 & 0xff);
  fVar1 = param_1 * ((float)(*(uint *)(param_4 + 0x18) >> 0x10 & 0xff) - fVar1) + fVar1 + 0.0;
  if (2.1474836e+09 <= fVar1) {
    fVar1 = fVar1 - 2.1474836e+09;
  }
  *(uint *)(param_2 + 0x18) = *(uint *)(param_2 + 0x18) | ((int)fVar1 & 0xffU) << 0x10;
  fVar1 = (float)(*(uint *)(param_3 + 0x18) >> 8 & 0xff);
  fVar1 = param_1 * ((float)(*(uint *)(param_4 + 0x18) >> 8 & 0xff) - fVar1) + fVar1 + 0.0;
  if (2.1474836e+09 <= fVar1) {
    fVar1 = fVar1 - 2.1474836e+09;
  }
  *(uint *)(param_2 + 0x18) = *(uint *)(param_2 + 0x18) | ((int)fVar1 & 0xffU) << 8;
  fVar1 = param_1 * ((float)*(byte *)(param_4 + 0x18) - (float)*(byte *)(param_3 + 0x18)) +
          (float)*(byte *)(param_3 + 0x18) + 0.0;
  if (2.1474836e+09 <= fVar1) {
    fVar1 = fVar1 - 2.1474836e+09;
  }
  *(uint *)(param_2 + 0x18) = *(uint *)(param_2 + 0x18) | (int)fVar1 & 0xffU;
  return;
}


// func_00252710  addr 0x00252710  window 848B
bool FUN_00252710(undefined8 param_1,uint *param_2,int param_3,undefined8 param_4)

{
  bool bVar1;
  uint uVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  int iVar5;
  int iVar6;
  undefined4 *puVar7;
  undefined4 *puVar8;
  long extraout_t0;
  long extraout_t0_00;
  long lVar9;
  undefined4 auStack_90 [8];
  undefined1 auStack_70 [64];
  undefined1 auStack_30 [4];
  float fStack_2c;
  float fStack_28;
  undefined1 auStack_24 [12];
  uint uStack_18;
  undefined4 uStack_14;
  short sStack_10;
  undefined2 uStack_e;
  
  bVar1 = *(int *)(param_3 + 8) == 10;
  if ((*param_2 & 2) == 0) {
    param_2[1] = param_2[1] + 1;
  }
  uVar2 = param_2[1];
  if ((int)uVar2 < 0x1f) {
    iVar5 = FUN_00252230((float)(int)uVar2 / 30.0,auStack_30,param_2 + 3,param_2 + 0xc,param_4,bVar1
                        );
    lVar9 = extraout_t0_00;
  }
  else {
    iVar5 = FUN_00252230((float)(int)(uVar2 - 0x1e) / 30.0,auStack_30,param_2 + 0xc,param_2 + 0x15,
                         param_4,bVar1);
    lVar9 = extraout_t0;
  }
  if (lVar9 != 0) {
    if (uStack_18 == 0xffe92cff) {
      param_2[3] = 0;
      uStack_18 = 0xffffffff;
    }
    else {
      uStack_18 = 0xbfbfbfff;
    }
  }
  puVar8 = (undefined4 *)0x6361f0;
  puVar7 = auStack_90;
  iVar6 = 4;
  do {
    uVar3 = *puVar8;
    uVar4 = puVar8[1];
    puVar8 = puVar8 + 2;
    iVar6 = iVar6 + -1;
    *puVar7 = uVar3;
    puVar7[1] = uVar4;
    puVar7 = puVar7 + 2;
  } while (0 < iVar6);
  FUN_0025f360(0x18,0,*(undefined4 *)(iVar5 + 0x10));
  FUN_003e0870(uStack_14,auStack_70,auStack_24,0);
  if (param_2[3] == 1) {
    (*DAT_00887300)(7,2);
    (*DAT_00887300)(9,2);
    (*DAT_00887300)(6,1);
    (*DAT_00887300)(8,1);
    (*DAT_00887300)(0xc,1);
    (*DAT_00887300)(2,4);
    (*DAT_00887300)(0xe,0);
    FUN_003f6440(3,0x7000d);
    FUN_003f6440(2,0x48);
    FUN_00366c70(0,(int)fStack_2c,(int)fStack_28,sStack_10,uStack_e,uStack_18 >> 8,uStack_18 & 0xff,
                 0,sStack_10 >> 1);
  }
  else {
    FUN_00366c70(0,(int)fStack_2c,(int)fStack_28,sStack_10,uStack_e,uStack_18 >> 8,uStack_18 & 0xff,
                 1,sStack_10 >> 1);
  }
  return 0x3b < (int)uVar2;
}


// func_00252a60  addr 0x00252a60  window 3568B
/* WARNING: Removing unreachable block (ram,0x00253130) */
/* WARNING: Removing unreachable block (ram,0x002531e8) */

bool FUN_00252a60(undefined8 param_1,uint *param_2,int param_3)

{
  uint uVar1;
  undefined8 uVar2;
  short sVar3;
  uint uVar4;
  ulong uVar5;
  long lVar6;
  undefined4 uVar7;
  undefined4 uVar8;
  int iVar9;
  int iVar10;
  undefined4 *puVar11;
  undefined8 *puVar12;
  float *pfVar13;
  undefined4 *puVar14;
  float *pfVar15;
  uint *puVar16;
  float fVar17;
  float fVar18;
  float afStack_180 [12];
  undefined4 auStack_150 [8];
  undefined4 auStack_130 [8];
  undefined8 uStack_110;
  undefined4 auStack_108 [14];
  undefined4 auStack_d0 [16];
  undefined1 auStack_90 [64];
  undefined1 auStack_50 [4];
  float fStack_4c;
  float fStack_48;
  undefined1 auStack_44 [12];
  uint uStack_38;
  undefined4 uStack_34;
  short sStack_30;
  undefined2 uStack_2e;
  undefined8 uStack_28;
  undefined4 uStack_20;
  float fStack_18;
  float fStack_14;
  undefined8 uStack_10;
  undefined4 uStack_8;
  
  iVar10 = *(int *)(param_3 + 8);
  if ((*param_2 & 2) == 0) {
    param_2[1] = param_2[1] + 1;
  }
  uVar1 = param_2[1];
  if ((int)uVar1 < 0x1f) {
    uVar7 = FUN_0044b7b0((fGpffff8094 * (float)(int)uVar1) / 30.0);
    FUN_00252230(uVar7,auStack_50,param_2 + 3,param_2 + 0xc);
  }
  else {
    FUN_00252230((float)(int)(uVar1 - 0x1e) / 30.0,auStack_50,param_2 + 0xc,param_2 + 0x15);
  }
  puVar14 = &DAT_00636210;
  puVar11 = auStack_130;
  iVar9 = 4;
  do {
    uVar7 = *puVar14;
    uVar8 = puVar14[1];
    puVar14 = puVar14 + 2;
    iVar9 = iVar9 + -1;
    *puVar11 = uVar7;
    puVar11[1] = uVar8;
    puVar11 = puVar11 + 2;
  } while (0 < iVar9);
  puVar14 = &DAT_00636230;
  puVar11 = auStack_150;
  iVar9 = 4;
  do {
    uVar7 = *puVar14;
    uVar8 = puVar14[1];
    puVar14 = puVar14 + 2;
    iVar9 = iVar9 + -1;
    *puVar11 = uVar7;
    puVar11[1] = uVar8;
    puVar11 = puVar11 + 2;
  } while (0 < iVar9);
  uVar4 = param_2[1];
  if ((int)uVar4 < 0x1f) {
    FUN_003e0870(uStack_34,auStack_90,auStack_44,0);
  }
  else {
    uStack_28 = DAT_00636250;
    uStack_20 = DAT_00636258;
    uStack_10 = DAT_00636250;
    uStack_8 = DAT_00636258;
    FUN_003e0870(uStack_34,auStack_90,auStack_44,0);
    FUN_003e0870(((float)(int)(uVar4 - 0x1e) * -90.0) / 30.0,auStack_90,&uStack_10,2);
  }
  FUN_0035afa0(*(undefined4 *)(param_3 + 0x14));
  FUN_0035afa0(*(undefined4 *)(param_3 + 0x18));
  if (0x18 < (int)param_2[1]) {
    FUN_0025f360(0x19,0,*(undefined4 *)(param_3 + 0x10));
    uVar4 = param_2[1];
    if ((int)uVar4 < 0x1f) {
      fVar17 = (float)(int)(uVar4 - 0x19) / 5.0;
    }
    else if ((float)(int)(uVar4 - 0x1e) < 5.0) {
      fVar17 = 1.0 - (float)(int)(uVar4 - 0x1e) / 5.0;
    }
    else {
      fVar17 = 0.0;
    }
    FUN_003e0870(fGpffff82b0 * fVar17,auStack_d0,auStack_44,0);
    FUN_003e05f0(&uStack_110,auStack_d0,auStack_90);
    puVar12 = &uStack_110;
    puVar11 = auStack_d0;
    iVar9 = 4;
    do {
      uVar2 = *puVar12;
      uVar7 = *(undefined4 *)(puVar12 + 1);
      uVar8 = *(undefined4 *)((int)puVar12 + 0xc);
      puVar12 = puVar12 + 2;
      iVar9 = iVar9 + -1;
      *puVar11 = (int)uVar2;
      puVar11[1] = (int)((ulong)uVar2 >> 0x20);
      puVar11[2] = uVar7;
      puVar11[3] = uVar8;
      puVar11 = puVar11 + 4;
    } while (0 < iVar9);
    FUN_00366c70(0,(int)fStack_4c,(int)fStack_48,0x73,0x90,0xffffff,(undefined1)uStack_38,1,0x39);
    if (iVar10 == 10) {
      FUN_00366c70(0,(int)fStack_4c,(int)fStack_48,0x6d,0x89,0x7f7f7f,0xff,1,0x37);
    }
    else {
      FUN_00366c70(0,(int)fStack_4c,(int)fStack_48,0x6d,0x89,0xff9c35,0xff,1,0x37);
    }
  }
  FUN_00366c70(0,(int)fStack_4c,(int)fStack_48,sStack_30,uStack_2e,uStack_38 >> 8,uStack_38 & 0xff,3
               ,sStack_30 >> 1);
  FUN_00366c70(0,(int)fStack_4c,(int)fStack_48,sStack_30,uStack_2e,uStack_38 >> 8,uStack_38 & 0xff,5
               ,sStack_30 >> 1);
  (*DAT_00887300)(7,2);
  (*DAT_00887300)(9,2);
  (*DAT_00887300)(6,0);
  (*DAT_00887300)(8,0);
  (*DAT_00887300)(0xc,1);
  (*DAT_00887300)(2,4);
  (*DAT_00887300)(0xe,0);
  FUN_003f6440(3,0x30003);
  FUN_003f6440(2,0x48);
  sVar3 = *(short *)(param_3 + 0x3c) + 1;
  *(short *)(param_3 + 0x3c) = sVar3;
  if (0x77 < sVar3) {
    *(undefined2 *)(param_3 + 0x3c) = 0;
  }
  fVar17 = (float)FUN_0044b7b0(fGpffff81dc +
                               (fGpffff81e0 * (float)(int)*(short *)(param_3 + 0x3c)) / 120.0);
  fVar17 = (fVar17 + 1.0) / 2.0;
  FUN_00366c70(0,(int)fStack_4c,(int)fStack_48,sStack_30,uStack_2e,uStack_38 >> 8,
               (int)(fGpffff811c * (float)(uStack_38 & 0xff) * fVar17),2,sStack_30 >> 1);
  FUN_00366c70(0,(int)fStack_4c,(int)fStack_48,sStack_30,uStack_2e,uStack_38 >> 8,
               (int)(fGpffff811c * (float)(uStack_38 & 0xff) * fVar17),4,sStack_30 >> 1);
  uVar5 = FUN_003b7060();
  if ((long)uVar5 < 0) {
    fVar17 = (float)(uVar5 & 0xffffffff);
  }
  else {
    fVar17 = (float)(int)uVar5;
  }
  fVar17 = fGpffff81e0 * (fVar17 / 2.1474836e+09);
  uVar5 = FUN_003b7060();
  if ((long)uVar5 < 0) {
    fVar18 = (float)(uVar5 & 0xffffffff);
  }
  else {
    fVar18 = (float)(int)uVar5;
  }
  if (fVar18 / 2.1474836e+09 < fGpffff8198) {
    uVar5 = FUN_003b7060();
    if ((long)uVar5 < 0) {
      fVar18 = (float)(uVar5 & 0xffffffff);
    }
    else {
      fVar18 = (float)(int)uVar5;
    }
    fVar18 = (fVar18 / 2.1474836e+09) * 46.0;
    if (fVar18 < 2.1474836e+09) {
      uVar4 = (uint)fVar18;
    }
    else {
      uVar4 = (int)(fVar18 - 2.1474836e+09) | 0x80000000;
    }
    fVar18 = (float)(uVar4 + 0x46);
  }
  else {
    uVar5 = FUN_003b7060();
    if ((long)uVar5 < 0) {
      fVar18 = (float)(uVar5 & 0xffffffff);
    }
    else {
      fVar18 = (float)(int)uVar5;
    }
    fVar18 = (fVar18 / 2.1474836e+09) * 40.0;
    if (fVar18 < 2.1474836e+09) {
      uVar4 = (uint)fVar18;
    }
    else {
      uVar4 = (int)(fVar18 - 2.1474836e+09) | 0x80000000;
    }
    uVar4 = uVar4 + 0x1e;
    if ((int)uVar4 < 0) {
      fVar18 = (float)uVar4;
    }
    else {
      fVar18 = (float)(int)uVar4;
    }
  }
  fStack_18 = (float)FUN_0044b610(fVar17);
  fStack_18 = fVar18 * fStack_18;
  fStack_14 = (float)FUN_0044b7b0(fVar17);
  fStack_14 = -fVar18 * fStack_14;
  if ((int)param_2[1] < 0x29) {
    fVar18 = fStack_48 + fStack_14;
    fVar17 = fStack_4c + fStack_18;
    lVar6 = FUN_00251570(param_1,0);
    if (lVar6 != 0) {
      *(float *)((int)lVar6 + 4) = fVar17;
      *(float *)((int)lVar6 + 8) = fVar18;
    }
    pfVar15 = (float *)&DAT_00636260;
    pfVar13 = afStack_180;
    iVar10 = 5;
    do {
      fVar17 = *pfVar15;
      fVar18 = pfVar15[1];
      pfVar15 = pfVar15 + 2;
      iVar10 = iVar10 + -1;
      *pfVar13 = fVar17;
      pfVar13[1] = fVar18;
      pfVar13 = pfVar13 + 2;
    } while (0 < iVar10);
    uVar5 = FUN_003b7060();
    if ((long)uVar5 < 0) {
      fVar17 = (float)(uVar5 & 0xffffffff);
    }
    else {
      fVar17 = (float)(int)uVar5;
    }
    iVar10 = (int)((fVar17 / 2.1474836e+09) * 5.0);
    fStack_18 = afStack_180[iVar10 * 2];
    fVar17 = afStack_180[iVar10 * 2 + 1];
    fStack_14 = fVar17;
    lVar6 = FUN_00251570(param_1,3);
    if (lVar6 != 0) {
      uVar5 = FUN_003b7060();
      if ((long)uVar5 < 0) {
        fVar18 = (float)(uVar5 & 0xffffffff);
      }
      else {
        fVar18 = (float)(int)uVar5;
      }
      iVar10 = (int)lVar6;
      *(int *)(iVar10 + 0xc) = (int)((fVar18 / 2.1474836e+09) * 100.0);
      *(float *)(iVar10 + 4) = fStack_18;
      *(float *)(iVar10 + 8) = fVar17;
    }
  }
  if (param_2[1] == 0x14) {
    lVar6 = FUN_00251570(param_1,1);
    if (lVar6 != 0) {
      puVar16 = (uint *)lVar6;
      *puVar16 = *puVar16 | 2;
      uVar5 = FUN_003b7060();
      if ((long)uVar5 < 0) {
        fVar17 = (float)(uVar5 & 0xffffffff);
      }
      else {
        fVar17 = (float)(int)uVar5;
      }
      puVar16[3] = (int)((fVar17 / 2.1474836e+09) * 100.0);
      puVar16[1] = 0x42f60000;
      puVar16[2] = 0x43880000;
    }
    lVar6 = FUN_00251570(param_1,2);
    if (lVar6 != 0) {
      puVar16 = (uint *)lVar6;
      *puVar16 = *puVar16 | 4;
      uVar5 = FUN_003b7060();
      if ((long)uVar5 < 0) {
        fVar17 = (float)(uVar5 & 0xffffffff);
      }
      else {
        fVar17 = (float)(int)uVar5;
      }
      puVar16[3] = (int)((fVar17 / 2.1474836e+09) * 100.0);
      puVar16[1] = 0x42880000;
      puVar16[2] = 0x43d18000;
    }
  }
  else if (param_2[1] == 0x1f) {
    FUN_00251850(param_1);
  }
  return 0x3b < (int)uVar1;
}


// func_00253850  addr 0x00253850  window 4640B
undefined8 FUN_00253850(undefined8 param_1,int param_2,int param_3)

{
  bool bVar1;
  short sVar2;
  long lVar3;
  undefined8 uVar4;
  int iVar5;
  uint uVar6;
  float *pfVar7;
  float *pfVar8;
  undefined8 unaff_s1;
  float fVar9;
  float fVar10;
  int iVar11;
  undefined4 uVar12;
  float fVar13;
  float fVar14;
  undefined1 auStack_a0 [16];
  float afStack_90 [8];
  undefined1 auStack_70 [16];
  float afStack_60 [24];
  
  bVar1 = *(int *)(param_3 + 8) == 10;
  if (0xf < *(int *)(param_2 + 4)) {
    if (*(int *)(param_2 + 4) < 0x20) {
      pfVar8 = (float *)0x636290;
      pfVar7 = afStack_60 + 8;
      iVar5 = 8;
      do {
        fVar10 = *pfVar8;
        fVar13 = pfVar8[1];
        pfVar8 = pfVar8 + 2;
        iVar5 = iVar5 + -1;
        *pfVar7 = fVar10;
        pfVar7[1] = fVar13;
        pfVar7 = pfVar7 + 2;
      } while (0 < iVar5);
      for (iVar5 = 0; iVar5 < 8; iVar5 = iVar5 + 1) {
        iVar11 = *(int *)(param_2 + 4) + -0xf;
        if (iVar5 <= iVar11) {
          iVar11 = iVar11 - iVar5;
          if (iVar11 < 9) {
            fVar10 = (float)FUN_0044b7b0((fGpffff8084 * (float)iVar11) / 8.0);
            FUN_0025f3f0(afStack_60[iVar5 * 2 + 8],(afStack_60[iVar5 * 2 + 9] + 0.0) - fVar10 * 40.0
                         ,0xffffff,0xff,iVar5 + 0xd,0,*(undefined4 *)(param_3 + 0x10),1);
          }
          else {
            FUN_0025f3f0(afStack_60[iVar5 * 2 + 8],afStack_60[iVar5 * 2 + 9],0,0xffffff,0xff,
                         iVar5 + 0xd,0,*(undefined4 *)(param_3 + 0x10),1);
          }
        }
      }
    }
    else {
      FUN_0025f3f0(0x43b20000,0x43aa0000,0,0xffffff,0xff,0xd,0,*(undefined4 *)(param_3 + 0x10),1);
      FUN_0025f3f0(0x43c60000,0x43af0000,0,0xffffff,0xff,0xe,0,*(undefined4 *)(param_3 + 0x10),1);
      FUN_0025f3f0(0x43d70000,0x43af0000,0,0xffffff,0xff,0xf,0,*(undefined4 *)(param_3 + 0x10),1);
      FUN_0025f3f0(0x43e98000,0x43a90000,0,0xffffff,0xff,0x10,0,*(undefined4 *)(param_3 + 0x10),1);
      FUN_0025f3f0(0x4400c000,0x43ae8000,0,0xffffff,0xff,0x11,0,*(undefined4 *)(param_3 + 0x10),1);
      FUN_0025f3f0(0x44098000,0x43ad8000,0,0xffffff,0xff,0x12,0,*(undefined4 *)(param_3 + 0x10),1);
      FUN_0025f3f0(0x44130000,0x43aa0000,0,0xffffff,0xff,0x13,0,*(undefined4 *)(param_3 + 0x10),1);
      FUN_0025f3f0(0x4416c000,0x43aa0000,0,0xffffff,0xff,0x13,0,*(undefined4 *)(param_3 + 0x10),1);
    }
  }
  if (*(int *)(param_2 + 4) < 0x10) {
    fVar10 = (float)FUN_0044b7b0((fGpffff8094 * (float)*(int *)(param_2 + 4)) / 15.0);
    uVar12 = 0x43bb8000;
    FUN_0025f3f0(-((1.0 - fVar10) * 640.0),0x43bb8000,0,0xffffff,0xff,0x29,0,
                 *(undefined4 *)(param_3 + 0x10),1);
  }
  else {
    uVar12 = 0x43bb8000;
    FUN_0025f3f0(0,0x43bb8000,0,0xffffff,0xff,0x29,0,*(undefined4 *)(param_3 + 0x10),1);
  }
  iVar5 = *(int *)(param_2 + 4);
  if (7 < iVar5) {
    if (iVar5 < 0x10) {
      fVar10 = (float)FUN_0044b7b0((fGpffff8094 * ((float)iVar5 - 7.0)) / 8.0);
      FUN_0025f430(0,(1.0 - fVar10) * 10.0 + 380.0,0,0,0x3f800000,fVar10,0xffffff,0xff,bVar1 + '*',0
                   ,*(undefined4 *)(param_3 + 0x10),1,0,0);
    }
    else {
      FUN_0025f3f0(0,0x43be0000,0,0xffffff,0xff,bVar1 + '*',0,*(undefined4 *)(param_3 + 0x10),1);
    }
  }
  iVar5 = *(int *)(param_2 + 4);
  if (0x12 < iVar5) {
    if (iVar5 < 0x1b) {
      fVar10 = (float)FUN_0044b7b0((fGpffff8094 * (float)(iVar5 + -0x12)) / 8.0);
      if (bVar1) {
        fVar13 = (1.0 - fVar10) * 450.0;
        FUN_0025f3f0(fVar13 + 184.0,0x43a80000,0,0xffffff,0xff,0x1a,0,
                     *(undefined4 *)(param_3 + 0x10),1);
      }
      else {
        fVar13 = (1.0 - fVar10) * 450.0;
        FUN_0025f3f0(fVar13 + 188.0,uVar12,0,0xffffff,0xff,1,0,*(undefined4 *)(param_3 + 0x10),1);
      }
      pfVar8 = (float *)&DAT_00635cc0;
      pfVar7 = afStack_60;
      iVar5 = 4;
      do {
        fVar14 = *pfVar8;
        fVar9 = pfVar8[1];
        pfVar8 = pfVar8 + 2;
        iVar5 = iVar5 + -1;
        *pfVar7 = fVar14;
        pfVar7[1] = fVar9;
        pfVar7 = pfVar7 + 2;
      } while (0 < iVar5);
      for (uVar6 = 0; uVar6 < 4; uVar6 = uVar6 + 1) {
        afStack_60[uVar6 * 2] = afStack_60[uVar6 * 2] + (float)(int)(fVar13 + 218.0);
        afStack_60[uVar6 * 2 + 1] = afStack_60[uVar6 * 2 + 1] + 406.0;
        iVar5 = uVar6 * 4;
        auStack_70[iVar5] = 0;
        auStack_70[iVar5 + 1] = 0;
        auStack_70[iVar5 + 2] = 0;
        auStack_70[iVar5 + 3] = 0x99;
      }
      FUN_0045dfd0(0,auStack_70,afStack_60,4,4,1);
      uVar6 = *(uint *)(param_3 + 4);
      uVar12 = *(undefined4 *)(param_3 + 0x10);
      lVar3 = FUN_0046a770(0x635ce0);
      if (lVar3 == 0) {
        FUN_0046d730(0x635cf8,0x1e4);
      }
      iVar5 = FUN_002467b0(uVar6 & 0xffff);
      fVar13 = (float)FUN_0046b1f0(lVar3,*(byte *)(iVar5 + 8) + 0x20);
      iVar11 = (int)((1.0 - fVar10) * 450.0);
      iVar5 = FUN_002467b0(uVar6 & 0xffff);
      FUN_0025e9e0((float)((iVar11 + 299) - ((int)fVar13 >> 1)),0x43cb8000,0,0xffffff,0xff,
                   *(byte *)(iVar5 + 8) + 0x20,lVar3,1);
      FUN_0025f3f0((float)(iVar11 + 0x163),0x43cd8000,0,0xffffff,0xff,0x16,0,uVar12,1);
      uVar4 = FUN_00246830(uVar6 & 0xffff);
      FUN_00274ed0((float)(iVar11 + 0x188),0x43c98000,0,0xffffffffffffffff,0,1,uVar4,0,0);
    }
    else {
      if (bVar1) {
        FUN_0025f3f0(0x43380000,0x43a80000,0,0xffffff,0xff,0x1a,0,*(undefined4 *)(param_3 + 0x10),1)
        ;
      }
      else {
        FUN_0025f3f0(0x433c0000,uVar12,0,0xffffff,0xff,1,0,*(undefined4 *)(param_3 + 0x10),1);
      }
      pfVar8 = (float *)&DAT_00635cc0;
      pfVar7 = afStack_90;
      iVar5 = 4;
      do {
        fVar10 = *pfVar8;
        fVar13 = pfVar8[1];
        pfVar8 = pfVar8 + 2;
        iVar5 = iVar5 + -1;
        *pfVar7 = fVar10;
        pfVar7[1] = fVar13;
        pfVar7 = pfVar7 + 2;
      } while (0 < iVar5);
      for (uVar6 = 0; uVar6 < 4; uVar6 = uVar6 + 1) {
        afStack_90[uVar6 * 2] = afStack_90[uVar6 * 2] + 218.0;
        afStack_90[uVar6 * 2 + 1] = afStack_90[uVar6 * 2 + 1] + 406.0;
        iVar5 = uVar6 * 4;
        auStack_a0[iVar5] = 0;
        auStack_a0[iVar5 + 1] = 0;
        auStack_a0[iVar5 + 2] = 0;
        auStack_a0[iVar5 + 3] = 0x99;
      }
      FUN_0045dfd0(0,auStack_a0,afStack_90,4,4,1);
      uVar6 = *(uint *)(param_3 + 4);
      uVar12 = *(undefined4 *)(param_3 + 0x10);
      lVar3 = FUN_0046a770(0x635ce0);
      if (lVar3 == 0) {
        FUN_0046d730(0x635cf8,0x1e4);
      }
      iVar5 = FUN_002467b0(uVar6 & 0xffff);
      fVar10 = (float)FUN_0046b1f0(lVar3,*(byte *)(iVar5 + 8) + 0x20);
      iVar5 = FUN_002467b0(uVar6 & 0xffff);
      FUN_0025e9e0((float)(299 - ((int)fVar10 >> 1)),0x43cb8000,0,0xffffff,0xff,
                   *(byte *)(iVar5 + 8) + 0x20,lVar3,1);
      FUN_0025f3f0(0x43b18000,0x43cd8000,0,0xffffff,0xff,0x16,0,uVar12,1);
      uVar4 = FUN_00246830(uVar6 & 0xffff);
      FUN_00274ed0(0x43c40000,0x43c98000,0,0xffffffffffffffff,0,1,uVar4,0,0);
    }
  }
  iVar5 = *(int *)(param_2 + 4);
  if (0x1e < iVar5) {
    if (iVar5 < 0x27) {
      fVar10 = (float)FUN_0044b7b0((fGpffff8084 * (float)(iVar5 + -0x1e)) / 8.0);
      if (!bVar1) {
        FUN_0025f3f0(0x438a8000,350.0 - fVar10 * 17.0,0xffffff,0xff,*(int *)(param_3 + 8) + 1,0,
                     *(undefined4 *)(param_3 + 0x10),1);
      }
    }
    else if (!bVar1) {
      FUN_0025f3f0(0x438a8000,0x43af0000,0,0xffffff,0xff,*(int *)(param_3 + 8) + 1,0,
                   *(undefined4 *)(param_3 + 0x10),1);
    }
  }
  if (0x17 < *(int *)(param_2 + 4)) {
    if (*(int *)(param_2 + 4) < 0x27) {
      for (iVar5 = 0; iVar5 < 10; iVar5 = iVar5 + 1) {
        iVar11 = *(int *)(param_2 + 4) + -0x17;
        if (iVar5 <= iVar11) {
          unaff_s1 = 0xffffff;
          if (*(int *)(param_3 + 8) <= iVar5) {
            unaff_s1 = 0xde7201;
          }
          fVar10 = (float)(iVar11 - iVar5);
          if (fVar10 < 5.0) {
            fVar10 = (float)FUN_0044b7b0((fGpffff8094 * fVar10) / 5.0);
            FUN_0025f3f0((1.0 - fVar10) * 400.0 + (float)(iVar5 * 0x17 + 0x162) + 0.0,0x43be8000,
                         unaff_s1,0xff,0x15,0,*(undefined4 *)(param_3 + 0x10),1);
          }
          else {
            FUN_0025f3f0((float)(iVar5 * 0x17 + 0x162),0x43be8000,0,unaff_s1,0xff,0x15,0,
                         *(undefined4 *)(param_3 + 0x10),1);
          }
        }
      }
    }
    else {
      for (iVar5 = 0; iVar5 < 10; iVar5 = iVar5 + 1) {
        unaff_s1 = 0xffffff;
        if (*(int *)(param_3 + 8) <= iVar5) {
          unaff_s1 = 0xde7201;
        }
        FUN_0025f3f0((float)(iVar5 * 0x17 + 0x162),0x43be8000,0,unaff_s1,0xff,0x15,0,
                     *(undefined4 *)(param_3 + 0x10),1);
      }
    }
  }
  if (0x1e < *(int *)(param_2 + 4)) {
    sVar2 = *(short *)(param_3 + 0x3e) + 1;
    *(short *)(param_3 + 0x3e) = sVar2;
    if (0x2c < sVar2) {
      *(undefined2 *)(param_3 + 0x3e) = 0;
    }
    iVar5 = *(int *)(param_3 + 8) + -1;
    fVar10 = (float)FUN_0044b7b0(fGpffff81dc +
                                 (fGpffff81e0 * (float)(int)*(short *)(param_3 + 0x3e)) / 45.0);
    fVar13 = 1.0;
    fVar14 = fGpffff8198 + 0.0;
    fVar10 = fGpffff809c * ((fVar10 + 1.0) / 2.0);
    if (*(int *)(param_2 + 4) < 0x3d) {
      fVar13 = (float)(*(int *)(param_2 + 4) + -0x1e) / 30.0;
      fVar9 = (1.0 - fVar13) * 255.0;
      if (2.1474836e+09 <= fVar9) {
        fVar9 = fVar9 - 2.1474836e+09;
      }
      FUN_0025f430((float)(iVar5 * 0x17 + 0x165) - fVar13 * 58.0,385.0 - fVar13 * 62.0,0,
                   fVar13 * 90.0,fVar13,fVar13,0xffffff,(int)fVar9 & 0xff,0x1b,0,
                   *(undefined4 *)(param_3 + 0x10),1,(short)(int)(fVar13 * 58.0),
                   (short)(int)(fVar13 * 62.0));
    }
    fVar13 = (fVar10 + fVar14) * fVar13;
    fVar14 = fGpffff8218 * fVar13 + 1.0;
    fVar10 = fVar13 * 255.0;
    if (2.1474836e+09 <= fVar10) {
      fVar10 = fVar10 - 2.1474836e+09;
    }
    FUN_0025f430(((float)(iVar5 * 0x17 + 0x15e) + 0.0) - fGpffff82ac * fVar13,
                 377.0 - fGpffff823c * fVar13,0,0,fVar14,fVar14,unaff_s1,(int)fVar10 & 0xff,0x1c,0,
                 *(undefined4 *)(param_3 + 0x10),1,0,0);
  }
  return 0;
}


// func_00254a70  addr 0x00254a70  window 4240B
undefined8 FUN_00254a70(undefined8 param_1,int param_2,int param_3)

{
  bool bVar1;
  undefined4 uVar2;
  float fVar3;
  undefined4 *puVar4;
  short sVar5;
  undefined4 *puVar6;
  long lVar7;
  undefined8 uVar8;
  undefined4 *puVar9;
  int iVar10;
  int iVar11;
  uint uVar12;
  float *pfVar13;
  float *pfVar14;
  int iVar15;
  undefined8 unaff_s3;
  float fVar16;
  float fVar17;
  undefined1 auStack_f0 [16];
  float afStack_e0 [8];
  undefined1 auStack_c0 [16];
  float afStack_b0 [8];
  undefined4 uStack_90;
  undefined4 uStack_8c;
  undefined4 uStack_88;
  undefined4 uStack_84;
  undefined4 uStack_80;
  undefined4 uStack_7c;
  undefined4 uStack_78;
  undefined4 uStack_74;
  undefined4 uStack_70;
  undefined4 uStack_6c;
  undefined4 uStack_68;
  undefined4 uStack_64;
  undefined4 uStack_60;
  undefined4 uStack_5c;
  undefined4 uStack_58;
  undefined4 uStack_54;
  float afStack_50 [16];
  undefined4 uStack_10;
  undefined4 uStack_c;
  undefined4 uStack_8;
  undefined4 uStack_4;
  
  bVar1 = *(int *)(param_3 + 8) == 10;
  iVar11 = *(int *)(param_2 + 4);
  iVar15 = iVar11 + -0x3c;
  if (iVar15 < 0x13) {
    pfVar14 = (float *)&DAT_006362d0;
    pfVar13 = afStack_50;
    iVar10 = 8;
    do {
      fVar16 = *pfVar14;
      fVar17 = pfVar14[1];
      pfVar14 = pfVar14 + 2;
      iVar10 = iVar10 + -1;
      *pfVar13 = fVar16;
      pfVar13[1] = fVar17;
      pfVar13 = pfVar13 + 2;
    } while (0 < iVar10);
    puVar6 = (undefined4 *)0x4;
    puVar9 = &uStack_8;
    puVar4 = puVar9;
    while (puVar4 != (undefined4 *)0x0) {
      *(undefined1 *)puVar9 = 0;
      puVar9 = (undefined4 *)((int)puVar9 + 1);
      puVar6 = (undefined4 *)((int)puVar6 + -1);
      puVar4 = puVar6;
    }
    uStack_4 = uStack_8;
    puVar6 = (undefined4 *)0x10;
    puVar9 = &uStack_70;
    puVar4 = puVar9;
    while (puVar4 != (undefined4 *)0x0) {
      *(undefined1 *)puVar9 = 0;
      puVar9 = (undefined4 *)((int)puVar9 + 1);
      puVar6 = (undefined4 *)((int)puVar6 + -1);
      puVar4 = puVar6;
    }
    uStack_70 = 0x15e;
    uStack_6c = 0x17c;
    uStack_68 = 0x122;
    uStack_64 = 100;
    uStack_60 = 0x15e;
    uStack_5c = 0x17c;
    uStack_58 = 0x122;
    uStack_54 = 100;
    (*DAT_00887300)(0xe,0);
    (*DAT_00887300)(0xc,1);
    (*DAT_00887300)(7,2);
    (*DAT_00887300)(9,1);
    (*DAT_00887300)(0x14,1);
    (*DAT_00887300)(6,0);
    (*DAT_00887300)(8,1);
    FUN_003f6440(3,0x31003);
    FUN_003f6440(2,0x44);
    FUN_00489f80();
    FUN_0045d6e0(0x40a00000,&uStack_4,&uStack_60,0);
    FUN_0048a000();
    for (iVar10 = 0; iVar10 < 8; iVar10 = iVar10 + 1) {
      if (iVar15 < iVar10) {
        FUN_0025f3f0(afStack_50[iVar10 * 2],afStack_50[iVar10 * 2 + 1],0x41200000,0xffffff,0xff,
                     iVar10 + 0xd,0,*(undefined4 *)(param_3 + 0x10),1);
      }
      else if (iVar15 - iVar10 < 9) {
        fVar16 = (float)FUN_0044b7b0((fGpffff8094 * (float)(iVar15 - iVar10)) / 8.0);
        FUN_0025f3f0(afStack_50[iVar10 * 2],fVar16 * 50.0 + afStack_50[iVar10 * 2 + 1] + 0.0,
                     0x41200000,0xffffff,0xff,iVar10 + 0xd,0,*(undefined4 *)(param_3 + 0x10),1);
      }
    }
    puVar6 = (undefined4 *)0x4;
    puVar9 = &uStack_10;
    puVar4 = puVar9;
    while (puVar4 != (undefined4 *)0x0) {
      *(undefined1 *)puVar9 = 0;
      puVar9 = (undefined4 *)((int)puVar9 + 1);
      puVar6 = (undefined4 *)((int)puVar6 + -1);
      puVar4 = puVar6;
    }
    uStack_c = uStack_10;
    puVar6 = (undefined4 *)0x10;
    puVar9 = &uStack_90;
    puVar4 = puVar9;
    while (puVar4 != (undefined4 *)0x0) {
      *(undefined1 *)puVar9 = 0;
      puVar9 = (undefined4 *)((int)puVar9 + 1);
      puVar6 = (undefined4 *)((int)puVar6 + -1);
      puVar4 = puVar6;
    }
    uStack_90 = 0x15e;
    uStack_8c = 0x17c;
    uStack_88 = 0x122;
    uStack_84 = 100;
    uStack_80 = 0x15e;
    uStack_7c = 0x17c;
    uStack_78 = 0x122;
    uStack_74 = 100;
    (*DAT_00887300)(0xe,0);
    (*DAT_00887300)(0xc,1);
    (*DAT_00887300)(7,2);
    (*DAT_00887300)(9,1);
    (*DAT_00887300)(0x14,1);
    (*DAT_00887300)(6,0);
    (*DAT_00887300)(8,1);
    FUN_003f6440(3,0x31003);
    FUN_003f6440(2,0x44);
    FUN_00489f80();
    FUN_0045d6e0(0,&uStack_c,&uStack_80,0);
    FUN_0048a000();
  }
  if (iVar15 < 0x19) {
    FUN_0025f3f0(0,0x43bb8000,0,0xffffff,0xff,0x29,0,*(undefined4 *)(param_3 + 0x10),1);
  }
  else if (iVar15 < 0x24) {
    fVar16 = (float)FUN_0044b7b0((fGpffff8094 * (float)(iVar11 + -0x55)) / 10.0);
    FUN_0025f3f0(fVar16 * 640.0,0x43bb8000,0,0xffffff,0xff,0x29,0,*(undefined4 *)(param_3 + 0x10),1)
    ;
  }
  if (iVar15 < 0x1e) {
    FUN_0025f3f0(0,0x43be0000,0,0xffffff,0xff,bVar1 + '*',0,*(undefined4 *)(param_3 + 0x10),1);
  }
  else if (iVar15 < 0x24) {
    fVar16 = (float)FUN_0044b7b0((fGpffff8094 * (float)(iVar11 + -0x5a)) / 5.0);
    FUN_0025f430(0,fVar16 * 10.0 + 380.0,0,0,0x3f800000,1.0 - fVar16,0xffffff,0xff,bVar1 + '*',0,
                 *(undefined4 *)(param_3 + 0x10),1,0,0);
  }
  if (iVar15 < 0x14) {
    if (bVar1) {
      FUN_0025f3f0(0x43380000,0x43a80000,0,0xffffff,0xff,0x1a,0,*(undefined4 *)(param_3 + 0x10),1);
    }
    else {
      FUN_0025f3f0(0x433c0000,0x43bb8000,0,0xffffff,0xff,1,0,*(undefined4 *)(param_3 + 0x10),1);
      FUN_0025f3f0(0x438a8000,0x43af0000,0,0xffffff,0xff,*(int *)(param_3 + 8) + 1,0,
                   *(undefined4 *)(param_3 + 0x10),1);
    }
  }
  else if (iVar15 < 0x1a) {
    fVar16 = (float)FUN_0044b7b0((fGpffff8094 * (float)(iVar11 + -0x50)) / 5.0);
    if (bVar1) {
      FUN_0025f430(0x43380000,fVar16 * 62.0 + 336.0,0,0,0x3f800000,1.0 - fVar16,0xffffff,0xff,0x1a,0
                   ,*(undefined4 *)(param_3 + 0x10),1,0,0);
    }
    else {
      fVar17 = 1.0 - fVar16;
      FUN_0025f430(0x433c0000,fVar16 * 28.0 + 375.0,0,0,0x3f800000,fVar17,0xffffff,0xff,1,0,
                   *(undefined4 *)(param_3 + 0x10),1,0,0);
      FUN_0025f430(0x438a8000,fVar16 * 50.0 + 350.0,0,0,0x3f800000,fVar17,0xffffff,0xff,
                   *(int *)(param_3 + 8) + 1,0,*(undefined4 *)(param_3 + 0x10),1,0,0);
    }
  }
  if (iVar15 < 5) {
    pfVar14 = (float *)&DAT_00635cc0;
    pfVar13 = afStack_b0;
    iVar11 = 4;
    do {
      fVar16 = *pfVar14;
      fVar17 = pfVar14[1];
      pfVar14 = pfVar14 + 2;
      iVar11 = iVar11 + -1;
      *pfVar13 = fVar16;
      pfVar13[1] = fVar17;
      pfVar13 = pfVar13 + 2;
    } while (0 < iVar11);
    for (uVar12 = 0; uVar12 < 4; uVar12 = uVar12 + 1) {
      afStack_b0[uVar12 * 2] = afStack_b0[uVar12 * 2] + 218.0;
      afStack_b0[uVar12 * 2 + 1] = afStack_b0[uVar12 * 2 + 1] + 406.0;
      iVar11 = uVar12 * 4;
      auStack_c0[iVar11] = 0;
      auStack_c0[iVar11 + 1] = 0;
      auStack_c0[iVar11 + 2] = 0;
      auStack_c0[iVar11 + 3] = 0x99;
    }
    FUN_0045dfd0(0,auStack_c0,afStack_b0,4,4,1);
    uVar12 = *(uint *)(param_3 + 4);
    uVar2 = *(undefined4 *)(param_3 + 0x10);
    lVar7 = FUN_0046a770(0x635ce0);
    if (lVar7 == 0) {
      FUN_0046d730(0x635cf8,0x1e4);
    }
    iVar11 = FUN_002467b0(uVar12 & 0xffff);
    fVar16 = (float)FUN_0046b1f0(lVar7,*(byte *)(iVar11 + 8) + 0x20);
    iVar11 = FUN_002467b0(uVar12 & 0xffff);
    FUN_0025e9e0((float)(299 - ((int)fVar16 >> 1)),0x43cb8000,0,0xffffff,0xff,
                 *(byte *)(iVar11 + 8) + 0x20,lVar7,1);
    FUN_0025f3f0(0x43b18000,0x43cd8000,0,0xffffff,0xff,0x16,0,uVar2,1);
    uVar8 = FUN_00246830(uVar12 & 0xffff);
    FUN_00274ed0(0x43c40000,0x43c98000,0,0xffffffffffffffff,0,1,uVar8,0,0);
    for (iVar11 = 0; iVar11 < 10; iVar11 = iVar11 + 1) {
      if (iVar11 < *(int *)(param_3 + 8)) {
        unaff_s3 = 0xffffff;
      }
      else {
        unaff_s3 = 0xde7201;
      }
      FUN_0025f3f0((float)(iVar11 * 0x17 + 0x162),0x43be8000,0,unaff_s3,0xff,0x15,0,
                   *(undefined4 *)(param_3 + 0x10),1);
    }
    sVar5 = *(short *)(param_3 + 0x3e) + 1;
    *(short *)(param_3 + 0x3e) = sVar5;
    if (0x2c < sVar5) {
      *(undefined2 *)(param_3 + 0x3e) = 0;
    }
    fVar16 = (float)FUN_0044b7b0(fGpffff81dc +
                                 (fGpffff81e0 * (float)(int)*(short *)(param_3 + 0x3e)) / 45.0);
    fVar16 = (fGpffff809c * ((fVar16 + 1.0) / 2.0) + fGpffff8198 + 0.0) *
             (1.0 - (float)iVar15 / 5.0) * 255.0;
    if (2.1474836e+09 <= fVar16) {
      fVar16 = fVar16 - 2.1474836e+09;
    }
    FUN_0025f3f0((float)((*(int *)(param_3 + 8) + -1) * 0x17 + 0x15d),0x43bc0000,0,unaff_s3,
                 (int)fVar16 & 0xff,0x1c,0,*(undefined4 *)(param_3 + 0x10),1);
  }
  else if (iVar15 < 0x15) {
    fVar16 = (float)FUN_0044b7b0((fGpffff8094 * (float)(iVar11 + -0x41)) / 15.0);
    pfVar14 = (float *)&DAT_00635cc0;
    pfVar13 = afStack_e0;
    iVar11 = 4;
    do {
      fVar17 = *pfVar14;
      fVar3 = pfVar14[1];
      pfVar14 = pfVar14 + 2;
      iVar11 = iVar11 + -1;
      *pfVar13 = fVar17;
      pfVar13[1] = fVar3;
      pfVar13 = pfVar13 + 2;
    } while (0 < iVar11);
    for (uVar12 = 0; uVar12 < 4; uVar12 = uVar12 + 1) {
      afStack_e0[uVar12 * 2] = afStack_e0[uVar12 * 2] + (float)(int)(fVar16 * 500.0 + 218.0);
      afStack_e0[uVar12 * 2 + 1] = afStack_e0[uVar12 * 2 + 1] + 406.0;
      iVar11 = uVar12 * 4;
      auStack_f0[iVar11] = 0;
      auStack_f0[iVar11 + 1] = 0;
      auStack_f0[iVar11 + 2] = 0;
      auStack_f0[iVar11 + 3] = 0x99;
    }
    FUN_0045dfd0(0,auStack_f0,afStack_e0,4,4,1);
    uVar12 = *(uint *)(param_3 + 4);
    uVar2 = *(undefined4 *)(param_3 + 0x10);
    lVar7 = FUN_0046a770(0x635ce0);
    if (lVar7 == 0) {
      FUN_0046d730(0x635cf8,0x1e4);
    }
    iVar11 = FUN_002467b0(uVar12 & 0xffff);
    fVar17 = (float)FUN_0046b1f0(lVar7,*(byte *)(iVar11 + 8) + 0x20);
    iVar15 = (int)(fVar16 * 500.0);
    fVar17 = (float)((iVar15 + 299) - ((int)fVar17 >> 1));
    iVar11 = FUN_002467b0(uVar12 & 0xffff);
    FUN_0025e9e0(fVar17,0x43cb8000,0,0xffffff,0xff,*(byte *)(iVar11 + 8) + 0x20,lVar7,1);
    FUN_0025f3f0((float)(iVar15 + 0x163),0x43cd8000,0,0xffffff,0xff,0x16,0,uVar2,1);
    fVar17 = (float)(iVar15 + 0x188);
    uVar8 = FUN_00246830(uVar12 & 0xffff);
    FUN_00274ed0(fVar17,0x43c98000,0,0xffffffffffffffff,0,1,uVar8,0,0);
    for (iVar11 = 0; iVar11 < 10; iVar11 = iVar11 + 1) {
      if (iVar11 < *(int *)(param_3 + 8)) {
        uVar8 = 0xffffff;
      }
      else {
        uVar8 = 0xde7201;
      }
      FUN_0025f3f0(fVar16 * 500.0 + (float)(iVar11 * 0x17 + 0x162),0x43be8000,0,uVar8,0xff,0x15,0,
                   *(undefined4 *)(param_3 + 0x10),1);
    }
  }
  return 0;
}


// func_002561f0  addr 0x002561f0  window 624B
void FUN_002561f0(float param_1,float param_2,undefined4 param_3,undefined4 param_4,
                 undefined4 param_5,int param_6,uint param_7,int param_8,int param_9,
                 undefined8 param_10,undefined2 param_11,undefined2 param_12)

{
  float fVar1;
  float fVar2;
  uint uVar3;
  uint uVar4;
  int iVar5;
  float *pfVar6;
  float *pfVar7;
  uint uVar8;
  uint uVar9;
  uint uVar10;
  uint uVar11;
  undefined1 auStack_d0 [80];
  float afStack_80 [32];
  
  pfVar7 = (float *)&DAT_00636310;
  pfVar6 = afStack_80;
  iVar5 = 0x10;
  do {
    fVar1 = *pfVar7;
    fVar2 = pfVar7[1];
    pfVar7 = pfVar7 + 2;
    iVar5 = iVar5 + -1;
    *pfVar6 = fVar1;
    pfVar6[1] = fVar2;
    pfVar6 = pfVar6 + 2;
  } while (0 < iVar5);
  uVar9 = param_6 << 8;
  uVar3 = uVar9 | param_7;
  uVar10 = (uint)(((float)param_9 * 255.0) / 255.0);
  uVar4 = uVar9 | uVar10;
  uVar11 = (uint)(((float)param_8 * 255.0) / 255.0);
  uVar9 = uVar9 | uVar11;
  for (uVar8 = 0; uVar8 < 0x10; uVar8 = uVar8 + 1) {
    afStack_80[uVar8 * 2] = afStack_80[uVar8 * 2] + param_1;
    afStack_80[uVar8 * 2 + 1] = afStack_80[uVar8 * 2 + 1] + param_2;
    if (((uVar8 == 0) || (uVar8 == 1)) || (uVar8 - 0xe < 2)) {
      iVar5 = uVar8 * 4;
      auStack_d0[iVar5] = (char)((uint)param_6 >> 0x10);
      auStack_d0[iVar5 + 1] = (char)((uint)param_6 >> 8);
      auStack_d0[iVar5 + 2] = (char)param_6;
      auStack_d0[iVar5 + 3] = 0;
    }
    else if (uVar8 - 6 < 4) {
      iVar5 = uVar8 * 4;
      auStack_d0[iVar5] = (char)(uVar9 >> 0x18);
      auStack_d0[iVar5 + 1] = (char)(uVar9 >> 0x10);
      auStack_d0[iVar5 + 2] = (char)(uVar9 >> 8);
      auStack_d0[iVar5 + 3] = (char)uVar11;
    }
    else if (uVar8 - 10 < 4) {
      iVar5 = uVar8 * 4;
      auStack_d0[iVar5] = (char)(uVar4 >> 0x18);
      auStack_d0[iVar5 + 1] = (char)(uVar4 >> 0x10);
      auStack_d0[iVar5 + 2] = (char)(uVar4 >> 8);
      auStack_d0[iVar5 + 3] = (char)uVar10;
    }
    else {
      iVar5 = uVar8 * 4;
      auStack_d0[iVar5] = (char)(uVar3 >> 0x18);
      auStack_d0[iVar5 + 1] = (char)(uVar3 >> 0x10);
      auStack_d0[iVar5 + 2] = (char)(uVar3 >> 8);
      auStack_d0[iVar5 + 3] = (char)param_7;
    }
  }
  FUN_0045e6a0(param_3,0,param_4,param_5,auStack_d0,afStack_80,0x10,4,param_10,param_11,param_12);
  return;
}


// func_00256460  addr 0x00256460  window 624B
void FUN_00256460(float param_1,float param_2,undefined4 param_3,undefined4 param_4,
                 undefined4 param_5,int param_6,uint param_7,int param_8,int param_9,
                 undefined8 param_10,undefined2 param_11,undefined2 param_12)

{
  float fVar1;
  float fVar2;
  uint uVar3;
  uint uVar4;
  int iVar5;
  float *pfVar6;
  float *pfVar7;
  uint uVar8;
  uint uVar9;
  uint uVar10;
  uint uVar11;
  undefined1 auStack_d0 [80];
  float afStack_80 [32];
  
  pfVar7 = (float *)&DAT_00636390;
  pfVar6 = afStack_80;
  iVar5 = 0x10;
  do {
    fVar1 = *pfVar7;
    fVar2 = pfVar7[1];
    pfVar7 = pfVar7 + 2;
    iVar5 = iVar5 + -1;
    *pfVar6 = fVar1;
    pfVar6[1] = fVar2;
    pfVar6 = pfVar6 + 2;
  } while (0 < iVar5);
  uVar9 = param_6 << 8;
  uVar3 = uVar9 | param_7;
  uVar10 = (uint)(((float)param_9 * 255.0) / 255.0);
  uVar4 = uVar9 | uVar10;
  uVar11 = (uint)(((float)param_8 * 255.0) / 255.0);
  uVar9 = uVar9 | uVar11;
  for (uVar8 = 0; uVar8 < 0x10; uVar8 = uVar8 + 1) {
    afStack_80[uVar8 * 2] = afStack_80[uVar8 * 2] + param_1;
    afStack_80[uVar8 * 2 + 1] = afStack_80[uVar8 * 2 + 1] + param_2;
    if (((uVar8 == 0) || (uVar8 == 1)) || (uVar8 - 0xe < 2)) {
      iVar5 = uVar8 * 4;
      auStack_d0[iVar5] = (char)((uint)param_6 >> 0x10);
      auStack_d0[iVar5 + 1] = (char)((uint)param_6 >> 8);
      auStack_d0[iVar5 + 2] = (char)param_6;
      auStack_d0[iVar5 + 3] = 0;
    }
    else if (uVar8 - 6 < 4) {
      iVar5 = uVar8 * 4;
      auStack_d0[iVar5] = (char)(uVar9 >> 0x18);
      auStack_d0[iVar5 + 1] = (char)(uVar9 >> 0x10);
      auStack_d0[iVar5 + 2] = (char)(uVar9 >> 8);
      auStack_d0[iVar5 + 3] = (char)uVar11;
    }
    else if (uVar8 - 10 < 4) {
      iVar5 = uVar8 * 4;
      auStack_d0[iVar5] = (char)(uVar4 >> 0x18);
      auStack_d0[iVar5 + 1] = (char)(uVar4 >> 0x10);
      auStack_d0[iVar5 + 2] = (char)(uVar4 >> 8);
      auStack_d0[iVar5 + 3] = (char)uVar10;
    }
    else {
      iVar5 = uVar8 * 4;
      auStack_d0[iVar5] = (char)(uVar3 >> 0x18);
      auStack_d0[iVar5 + 1] = (char)(uVar3 >> 0x10);
      auStack_d0[iVar5 + 2] = (char)(uVar3 >> 8);
      auStack_d0[iVar5 + 3] = (char)param_7;
    }
  }
  FUN_0045e6a0(param_3,0,param_4,param_5,auStack_d0,afStack_80,0x10,4,param_10,param_11,param_12);
  return;
}


// func_002566d0  addr 0x002566d0  window 1296B
/* WARNING: Removing unreachable block (ram,0x00256a30) */
/* WARNING: Removing unreachable block (ram,0x00256804) */
/* WARNING: Removing unreachable block (ram,0x002568b4) */
/* WARNING: Removing unreachable block (ram,0x00256b38) */

void FUN_002566d0(undefined8 param_1,int param_2)

{
  undefined4 uVar1;
  undefined4 uVar2;
  int iVar3;
  undefined4 *puVar4;
  undefined4 *puVar5;
  undefined4 in_f15;
  float in_f16;
  float fVar6;
  float fVar7;
  float fVar8;
  undefined1 auStack_e0 [64];
  undefined4 auStack_a0 [8];
  undefined4 auStack_80 [9];
  undefined1 auStack_5c [44];
  undefined1 auStack_30 [4];
  float fStack_2c;
  float fStack_28;
  undefined1 auStack_24 [12];
  uint uStack_18;
  undefined4 uStack_14;
  short sStack_10;
  short sStack_e;
  
  puVar5 = &DAT_00636410;
  puVar4 = auStack_80;
  iVar3 = 9;
  do {
    uVar1 = *puVar5;
    uVar2 = puVar5[1];
    puVar5 = puVar5 + 2;
    iVar3 = iVar3 + -1;
    *puVar4 = uVar1;
    puVar4[1] = uVar2;
    puVar4 = puVar4 + 2;
  } while (0 < iVar3);
  puVar5 = &DAT_00636460;
  puVar4 = auStack_a0;
  iVar3 = 4;
  do {
    uVar1 = *puVar5;
    uVar2 = puVar5[1];
    puVar5 = puVar5 + 2;
    iVar3 = iVar3 + -1;
    *puVar4 = uVar1;
    puVar4[1] = uVar2;
    puVar4 = puVar4 + 2;
  } while (0 < iVar3);
  fVar6 = (float)param_2 / 255.0;
  FUN_00252230(in_f15,auStack_30,auStack_80,auStack_5c);
  FUN_003e0870(uStack_14,auStack_e0,auStack_24,0);
  FUN_00366c70(0,(int)fStack_2c,(int)fStack_28,sStack_10,sStack_e,uStack_18 >> 8,
               (int)((float)(uStack_18 & 0xff) * fVar6),3,sStack_10 >> 1);
  FUN_00366c70(0,(int)fStack_2c,(int)fStack_28,sStack_10,sStack_e,uStack_18 >> 8,
               (int)((float)(uStack_18 & 0xff) * fVar6),5,sStack_10 >> 1);
  (*DAT_00887300)(6,0);
  (*DAT_00887300)(8,1);
  FUN_003f6440(3,0x31003);
  FUN_003f6440(2,0x48);
  fVar6 = fGpffff813c * (1.0 - in_f16) * fVar6;
  fVar7 = in_f16 * 0.25 + 1.0;
  fVar8 = in_f16 * 0.25 * 0.5;
  FUN_00366c70(0,(int)((fStack_2c + 0.0) - (float)(int)sStack_10 * fVar8),
               (int)((fStack_28 + 0.0) - (float)(int)sStack_e * fVar8),
               (int)((float)(int)sStack_10 * fVar7),(int)((float)(int)sStack_e * fVar7),
               uStack_18 >> 8,(int)((float)(uStack_18 & 0xff) * fVar6),2,sStack_10 >> 1);
  FUN_00366c70(0,(int)((fStack_2c + 0.0) - (float)(int)sStack_10 * fVar8),
               (int)((fStack_28 + 0.0) - (float)(int)sStack_e * fVar8),
               (int)((float)(int)sStack_10 * fVar7),(int)((float)(int)sStack_e * fVar7),
               uStack_18 >> 8,(int)((float)(uStack_18 & 0xff) * fVar6),4,sStack_10 >> 1);
  return;
}


// func_00256be0  addr 0x00256be0  window 1296B
/* WARNING: Removing unreachable block (ram,0x00256f40) */
/* WARNING: Removing unreachable block (ram,0x00256d14) */
/* WARNING: Removing unreachable block (ram,0x00256dc4) */
/* WARNING: Removing unreachable block (ram,0x00257048) */

void FUN_00256be0(undefined8 param_1,int param_2)

{
  undefined4 uVar1;
  undefined4 uVar2;
  int iVar3;
  undefined4 *puVar4;
  undefined4 *puVar5;
  undefined4 in_f15;
  float in_f16;
  float fVar6;
  float fVar7;
  float fVar8;
  undefined1 auStack_e0 [64];
  undefined4 auStack_a0 [8];
  undefined4 auStack_80 [9];
  undefined1 auStack_5c [44];
  undefined1 auStack_30 [4];
  float fStack_2c;
  float fStack_28;
  undefined1 auStack_24 [12];
  uint uStack_18;
  undefined4 uStack_14;
  short sStack_10;
  short sStack_e;
  
  puVar5 = &DAT_00636480;
  puVar4 = auStack_80;
  iVar3 = 9;
  do {
    uVar1 = *puVar5;
    uVar2 = puVar5[1];
    puVar5 = puVar5 + 2;
    iVar3 = iVar3 + -1;
    *puVar4 = uVar1;
    puVar4[1] = uVar2;
    puVar4 = puVar4 + 2;
  } while (0 < iVar3);
  puVar5 = &DAT_006364d0;
  puVar4 = auStack_a0;
  iVar3 = 4;
  do {
    uVar1 = *puVar5;
    uVar2 = puVar5[1];
    puVar5 = puVar5 + 2;
    iVar3 = iVar3 + -1;
    *puVar4 = uVar1;
    puVar4[1] = uVar2;
    puVar4 = puVar4 + 2;
  } while (0 < iVar3);
  fVar6 = (float)param_2 / 255.0;
  FUN_00252230(in_f15,auStack_30,auStack_80,auStack_5c);
  FUN_003e0870(uStack_14,auStack_e0,auStack_24,0);
  FUN_00366c70(0,(int)fStack_2c,(int)fStack_28,sStack_10,sStack_e,uStack_18 >> 8,
               (int)((float)(uStack_18 & 0xff) * fVar6),3,sStack_10 >> 1);
  FUN_00366c70(0,(int)fStack_2c,(int)fStack_28,sStack_10,sStack_e,uStack_18 >> 8,
               (int)((float)(uStack_18 & 0xff) * fVar6),5,sStack_10 >> 1);
  (*DAT_00887300)(6,0);
  (*DAT_00887300)(8,1);
  FUN_003f6440(3,0x31003);
  FUN_003f6440(2,0x48);
  fVar6 = fGpffff813c * (1.0 - in_f16) * fVar6;
  fVar7 = in_f16 * 0.25 + 1.0;
  fVar8 = in_f16 * 0.25 * 0.5;
  FUN_00366c70(0,(int)((fStack_2c + 0.0) - (float)(int)sStack_10 * fVar8),
               (int)((fStack_28 + 0.0) - (float)(int)sStack_e * fVar8),
               (int)((float)(int)sStack_10 * fVar7),(int)((float)(int)sStack_e * fVar7),
               uStack_18 >> 8,(int)((float)(uStack_18 & 0xff) * fVar6),2,sStack_10 >> 1);
  FUN_00366c70(0,(int)((fStack_2c + 0.0) - (float)(int)sStack_10 * fVar8),
               (int)((fStack_28 + 0.0) - (float)(int)sStack_e * fVar8),
               (int)((float)(int)sStack_10 * fVar7),(int)((float)(int)sStack_e * fVar7),
               uStack_18 >> 8,(int)((float)(uStack_18 & 0xff) * fVar6),4,sStack_10 >> 1);
  return;
}


// func_002570f0  addr 0x002570f0  window 1840B
/* WARNING: Removing unreachable block (ram,0x0025748c) */
/* WARNING: Removing unreachable block (ram,0x00257780) */

void FUN_002570f0(undefined8 param_1,int param_2)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined1 *puVar3;
  undefined4 *puVar4;
  undefined1 *puVar5;
  undefined1 *puVar6;
  undefined4 *puVar7;
  int iVar8;
  undefined4 *puVar9;
  float in_f15;
  float fVar10;
  undefined4 uStack_160;
  undefined4 uStack_15c;
  undefined4 uStack_158;
  undefined4 uStack_154;
  undefined4 uStack_150;
  undefined4 uStack_14c;
  undefined4 uStack_148;
  undefined4 uStack_144;
  undefined4 uStack_140;
  undefined4 uStack_13c;
  undefined4 uStack_138;
  undefined4 uStack_134;
  undefined4 uStack_130;
  undefined4 uStack_12c;
  undefined4 uStack_128;
  undefined4 uStack_124;
  int iStack_120;
  int iStack_11c;
  undefined4 uStack_118;
  undefined4 uStack_114;
  int iStack_110;
  int iStack_10c;
  undefined4 uStack_108;
  undefined4 uStack_104;
  int iStack_100;
  int iStack_fc;
  undefined4 uStack_f8;
  undefined4 uStack_f4;
  undefined1 auStack_f0 [64];
  undefined4 auStack_b0 [8];
  undefined4 auStack_90 [9];
  undefined1 auStack_6c [44];
  undefined1 auStack_40 [4];
  float fStack_3c;
  float fStack_38;
  undefined1 auStack_34 [12];
  uint uStack_28;
  undefined4 uStack_24;
  short sStack_20;
  undefined2 uStack_1e;
  undefined4 uStack_14;
  undefined4 uStack_10;
  undefined4 uStack_c;
  undefined4 uStack_8;
  undefined1 auStack_4 [4];
  
  puVar9 = &DAT_006364f0;
  puVar7 = auStack_90;
  iVar8 = 9;
  do {
    uVar1 = *puVar9;
    uVar2 = puVar9[1];
    puVar9 = puVar9 + 2;
    iVar8 = iVar8 + -1;
    *puVar7 = uVar1;
    puVar7[1] = uVar2;
    puVar7 = puVar7 + 2;
  } while (0 < iVar8);
  puVar9 = &DAT_00636540;
  puVar7 = auStack_b0;
  iVar8 = 4;
  do {
    uVar1 = *puVar9;
    uVar2 = puVar9[1];
    puVar9 = puVar9 + 2;
    iVar8 = iVar8 + -1;
    *puVar7 = uVar1;
    puVar7[1] = uVar2;
    puVar7 = puVar7 + 2;
  } while (0 < iVar8);
  puVar5 = (undefined1 *)0x4;
  puVar6 = auStack_4;
  puVar3 = puVar6;
  while (puVar3 != (undefined1 *)0x0) {
    *puVar6 = 0;
    puVar6 = puVar6 + 1;
    puVar5 = puVar5 + -1;
    puVar3 = puVar5;
  }
  FUN_00252230(0,auStack_40,auStack_90,auStack_6c);
  FUN_003e0870(uStack_24,auStack_f0,auStack_34,0);
  fVar10 = in_f15 * 80.0;
  in_f15 = in_f15 * -80.0;
  puVar9 = (undefined4 *)0x4;
  puVar7 = &uStack_c;
  puVar4 = puVar7;
  while (puVar4 != (undefined4 *)0x0) {
    *(undefined1 *)puVar7 = 0;
    puVar7 = (undefined4 *)((int)puVar7 + 1);
    puVar9 = (undefined4 *)((int)puVar9 + -1);
    puVar4 = puVar9;
  }
  uStack_8 = uStack_c;
  puVar9 = (undefined4 *)0x10;
  puVar7 = &uStack_140;
  puVar4 = puVar7;
  while (puVar4 != (undefined4 *)0x0) {
    *(undefined1 *)puVar7 = 0;
    puVar7 = (undefined4 *)((int)puVar7 + 1);
    puVar9 = (undefined4 *)((int)puVar9 + -1);
    puVar4 = puVar9;
  }
  uStack_140 = 0;
  uStack_13c = 0;
  uStack_138 = 0x280;
  uStack_134 = 0x1e0;
  uStack_130 = 0;
  uStack_12c = 0;
  uStack_128 = 0x280;
  uStack_124 = 0x1e0;
  (*DAT_00887300)(0xe,0);
  (*DAT_00887300)(0xc,1);
  (*DAT_00887300)(7,2);
  (*DAT_00887300)(9,1);
  (*DAT_00887300)(0x14,1);
  (*DAT_00887300)(6,0);
  (*DAT_00887300)(8,1);
  FUN_003f6440(3,0x31003);
  FUN_003f6440(2,0x44);
  FUN_00489f80();
  FUN_0045d6e0(0x41200000,&uStack_8,&uStack_130,0);
  FUN_0048a000();
  iStack_110 = DAT_00636560;
  iStack_10c = DAT_00636564;
  uStack_108 = DAT_00636568;
  uStack_104 = DAT_0063656c;
  uStack_f8 = DAT_00636568;
  uStack_f4 = DAT_0063656c;
  iStack_100 = (int)((float)DAT_00636560 + fVar10);
  iStack_fc = (int)((float)DAT_00636564 + in_f15);
  (*DAT_00887300)(6,1);
  (*DAT_00887300)(8,1);
  FUN_003f6440(3,0x71003);
  FUN_003f6440(2,0x44);
  FUN_0045db40(0,0x42340000,0x3f800000,0x3f800000,auStack_4,&iStack_100,0,200,0);
  FUN_00366c70(0x40a00000,(int)(fStack_3c + fVar10),(int)(fStack_38 + in_f15),sStack_20,uStack_1e,
               uStack_28 >> 8,(int)((float)(uStack_28 & 0xff) * ((float)param_2 / 255.0)),1,
               sStack_20 >> 1);
  puVar9 = (undefined4 *)0x4;
  puVar7 = &uStack_14;
  puVar4 = puVar7;
  while (puVar4 != (undefined4 *)0x0) {
    *(undefined1 *)puVar7 = 0;
    puVar7 = (undefined4 *)((int)puVar7 + 1);
    puVar9 = (undefined4 *)((int)puVar9 + -1);
    puVar4 = puVar9;
  }
  uStack_10 = uStack_14;
  puVar9 = (undefined4 *)0x10;
  puVar7 = &uStack_160;
  puVar4 = puVar7;
  while (puVar4 != (undefined4 *)0x0) {
    *(undefined1 *)puVar7 = 0;
    puVar7 = (undefined4 *)((int)puVar7 + 1);
    puVar9 = (undefined4 *)((int)puVar9 + -1);
    puVar4 = puVar9;
  }
  uStack_160 = 0;
  uStack_15c = 0;
  uStack_158 = 0x280;
  uStack_154 = 0x1e0;
  uStack_150 = 0;
  uStack_14c = 0;
  uStack_148 = 0x280;
  uStack_144 = 0x1e0;
  (*DAT_00887300)(0xe,0);
  (*DAT_00887300)(0xc,1);
  (*DAT_00887300)(7,2);
  (*DAT_00887300)(9,1);
  (*DAT_00887300)(0x14,1);
  (*DAT_00887300)(6,0);
  (*DAT_00887300)(8,1);
  FUN_003f6440(3,0x31003);
  FUN_003f6440(2,0x44);
  FUN_00489f80();
  FUN_0045d6e0(0x41200000,&uStack_10,&uStack_150,0);
  FUN_0048a000();
  iStack_120 = DAT_00636570;
  iStack_11c = DAT_00636574;
  uStack_118 = DAT_00636578;
  uStack_114 = DAT_0063657c;
  uStack_f8 = DAT_00636578;
  uStack_f4 = DAT_0063657c;
  iStack_100 = (int)((float)DAT_00636570 - fVar10);
  iStack_fc = (int)((float)DAT_00636574 + (-in_f15 - 200.0));
  (*DAT_00887300)(6,1);
  (*DAT_00887300)(8,1);
  FUN_003f6440(3,0x71003);
  FUN_003f6440(2,0x44);
  FUN_0045db40(0,0x42340000,0x3f800000,0x3f800000,auStack_4,&iStack_100,0,200,200);
  FUN_00366c70(0x40a00000,(int)(fStack_3c - fVar10),(int)(fStack_38 - in_f15),sStack_20,uStack_1e,
               uStack_28 >> 8,(int)((float)(uStack_28 & 0xff) * ((float)param_2 / 255.0)),1,
               sStack_20 >> 1);
  return;
}


// func_00257900  addr 0x00257900  window 14320B
/* WARNING: Removing unreachable block (ram,0x0025aba8) */
/* WARNING: Removing unreachable block (ram,0x00258d44) */
/* WARNING: Removing unreachable block (ram,0x0025ab14) */
/* WARNING: Removing unreachable block (ram,0x0025ac3c) */
/* WARNING: Removing unreachable block (ram,0x0025a4b0) */
/* WARNING: Removing unreachable block (ram,0x0025a29c) */
/* WARNING: Removing unreachable block (ram,0x0025a6f8) */

undefined8 FUN_00257900(undefined8 param_1)

{
  undefined4 uVar1;
  undefined4 uVar2;
  byte bVar3;
  undefined4 *puVar4;
  undefined1 uVar5;
  uint *puVar6;
  int iVar7;
  byte *pbVar8;
  undefined4 *puVar9;
  undefined8 uVar10;
  undefined8 uVar11;
  undefined8 uVar12;
  undefined8 uVar13;
  long lVar14;
  uint uVar15;
  undefined4 *puVar16;
  byte *pbVar17;
  int iVar18;
  float fVar19;
  float fVar20;
  float fVar21;
  float fVar22;
  undefined4 uStack_340;
  undefined4 uStack_33c;
  undefined4 uStack_338;
  undefined4 uStack_334;
  undefined4 uStack_330;
  undefined4 uStack_32c;
  undefined4 uStack_328;
  undefined4 uStack_324;
  undefined1 auStack_320 [64];
  undefined4 auStack_2e0 [8];
  undefined4 auStack_2c0 [6];
  undefined4 uStack_2a8;
  undefined1 auStack_29c [24];
  undefined4 uStack_284;
  undefined1 auStack_270 [4];
  float fStack_26c;
  float fStack_268;
  undefined1 auStack_264 [12];
  uint uStack_258;
  undefined4 uStack_254;
  short sStack_250;
  undefined2 uStack_24e;
  undefined1 auStack_240 [64];
  undefined4 auStack_200 [8];
  undefined4 auStack_1e0 [6];
  undefined4 uStack_1c8;
  undefined1 auStack_1bc [24];
  undefined4 uStack_1a4;
  undefined1 auStack_190 [4];
  float fStack_18c;
  float fStack_188;
  undefined1 auStack_184 [12];
  uint uStack_178;
  undefined4 uStack_174;
  short sStack_170;
  undefined2 uStack_16e;
  undefined1 auStack_160 [64];
  undefined4 auStack_120 [8];
  undefined4 auStack_100 [6];
  undefined4 uStack_e8;
  undefined1 auStack_dc [24];
  undefined4 uStack_c4;
  undefined1 auStack_b0 [4];
  float fStack_ac;
  float fStack_a8;
  undefined1 auStack_a4 [12];
  uint uStack_98;
  undefined4 uStack_94;
  short sStack_90;
  undefined2 uStack_8e;
  undefined4 uStack_80;
  undefined4 uStack_7c;
  undefined4 uStack_78;
  undefined4 uStack_74;
  undefined4 uStack_70;
  undefined4 uStack_6c;
  undefined4 uStack_68;
  undefined4 uStack_64;
  undefined4 uStack_60;
  undefined4 uStack_5c;
  undefined4 uStack_58;
  undefined4 uStack_54;
  undefined4 uStack_50;
  undefined4 uStack_4c;
  undefined4 uStack_48;
  undefined4 uStack_44;
  undefined4 uStack_40;
  undefined4 uStack_3c;
  undefined4 uStack_38;
  undefined4 uStack_34;
  undefined1 auStack_30 [16];
  undefined4 uStack_20;
  undefined4 uStack_1c;
  undefined4 uStack_18;
  uint uStack_14;
  uint uStack_10;
  undefined4 uStack_c;
  undefined4 uStack_8;
  undefined1 auStack_4 [4];
  
  puVar6 = (uint *)FUN_00452560();
  uVar10 = FUN_0035afa0(puVar6[0xb]);
  uVar11 = FUN_0035afa0(puVar6[0xc]);
  uVar15 = puVar6[7];
  if (uVar15 == 0xc) {
    if (puVar6[2] == 0) {
      uVar11 = FUN_00455f70(0x636630,auStack_4);
      uVar11 = FUN_0025fe50(param_1,uVar11,0x96,0x5dc974);
      FUN_001102f0(0x43960000,auStack_30,0x140,0xa5);
      uVar11 = FUN_0025ff60(uVar11);
      iVar7 = FUN_00457120();
      uVar12 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar11,uVar12);
      FUN_004b1250(uVar11,auStack_30);
    }
    if (puVar6[2] == 0x9b) {
      uVar11 = FUN_00455f70(0x636710,auStack_4);
      uVar11 = FUN_0025fe50(param_1,uVar11,0x96,0x5dc974);
      FUN_001102f0(0x43960000,auStack_30,0x140,0xb4);
      uVar11 = FUN_0025ff60(uVar11);
      iVar7 = FUN_00457120();
      uVar12 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar11,uVar12);
      FUN_004b1250(uVar11,auStack_30);
    }
    uVar15 = puVar6[2];
    if ((int)uVar15 < 0x50) {
      FUN_002570f0(0,0,0,0,0xffffff,(int)(((float)(int)uVar15 / 80.0) * 255.0),uVar10);
    }
    else if ((int)uVar15 < 0x65) {
      FUN_002570f0(0,0,0,0,0xffffff,0xff,uVar10);
    }
    else if ((int)uVar15 < 0x8d) {
      fVar20 = (float)(int)(uVar15 - 100) / 40.0;
      fVar22 = fVar20 * 76.5;
      if (fVar22 < 2.1474836e+09) {
        uVar5 = (undefined1)(int)fVar22;
      }
      else {
        uVar5 = (undefined1)(int)(fVar22 - 2.1474836e+09);
      }
      uStack_c = CONCAT13(uVar5,(int3)uGpffffa66c);
      uStack_8 = uStack_c;
      uStack_50 = DAT_006365f0;
      uStack_4c = DAT_006365f4;
      uStack_48 = DAT_006365f8;
      uStack_44 = DAT_006365fc;
      uStack_40 = DAT_006365f0;
      uStack_3c = DAT_006365f4;
      uStack_38 = DAT_006365f8;
      uStack_34 = DAT_006365fc;
      FUN_0045d6e0(0,&uStack_8,&uStack_40,1);
      pbVar8 = (byte *)FUN_003ec3d0(uVar10,1);
      pbVar17 = (byte *)puVar6[0x16];
      if (pbVar8 == (byte *)0x0) {
        FUN_0046d730(0x635cf8,0xa5e);
      }
      for (iVar7 = 0; iVar7 < 0x100; iVar7 = iVar7 + 1) {
        uVar15 = (uint)pbVar8[1];
        if (uVar15 < *pbVar8) {
          uVar15 = (uint)*pbVar8;
        }
        if (uVar15 < pbVar8[2]) {
          uVar15 = (uint)pbVar8[2];
        }
        fVar22 = fVar20 * (float)(int)(uVar15 - *pbVar17) + (float)*pbVar17 + 0.0;
        if (fVar22 < 2.1474836e+09) {
          bVar3 = (byte)(int)fVar22;
        }
        else {
          bVar3 = (byte)(int)(fVar22 - 2.1474836e+09);
        }
        *pbVar8 = bVar3;
        fVar22 = fVar20 * (float)(int)(uVar15 - pbVar17[1]) + (float)pbVar17[1] + 0.0;
        if (fVar22 < 2.1474836e+09) {
          bVar3 = (byte)(int)fVar22;
        }
        else {
          bVar3 = (byte)(int)(fVar22 - 2.1474836e+09);
        }
        pbVar8[1] = bVar3;
        fVar22 = fVar20 * (float)(int)(uVar15 - pbVar17[2]) + (float)pbVar17[2] + 0.0;
        if (fVar22 < 2.1474836e+09) {
          bVar3 = (byte)(int)fVar22;
        }
        else {
          bVar3 = (byte)(int)(fVar22 - 2.1474836e+09);
        }
        pbVar8[2] = bVar3;
        pbVar8[3] = pbVar8[3];
        pbVar8 = pbVar8 + 4;
        pbVar17 = pbVar17 + 4;
      }
      FUN_003ec2e0(uVar10);
      FUN_002570f0(0,0,0,0,0xffffff,0xff,uVar10);
    }
    else if ((int)uVar15 < 0xa1) {
      uStack_10 = uGpffffa670;
      uStack_8 = uGpffffa670;
      uStack_60 = DAT_00636600;
      uStack_5c = DAT_00636604;
      uStack_58 = DAT_00636608;
      uStack_54 = DAT_0063660c;
      uStack_40 = DAT_00636600;
      uStack_3c = DAT_00636604;
      uStack_38 = DAT_00636608;
      uStack_34 = DAT_0063660c;
      FUN_0045d6e0(0,&uStack_8,&uStack_40,1);
      FUN_002570f0(0,0,0,0,0xffffff,0xff,uVar10);
    }
    else if ((int)uVar15 < 0xa4) {
      uStack_14 = uGpffffa674;
      uStack_8 = uGpffffa674;
      uStack_70 = DAT_00636610;
      uStack_6c = DAT_00636614;
      uStack_68 = DAT_00636618;
      uStack_64 = DAT_0063661c;
      uStack_40 = DAT_00636610;
      uStack_3c = DAT_00636614;
      uStack_38 = DAT_00636618;
      uStack_34 = DAT_0063661c;
      FUN_0045d6e0(0,&uStack_8,&uStack_40,1);
      fVar22 = (float)(int)(puVar6[2] - 0xa0) / 3.0;
      FUN_002570f0(0,0,0,fVar22 * fVar22,0xffffff,0xff,uVar10);
    }
    else if ((int)uVar15 < 0xc9) {
      fVar20 = 1.0 - (float)(int)(uVar15 - 0xa3) / 37.0;
      fVar22 = fVar20 * 76.5;
      if (fVar22 < 2.1474836e+09) {
        uVar5 = (undefined1)(int)fVar22;
      }
      else {
        uVar5 = (undefined1)(int)(fVar22 - 2.1474836e+09);
      }
      uStack_18 = CONCAT13(uVar5,(int3)uGpffffa678);
      uStack_8 = uStack_18;
      uStack_80 = DAT_00636620;
      uStack_7c = DAT_00636624;
      uStack_78 = DAT_00636628;
      uStack_74 = DAT_0063662c;
      uStack_40 = DAT_00636620;
      uStack_3c = DAT_00636624;
      uStack_38 = DAT_00636628;
      uStack_34 = DAT_0063662c;
      FUN_0045d6e0(0,&uStack_8,&uStack_40,1);
      FUN_002570f0(0,0,0,0x3f800000,0xffffff,(int)(fVar20 * 255.0),uVar10);
    }
    uVar15 = puVar6[2];
    puVar6[2] = uVar15 + 1;
    if (0xef < (int)(uVar15 + 1)) {
      puVar6[2] = 100;
      puVar6[0x11] = 1;
    }
  }
  else if (uVar15 == 0xb) {
    if (puVar6[2] == 0) {
      uVar12 = FUN_00455f70(0x636630,auStack_4);
      uVar12 = FUN_0025fe50(param_1,uVar12,0x96,0x5dc974);
      FUN_001102f0(0x43960000,auStack_30,0x140,0xa5);
      uVar12 = FUN_0025ff60(uVar12);
      iVar7 = FUN_00457120();
      uVar13 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar12,uVar13);
      FUN_004b1250(uVar12,auStack_30);
    }
    if (puVar6[2] == 0xbe) {
      uVar12 = FUN_00455f70(0x636630,auStack_4);
      uVar12 = FUN_0025fe50(param_1,uVar12,0x96,0x5dc974);
      FUN_001102f0(0x43960000,auStack_30,0x140,0xa5);
      uVar12 = FUN_0025ff60(uVar12);
      iVar7 = FUN_00457120();
      uVar13 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar12,uVar13);
      FUN_004b1250(uVar12,auStack_30);
    }
    uVar15 = puVar6[2];
    if ((int)uVar15 < 0x50) {
      FUN_00256be0(0,0,0,0,0,0xffffff,(int)(((float)(int)uVar15 / 80.0) * 255.0),uVar10,uVar11);
    }
    else if ((int)uVar15 < 0x65) {
      FUN_00256be0(0,0,0,0,0,0xffffff,0xff,uVar10,uVar11);
    }
    else if ((int)uVar15 < 0x6f) {
      fVar22 = (float)(int)(uVar15 - 100) / 10.0;
      FUN_00256be0(0,0,0,fVar22,0,0xffffff,0xff,uVar10,uVar11);
      puVar9 = &DAT_00636580;
      puVar16 = auStack_100;
      iVar7 = 9;
      do {
        uVar1 = *puVar9;
        uVar2 = puVar9[1];
        puVar9 = puVar9 + 2;
        iVar7 = iVar7 + -1;
        *puVar16 = uVar1;
        puVar16[1] = uVar2;
        puVar16 = puVar16 + 2;
      } while (0 < iVar7);
      uStack_e8 = 0xff0000ff;
      uStack_c4 = 0xff0000ff;
      puVar9 = &DAT_006365d0;
      puVar16 = auStack_120;
      iVar7 = 4;
      do {
        uVar1 = *puVar9;
        uVar2 = puVar9[1];
        puVar9 = puVar9 + 2;
        iVar7 = iVar7 + -1;
        *puVar16 = uVar1;
        puVar16[1] = uVar2;
        puVar16 = puVar16 + 2;
      } while (0 < iVar7);
      FUN_00252230(fVar22,auStack_b0,auStack_100,auStack_dc);
      FUN_003e0870(uStack_94,auStack_160,auStack_a4,0);
      (*DAT_00887300)(6,0);
      (*DAT_00887300)(8,1);
      FUN_003f6440(3,0x31003);
      FUN_003f6440(2,0x48);
      FUN_00366c70(0,(int)fStack_ac,(int)fStack_a8,sStack_90,uStack_8e,uStack_98 >> 8,
                   (int)((float)(uStack_98 & 0xff) * ((float)(int)(fVar22 * 255.0) / 255.0)),0,
                   sStack_90 >> 1);
    }
    else if ((int)uVar15 < 0xab) {
      FUN_00256be0(0,0,0,0x3f800000,0,0xffffff,0xff,uVar10,uVar11);
      puVar9 = &DAT_00636580;
      puVar16 = auStack_1e0;
      iVar7 = 9;
      do {
        uVar1 = *puVar9;
        uVar2 = puVar9[1];
        puVar9 = puVar9 + 2;
        iVar7 = iVar7 + -1;
        *puVar16 = uVar1;
        puVar16[1] = uVar2;
        puVar16 = puVar16 + 2;
      } while (0 < iVar7);
      uStack_1c8 = 0xff0000ff;
      uStack_1a4 = 0xff0000ff;
      puVar9 = &DAT_006365d0;
      puVar16 = auStack_200;
      iVar7 = 4;
      do {
        uVar1 = *puVar9;
        uVar2 = puVar9[1];
        puVar9 = puVar9 + 2;
        iVar7 = iVar7 + -1;
        *puVar16 = uVar1;
        puVar16[1] = uVar2;
        puVar16 = puVar16 + 2;
      } while (0 < iVar7);
      FUN_00252230(0x3f800000,auStack_190,auStack_1e0,auStack_1bc);
      FUN_003e0870(uStack_174,auStack_240,auStack_184,0);
      (*DAT_00887300)(6,0);
      (*DAT_00887300)(8,1);
      FUN_003f6440(3,0x31003);
      FUN_003f6440(2,0x48);
      FUN_00366c70(0,(int)fStack_18c,(int)fStack_188,sStack_170,uStack_16e,uStack_178 >> 8,
                   (int)((float)(uStack_178 & 0xff) * 1.0),0,sStack_170 >> 1);
    }
    else if ((int)uVar15 < 0xd3) {
      iVar18 = (int)((1.0 - (float)(int)(uVar15 - 0xaa) / 40.0) * 255.0);
      FUN_00256be0(0,0,0,0x3f800000,0,0xffffff,iVar18,uVar10,uVar11);
      puVar9 = &DAT_00636580;
      puVar16 = auStack_2c0;
      iVar7 = 9;
      do {
        uVar1 = *puVar9;
        uVar2 = puVar9[1];
        puVar9 = puVar9 + 2;
        iVar7 = iVar7 + -1;
        *puVar16 = uVar1;
        puVar16[1] = uVar2;
        puVar16 = puVar16 + 2;
      } while (0 < iVar7);
      uStack_2a8 = 0xff0000ff;
      uStack_284 = 0xff0000ff;
      puVar9 = &DAT_006365d0;
      puVar16 = auStack_2e0;
      iVar7 = 4;
      do {
        uVar1 = *puVar9;
        uVar2 = puVar9[1];
        puVar9 = puVar9 + 2;
        iVar7 = iVar7 + -1;
        *puVar16 = uVar1;
        puVar16[1] = uVar2;
        puVar16 = puVar16 + 2;
      } while (0 < iVar7);
      FUN_00252230(0x3f800000,auStack_270,auStack_2c0,auStack_29c);
      FUN_003e0870(uStack_254,auStack_320,auStack_264,0);
      (*DAT_00887300)(6,0);
      (*DAT_00887300)(8,1);
      FUN_003f6440(3,0x31003);
      FUN_003f6440(2,0x48);
      FUN_00366c70(0,(int)fStack_26c,(int)fStack_268,sStack_250,uStack_24e,uStack_258 >> 8,
                   (int)((float)(uStack_258 & 0xff) * ((float)iVar18 / 255.0)),0,sStack_250 >> 1);
    }
    uVar15 = puVar6[2];
    puVar6[2] = uVar15 + 1;
    if (0xd1 < (int)(uVar15 + 1)) {
      puVar6[0x11] = 1;
    }
  }
  else if (uVar15 == 10) {
    if ((0x6d < (int)puVar6[2]) &&
       (uVar15 = puVar6[0x12], puVar6[0x12] = uVar15 + 1, 0x2c < (int)(uVar15 + 1))) {
      puVar6[0x12] = 0;
    }
    fVar22 = (float)(int)puVar6[0x12] / 45.0;
    if (puVar6[2] == 0) {
      uVar12 = FUN_00455f70(0x636630,auStack_4);
      uVar12 = FUN_0025fe50(param_1,uVar12,0x96,0x5dc974);
      FUN_001102f0(0x43960000,auStack_30,0x140,0xa5);
      uVar12 = FUN_0025ff60(uVar12);
      iVar7 = FUN_00457120();
      uVar13 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar12,uVar13);
      FUN_004b1250(uVar12,auStack_30);
    }
    if (puVar6[2] == 10) {
      FUN_0045aeb0(2,0x6366d0);
    }
    if (((int)puVar6[2] % 10 == 0) && ((int)puVar6[2] < 0x1cd)) {
      uVar12 = FUN_00455f70(0x6366f0,auStack_4);
      uVar12 = FUN_0025fe50(param_1,uVar12,0x32,0x5dc974);
      FUN_001102f0(0x43960000,auStack_30,0x140,0xa5);
      uVar12 = FUN_0025ff60(uVar12);
      iVar7 = FUN_00457120();
      uVar13 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar12,uVar13);
      FUN_004b1250(uVar12,auStack_30);
      FUN_004b14f0(uVar12,&uStack_8);
      fVar20 = (float)(uStack_8 >> 0x18) * 0.5;
      if (fVar20 < 2.1474836e+09) {
        uVar5 = (undefined1)(int)fVar20;
      }
      else {
        uVar5 = (undefined1)(int)(fVar20 - 2.1474836e+09);
      }
      uStack_8 = CONCAT13(uVar5,(undefined3)uStack_8);
      FUN_004b13f0(uVar12,&uStack_8);
    }
    if (puVar6[2] == 0x21c) {
      uVar12 = FUN_00455f70(0x636630,auStack_4);
      uVar12 = FUN_0025fe50(param_1,uVar12,0x96,0x5dc974);
      FUN_001102f0(0x43960000,auStack_30,0x140,0xa5);
      uVar12 = FUN_0025ff60(uVar12);
      iVar7 = FUN_00457120();
      uVar13 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar12,uVar13);
      FUN_004b1250(uVar12,auStack_30);
    }
    if ((puVar6[2] == 0x23a) && (lVar14 = FUN_00257820(puVar6[8],auStack_30), lVar14 != 0)) {
      uVar12 = FUN_00455f70(0x636690,auStack_4);
      uVar12 = FUN_0025fe50(param_1,uVar12,0x96,0x5dc974);
      uVar12 = FUN_0025ff60(uVar12);
      iVar7 = FUN_00457120();
      uVar13 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar12,uVar13);
      FUN_004b1250(uVar12,auStack_30);
    }
    if ((puVar6[2] == 0x262) && (lVar14 = FUN_00257820(puVar6[8],auStack_30), lVar14 != 0)) {
      uVar12 = FUN_00455f70(0x6366b0,auStack_4);
      uVar12 = FUN_0025fe50(param_1,uVar12,0x96,0x5dc974);
      uVar12 = FUN_0025ff60(uVar12);
      iVar7 = FUN_00457120();
      uVar13 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar12,uVar13);
      FUN_004b1250(uVar12,auStack_30);
    }
    uVar15 = puVar6[2];
    if ((int)uVar15 < 0x50) {
      FUN_002566d0(0,0,0,0,0,0xffffff,(int)(((float)(int)uVar15 / 80.0) * 255.0),uVar10,uVar11);
    }
    else if ((int)uVar15 < 0x5b) {
      FUN_002566d0(0,0,0,0,0,0xffffff,0xff,uVar10,uVar11);
    }
    else if ((int)uVar15 < 0x97) {
      FUN_002566d0(0,0,0,0,fVar22,0xffffff,0xff,uVar10,uVar11);
    }
    else if ((int)uVar15 < 0x1c3) {
      FUN_002566d0(0,0,0,0,fVar22,0xffffff,0xff,uVar10,uVar11);
      uVar15 = puVar6[2];
      uVar5 = FUN_00248760((short)puVar6[6]);
      uVar10 = FUN_002438b0(uVar5);
      FUN_00278450((char)puVar6[0xf],0,uVar10);
      uVar5 = FUN_00248760((short)puVar6[6]);
      iVar7 = FUN_00246d90(uVar5);
      uVar10 = FUN_00109220(*(undefined2 *)(iVar7 + 0x40));
      FUN_00278450((char)puVar6[0xf],1,uVar10);
      if (0 < (int)puVar6[3]) {
        puVar6[3] = puVar6[3] + 1;
      }
      if (0 < (int)puVar6[4]) {
        puVar6[4] = puVar6[4] + 1;
      }
      if (0 < (int)puVar6[5]) {
        puVar6[5] = puVar6[5] + 1;
      }
      if ((*puVar6 & 0x10) == 0) {
        if (uVar15 == 0x97) {
          puVar6[3] = puVar6[3] + 1;
        }
        else if (uVar15 == 0xf0) {
          puVar6[4] = puVar6[4] + 1;
        }
        else if (uVar15 == 0x14a) {
          puVar6[5] = puVar6[5] + 1;
        }
      }
      else {
        if (puVar6[3] == 0) {
          puVar6[3] = 1;
        }
        if (puVar6[4] == 0) {
          puVar6[4] = 1;
        }
        if (puVar6[5] == 0) {
          puVar6[5] = 1;
        }
      }
      fVar22 = 0.0;
      if (0 < (int)puVar6[3]) {
        fVar20 = (float)(int)puVar6[3] / 30.0;
        fVar22 = 1.0;
        if (fVar20 < 1.0) {
          fVar22 = fVar20;
        }
      }
      fVar20 = 0.0;
      if (0 < (int)puVar6[4]) {
        fVar21 = (float)(int)puVar6[4] / 30.0;
        fVar20 = 1.0;
        if (fVar21 < 1.0) {
          fVar20 = fVar21;
        }
      }
      fVar21 = 0.0;
      if (0 < (int)puVar6[5]) {
        fVar19 = (float)(int)puVar6[5] / 30.0;
        fVar21 = 1.0;
        if (fVar19 < 1.0) {
          fVar21 = fVar19;
        }
      }
      if (0.0 < fVar22) {
        FUN_00256460(0,0x42200000,0,0x3f800000,0x3f800000,0,(int)(fVar22 * 153.0),
                     (int)(fVar20 * 153.0),(int)(fVar21 * 153.0),1,0,0);
      }
      if (0 < (int)puVar6[3]) {
        fVar20 = (float)(int)puVar6[3] / 30.0;
        fVar22 = 1.0;
        if (fVar20 < 1.0) {
          fVar22 = fVar20;
        }
        iVar7 = (int)(fVar22 * 255.0);
        FUN_00256040(0x43a00000,0x42700000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,0);
        FUN_00256040(0x43a00000,0x42c80000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,1);
        FUN_00256040(0x43a00000,0x430c0000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,2);
      }
      if (0 < (int)puVar6[4]) {
        fVar20 = (float)(int)puVar6[4] / 30.0;
        fVar22 = 1.0;
        if (fVar20 < 1.0) {
          fVar22 = fVar20;
        }
        iVar7 = (int)(fVar22 * 255.0);
        FUN_00256040(0x43a00000,0x43340000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,3);
        FUN_00256040(0x43a00000,0x435c0000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,4);
        FUN_00256040(0x43a00000,0x43820000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,5);
      }
      if (0 < (int)puVar6[5]) {
        fVar20 = (float)(int)puVar6[5] / 30.0;
        fVar22 = 1.0;
        if (fVar20 < 1.0) {
          fVar22 = fVar20;
        }
        iVar7 = (int)(fVar22 * 255.0);
        FUN_00256040(0x43a00000,0x43820000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,6);
        FUN_00256040(0x43a00000,0x43960000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,7);
        FUN_00256040(0x43a00000,0x43aa0000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,8);
      }
      if (((DAT_008c024e & 0x40) != 0) && ((int)puVar6[2] < 0x1a4)) {
        puVar6[2] = 0x1a4;
        *puVar6 = *puVar6 | 0x10;
      }
    }
    else if ((int)uVar15 < 0x1f5) {
      FUN_002566d0(0,0,0,0,fVar22,0xffffff,0xff,uVar10,uVar11);
      FUN_00256460(0,0x42200000,0,0x3f800000,0x3f800000,0,0x99,0x99,0x99,1,0,0);
      uVar5 = FUN_00248760((short)puVar6[6]);
      uVar10 = FUN_002438b0(uVar5);
      FUN_00278450((char)puVar6[0xf],0,uVar10);
      uVar5 = FUN_00248760((short)puVar6[6]);
      iVar7 = FUN_00246d90(uVar5);
      uVar10 = FUN_00109220(*(undefined2 *)(iVar7 + 0x40));
      FUN_00278450((char)puVar6[0xf],1,uVar10);
      FUN_00256040(0x43a00000,0x42700000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],1,0);
      FUN_00256040(0x43a00000,0x42c80000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],1,1);
      FUN_00256040(0x43a00000,0x430c0000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],1,2);
      FUN_00256040(0x43a00000,0x43340000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],1,3);
      FUN_00256040(0x43a00000,0x435c0000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],1,4);
      FUN_00256040(0x43a00000,0x43820000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],1,5);
      FUN_00256040(0x43a00000,0x43820000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],1,6);
      FUN_00256040(0x43a00000,0x43960000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],1,7);
      FUN_00256040(0x43a00000,0x43aa0000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],1,8);
    }
    else if ((int)uVar15 < 0x209) {
      fVar20 = 1.0 - (float)(int)(uVar15 - 500) / 20.0;
      FUN_002566d0(0,0,0,0,fVar22,0xffffff,0xff,uVar10,uVar11);
      iVar7 = (int)(fVar20 * 153.0);
      FUN_00256460(0,0x42200000,0,0x3f800000,0x3f800000,0,iVar7,iVar7,iVar7,1,0,0);
      uVar5 = FUN_00248760((short)puVar6[6]);
      uVar10 = FUN_002438b0(uVar5);
      FUN_00278450((char)puVar6[0xf],0,uVar10);
      uVar5 = FUN_00248760((short)puVar6[6]);
      iVar7 = FUN_00246d90(uVar5);
      uVar10 = FUN_00109220(*(undefined2 *)(iVar7 + 0x40));
      FUN_00278450((char)puVar6[0xf],1,uVar10);
      iVar7 = (int)(fVar20 * 255.0);
      FUN_00256040(0x43a00000,0x42700000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,0);
      FUN_00256040(0x43a00000,0x42c80000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,1);
      FUN_00256040(0x43a00000,0x430c0000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,2);
      FUN_00256040(0x43a00000,0x43340000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,3);
      FUN_00256040(0x43a00000,0x435c0000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,4);
      FUN_00256040(0x43a00000,0x43820000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,5);
      FUN_00256040(0x43a00000,0x43820000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,6);
      FUN_00256040(0x43a00000,0x43960000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,7);
      FUN_00256040(0x43a00000,0x43aa0000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],1,8);
    }
    else if ((int)uVar15 < 0x231) {
      if (uVar15 - 0x208 == 1) {
        if ((puVar6[7] == 10) || (puVar6[7] == 0)) {
          FUN_0045aeb0(2,0x635c80);
        }
        else {
          FUN_0045aeb0(2,0x635ca0);
        }
      }
      FUN_002566d0(0,0,0,0,fVar22,0xffffff,
                   (int)((1.0 - (float)(int)(uVar15 - 0x208) / 40.0) * 255.0),uVar10,uVar11);
    }
    uVar15 = puVar6[2];
    puVar6[2] = uVar15 + 1;
    if (0x29d < (int)(uVar15 + 1)) {
      puVar6[0x11] = 1;
    }
  }
  else if (uVar15 == 0) {
    if ((0x95 < (int)puVar6[2]) &&
       (uVar15 = puVar6[0x12], puVar6[0x12] = uVar15 + 1, 0x2c < (int)(uVar15 + 1))) {
      puVar6[0x12] = 0;
    }
    fVar22 = (float)(int)puVar6[0x12] / 45.0;
    if (puVar6[2] == 0) {
      uVar12 = FUN_00455f70(0x636630,auStack_4);
      uVar12 = FUN_0025fe50(param_1,uVar12,0x96,0x5dc974);
      FUN_001102f0(0x43960000,auStack_30,0x140,0xa5);
      uVar12 = FUN_0025ff60(uVar12);
      iVar7 = FUN_00457120();
      uVar13 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar12,uVar13);
      FUN_004b1250(uVar12,auStack_30);
    }
    if (puVar6[2] == 0) {
      uVar12 = FUN_00455f70(0x636650,auStack_4);
      uVar12 = FUN_0025fe50(param_1,uVar12,100,0x5dc974);
      FUN_001102f0(0x43960000,auStack_30,0x140,0xb4);
      uVar12 = FUN_0025ff60(uVar12);
      iVar7 = FUN_00457120();
      uVar13 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar12,uVar13);
      FUN_004b1250(uVar12,auStack_30);
    }
    if (puVar6[2] == 0x78) {
      uVar12 = FUN_00455f70(0x636670,auStack_4);
      uVar12 = FUN_0025fe50(param_1,uVar12,0x96,0x5dc974);
      FUN_001102f0(0x43960000,auStack_30,0x140,0xb4);
      uVar12 = FUN_0025ff60(uVar12);
      iVar7 = FUN_00457120();
      uVar13 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar12,uVar13);
      FUN_004b1250(uVar12,auStack_30);
    }
    if (puVar6[2] == 0x23a) {
      uVar12 = FUN_00455f70(0x636630,auStack_4);
      uVar12 = FUN_0025fe50(param_1,uVar12,0x96,0x5dc974);
      FUN_001102f0(0x43960000,auStack_30,0x140,0xa5);
      uVar12 = FUN_0025ff60(uVar12);
      iVar7 = FUN_00457120();
      uVar13 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar12,uVar13);
      FUN_004b1250(uVar12,auStack_30);
    }
    if ((puVar6[2] == 600) && (lVar14 = FUN_00257820(puVar6[8],auStack_30), lVar14 != 0)) {
      uVar12 = FUN_00455f70(0x636690,auStack_4);
      uVar12 = FUN_0025fe50(param_1,uVar12,0x96,0x5dc974);
      uVar12 = FUN_0025ff60(uVar12);
      iVar7 = FUN_00457120();
      uVar13 = FUN_003e9700(*(undefined4 *)(iVar7 + 4));
      FUN_004b12e0(uVar12,uVar13);
      FUN_004b1250(uVar12,auStack_30);
    }
    if ((puVar6[2] == 0x280) && (lVar14 = FUN_00257820(puVar6[8],auStack_30), lVar14 != 0)) {
      uVar12 = FUN_00455f70(0x6366b0,auStack_4);
      uVar12 = FUN_0025fe50(param_1,uVar12,0x96,0x5dc974);
      uVar12 = FUN_0025ff60(uVar12);
      FUN_004b1250(uVar12,auStack_30);
    }
    uVar15 = puVar6[2];
    if (9 < (int)uVar15) {
      if ((int)uVar15 < 0x50) {
        FUN_002566d0(0,0,0,0x3f800000,0,0xffffff,(int)(((float)(int)(uVar15 - 10) / 70.0) * 255.0),
                     uVar10,uVar11);
      }
      else if ((int)uVar15 < 0x65) {
        FUN_002566d0(0,0,0,0x3f800000,0,0xffffff,0xff,uVar10,uVar11);
      }
      else if ((int)uVar15 < 0x79) {
        FUN_002566d0(0,0,0,1.0 - (float)(int)(uVar15 - 100) / 20.0,0,0xffffff,0xff,uVar10,uVar11);
      }
      else if ((int)uVar15 < 0x97) {
        FUN_002566d0(0,0,0,0,0,0xffffff,0xff,uVar10,uVar11);
      }
      else if ((int)uVar15 < 0xbf) {
        FUN_002566d0(0,0,0,0,fVar22,0xffffff,0xff,uVar10,uVar11);
      }
      else if ((int)uVar15 < 0x1eb) {
        FUN_002566d0(0,0,0,0,fVar22,0xffffff,0xff,uVar10,uVar11);
        uVar15 = puVar6[2];
        uVar5 = FUN_00248760((short)puVar6[6]);
        uVar10 = FUN_002438b0(uVar5);
        FUN_00278450((char)puVar6[0xf],0,uVar10);
        if (0 < (int)puVar6[3]) {
          puVar6[3] = puVar6[3] + 1;
        }
        if (0 < (int)puVar6[4]) {
          puVar6[4] = puVar6[4] + 1;
        }
        if (0 < (int)puVar6[5]) {
          puVar6[5] = puVar6[5] + 1;
        }
        if ((*puVar6 & 0x10) == 0) {
          if (uVar15 == 0xbf) {
            puVar6[3] = puVar6[3] + 1;
          }
          else if (uVar15 == 0x118) {
            puVar6[4] = puVar6[4] + 1;
          }
          else if (uVar15 == 0x172) {
            puVar6[5] = puVar6[5] + 1;
          }
        }
        else {
          if (puVar6[3] == 0) {
            puVar6[3] = 1;
          }
          if (puVar6[4] == 0) {
            puVar6[4] = 1;
          }
          if (puVar6[5] == 0) {
            puVar6[5] = 1;
          }
        }
        fVar22 = 0.0;
        if (0 < (int)puVar6[3]) {
          fVar20 = (float)(int)puVar6[3] / 30.0;
          fVar22 = 1.0;
          if (fVar20 < 1.0) {
            fVar22 = fVar20;
          }
        }
        fVar20 = 0.0;
        if (0 < (int)puVar6[4]) {
          fVar21 = (float)(int)puVar6[4] / 30.0;
          fVar20 = 1.0;
          if (fVar21 < 1.0) {
            fVar20 = fVar21;
          }
        }
        fVar21 = 0.0;
        if (0 < (int)puVar6[5]) {
          fVar19 = (float)(int)puVar6[5] / 30.0;
          fVar21 = 1.0;
          if (fVar19 < 1.0) {
            fVar21 = fVar19;
          }
        }
        if (0.0 < fVar22) {
          FUN_002561f0(0,0x42200000,0,0x3f800000,0x3f800000,0,(int)(fVar22 * 153.0),
                       (int)(fVar20 * 153.0),(int)(fVar21 * 153.0),1,0,0);
        }
        if (0 < (int)puVar6[3]) {
          fVar20 = (float)(int)puVar6[3] / 30.0;
          fVar22 = 1.0;
          if (fVar20 < 1.0) {
            fVar22 = fVar20;
          }
          FUN_00256040(0x43a00000,0x42700000,0,0xffffff,(int)(fVar22 * 255.0),0,0,0,
                       (char)puVar6[0xf],0,0);
          FUN_00256040(0x43a00000,0x42c80000,0,0xffffff,(int)(fVar22 * 255.0),0,0,0,
                       (char)puVar6[0xf],0,1);
        }
        if (0 < (int)puVar6[4]) {
          fVar20 = (float)(int)puVar6[4] / 30.0;
          fVar22 = 1.0;
          if (fVar20 < 1.0) {
            fVar22 = fVar20;
          }
          iVar7 = (int)(fVar22 * 255.0);
          FUN_00256040(0x43a00000,0x430c0000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],0,2);
          FUN_00256040(0x43a00000,0x43340000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],0,3);
          FUN_00256040(0x43a00000,0x435c0000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],0,4);
        }
        if (0 < (int)puVar6[5]) {
          fVar20 = (float)(int)puVar6[5] / 30.0;
          fVar22 = 1.0;
          if (fVar20 < 1.0) {
            fVar22 = fVar20;
          }
          FUN_00256040(0x43a00000,0x43820000,0,0xffffff,(int)(fVar22 * 255.0),0,0,0,
                       (char)puVar6[0xf],0,5);
          FUN_00256040(0x43a00000,0x43960000,0,0xffffff,(int)(fVar22 * 255.0),0,0,0,
                       (char)puVar6[0xf],0,6);
        }
        if (((DAT_008c024e & 0x40) != 0) && ((int)puVar6[2] < 0x1cc)) {
          puVar6[2] = 0x1cc;
          *puVar6 = *puVar6 | 0x10;
        }
      }
      else if ((int)uVar15 < 0x213) {
        FUN_002566d0(0,0,0,0,fVar22,0xffffff,0xff,uVar10,uVar11);
        FUN_002561f0(0,0x42200000,0,0x3f800000,0x3f800000,0,0x99,0x99,0x99,1,0,0);
        uVar5 = FUN_00248760((short)puVar6[6]);
        uVar10 = FUN_002438b0(uVar5);
        FUN_00278450((char)puVar6[0xf],0,uVar10);
        FUN_00256040(0x43a00000,0x42700000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],0,0);
        FUN_00256040(0x43a00000,0x42c80000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],0,1);
        FUN_00256040(0x43a00000,0x430c0000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],0,2);
        FUN_00256040(0x43a00000,0x43340000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],0,3);
        FUN_00256040(0x43a00000,0x435c0000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],0,4);
        FUN_00256040(0x43a00000,0x43820000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],0,5);
        FUN_00256040(0x43a00000,0x43960000,0,0xffffff,0xff,0,0,0,(char)puVar6[0xf],0,6);
      }
      else if ((int)uVar15 < 0x227) {
        fVar20 = 1.0 - (float)(int)(uVar15 - 0x212) / 20.0;
        FUN_002566d0(0,0,0,0,fVar22,0xffffff,0xff,uVar10,uVar11);
        iVar7 = (int)(fVar20 * 153.0);
        FUN_002561f0(0,0x42200000,0,0x3f800000,0x3f800000,0,iVar7,iVar7,iVar7,1,0,0);
        uVar5 = FUN_00248760((short)puVar6[6]);
        uVar10 = FUN_002438b0(uVar5);
        FUN_00278450((char)puVar6[0xf],0,uVar10);
        iVar7 = (int)(fVar20 * 255.0);
        FUN_00256040(0x43a00000,0x42700000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],0,0);
        FUN_00256040(0x43a00000,0x42c80000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],0,1);
        FUN_00256040(0x43a00000,0x430c0000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],0,2);
        FUN_00256040(0x43a00000,0x43340000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],0,3);
        FUN_00256040(0x43a00000,0x435c0000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],0,4);
        FUN_00256040(0x43a00000,0x43820000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],0,5);
        FUN_00256040(0x43a00000,0x43960000,0,0xffffff,iVar7,0,0,0,(char)puVar6[0xf],0,6);
      }
      else if ((int)uVar15 < 0x24f) {
        if (uVar15 - 0x226 == 1) {
          if ((puVar6[7] == 10) || (puVar6[7] == 0)) {
            FUN_0045aeb0(2,0x635c80);
          }
          else {
            FUN_0045aeb0(2,0x635ca0);
          }
        }
        FUN_002566d0(0,0,0,0,fVar22,0xffffff,
                     (int)((1.0 - (float)(int)(uVar15 - 0x226) / 40.0) * 255.0),uVar10,uVar11);
      }
    }
    uVar15 = puVar6[2];
    puVar6[2] = uVar15 + 1;
    if (699 < (int)(uVar15 + 1)) {
      puVar6[0x11] = 1;
    }
  }
  puVar9 = (undefined4 *)0x4;
  puVar16 = &uStack_20;
  puVar4 = puVar16;
  while (puVar4 != (undefined4 *)0x0) {
    *(undefined1 *)puVar16 = 0;
    puVar16 = (undefined4 *)((int)puVar16 + 1);
    puVar9 = (undefined4 *)((int)puVar9 + -1);
    puVar4 = puVar9;
  }
  uStack_1c = uStack_20;
  puVar9 = (undefined4 *)0x10;
  puVar16 = &uStack_340;
  puVar4 = puVar16;
  while (puVar4 != (undefined4 *)0x0) {
    *(undefined1 *)puVar16 = 0;
    puVar16 = (undefined4 *)((int)puVar16 + 1);
    puVar9 = (undefined4 *)((int)puVar9 + -1);
    puVar4 = puVar9;
  }
  uStack_340 = 0;
  uStack_33c = 0;
  uStack_338 = 0x280;
  uStack_334 = 0x1c0;
  uStack_330 = 0;
  uStack_32c = 0;
  uStack_328 = 0x280;
  uStack_324 = 0x1c0;
  (*DAT_00887300)(0xe,0);
  (*DAT_00887300)(0xc,1);
  (*DAT_00887300)(7,2);
  (*DAT_00887300)(9,1);
  (*DAT_00887300)(0x14,1);
  (*DAT_00887300)(6,0);
  (*DAT_00887300)(8,1);
  FUN_003f6440(3,0x31003);
  FUN_003f6440(2,0x44);
  FUN_00489f80();
  FUN_0045d6e0(0x477fff00,&uStack_1c,&uStack_330,0);
  FUN_0048a000();
  return 0;
}


// func_0025b0f0  addr 0x0025b0f0  window 336B
void FUN_0025b0f0(undefined8 param_1,undefined8 param_2)

{
  undefined4 *puVar1;
  int iVar2;
  undefined4 *puVar3;
  undefined4 *puVar4;
  float fVar5;
  undefined1 uVar6;
  undefined4 uStack_20;
  undefined4 uStack_1c;
  undefined4 uStack_18;
  undefined4 uStack_14;
  undefined4 uStack_8;
  undefined4 uStack_4;
  
  iVar2 = FUN_00452560(param_2);
  puVar3 = (undefined4 *)0x4;
  puVar4 = &uStack_8;
  puVar1 = puVar4;
  while (puVar1 != (undefined4 *)0x0) {
    *(undefined1 *)puVar4 = 0;
    puVar4 = (undefined4 *)((int)puVar4 + 1);
    puVar3 = (undefined4 *)((int)puVar3 + -1);
    puVar1 = puVar3;
  }
  fVar5 = ((float)*(int *)(iVar2 + 0x4c) * 127.5) / 40.0;
  if (fVar5 < 2.1474836e+09) {
    uVar6 = (undefined1)(int)fVar5;
  }
  else {
    uVar6 = (undefined1)(int)(fVar5 - 2.1474836e+09);
  }
  uStack_8 = CONCAT13(uVar6,(undefined3)uStack_8);
  uStack_4 = uStack_8;
  uStack_20 = DAT_00636730;
  uStack_1c = DAT_00636734;
  uStack_18 = DAT_00636738;
  uStack_14 = DAT_0063673c;
  FUN_0045d6e0(0,&uStack_4,&uStack_20,1);
  switch(*(undefined4 *)(iVar2 + 4)) {
  case 9:
  case 10:
    FUN_00257900(param_2);
  }
  return;
}


// func_0025b240  addr 0x0025b240  window 3776B
undefined4 FUN_0025b240(undefined8 param_1)

{
  uint uVar1;
  undefined4 uVar2;
  undefined1 uVar3;
  char cVar4;
  uint *puVar5;
  uint uVar6;
  undefined8 uVar7;
  long lVar8;
  undefined8 uVar9;
  int iVar10;
  undefined4 *puVar11;
  undefined4 *puVar12;
  long lVar13;
  undefined4 auStack_138 [10];
  undefined1 auStack_110 [224];
  undefined1 auStack_30 [40];
  int iStack_8;
  undefined1 auStack_4 [4];
  
  puVar5 = (uint *)FUN_00452560();
  lVar13 = 0;
  switch(puVar5[1]) {
  case 0:
    puVar5[1] = 3;
    uVar9 = FUN_00248760((short)puVar5[6]);
    uVar6 = func_0x0035adc0(param_1,uVar9,0);
    puVar5[0xb] = uVar6;
    uVar6 = func_0x0035adc0(param_1,0xffffffffffffffff,0);
    puVar5[0xc] = uVar6;
    FUN_00440b68(&gp0xffffa680,0x635cf8,0xadb);
    uVar6 = FUN_00454a60(0x636760,1);
    puVar5[0xd] = uVar6;
    break;
  case 1:
    puVar5[1] = 2;
    if (((int)puVar5[7] < 1) || (9 < (int)puVar5[7])) {
      FUN_004598e0(10);
    }
  case 2:
    if ((*puVar5 & 8) == 0) {
      if (iGpffffa664 == -1) {
        func_0x00459880();
      }
      else {
        FUN_004599a0((short)iGpffffa664,10);
        func_0x00459950(0xffffffffffffffc4);
      }
      if (iGpffffa668 == -1) {
        func_0x0045a8d0(3,0);
      }
      else {
        func_0x0045b2e0();
      }
      return 0xffffffff;
    }
    break;
  case 3:
    lVar13 = func_0x0035af60(puVar5[0xb]);
    if (((lVar13 != 0) && (lVar13 = func_0x0035af60(puVar5[0xc]), lVar13 != 0)) &&
       (lVar13 = FUN_004553c0(puVar5[0xd]), lVar13 != 0)) {
      puVar5[1] = 4;
      uVar6 = FUN_00455f70(0x636780,auStack_4);
      puVar5[0xe] = uVar6;
      uVar6 = FUN_004667d0(0,0x6367a0,0,0,0,0,0,0);
      puVar5[0x14] = uVar6;
      uVar9 = FUN_0035afa0(puVar5[0xb]);
      lVar13 = FUN_003ec3d0(uVar9,1);
      if (lVar13 == 0) {
        FUN_0046d730(0x635cf8,0xaf7);
      }
      FUN_0044ea90(0x635cf8,0xaf8);
      uVar7 = (*DAT_008873f4)(1,0x400,0x40000);
      puVar5[0x16] = (uint)uVar7;
      FUN_0043f810(uVar7,lVar13,0x400);
      FUN_003ec2e0(uVar9);
    }
    break;
  case 4:
    uVar6 = FUN_004669d0(puVar5[0x14],&iStack_8,0);
    puVar5[0x15] = uVar6;
    if (iStack_8 != 0) {
      puVar5[1] = 5;
      puVar5[0x14] = 0;
    }
    break;
  case 5:
    iGpffffa664 = func_0x00459760();
    iGpffffa668 = func_0x0045b400();
    func_0x00459a60();
    FUN_0045aac0(3,0,10);
    puVar5[1] = 6;
    puVar5[2] = 0;
    FUN_0043f9c8(auStack_110,0,0xd8);
    func_0x0025fd70(auStack_110,0x35,0);
    func_0x0025fbb0(0,0,auStack_110,0,0xffffffffffffffff,0xffffffffffffffff,0,0);
    func_0x0025fd00(uGpffff82a4,0x3e800000,auStack_110,0xff,0);
    uVar6 = func_0x0025fab0(param_1,1,0,auStack_110,0x5dc974);
    puVar5[10] = uVar6;
    uVar6 = func_0x00255b90();
    puVar5[0x10] = uVar6;
    func_0x002518d0(puVar5[7]);
  case 6:
    uVar6 = puVar5[2];
    puVar5[2] = uVar6 + 1;
    if ((uVar6 + 1 == 5) && (lVar13 = func_0x00189fa0(), lVar13 != 0)) {
      *puVar5 = *puVar5 | 1;
    }
    if (0x34 < (int)puVar5[2]) {
      FUN_00452080(puVar5[10]);
      if (((int)puVar5[7] < 1) || (10 < (int)puVar5[7])) {
        puVar5[1] = 9;
      }
      else {
        puVar5[1] = 7;
      }
      puVar5[2] = 0;
    }
    break;
  case 7:
    puVar5[1] = 8;
    uVar6 = puVar5[7];
    uVar1 = puVar5[6];
    if (uVar1 == 0) {
      FUN_0046d730(0x635cf8,0x25d);
    }
    FUN_0044ea90(0x635cf8,0x25e);
    uVar9 = (*DAT_008873f4)(1,0x40,0x40000);
    *(uint *)((int)uVar9 + 4) = uVar1;
    *(uint *)((int)uVar9 + 8) = uVar6;
    uVar6 = FUN_00451fc0(param_1,0x635d08,0xf,0,0,0x2519e0,0x251ce0,uVar9);
    puVar5[9] = uVar6;
  case 8:
    lVar13 = FUN_00452380(0x635d08);
    if (lVar13 == 0) {
      if ((puVar5[7] == 0) || (puVar5[7] == 10)) {
        puVar5[1] = 9;
      }
      else {
        puVar5[1] = 0xb;
      }
      puVar5[2] = 0;
    }
    break;
  case 9:
    puVar5[1] = 10;
    uVar3 = FUN_002774d0(puVar5[0xe]);
    *(undefined1 *)(puVar5 + 0xf) = uVar3;
    puVar5[0x11] = 0;
    *puVar5 = *puVar5 | 2;
    uVar6 = puVar5[7];
    FUN_0045aac0(3,0,10);
    if (((int)uVar6 < 1) || (9 < (int)uVar6)) {
      if (uVar6 == 10) {
        FUN_004599a0(0xf);
      }
      else {
        FUN_004599a0(0xe);
      }
    }
  case 10:
    iVar10 = FUN_00452560(param_1);
    if (*(int *)(iVar10 + 0x44) != 0) {
      puVar5[1] = 0xb;
      FUN_002777f0((char)puVar5[0xf]);
      puVar5[2] = 0;
    }
    break;
  case 0xb:
    puVar5[1] = 0xc;
  case 0xc:
    puVar5[1] = 0xd;
    puVar5[2] = 0;
    break;
  case 0xd:
    puVar5[1] = 0xe;
    uVar3 = FUN_002bab80(puVar5[0xe]);
    *(undefined1 *)(puVar5 + 0xf) = uVar3;
    uVar6 = puVar5[7];
    if (uVar6 == 0) {
      uVar3 = FUN_00248760((short)puVar5[6]);
      uVar9 = FUN_002438b0(uVar3);
      FUN_002bbd80((char)puVar5[0xf],0,uVar9);
      if (puVar5[6] == 7) {
        FUN_002badc0((char)puVar5[0xf],0xc);
      }
      else {
        FUN_002badc0((char)puVar5[0xf],2);
      }
    }
    else if (uVar6 == 10) {
      uVar9 = FUN_00246830((short)puVar5[6]);
      func_0x00275980(uVar9,auStack_30,0x20);
      FUN_002bbd80((char)puVar5[0xf],0,auStack_30);
      uVar3 = FUN_00248760((short)puVar5[6]);
      uVar9 = FUN_002438b0(uVar3);
      FUN_002bbd80((char)puVar5[0xf],1,uVar9);
      uVar3 = FUN_00248760((short)puVar5[6]);
      uVar9 = FUN_00246d90(uVar3);
      func_0x00275980(uVar9,auStack_30,0x20);
      FUN_002bbd80((char)puVar5[0xf],2,auStack_30);
      uVar3 = FUN_00248760((short)puVar5[6]);
      iVar10 = FUN_00246d90(uVar3);
      uVar9 = FUN_00109220(*(undefined2 *)(iVar10 + 0x40));
      FUN_00442830(auStack_30,uVar9);
      FUN_002bbd80((char)puVar5[0xf],3,auStack_30);
      FUN_002badc0((char)puVar5[0xf],4);
    }
    else if (uVar6 == 0xb) {
      FUN_002badc0((char)puVar5[0xf],5);
    }
    else if (uVar6 == 0xc) {
      FUN_002badc0((char)puVar5[0xf],6);
    }
    else {
      if (iGpffffa664 == -1) {
        func_0x00459880();
      }
      else {
        FUN_004599a0((short)iGpffffa664);
        func_0x00459950(0xffffffffffffff4c);
      }
      if (iGpffffa668 == -1) {
        func_0x0045a8d0(3,0);
      }
      else {
        func_0x0045b2e0();
      }
      uVar9 = FUN_00246830((short)puVar5[6]);
      func_0x00275980(uVar9,auStack_30,0x20);
      FUN_002bbd80((char)puVar5[0xf],0,auStack_30);
      FUN_00442088(auStack_30,&gp0xffffa688,puVar5[7]);
      FUN_002bbd80((char)puVar5[0xf],1,auStack_30);
      uVar3 = FUN_00248760((short)puVar5[6]);
      uVar9 = FUN_002438b0(uVar3);
      FUN_002bbd80((char)puVar5[0xf],2,uVar9);
      FUN_002badc0((char)puVar5[0xf],3);
    }
  case 0xe:
    lVar13 = FUN_002bb680((char)puVar5[0xf]);
    if (lVar13 == 0) {
      func_0x002bb420((char)puVar5[0xf]);
      uVar6 = puVar5[7];
      cVar4 = (char)uVar6;
      if (cVar4 == '\0') {
        cVar4 = '\x01';
      }
      if (((uVar6 == 0xb) || (uVar6 == 0xc)) ||
         (lVar13 = func_0x00255ed0(puVar5[6],cVar4), lVar13 == 0)) {
        FUN_002bb550((char)puVar5[0xf]);
        puVar5[1] = 1;
        *puVar5 = *puVar5 | 4;
      }
      else {
        puVar5[1] = 0xf;
      }
    }
    FUN_002bbcf0((char)puVar5[0xf]);
    break;
  case 0xf:
    puVar5[1] = 0x10;
    cVar4 = (char)puVar5[7];
    if (cVar4 == '\0') {
      cVar4 = '\x01';
    }
    puVar12 = (undefined4 *)0x636740;
    puVar11 = auStack_138 + 2;
    iVar10 = 5;
    do {
      uVar2 = *puVar12;
      puVar12 = puVar12 + 1;
      iVar10 = iVar10 + -1;
      *puVar11 = uVar2;
      puVar11 = puVar11 + 1;
    } while (0 < iVar10);
    cVar4 = func_0x00255ed0(puVar5[6],cVar4);
    if (((cVar4 < '\x02') || ('\x06' < cVar4)) || ((*puVar5 & 0x20) == 0)) {
      if ((('\x01' < cVar4) && (cVar4 < '\a')) &&
         (lVar8 = FUN_00106330(auStack_138[cVar4]), lVar8 == 0)) {
        *puVar5 = *puVar5 | 0x20;
      }
      uVar9 = func_0x002468a0((short)puVar5[6]);
      func_0x00275980(uVar9,auStack_30,0x20);
      FUN_002bbd80((char)puVar5[0xf],0,auStack_30);
      switch(cVar4) {
      case '\x02':
        FUN_002badc0((char)puVar5[0xf],7);
        break;
      case '\x03':
        FUN_002badc0((char)puVar5[0xf],8);
        break;
      case '\x04':
        FUN_002badc0((char)puVar5[0xf],9);
        break;
      case '\x05':
        FUN_002badc0((char)puVar5[0xf],10);
        break;
      case '\x06':
        FUN_002badc0((char)puVar5[0xf],0xb);
        break;
      case '\a':
        lVar13 = 0x113;
        FUN_002bbd80((char)puVar5[0xf],1,iGpffffb448 + 0x1469);
        FUN_002badc0((char)puVar5[0xf],0x12);
        uVar9 = FUN_0010a900(5);
        FUN_0010cc20(uVar9,0x113);
        break;
      case '\b':
        lVar13 = 0x112;
        FUN_002bbd80((char)puVar5[0xf],1,iGpffffb448 + 0x1456);
        FUN_002badc0((char)puVar5[0xf],0x13);
        uVar9 = FUN_0010a900(5);
        FUN_0010cc20(uVar9,0x112);
        break;
      case '\t':
        lVar13 = 0x10d;
        FUN_002bbd80((char)puVar5[0xf],1,iGpffffb448 + 0x13f7);
        uVar9 = FUN_0010a900(5);
        FUN_0010cc20(uVar9,0x10d);
      }
      if (lVar13 == 0x113) {
        FUN_00106390(0x1013,1);
      }
      if (lVar13 == 0x112) {
        FUN_00106390(0x1012,1);
      }
    }
    else {
      FUN_00106390(auStack_138[cVar4],1);
      if (cVar4 == '\x06') {
        func_0x002bae80((char)puVar5[0xf],0x11);
      }
      else if (cVar4 == '\x05') {
        func_0x002bae80((char)puVar5[0xf],0x10);
      }
      else if (cVar4 == '\x04') {
        func_0x002bae80((char)puVar5[0xf],0xf);
      }
      else if (cVar4 == '\x03') {
        func_0x002bae80((char)puVar5[0xf],0xe);
      }
      else if (cVar4 == '\x02') {
        func_0x002bae80((char)puVar5[0xf],0xd);
      }
      *puVar5 = *puVar5 & 0xffffffdf;
    }
  case 0x10:
    lVar13 = FUN_002bb680((char)puVar5[0xf]);
    if (lVar13 == 0) {
      func_0x002bb420((char)puVar5[0xf]);
      if ((*puVar5 & 0x20) == 0) {
        FUN_002bb550((char)puVar5[0xf]);
        puVar5[1] = 1;
        *puVar5 = *puVar5 | 4;
      }
      else {
        puVar5[1] = 0xf;
      }
    }
    FUN_002bbcf0((char)puVar5[0xf]);
  }
  uVar6 = *puVar5;
  if ((uVar6 & 8) == 0) {
    if (((uVar6 & 2) != 0) &&
       (uVar6 = puVar5[0x13], puVar5[0x13] = uVar6 + 1, 0x27 < (int)(uVar6 + 1))) {
      uVar6 = *puVar5;
      *puVar5 = uVar6 & 0xfffffffd;
      *puVar5 = uVar6 & 0xfffffffd | 8;
    }
  }
  else if (((uVar6 & 4) != 0) &&
          (uVar6 = puVar5[0x13], puVar5[0x13] = uVar6 - 1, (int)(uVar6 - 1) < 1)) {
    uVar6 = *puVar5;
    *puVar5 = uVar6 & 0xfffffffb;
    *puVar5 = uVar6 & 0xfffffff3;
  }
  uVar9 = FUN_00460990();
  *(code **)((int)uVar9 + 8) = FUN_0025b0f0;
  *(int *)((int)uVar9 + 0x10) = (int)param_1;
  FUN_00460ac0(0x7963d0,uVar9);
  return 0;
}

