/* Generated by tools/ida_headstart.py -- Hex-Rays (IDA Pro 9.4) pseudocode.
 *
 * REFERENCE ONLY. This is not valid C and is never compiled: IDA's pseudo
 * types (__int64, _DWORD, _$F0 register aliases) are not MWCC input, and a
 * raw `__asm { ... }` block below is Hex-Rays declining to model an Emotion
 * Engine instruction it does not understand (FPU multiply-accumulate chains,
 * or a rare single op like mfthc1/pcpyld). Everything else in a function
 * usually decompiles correctly -- control flow, hardware MMIO addresses
 * (rendered as MEMORY[0x...]), struct layout. Translate an asm island by
 * hand using the measured b210 rules in docs/matching.md; do not guess.
 *
 * Regenerate: python3 tools/ida_headstart.py --report <verify.json>
 */

// func_00480f20  addr 0x00480f20  window 416B
void __fastcall sub_480F20(float *a1, float *a2)
{
  float v2; // $f0
  float v3; // $f1
  float v4; // $f9
  float v5; // $f10
  float v6; // $f7
  float v7; // $f6
  float v8; // $f5
  float v9; // $f4
  float v10; // $f2
  float v11; // $f0
  float v15; // [sp+0h] [-10h]
  float v16; // [sp+4h] [-Ch]
  float v17; // [sp+8h] [-8h]
  float v18; // [sp+Ch] [-4h]

  v15 = a1[2];
  v16 = a1[3];
  v17 = a1[4];
  v18 = a1[5];
  v6 = a2[3];
  v7 = a2[2];
  v8 = a2[4];
  v9 = a2[5];
  v10 = (float)((float)((float)(v6 * v6) + (float)(v7 * v7)) + (float)(v8 * v8)) + (float)(v9 * v9);
  if ( v10 > 0.0 )
  {
    v5 = v9 * (float)(1.0 / v10);
    v11 = -(float)(1.0 / v10);
    v4 = v7 * v11;
    v3 = v6 * v11;
    v2 = v8 * v11;
  }
  _$F6 = v18;
  a1[5] = (float)(v5 * v18) - (float)((float)((float)(v3 * v16) + (float)(v4 * v15)) + (float)(v2 * v17));
  a1[2] = (float)(v3 * v17) - (float)(v2 * v16);
  a1[3] = (float)(v2 * v15) - (float)(v4 * v17);
  a1[4] = (float)(v4 * v16) - (float)(v3 * v15);
  a1[2] = (float)(a1[2] + 0.0) + (float)(v15 * v5);
  a1[3] = (float)(a1[3] + 0.0) + (float)(v16 * v5);
  a1[4] = (float)(a1[4] + 0.0) + (float)(v17 * v5);
  a1[2] = (float)(a1[2] + 0.0) + (float)(v4 * v18);
  __asm { madd.s  $f1, $f6 }
  a1[3] = _$F1;
  __asm { madd.s  $f0, $f6 }
  a1[4] = _$F0;
  a1[6] = a1[6] - a2[6];
  a1[7] = a1[7] - a2[7];
  a1[8] = a1[8] - a2[8];
  a1[9] = a1[9] - a2[9];
  a1[10] = a1[10] - a2[10];
  a1[11] = a1[11] - a2[11];
}

