/* Generated by tools/ida_headstart.py -- Hex-Rays (IDA Pro 9.4) pseudocode.
 *
 * REFERENCE ONLY. This is not valid C and is never compiled: IDA's pseudo
 * types (__int64, _DWORD, _$F0 register aliases) are not MWCC input, and a
 * raw `__asm { ... }` block below is Hex-Rays declining to model an Emotion
 * Engine instruction it does not understand (FPU multiply-accumulate chains,
 * or a rare single op like mfthc1/pcpyld). Everything else in a function
 * usually decompiles correctly -- control flow, hardware MMIO addresses
 * (rendered as MEMORY[0x...]), struct layout. Translate an asm island by
 * hand using the measured b210 rules in docs/matching.md; do not guess.
 *
 * Regenerate: python3 tools/ida_headstart.py --report <verify.json>
 */

// func_00121690  addr 0x00121690  window 688B
__int64 sub_121690()
{
  int v0; // $gp
  int v1; // $s1
  __int64 v3; // $v0
  __int64 v4; // $s2
  __int64 v5; // $v0
  int v6; // $s0
  int v7; // $s3
  int v8; // $v0
  unsigned __int8 v9; // $v0
  __int64 i; // $s0
  int v11; // [sp+50h] [-30h] BYREF
  int v12; // [sp+54h] [-2Ch]
  int v13; // [sp+58h] [-28h]
  int v14; // [sp+5Ch] [-24h]
  __int64 v15; // [sp+68h] [-18h]
  _BYTE v16[3]; // [sp+74h] [-Ch] BYREF
  char v17; // [sp+77h] [-9h]
  _BYTE v18[4]; // [sp+78h] [-8h] BYREF
  int v19; // [sp+7Ch] [-4h] BYREF

  v1 = *(_DWORD *)(v0 - 20028);
  if ( v1 == 0 )
    return 0;
  if ( *(_DWORD *)(v1 + 4) == 0 )
    return 0;
  memset(v16, 64, sizeof(v16));
  v17 = -1;
  v11 = 100;
  v12 = 100;
  v13 = 250;
  v14 = 100;
  sub_45D6E0((int)v16, (int)&v11, 1);
  sub_1104D0(*(int *)(v1 + 8), (int)&v19, (int)v18);
  v3 = sub_110600(v19, 1);
  v4 = sub_110580(v3);
  v5 = sub_110580(*(int *)(v1 + 8));
  v6 = v5;
  if ( v5 < v4 )
    v7 = 12;
  else
    v7 = 0;
  v8 = sub_1105B0(*(int *)(v1 + 8));
  v16[0] = 64;
  v16[1] = 0x80;
  v16[2] = 0x80;
  v17 = -1;
  v11 = 36 * v6 + 100;
  v12 = v7 + 12 * (v8 - 1) + 124;
  v13 = 36;
  v14 = 12;
  sub_45D6E0((int)v16, (int)&v11, 1);
  v15 = 0x42C8000042C80000LL;
  v9 = sub_1060C0();
  sub_450DD0(v15, "%2d  ##%s##", v19, (const char *)off_5E5010[v9]);
  *(float *)&v15 = (float)(100.0 + 0.0) + (float)(36.0 * (float)(int)v4);
  HIDWORD(v15) = 1123549184;
  for ( i = 0; i < sub_1104A0(v19); i = (int)i + 1 )
  {
    sub_450DD0(v15, (const char *)(v0 - 25516), (int)i + 1);
    v4 = (int)v4 + 1;
    if ( v4 >= 7 )
    {
      LODWORD(v4) = 0;
      *(float *)&v15 = *(float *)&v15 - 252.0;
      *((float *)&v15 + 1) = *((float *)&v15 + 1) + 12.0;
    }
    *(float *)&v15 = *(float *)&v15 + 36.0;
  }
  return 0;
}

