/* Generated by tools/ida_headstart.py -- Hex-Rays (IDA Pro 9.4) pseudocode.
 *
 * REFERENCE ONLY. This is not valid C and is never compiled: IDA's pseudo
 * types (__int64, _DWORD, _$F0 register aliases) are not MWCC input, and a
 * raw `__asm { ... }` block below is Hex-Rays declining to model an Emotion
 * Engine instruction it does not understand (FPU multiply-accumulate chains,
 * or a rare single op like mfthc1/pcpyld). Everything else in a function
 * usually decompiles correctly -- control flow, hardware MMIO addresses
 * (rendered as MEMORY[0x...]), struct layout. Translate an asm island by
 * hand using the measured b210 rules in docs/matching.md; do not guess.
 *
 * Regenerate: python3 tools/ida_headstart.py --report <verify.json>
 */

// func_00285dd0  addr 0x00285dd0  window 1136B
__int64 __fastcall sub_285DD0(__int64 a1)
{
  __int64 v3; // $ra
  __int64 v5; // $v0
  __int64 v6; // $s1
  int v7; // $v1
  __int64 v8; // $a0
  __int64 v9; // $v0
  int *v10; // $s0
  __int64 i; // $v0
  __int64 j; // $s0
  int v13; // $a0
  int v14; // $v1
  __int64 v15; // $a2
  __int64 v16; // $v0
  __int64 v17; // $v0
  __int64 v23; // [sp+20h] [-50h]
  _BYTE v24[64]; // [sp+30h] [-40h] BYREF

  v23 = v3;
  __asm
  {
    sq      $s1, 0x70+var_60($sp)
    sq      $s0, 0x70+var_70($sp)
  }
  v5 = sub_452560(a1);
  v6 = v5;
  switch ( *(_DWORD *)(v5 + 1900) )
  {
    case 0:
      *(_DWORD *)(v5 + 1900) = 1;
      *(_DWORD *)(v5 + 1904) |= 2u;
      goto LABEL_3;
    case 1:
LABEL_3:
      v7 = *(_DWORD *)(v5 + 1904);
      if ( (v7 & 2) != 0 && (v7 & 1) != 0 )
      {
        *(_DWORD *)(v5 + 1900) = 2;
        *(_DWORD *)(v5 + 1904) &= ~2u;
      }
      goto LABEL_45;
    case 2:
      *(_DWORD *)(v5 + 1900) = 3;
      if ( *(_DWORD *)(v5 + 1916) == 0 )
      {
        sub_28AD90(v5, (*(int *)v5 & 0xFFFFFFFF80000000LL) != 0);
        sub_2865E0(v6);
        *(_DWORD *)v6 |= 1u;
        v9 = sub_457120(v8);
        *(float *)(v6 + 1872) = sub_457850(v9);
        *(_DWORD *)(v6 + 1916) = sub_293ED0(
                                   *(int *)(v6 + 1932),
                                   *(int *)(v6 + 1936),
                                   *(int *)(v6 + 1940),
                                   *(int *)(v6 + 1928));
      }
      goto LABEL_8;
    case 3:
LABEL_8:
      if ( sub_293FC0(*(int *)(v6 + 1916)) != 0 )
      {
        if ( (*(int *)v6 & 0xFFFFFFFF80000000LL) != 0 )
          *(_DWORD *)(v6 + 1900) = 4;
        else
          *(_DWORD *)(v6 + 1900) = 8;
        v10 = (int *)sub_294040(*(int *)(v6 + 1916));
        *(_DWORD *)(v6 + 4) = sub_28FB90();
        sub_28FC40((int)v6 + 1656, *(int *)(v6 + 4), v10[13], v10[14], v10[15]);
      }
      goto LABEL_45;
    case 4:
      if ( sub_285CC0(*(int *)(v5 + 4)) != 0 )
      {
        *(_DWORD *)(v6 + 1900) = 5;
LABEL_16:
        if ( sub_144F60() != 0 )
          *(_DWORD *)(v6 + 1900) = 8;
      }
      else
      {
        *(_DWORD *)(v6 + 1900) = 8;
      }
      goto LABEL_45;
    case 5:
      goto LABEL_16;
    case 8:
      *(_DWORD *)(v5 + 1900) = 9;
      for ( i = sub_1452B0(3); i != 0; i = *(int *)(i + 312) )
        ;
      goto LABEL_21;
    case 9:
LABEL_21:
      *(_DWORD *)(v6 + 1900) = 10;
      *(_DWORD *)(v6 + 1488) = sub_290F00();
      for ( j = 0; ; j = (int)j + 1 )
      {
        v14 = *(_DWORD *)(v6 + 4);
        if ( j >= *(int *)(v14 + 68) )
          break;
        v13 = *(_DWORD *)(v14 + 64) + 16 * j;
        if ( *(_DWORD *)(v13 + 8) == 4 )
          sub_290EC0(*(int *)(v6 + 1488), *(_DWORD *)(*(_DWORD *)(v6 + 4) + 16) + *(_DWORD *)(v13 + 4));
      }
      sub_291060(*(int *)(v6 + 1488));
      goto LABEL_27;
    case 0xA:
LABEL_27:
      if ( sub_291080((_DWORD *)*(_DWORD *)(v6 + 1488)) != 0 )
        *(_DWORD *)(v6 + 1900) = 11;
      goto LABEL_45;
    case 0xB:
      *(_DWORD *)(v5 + 1900) = 12;
      sub_296850(*(int *)(v5 + 4), v5);
      goto LABEL_30;
    case 0xC:
LABEL_30:
      *(_DWORD *)(v6 + 1900) = 13;
      if ( (*(_BYTE *)(v6 + 68) & 1) != 0 )
      {
        v15 = *(int *)(v6 + 1932);
        if ( v15 < 500 )
          sub_442088((int)v24, "sound/v%03d%03d.afs", v15, *(_DWORD *)(v6 + 1936));
        else
          sub_442088((int)v24, aSoundCommuAfs);
        *(_DWORD *)(v6 + 1920) = sub_45B1C0(a1, 2, 0, (int)v24);
LABEL_36:
        if ( sub_45B170(*(int *)(v6 + 1920)) != 0 )
          *(_DWORD *)(v6 + 1900) = 14;
      }
      else
      {
        *(_DWORD *)(v6 + 1900) = 14;
      }
LABEL_45:
      __asm
      {
        lq      $s1, 0x70+var_60($sp)
        lq      $s0, 0x70+var_70($sp)
      }
      return 0;
    case 0xD:
      goto LABEL_36;
    case 0xE:
      *(_DWORD *)(v5 + 1900) = 0;
      *(_DWORD *)(v5 + 1904) &= ~1u;
      v16 = sub_298250(*(int *)(v5 + 1932), *(int *)(v5 + 1936));
      if ( v16 != 1 && v16 != 2 )
      {
        sub_294040(a1);
        v17 = sub_248D00(*(int *)(v6 + 1932), *(int *)(v6 + 1936), *(int *)(v6 + 1940));
        if ( v17 > 0 )
          sub_298100(v17);
      }
      if ( (*(int *)v6 & 0xFFFFFFFF80000000LL) != 0 )
        sub_28B7B0(v6);
      sub_28B320(v6, 0);
      sub_28B550(v6);
      goto LABEL_45;
    default:
      goto LABEL_45;
  }
}


// func_00286430  addr 0x00286430  window 432B
__int64 __fastcall sub_286430(int a1)
{
  int v4; // $a1
  __int64 v5; // $v1
  __int64 result; // $v0
  __int64 v7; // $s1
  unsigned __int64 v8; // $v1
  __int64 v9; // $v0
  __int64 v10; // $v0

  __asm
  {
    sq      $s1, 0x20+var_10($sp)
    sq      $s0, 0x20+var_20($sp)
  }
  v4 = 0;
  v5 = *(char *)(a1 + 12);
  if ( v5 == 3 )
  {
    v9 = sub_286350();
    if ( v9 != 0 )
    {
      v10 = sub_452560(v9);
      if ( v10 != 0 )
      {
        result = sub_290DE0((int)v10 + 1656) != 0;
        goto LABEL_22;
      }
    }
    goto LABEL_21;
  }
  if ( v5 != 2 )
  {
    result = 1;
    if ( v5 != 1 )
    {
      if ( *(_BYTE *)(a1 + 12) != 0 )
      {
        sub_440B68("ASSERT!! Comp flag Invalid Value!! objtype =%d\n", *(_DWORD *)(a1 + 56));
        sub_43F9C8(a1 + 8, 0, 8);
        result = 1;
      }
      goto LABEL_22;
    }
    v7 = *(__int16 *)(a1 + 10);
    if ( v7 == sub_28D060(*(__int16 *)(a1 + 8), 0) )
    {
      result = 1;
      goto LABEL_22;
    }
LABEL_21:
    result = 0;
    goto LABEL_22;
  }
  v8 = *(unsigned __int8 *)(a1 + 14);
  if ( v8 < 3 )
  {
    if ( v8 == 2 )
    {
      v4 = 4608;
    }
    else if ( v8 == 1 )
    {
      v4 = 1024;
    }
    if ( *(_WORD *)(a1 + 10) != 0 )
      result = sub_106330(*(__int16 *)(a1 + 8) + v4) == 1;
    else
      result = sub_106330(*(__int16 *)(a1 + 8) + v4) == 0;
  }
  else
  {
    result = 0;
  }
LABEL_22:
  __asm
  {
    lq      $s1, 0x20+var_10($sp)
    lq      $s0, 0x20+var_20($sp)
  }
  return result;
}


// func_0028b7b0  addr 0x0028b7b0  window 1728B
__int64 __fastcall sub_28B7B0(int a1)
{
  __int64 v8; // $s0
  int v9; // $s5
  __int64 result; // $v0
  __int64 i; // $s1
  __int64 v12; // $a1
  __int64 v13; // $a0
  __int64 v14; // $v1
  __int64 v15; // $s1
  int v16; // $s2
  __int64 j; // $s1
  __int64 v18; // $s2
  __int64 v19; // $a0
  __int64 v20; // $v1
  unsigned int v21; // $s3
  __int64 v22; // $a0
  unsigned int v24; // $a1
  __int64 v26; // $a0
  unsigned int v28; // $a1
  __int64 v30; // $a1
  unsigned int v32; // $a2
  __int64 v35; // $a1
  int *v36; // $a3
  unsigned int v37; // $a2
  int v38; // $a0
  int v39; // $v1
  __int64 v40; // $a1
  int *v41; // $a3
  unsigned int v42; // $a2
  int v43; // $a0
  int v44; // $v1
  __int64 v45; // $a1
  int *v46; // $a3
  unsigned int v47; // $a2
  int v48; // $a0
  int v49; // $v1
  __int64 v50; // $a1
  int *v51; // $a3
  unsigned int v52; // $a2
  int v53; // $a0
  int v54; // $v1
  __int64 v55; // $a1
  int *v56; // $a3
  unsigned int v57; // $a2
  int v58; // $a0
  int v59; // $v1
  __int64 v60; // $a0
  unsigned int v62; // $a1

  __asm
  {
    sq      $s5, 0x60+var_10($sp)
    sq      $s4, 0x60+var_20($sp)
    sq      $s3, 0x60+var_30($sp)
    sq      $s2, 0x60+var_40($sp)
    sq      $s1, 0x60+var_50($sp)
    sq      $s0, 0x60+var_60($sp)
  }
  v8 = 0;
  v9 = 0;
  result = sub_28B6B0();
  for ( i = 1; i < 22; i = (int)i + 1 )
  {
    result = sub_1452B0(i);
    v12 = result;
    if ( result != 0 )
    {
      v13 = (*(_WORD *)result & 0xFC00) >> 10;
      v14 = v13 == 12 || v13 == 7 || v13 == 6 || v13 == 5 || v13 == 3 || v13 == 1;
      if ( v14 != 0 )
      {
        while ( v12 != 0 )
        {
          v8 = (int)v8 + 1;
          v12 = *(int *)(v12 + 312);
        }
      }
    }
  }
  if ( v8 != 0 )
  {
    *(_DWORD *)(a1 + 1952) = v8;
    nullsub_7((unsigned int)aEvtbaseH, 82);
    v15 = 4 * (int)v8;
    v16 = dword_8873F4(1, v15, 0x40000);
    result = sub_2852A0(12, v15);
    *(_DWORD *)(a1 + 1956) = v16;
    for ( j = 1; j < 22; j = (int)j + 1 )
    {
      result = sub_1452B0(j);
      v18 = result;
      if ( result != 0 )
      {
        v19 = (*(_WORD *)result & 0xFC00) >> 10;
        v20 = v19 == 12 || v19 == 7 || v19 == 6 || v19 == 5 || v19 == 3 || v19 == 1;
        if ( v20 != 0 )
        {
          while ( v18 != 0 )
          {
            v21 = 0;
            switch ( (*(_WORD *)v18 & 0xFC00) >> 10 )
            {
              case 1:
                nullsub_7((unsigned int)aEvtbaseH, 82);
                v21 = dword_8873F4(1, 560, 0x40000);
                result = sub_2852A0(12, 560);
                LODWORD(v22) = 35;
                _$A2 = v18;
                v24 = v21;
                do
                {
                  __asm { lq      $v1, 0($a2) }
                  _$A2 += 16;
                  v22 = (int)v22 - 1;
                  __asm { sq      $v1, 0($a1) }
                  v24 += 16;
                }
                while ( v22 > 0 );
                break;
              case 3:
                nullsub_7((unsigned int)aEvtbaseH, 82);
                v21 = dword_8873F4(1, 880, 0x40000);
                result = sub_2852A0(12, 880);
                LODWORD(v26) = 55;
                _$A2 = v18;
                v28 = v21;
                do
                {
                  __asm { lq      $v1, 0($a2) }
                  _$A2 += 16;
                  v26 = (int)v26 - 1;
                  __asm { sq      $v1, 0($a1) }
                  v28 += 16;
                }
                while ( v26 > 0 );
                break;
              case 5:
                nullsub_7((unsigned int)aEvtbaseH, 82);
                v21 = dword_8873F4(1, 512, 0x40000);
                result = sub_2852A0(12, 512);
                LODWORD(v30) = 16;
                _$A3 = v18;
                v32 = v21;
                do
                {
                  __asm
                  {
                    lq      $a0, 0($a3)
                    lq      $v1, 0x10($a3)
                  }
                  _$A3 += 32;
                  v30 = (int)v30 - 1;
                  __asm
                  {
                    sq      $a0, 0($a2)
                    sq      $v1, 0x10($a2)
                  }
                  v32 += 32;
                }
                while ( v30 > 0 );
                break;
              case 6:
                nullsub_7((unsigned int)aEvtbaseH, 82);
                v21 = dword_8873F4(1, 328, 0x40000);
                result = sub_2852A0(12, 328);
                LODWORD(v35) = 41;
                v36 = (int *)v18;
                v37 = v21;
                do
                {
                  v38 = *v36;
                  v39 = v36[1];
                  v36 += 2;
                  v35 = (int)v35 - 1;
                  *(_DWORD *)v37 = v38;
                  *(_DWORD *)(v37 + 4) = v39;
                  v37 += 8;
                }
                while ( v35 > 0 );
                break;
              case 7:
                nullsub_7((unsigned int)aEvtbaseH, 82);
                v21 = dword_8873F4(1, 336, 0x40000);
                result = sub_2852A0(12, 336);
                LODWORD(v40) = 42;
                v41 = (int *)v18;
                v42 = v21;
                do
                {
                  v43 = *v41;
                  v44 = v41[1];
                  v41 += 2;
                  v40 = (int)v40 - 1;
                  *(_DWORD *)v42 = v43;
                  *(_DWORD *)(v42 + 4) = v44;
                  v42 += 8;
                }
                while ( v40 > 0 );
                break;
              case 8:
                nullsub_7((unsigned int)aEvtbaseH, 82);
                v21 = dword_8873F4(1, 320, 0x40000);
                result = sub_2852A0(12, 320);
                LODWORD(v45) = 40;
                v46 = (int *)v18;
                v47 = v21;
                do
                {
                  v48 = *v46;
                  v49 = v46[1];
                  v46 += 2;
                  v45 = (int)v45 - 1;
                  *(_DWORD *)v47 = v48;
                  *(_DWORD *)(v47 + 4) = v49;
                  v47 += 8;
                }
                while ( v45 > 0 );
                break;
              case 9:
                nullsub_7((unsigned int)aEvtbaseH, 82);
                v21 = dword_8873F4(1, 328, 0x40000);
                result = sub_2852A0(12, 328);
                LODWORD(v50) = 41;
                v51 = (int *)v18;
                v52 = v21;
                do
                {
                  v53 = *v51;
                  v54 = v51[1];
                  v51 += 2;
                  v50 = (int)v50 - 1;
                  *(_DWORD *)v52 = v53;
                  *(_DWORD *)(v52 + 4) = v54;
                  v52 += 8;
                }
                while ( v50 > 0 );
                break;
              case 10:
                nullsub_7((unsigned int)aEvtbaseH, 82);
                v21 = dword_8873F4(1, 368, 0x40000);
                result = sub_2852A0(12, 368);
                LODWORD(v55) = 46;
                v56 = (int *)v18;
                v57 = v21;
                do
                {
                  v58 = *v56;
                  v59 = v56[1];
                  v56 += 2;
                  v55 = (int)v55 - 1;
                  *(_DWORD *)v57 = v58;
                  *(_DWORD *)(v57 + 4) = v59;
                  v57 += 8;
                }
                while ( v55 > 0 );
                break;
              case 12:
                nullsub_7((unsigned int)aEvtbaseH, 82);
                v21 = dword_8873F4(1, 432, 0x40000);
                result = sub_2852A0(12, 432);
                LODWORD(v60) = 27;
                _$A2 = v18;
                v62 = v21;
                do
                {
                  __asm { lq      $v1, 0($a2) }
                  _$A2 += 16;
                  v60 = (int)v60 - 1;
                  __asm { sq      $v1, 0($a1) }
                  v62 += 16;
                }
                while ( v60 > 0 );
                break;
              default:
                break;
            }
            *(_DWORD *)(*(_DWORD *)(a1 + 1956) + 4 * v9) = v21;
            v18 = *(int *)(v18 + 312);
            ++v9;
          }
        }
      }
    }
  }
  __asm
  {
    lq      $s5, 0x60+var_10($sp)
    lq      $s4, 0x60+var_20($sp)
    lq      $s3, 0x60+var_30($sp)
    lq      $s2, 0x60+var_40($sp)
    lq      $s1, 0x60+var_50($sp)
    lq      $s0, 0x60+var_60($sp)
  }
  return result;
}


// func_0028c080  addr 0x0028c080  window 752B
void __fastcall sub_28C080(__int64 a1, __int64 a2, __int64 a3, __int64 a4, float *a5, float *a6)
{
  int v11; // $gp
  __int64 v12; // $ra
  __int64 v16; // $a1
  float v17; // $f24
  float v18; // $f22
  __int64 v19; // $s0
  __int64 i; // $a2
  _DWORD *v21; // $a0
  _DWORD *v22; // $v1
  float v23; // $f0
  float v24; // $f0
  __int64 j; // $a2
  _DWORD *v26; // $a0
  _DWORD *v27; // $v1
  __int64 v38; // [sp+70h] [-20h]
  int v39; // [sp+88h] [-8h] BYREF
  int v40; // [sp+8Ch] [-4h] BYREF

  v38 = v12;
  __asm
  {
    sq      $s4, 0x90+var_30($sp)
    sq      $s3, 0x90+var_40($sp)
    sq      $s2, 0x90+var_50($sp)
    sq      $s1, 0x90+var_60($sp)
    sq      $s0, 0x90+var_70($sp)
  }
  sub_28BFB0(a2, a3, (int)&v40, (int)&v39);
  if ( v40 == 0 )
    goto LABEL_11;
  v16 = *(int *)(v40 + 72);
  v17 = *(float *)(v40 + 16);
  v18 = *(float *)(v40 + 20);
  v19 = *(int *)(v40 + 4);
  if ( v39 == 0 )
  {
    for ( i = 0; i < 4; i = (int)i + 1 )
    {
      v21 = (_DWORD *)(v16 + 4 * i);
      v22 = (_DWORD *)(a4 + 4 * i);
      *v22 = *v21;
      v22[4] = v21[4];
      v22[8] = v21[8];
    }
    *a5 = v17;
    *a6 = v18;
    goto LABEL_18;
  }
  if ( *(_DWORD *)(v40 + 72) == 0 && *(_DWORD *)(v39 + 72) == 0 )
  {
LABEL_11:
    v23 = *(float *)(v11 - 32612);
    *(float *)a4 = v23;
    *(float *)(a4 + 4) = v23;
    *(float *)(a4 + 8) = v23;
    *(_DWORD *)(a4 + 12) = 0;
    *(_DWORD *)(a4 + 16) = 0;
    *(_DWORD *)(a4 + 20) = 0;
    *(_DWORD *)(a4 + 24) = 0;
    *(_DWORD *)(a4 + 28) = 0;
    v24 = *(float *)(v11 - 32232);
    *(float *)(a4 + 32) = v24;
    *(float *)(a4 + 36) = v24;
    *(float *)(a4 + 40) = v24;
    *(_DWORD *)(a4 + 44) = 0;
    *a5 = 7.0;
    *a6 = 0.0;
    goto LABEL_18;
  }
  if ( *(_DWORD *)(v40 + 4) != 0 )
  {
    sub_28F990(*(int *)(v40 + 4), v16, *(int *)(v39 + 72), a4);
    *a5 = sub_28F960(v19);
    *a6 = sub_28F960(v19);
  }
  else
  {
    for ( j = 0; j < 4; j = (int)j + 1 )
    {
      v26 = (_DWORD *)(v16 + 4 * j);
      v27 = (_DWORD *)(a4 + 4 * j);
      *v27 = *v26;
      v27[4] = v26[4];
      v27[8] = v26[8];
    }
    *a5 = v17;
    *a6 = v18;
  }
LABEL_18:
  __asm
  {
    lq      $s4, 0x90+var_30($sp)
    lq      $s3, 0x90+var_40($sp)
    lq      $s2, 0x90+var_50($sp)
    lq      $s1, 0x90+var_60($sp)
    lq      $s0, 0x90+var_70($sp)
  }
}


// func_0028c3f0  addr 0x0028c3f0  window 400B
__int64 __fastcall sub_28C3F0(__int64 a1)
{
  __int64 v4; // $ra
  int v6; // $s1
  int v7; // $s0
  int v8; // $s0
  __int64 result; // $v0
  __int64 v10; // $s0
  __int64 i; // $v0
  __int64 j; // $v0
  __int64 k; // $a0
  __int64 m; // $s1
  __int64 v15; // $a1
  __int64 v16; // $a3
  __int64 n; // $a4
  __int64 v18; // $a2
  _QWORD v22[2]; // [sp+0h] [-110h] BYREF
  __int64 v25; // [sp+30h] [-E0h]
  _DWORD v26[52]; // [sp+40h] [-D0h]

  v25 = v4;
  __asm
  {
    sq      $s2, 0x110+var_F0($sp)
    sq      $s1, 0x110+var_100($sp)
    sq      $s0, 0x110+var_110($sp)
  }
  v6 = 0;
  v7 = sub_145300(3);
  v8 = v7 + sub_145300(1);
  result = sub_145300(12);
  v10 = v8 + (int)result;
  if ( v10 < 51 )
  {
    for ( i = sub_1452B0(3); i != 0; i = *(int *)(i + 312) )
      *((_DWORD *)&v22[8] + v6++) = i;
    for ( j = sub_1452B0(1); j != 0; j = *(int *)(j + 312) )
      *((_DWORD *)&v22[8] + v6++) = j;
    result = sub_1452B0(12);
    for ( k = result; k != 0; k = *(int *)(k + 312) )
      *((_DWORD *)&v22[8] + v6++) = k;
    for ( m = 0; m < v10; m = (int)m + 1 )
    {
      v15 = (int)v26[(_DWORD)m];
      v16 = *(unsigned __int16 *)v15;
      for ( n = 0; n < *(int *)(a1 + 1952); n = (int)n + 1 )
      {
        v18 = *(int *)(*(_DWORD *)(a1 + 1956) + 4 * n);
        if ( *(unsigned __int16 *)v18 == v16 )
          goto LABEL_17;
      }
      v18 = 0;
LABEL_17:
      result = sub_28C580(a1, v15, v18, v16);
    }
  }
  __asm
  {
    lq      $s2, 0x110+var_F0($sp)
    lq      $s1, 0x110+var_100($sp)
    lq      $s0, 0x110+var_110($sp)
  }
  return result;
}


// func_0028c580  addr 0x0028c580  window 2384B
void __fastcall sub_28C580(int a1, __int64 a2, __int64 a3)
{
  __int64 v8; // $ra
  __int64 v12; // $s1
  __int64 v13; // $s0
  __int64 i; // $a3
  int *v15; // $a0
  __int64 j; // $a2
  __int64 k; // $a2
  __int64 v18; // $a0
  float v19; // $f2
  float v20; // $f1
  float v21; // $f0
  float v22; // $f2
  float v23; // $f1
  float v24; // $f0
  int *v25; // $a2
  _DWORD *v26; // $a1
  __int64 v27; // $a0
  int v28; // $v1
  int v29; // $v0
  unsigned int v30; // $s1
  unsigned int v31; // $s0
  unsigned int v32; // $a3
  float v33; // $f2
  float v34; // $f1
  float v35; // $f0
  float v36; // $f2
  float v37; // $f1
  float v38; // $f0
  int *v39; // $a2
  __int64 v40; // $a1
  int v41; // $a0
  int v42; // $v1
  float v43; // $f2
  float v44; // $f1
  float v45; // $f0
  float v46; // $f2
  float v47; // $f1
  float v48; // $f0
  int *v49; // $a3
  _DWORD *v50; // $a2
  __int64 v51; // $a1
  int v52; // $a0
  int v53; // $v1
  float v54; // $f2
  float v55; // $f1
  float v56; // $f0
  float v57; // $f2
  float v58; // $f1
  float v59; // $f0
  int *v60; // $a3
  _DWORD *v61; // $a2
  __int64 v62; // $a1
  int v63; // $a0
  int v64; // $v1
  __int64 v65; // $a0
  __int64 v66; // $a0
  int *v67; // $a3
  _DWORD *v68; // $a2
  __int64 v69; // $a1
  int v70; // $a0
  int v71; // $v1
  unsigned int v72; // $s1
  unsigned int v73; // $s0
  unsigned int v74; // $a3
  float v75; // $f2
  float v76; // $f1
  float v77; // $f0
  float v78; // $f2
  float v79; // $f1
  float v80; // $f0
  int *v81; // $a2
  __int64 v82; // $a1
  int v83; // $a0
  int v84; // $v1
  int *v85; // $a3
  _DWORD *v86; // $a2
  __int64 v87; // $a1
  int v88; // $a0
  int v89; // $v1
  int *v90; // $a3
  _DWORD *v91; // $a2
  __int64 v92; // $a1
  int v93; // $a0
  int v94; // $v1
  __int64 v105; // [sp+60h] [-D0h]
  _DWORD v106[3]; // [sp+70h] [-C0h] BYREF
  int v107; // [sp+7Ch] [-B4h]
  int v108; // [sp+80h] [-B0h]
  int v109; // [sp+84h] [-ACh]
  int v110; // [sp+88h] [-A8h]
  int v111; // [sp+90h] [-A0h]
  int v112; // [sp+94h] [-9Ch]
  int v113; // [sp+98h] [-98h]
  int v114; // [sp+A0h] [-90h]
  int v115; // [sp+A4h] [-8Ch]
  int v116; // [sp+A8h] [-88h]
  _DWORD v117[3]; // [sp+B0h] [-80h] BYREF
  int v118; // [sp+BCh] [-74h]
  int v119; // [sp+C0h] [-70h]
  int v120; // [sp+C4h] [-6Ch]
  int v121; // [sp+C8h] [-68h]
  int v122; // [sp+D0h] [-60h]
  int v123; // [sp+D4h] [-5Ch]
  int v124; // [sp+D8h] [-58h]
  int v125; // [sp+E0h] [-50h]
  int v126; // [sp+E4h] [-4Ch]
  int v127; // [sp+E8h] [-48h]
  _DWORD v128[3]; // [sp+F0h] [-40h] BYREF
  int v129; // [sp+FCh] [-34h]
  int v130; // [sp+100h] [-30h]
  int v131; // [sp+104h] [-2Ch]
  int v132; // [sp+108h] [-28h]
  int v133; // [sp+110h] [-20h]
  int v134; // [sp+114h] [-1Ch]
  int v135; // [sp+118h] [-18h]
  int v136; // [sp+120h] [-10h]
  int v137; // [sp+124h] [-Ch]
  int v138; // [sp+128h] [-8h]

  v105 = v8;
  __asm
  {
    sq      $s4, 0x130+var_E0($sp)
    sq      $s3, 0x130+var_F0($sp)
    sq      $s2, 0x130+var_100($sp)
    sq      $s1, 0x130+var_110($sp)
    sq      $s0, 0x130+var_120($sp)
  }
  v12 = -1;
  v13 = 0;
  if ( a2 != 0 )
  {
    if ( (*(_WORD *)a2 & 0xFC00) >> 10 == 3 )
      sub_14A300();
    for ( i = 0; i < 3; i = (int)i + 1 )
    {
      v15 = &dword_882210[16 * (_DWORD)i];
      if ( *v15 == 3 && v15[1] == a2 )
      {
        v12 = i;
        if ( (*(_WORD *)a2 & 0xFC00) >> 10 == 3 )
          sub_14A300();
        break;
      }
    }
    if ( v12 == -1 && (*(_WORD *)a2 & 0xFC00) >> 10 != 12 )
    {
      for ( j = 0; j < 3; j = (int)j + 1 )
      {
        if ( dword_882210[16 * (_DWORD)j] == 2 )
        {
          v12 = j;
          break;
        }
      }
    }
    if ( v12 == -1 )
    {
      for ( k = 0; k < 3; k = (int)k + 1 )
      {
        if ( dword_882210[16 * (_DWORD)k] == 1 )
        {
          v12 = k;
          break;
        }
      }
    }
    if ( v12 == -1 )
    {
      if ( a3 != 0 )
      {
        v18 = (*(_WORD *)a2 & 0xFC00) >> 10;
        switch ( v18 )
        {
          case 12LL:
            v54 = *(float *)(a3 + 324);
            v55 = *(float *)(a3 + 328);
            v56 = *(float *)(a3 + 332);
            *(_DWORD *)(a2 + 320) = *(_DWORD *)(a3 + 320);
            *(float *)(a2 + 324) = v54;
            *(float *)(a2 + 328) = v55;
            *(float *)(a2 + 332) = v56;
            v57 = *(float *)(a3 + 340);
            v58 = *(float *)(a3 + 344);
            v59 = *(float *)(a3 + 348);
            *(_DWORD *)(a2 + 336) = *(_DWORD *)(a3 + 336);
            *(float *)(a2 + 340) = v57;
            *(float *)(a2 + 344) = v58;
            *(float *)(a2 + 348) = v59;
            v60 = (int *)(a3 + 352);
            v61 = (_DWORD *)(a2 + 352);
            LODWORD(v62) = 8;
            do
            {
              v63 = *v60;
              v64 = v60[1];
              v60 += 2;
              v62 = (int)v62 - 1;
              *v61 = v63;
              v61[1] = v64;
              v61 += 2;
            }
            while ( v62 > 0 );
            break;
          case 1LL:
            v43 = *(float *)(a3 + 364);
            v44 = *(float *)(a3 + 368);
            v45 = *(float *)(a3 + 372);
            *(_DWORD *)(a2 + 360) = *(_DWORD *)(a3 + 360);
            *(float *)(a2 + 364) = v43;
            *(float *)(a2 + 368) = v44;
            *(float *)(a2 + 372) = v45;
            v46 = *(float *)(a3 + 380);
            v47 = *(float *)(a3 + 384);
            v48 = *(float *)(a3 + 388);
            *(_DWORD *)(a2 + 376) = *(_DWORD *)(a3 + 376);
            *(float *)(a2 + 380) = v46;
            *(float *)(a2 + 384) = v47;
            *(float *)(a2 + 388) = v48;
            v49 = (int *)(a3 + 400);
            v50 = (_DWORD *)(a2 + 400);
            LODWORD(v51) = 8;
            do
            {
              v52 = *v49;
              v53 = v49[1];
              v49 += 2;
              v51 = (int)v51 - 1;
              *v50 = v52;
              v50[1] = v53;
              v50 += 2;
            }
            while ( v51 > 0 );
            break;
          case 3LL:
            v19 = *(float *)(a3 + 364);
            v20 = *(float *)(a3 + 368);
            v21 = *(float *)(a3 + 372);
            *(_DWORD *)(a2 + 360) = *(_DWORD *)(a3 + 360);
            *(float *)(a2 + 364) = v19;
            *(float *)(a2 + 368) = v20;
            *(float *)(a2 + 372) = v21;
            v22 = *(float *)(a3 + 380);
            v23 = *(float *)(a3 + 384);
            v24 = *(float *)(a3 + 388);
            *(_DWORD *)(a2 + 376) = *(_DWORD *)(a3 + 376);
            *(float *)(a2 + 380) = v22;
            *(float *)(a2 + 384) = v23;
            *(float *)(a2 + 388) = v24;
            v25 = (int *)(a3 + 400);
            v26 = (_DWORD *)(a2 + 400);
            LODWORD(v27) = 8;
            do
            {
              v28 = *v25;
              v29 = v25[1];
              v25 += 2;
              v27 = (int)v27 - 1;
              *v26 = v28;
              v26[1] = v29;
              v26 += 2;
            }
            while ( v27 > 0 );
            v30 = sub_14B000();
            v31 = sub_14B040();
            v32 = sub_14B080();
            v33 = *(float *)(a1 + 1780);
            v34 = *(float *)(a1 + 1784);
            v35 = *(float *)(a1 + 1788);
            *(_DWORD *)v30 = *(_DWORD *)(a1 + 1776);
            *(float *)(v30 + 4) = v33;
            *(float *)(v30 + 8) = v34;
            *(float *)(v30 + 12) = v35;
            v36 = *(float *)(a1 + 1796);
            v37 = *(float *)(a1 + 1800);
            v38 = *(float *)(a1 + 1804);
            *(_DWORD *)v31 = *(_DWORD *)(a1 + 1792);
            *(float *)(v31 + 4) = v36;
            *(float *)(v31 + 8) = v37;
            *(float *)(v31 + 12) = v38;
            v39 = (int *)(a1 + 1808);
            LODWORD(v40) = 8;
            do
            {
              v41 = *v39;
              v42 = v39[1];
              v39 += 2;
              v40 = (int)v40 - 1;
              *(_DWORD *)v32 = v41;
              *(_DWORD *)(v32 + 4) = v42;
              v32 += 8;
            }
            while ( v40 > 0 );
            break;
          default:
            break;
        }
      }
    }
    else
    {
      v65 = dword_882210[16 * (_DWORD)v12];
      if ( (v65 == 2 || v65 == 1) && (*(_WORD *)a2 & 0xFC00) >> 10 == 3 )
        v13 = 1;
      v66 = (*(_WORD *)a2 & 0xFC00) >> 10;
      switch ( v66 )
      {
        case 3LL:
          *(_DWORD *)(a2 + 360) = dword_882238[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 364) = dword_88223C[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 368) = dword_882240[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 372) = 0;
          *(_DWORD *)(a2 + 376) = dword_882218[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 380) = dword_88221C[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 384) = dword_882220[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 388) = 0;
          v135 = 1065353216;
          v131 = 1065353216;
          v128[0] = 1065353216;
          v130 = 0;
          v128[2] = 0;
          v128[1] = 0;
          v134 = 0;
          v133 = 0;
          v132 = 0;
          v138 = 0;
          v137 = 0;
          v136 = 0;
          v129 |= 0x20003u;
          sub_3E0870((int)v128, (unsigned int)&dword_5EFA20, 1);
          sub_3E0870((int)v128, (unsigned int)dword_5EFA10, 1);
          v67 = v128;
          v68 = (_DWORD *)(a2 + 400);
          LODWORD(v69) = 8;
          do
          {
            v70 = *v67;
            v71 = v67[1];
            v67 += 2;
            v69 = (int)v69 - 1;
            *v68 = v70;
            v68[1] = v71;
            v68 += 2;
          }
          while ( v69 > 0 );
          if ( v13 == 1 )
          {
            v72 = sub_14B000();
            v73 = sub_14B040();
            v74 = sub_14B080();
            v75 = *(float *)(a2 + 364);
            v76 = *(float *)(a2 + 368);
            v77 = *(float *)(a2 + 372);
            *(_DWORD *)v72 = *(_DWORD *)(a2 + 360);
            *(float *)(v72 + 4) = v75;
            *(float *)(v72 + 8) = v76;
            *(float *)(v72 + 12) = v77;
            v78 = *(float *)(a2 + 380);
            v79 = *(float *)(a2 + 384);
            v80 = *(float *)(a2 + 388);
            *(_DWORD *)v73 = *(_DWORD *)(a2 + 376);
            *(float *)(v73 + 4) = v78;
            *(float *)(v73 + 8) = v79;
            *(float *)(v73 + 12) = v80;
            v81 = (int *)(a2 + 400);
            LODWORD(v82) = 8;
            do
            {
              v83 = *v81;
              v84 = v81[1];
              v81 += 2;
              v82 = (int)v82 - 1;
              *(_DWORD *)v74 = v83;
              *(_DWORD *)(v74 + 4) = v84;
              v74 += 8;
            }
            while ( v82 > 0 );
          }
          break;
        case 1LL:
          *(_DWORD *)(a2 + 360) = dword_882238[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 364) = dword_88223C[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 368) = dword_882240[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 372) = 0;
          *(_DWORD *)(a2 + 376) = dword_882218[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 380) = dword_88221C[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 384) = dword_882220[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 388) = 0;
          v124 = 1065353216;
          v120 = 1065353216;
          v117[0] = 1065353216;
          v119 = 0;
          v117[2] = 0;
          v117[1] = 0;
          v123 = 0;
          v122 = 0;
          v121 = 0;
          v127 = 0;
          v126 = 0;
          v125 = 0;
          v118 |= 0x20003u;
          sub_3E0870((int)v117, (unsigned int)&dword_5EFA20, 1);
          sub_3E0870((int)v117, (unsigned int)dword_5EFA10, 1);
          v85 = v117;
          v86 = (_DWORD *)(a2 + 400);
          LODWORD(v87) = 8;
          do
          {
            v88 = *v85;
            v89 = v85[1];
            v85 += 2;
            v87 = (int)v87 - 1;
            *v86 = v88;
            v86[1] = v89;
            v86 += 2;
          }
          while ( v87 > 0 );
          break;
        case 12LL:
          *(_DWORD *)(a2 + 320) = dword_882238[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 324) = dword_88223C[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 328) = dword_882240[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 332) = 0;
          *(_DWORD *)(a2 + 336) = dword_882218[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 340) = dword_88221C[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 344) = dword_882220[16 * (_DWORD)v12];
          *(_DWORD *)(a2 + 348) = 0;
          v113 = 1065353216;
          v109 = 1065353216;
          v106[0] = 1065353216;
          v108 = 0;
          v106[2] = 0;
          v106[1] = 0;
          v112 = 0;
          v111 = 0;
          v110 = 0;
          v116 = 0;
          v115 = 0;
          v114 = 0;
          v107 |= 0x20003u;
          sub_3E0870((int)v106, (unsigned int)&dword_5EFA20, 1);
          sub_3E0870((int)v106, (unsigned int)dword_5EFA10, 1);
          v90 = v106;
          v91 = (_DWORD *)(a2 + 352);
          LODWORD(v92) = 8;
          do
          {
            v93 = *v90;
            v94 = v90[1];
            v90 += 2;
            v92 = (int)v92 - 1;
            *v91 = v93;
            v91[1] = v94;
            v91 += 2;
          }
          while ( v92 > 0 );
          break;
        default:
          break;
      }
    }
  }
  __asm
  {
    lq      $s4, 0x130+var_E0($sp)
    lq      $s3, 0x130+var_F0($sp)
    lq      $s2, 0x130+var_100($sp)
    lq      $s1, 0x130+var_110($sp)
    lq      $s0, 0x130+var_120($sp)
  }
}

