/* Generated by tools/ida_headstart.py -- Hex-Rays (IDA Pro 9.4) pseudocode.
 *
 * REFERENCE ONLY. This is not valid C and is never compiled: IDA's pseudo
 * types (__int64, _DWORD, _$F0 register aliases) are not MWCC input, and a
 * raw `__asm { ... }` block below is Hex-Rays declining to model an Emotion
 * Engine instruction it does not understand (FPU multiply-accumulate chains,
 * or a rare single op like mfthc1/pcpyld). Everything else in a function
 * usually decompiles correctly -- control flow, hardware MMIO addresses
 * (rendered as MEMORY[0x...]), struct layout. Translate an asm island by
 * hand using the measured b210 rules in docs/matching.md; do not guess.
 *
 * Regenerate: python3 tools/ida_headstart.py --report <verify.json>
 */

// func_00364320  addr 0x00364320  window 672B
void __fastcall sub_364320(int a1, char a2, __int64 a3)
{
  int v3; // $gp
  __int64 v5; // $v0
  unsigned __int8 v6; // $s0
  int i; // $s1
  __int64 v8; // $v1
  float v10; // [sp+48h] [-48h]
  _BYTE v11[64]; // [sp+50h] [-40h] BYREF

  if ( a2 != 0 )
  {
    if ( a3 <= 0 )
      a3 = sub_105ED0();
    sub_3645C0((int)v11, a3);
    if ( *(_DWORD *)(v3 - 19032) == 0 )
    {
      v5 = sub_46A770((unsigned int)aInitCTop01Spr);
      *(_DWORD *)(v3 - 19032) = v5;
      if ( v5 == 0 )
        nullsub_8((unsigned int)aShdmiscC, 49);
    }
    dword_887300(6, 1);
    dword_887300(7, 2);
    dword_887300(8, 1);
    dword_887300(9, 2);
    dword_887300(12, 1);
    dword_887300(11, 6);
    dword_887300(10, 5);
    dword_887300(2, 4);
    dword_887300(14, 0);
    v6 = -1 - a2;
    sub_46D3B0(0, *(int *)(v3 - 19032), 25, 0, (unsigned __int8)(-1 - a2), 0);
    v10 = *(float *)&a1 + 36.0;
    for ( i = 0; ; ++i )
    {
      v8 = (char)v11[i];
      if ( v11[i] == 0 )
        break;
      if ( v8 == 46 )
      {
        sub_46D3B0(0, *(int *)(v3 - 19032), 24, 0, v6, 0);
        v10 = v10 + 8.0;
      }
      else
      {
        sub_46D3B0(0, *(int *)(v3 - 19032), (int)v8 - 34, 0, v6, 0);
        v10 = v10 + 19.0;
      }
    }
  }
}


// func_00364680  addr 0x00364680  window 1488B
__int64 __usercall sub_364680@<$v0>(
        __int64 a1@<$a0>,
        __int64 a2@<$a1>,
        __int64 a3@<$a2>,
        __int64 a4@<$a3>,
        float a5@<$f12>,
        float a6@<$f13>,
        float a7@<$f15>,
        float a8@<$f18>)
{
  int v8; // $s0
  float v15; // $f26
  float v16; // $f25
  __int64 v17; // $v0
  __int64 v18; // $s1
  __int64 v19; // $a0
  __int64 v20; // $a1
  __int64 v21; // $a2
  __int64 v22; // $a3
  float v23; // $f21
  float v24; // $f23
  float v25; // $f27
  __int64 i; // $a0
  float *v27; // $v0
  __int64 j; // $a2
  float *v29; // $a1
  __int64 v30; // $a0
  __int64 v31; // $a1
  __int64 v32; // $a2
  __int64 v33; // $a3
  float v34; // $f21
  float v35; // $f23
  __int64 k; // $a4
  float *v37; // $a3
  float v39; // [sp+C0h] [-100h] BYREF
  float v40; // [sp+C4h] [-FCh]
  float v41; // [sp+C8h] [-F8h]
  int v42; // [sp+D0h] [-F0h]
  int v43; // [sp+D4h] [-ECh]
  float v44; // [sp+D8h] [-E8h]
  float v45; // [sp+100h] [-C0h]
  float v46; // [sp+104h] [-BCh]
  float v47; // [sp+108h] [-B8h]
  int v48; // [sp+110h] [-B0h]
  int v49; // [sp+114h] [-ACh]
  float v50; // [sp+118h] [-A8h]
  float v51; // [sp+140h] [-80h]
  float v52; // [sp+144h] [-7Ch]
  float v53; // [sp+148h] [-78h]
  int v54; // [sp+150h] [-70h]
  int v55; // [sp+154h] [-6Ch]
  float v56; // [sp+158h] [-68h]
  float v57; // [sp+180h] [-40h]
  float v58; // [sp+184h] [-3Ch]
  float v59; // [sp+188h] [-38h]
  int v60; // [sp+190h] [-30h]
  int v61; // [sp+194h] [-2Ch]
  float v62; // [sp+198h] [-28h]

  v8 = a1;
  v15 = *(float *)&dword_8872F8 - a5;
  v16 = 1.0 / *(float *)(sub_457120(a1) + 128);
  if ( a2 == 0 )
    nullsub_8((unsigned int)aShdmiscC, 153);
  v17 = (unsigned __int8)v8 ^ 0xFFLL;
  v18 = v17 != 0;
  if ( v17 != 0 )
    v18 = a3 != 0;
  v41 = v15;
  v47 = v15;
  v53 = v15;
  v59 = v15;
  v44 = v16;
  v50 = v16;
  v56 = v16;
  v62 = v16;
  v42 = 0;
  v43 = 0;
  v48 = 1065353216;
  v49 = 0;
  v54 = 1065353216;
  v55 = 1065353216;
  v60 = 0;
  v61 = 1065353216;
  dword_887300(7, 2);
  dword_887300(6, 0);
  dword_887300(8, 0);
  dword_887300(14, 0);
  dword_887300(9, 2);
  dword_887300(12, 1);
  dword_887300(1, *(int *)a2);
  sub_3F6440(2, 68);
  sub_489F80(v19, v20, v21, v22);
  if ( v18 != 0 )
  {
    v39 = a7;
    v40 = v25;
    v45 = a7 + v23;
    v46 = v25;
    v51 = v45;
    v52 = v25 + a8;
    v57 = a7;
    v58 = v52;
    for ( i = 0; i < 4; i = (int)i + 1 )
    {
      v27 = &v39 + 16 * i;
      v27[8] = 255.0;
      v27[9] = 255.0;
      v27[10] = 255.0;
      v27[11] = 255.0;
    }
    sub_3F6440(3, 202753);
    dword_887310(5, (int)&v39, 4);
  }
  v39 = a6;
  v40 = v24;
  v45 = a6 + v23;
  v46 = v24;
  v51 = v45;
  v52 = v24 + a8;
  v57 = a6;
  v58 = v52;
  for ( j = 0; j < 4; j = (int)j + 1 )
  {
    v29 = &v39 + 16 * j;
    v29[8] = 255.0;
    v29[9] = 255.0;
    v29[10] = 255.0;
    v29[11] = (float)(unsigned __int8)v8;
  }
  if ( v18 != 0 )
    sub_3F6440(3, 219137);
  else
    sub_3F6440(3, 202753);
  dword_887310(5, (int)&v39, 4);
  sub_48A000(v30, v31, v32, v33);
  dword_887300(1, 0);
  if ( a4 == 1 )
  {
    sub_3F6440(2, 88);
  }
  else if ( a4 != 0 )
  {
    nullsub_8((unsigned int)aShdmiscC, 265);
  }
  else
  {
    sub_3F6440(2, 84);
  }
  if ( v18 != 0 )
    sub_3F6440(3, 219137);
  else
    sub_3F6440(3, 202753);
  v39 = a6;
  v40 = v35;
  v45 = a6 + v34;
  v46 = v35;
  v51 = a6;
  v52 = v35 + a8;
  v57 = v45;
  v58 = v52;
  for ( k = 0; k < 4; k = (int)k + 1 )
  {
    v37 = &v39 + 16 * k;
    v37[8] = (float)((v8 & 0xFF000000) >> 24);
    v37[9] = (float)((v8 & 0xFF0000u) >> 16);
    v37[10] = (float)(unsigned __int8)((unsigned __int16)(v8 & 0xFF00) >> 8);
    v37[11] = (float)(unsigned __int8)v8;
  }
  return dword_887310(4, (int)&v39, 4);
}


// func_00364c90  addr 0x00364c90  window 800B
__int64 __usercall sub_364C90@<$v0>(__int64 a1@<$a0>, int a2@<$a1>, __int64 a3@<$a2>, float a4@<$f13>)
{
  int v4; // $gp
  __int64 v5; // $ra
  float v6; // $f20
  float v7; // $f21
  float v8; // $f22
  float v9; // $f23
  float v10; // $f24
  float v11; // $f25
  float v12; // $f26
  float v13; // $f27
  float v14; // $f28
  float v18; // $f20
  float v19; // $f22
  int v20; // $f28
  __int64 v21; // $a0
  __int64 v22; // $a1
  __int64 v23; // $a2
  __int64 v24; // $a3
  __int64 v25; // $a0
  __int64 v26; // $a1
  __int64 v27; // $a2
  __int64 v28; // $a3
  float v29; // $f0
  float v30; // $f21
  float v31; // $f23
  float v32; // $f25
  float v33; // $f27
  __int64 i; // $a1
  int v35; // $a2
  float v36; // $f8
  float v37; // $f7
  float *v38; // $a7
  __int64 result; // $v0
  float v40; // [sp+0h] [-180h] BYREF
  float v41; // [sp+4h] [-17Ch]
  float v42; // [sp+8h] [-178h]
  float v43; // [sp+Ch] [-174h]
  float v44; // [sp+10h] [-170h]
  float v45; // [sp+14h] [-16Ch]
  float v46; // [sp+18h] [-168h]
  float v47; // [sp+1Ch] [-164h]
  float v48; // [sp+20h] [-160h]
  __int64 v49; // [sp+50h] [-130h]
  __int64 v50; // [sp+68h] [-118h]
  float v51; // [sp+70h] [-110h]
  float v52; // [sp+74h] [-10Ch]
  float v53; // [sp+78h] [-108h]
  float v54; // [sp+7Ch] [-104h]
  _BYTE v55[256]; // [sp+80h] [-100h] BYREF

  v49 = v5;
  v48 = v14;
  v47 = v13;
  v46 = v12;
  v45 = v11;
  v44 = v10;
  v43 = v9;
  v42 = v8;
  v41 = v7;
  v40 = v6;
  v50 = a1;
  v18 = *((float *)&a1 + 1);
  v51 = flt_64E310;
  v52 = flt_64E314;
  v53 = flt_64E318;
  v54 = flt_64E31C;
  v19 = 1.0 / *(float *)(sub_457120(a1) + 128);
  v20 = dword_8872F8;
  sub_44B7B0(v21, v22, v23, v24);
  v29 = sub_44B610(v25, v26, v27, v28);
  for ( i = 0; i < 4; i = (int)i + 1 )
  {
    v35 = ((_BYTE)i + 1) & 3;
    if ( (int)i + 1 < 0LL && (((_BYTE)i + 1) & 3) != 0 )
      v35 -= 4;
    v36 = a4 * *(&v40 + v35 + 28);
    v37 = v32 * *(&v40 + (_DWORD)i + 28);
    v38 = (float *)&v55[64 * (_DWORD)i];
    *v38 = (float)((float)(v30 + 0.0) + (float)(v36 * v29)) - (float)(v37 * v31);
    v38[1] = (float)((float)(v18 + 0.0) + (float)(v36 * v31)) + (float)(v37 * v29);
    v38[2] = *(float *)&v20 - v33;
    v38[8] = (float)((a2 & 0xFF000000) >> 24);
    v38[9] = (float)((a2 & 0xFF0000u) >> 16);
    v38[10] = (float)(unsigned __int8)((unsigned __int16)(a2 & 0xFF00) >> 8);
    v38[11] = (float)(unsigned __int8)a2;
    v38[6] = v19;
  }
  dword_887300(1, 0);
  if ( a3 != 0 && (unsigned __int8)a2 == 255 )
    *(_QWORD *)(v4 - 21528) |= 0x80uLL;
  result = dword_887310(5, (int)v55, 4);
  if ( a3 != 0 && (unsigned __int8)a2 == 255 )
    *(_QWORD *)(v4 - 21528) &= ~0x80uLL;
  return result;
}


// func_00364fb0  addr 0x00364fb0  window 2080B
__int64 __usercall sub_364FB0@<$v0>(
        __int64 a1@<$a0>,
        int a2@<$a1>,
        __int64 a3@<$a2>,
        __int64 a4@<$a3>,
        float a5@<$f12>)
{
  int v5; // $gp
  float v10; // $f20
  float v11; // $f22
  __int64 v12; // $a0
  __int64 v13; // $a1
  __int64 v14; // $a2
  __int64 v15; // $a3
  __int64 v16; // $a0
  __int64 v17; // $a1
  __int64 v18; // $a2
  __int64 v19; // $a3
  float v20; // $f0
  float v21; // $f21
  float v22; // $f23
  float v23; // $f2
  float v24; // $f1
  __int64 result; // $v0
  float v26; // [sp+68h] [-108h]
  float v27[2]; // [sp+70h] [-100h] BYREF
  float v28; // [sp+78h] [-F8h]
  float v29; // [sp+88h] [-E8h]
  float v30; // [sp+90h] [-E0h]
  float v31; // [sp+94h] [-DCh]
  float v32; // [sp+98h] [-D8h]
  float v33; // [sp+9Ch] [-D4h]
  float v34; // [sp+B0h] [-C0h]
  float v35; // [sp+B4h] [-BCh]
  float v36; // [sp+B8h] [-B8h]
  float v37; // [sp+C8h] [-A8h]
  float v38; // [sp+D0h] [-A0h]
  float v39; // [sp+D4h] [-9Ch]
  float v40; // [sp+D8h] [-98h]
  float v41; // [sp+DCh] [-94h]
  float v42; // [sp+F0h] [-80h]
  float v43; // [sp+F4h] [-7Ch]
  float v44; // [sp+F8h] [-78h]
  float v45; // [sp+108h] [-68h]
  float v46; // [sp+110h] [-60h]
  float v47; // [sp+114h] [-5Ch]
  float v48; // [sp+118h] [-58h]
  float v49; // [sp+11Ch] [-54h]
  float v50; // [sp+130h] [-40h]
  float v51; // [sp+134h] [-3Ch]
  float v52; // [sp+138h] [-38h]
  float v53; // [sp+148h] [-28h]
  float v54; // [sp+150h] [-20h]
  float v55; // [sp+154h] [-1Ch]
  float v56; // [sp+158h] [-18h]
  float v57; // [sp+15Ch] [-14h]

  v26 = *(float *)&a1;
  v10 = *((float *)&a1 + 1);
  v11 = *(float *)&dword_8872F8 - a5;
  sub_457120(a1);
  sub_44B7B0(v12, v13, v14, v15);
  v20 = sub_44B610(v16, v17, v18, v19);
  v27[0] = v26;
  v27[1] = v10;
  v28 = v11 - a5;
  v30 = (float)HIBYTE(a2);
  v31 = (float)BYTE2(a2);
  v32 = (float)BYTE1(a2);
  v33 = (float)(unsigned __int8)a2;
  v29 = v21;
  v23 = 71.0 * v20;
  v34 = v26 + (float)(71.0 * v20);
  v24 = 71.0 * v22;
  v35 = v10 + (float)(71.0 * v22);
  v36 = v28;
  v38 = v30;
  v39 = v31;
  v40 = v32;
  v41 = v33;
  v37 = v21;
  if ( a4 != 0 )
  {
    v42 = (float)(v26 + 0.0) - (float)(402.0 * v22);
    v43 = (float)(v10 + 0.0) + (float)(402.0 * v20);
    v44 = v11 - a5;
    v46 = (float)HIBYTE(a2);
    v47 = (float)BYTE2(a2);
    v48 = (float)BYTE1(a2);
    v49 = (float)(unsigned __int8)a2;
    v45 = v21;
    v50 = (float)((float)(v26 + v23) + 0.0) - (float)((float)473 * v22);
    v51 = (float)((float)(v10 + 0.0) + (float)((float)473 * v20)) + v24;
  }
  else
  {
    v42 = (float)(v26 + 0.0) - (float)((float)473 * v22);
    v43 = (float)(v10 + 0.0) + (float)((float)473 * v20);
    v44 = v11 - a5;
    v46 = (float)HIBYTE(a2);
    v47 = (float)BYTE2(a2);
    v48 = (float)BYTE1(a2);
    v49 = (float)(unsigned __int8)a2;
    v45 = v21;
    v50 = (float)((float)(v26 + v23) + 0.0) - (float)(402.0 * v22);
    v51 = (float)((float)(v10 + 0.0) + (float)(402.0 * v20)) + v24;
  }
  v52 = v11 - a5;
  v54 = (float)HIBYTE(a2);
  v55 = (float)BYTE2(a2);
  v56 = (float)BYTE1(a2);
  v57 = (float)(unsigned __int8)a2;
  v53 = v21;
  if ( a3 != 0 )
    *(_QWORD *)(v5 - 21528) |= 0x80uLL;
  result = dword_887310(4, (int)v27, 4);
  if ( a3 != 0 )
    *(_QWORD *)(v5 - 21528) &= ~0x80uLL;
  return result;
}


// func_003657d0  addr 0x003657d0  window 752B
__int64 __usercall sub_3657D0@<$v0>(__int64 a1@<$a0>, int a2@<$a1>, __int64 a3@<$a2>, float a4@<$f12>)
{
  int v4; // $gp
  float v8; // $f22
  __int64 v9; // $a0
  __int64 v10; // $a1
  __int64 v11; // $a2
  __int64 v12; // $a3
  __int64 v13; // $s4
  float v14; // $f20
  float v15; // $f26
  __int64 v16; // $a0
  __int64 v17; // $a1
  __int64 v18; // $a2
  __int64 v19; // $a3
  float v20; // $f0
  float v21; // $f25
  float v22; // $f21
  float v23; // $f23
  __int64 result; // $v0
  _BYTE v25[256]; // [sp+A0h] [-100h] BYREF

  v8 = *(float *)&a1;
  sub_457120(a1);
  v13 = 0;
  v14 = *(float *)&dword_8872F8 - a4;
  while ( v13 < 4 )
  {
    v15 = sub_44B7B0(v9, v10, v11, v12);
    v20 = sub_44B610(v16, v17, v18, v19);
    v9 = (int)&v25[64 * (_DWORD)v13];
    *(float *)v9 = (float)(v8 + 0.0) + (float)(v21 * v15);
    *(float *)(v9 + 4) = (float)(v22 + 0.0) + (float)(v21 * v20);
    *(float *)(v9 + 8) = v14;
    *(float *)(v9 + 32) = (float)((a2 & 0xFF000000) >> 24);
    *(float *)(v9 + 36) = (float)((a2 & 0xFF0000u) >> 16);
    *(float *)(v9 + 40) = (float)(unsigned __int8)((unsigned __int16)(a2 & 0xFF00) >> 8);
    *(float *)(v9 + 44) = (float)(unsigned __int8)a2;
    *(float *)(v9 + 24) = v23;
    v13 = (int)v13 + 1;
  }
  dword_887300(1, 0);
  if ( a3 != 0 && (unsigned __int8)a2 == 255 )
    *(_QWORD *)(v4 - 21528) |= 0x80uLL;
  result = dword_887310(5, (int)v25, 4);
  if ( a3 != 0 && (unsigned __int8)a2 == 255 )
    *(_QWORD *)(v4 - 21528) &= ~0x80uLL;
  return result;
}


// func_00365ac0  addr 0x00365ac0  window 1088B
__int64 __usercall sub_365AC0@<$v0>(__int64 a1@<$a0>, int a2@<$a1>, __int64 a3@<$a2>, float a4@<$f12>, float a5@<$f14>)
{
  int v5; // $gp
  float v8; // $f20
  float v9; // $f26
  float v10; // $f24
  __int64 v11; // $a0
  __int64 v12; // $a1
  __int64 v13; // $a2
  __int64 v14; // $a3
  float v15; // $f22
  __int64 v16; // $a0
  __int64 v17; // $a1
  __int64 v18; // $a2
  __int64 v19; // $a3
  float v20; // $f0
  float v21; // $f21
  float v22; // $f23
  float v23; // $f25
  __int64 i; // $a1
  __int64 v25; // $t5
  __int64 v26; // $a0
  __int64 v27; // $a6
  BOOL v28; // $t4
  __int64 v29; // $a7
  int v30; // $a6
  float v31; // $f7
  int v32; // $a6
  float v33; // $f8
  __int64 v34; // $a6
  BOOL v35; // $t4
  __int64 v36; // $a7
  int v37; // $a6
  int v38; // $a0
  float v39; // $f7
  float *v40; // $a6
  __int64 result; // $v0
  _BYTE v42[640]; // [sp+90h] [-280h] BYREF

  v8 = *((float *)&a1 + 1);
  v9 = a5 * *(float *)(v5 - 31788);
  v10 = *(float *)&dword_8872F8 - a4;
  sub_457120(a1);
  v15 = sub_44B7B0(v11, v12, v13, v14);
  v20 = sub_44B610(v16, v17, v18, v19);
  for ( i = 0; i < 10; i = (int)i + 1 )
  {
    v25 = i & 7;
    if ( i < 0 && (i & 7) != 0 )
      v25 = (int)v25 - 8;
    v26 = ((_BYTE)i + 6) & 7;
    if ( (int)i + 6 < 0LL && (((_BYTE)i + 6) & 7) != 0 )
      v26 = (int)v26 - 8;
    v27 = v25 & 3;
    if ( v25 < 0 && (v25 & 3) != 0 )
      v27 = (int)v27 - 4;
    v28 = v27 == 1;
    v29 = ((_BYTE)v25 + 1) & 3;
    if ( (int)v25 + 1 < 0LL && (((_BYTE)v25 + 1) & 3) != 0 )
      v29 = (int)v29 - 4;
    v30 = (int)v29 >> 1;
    if ( v29 < 0 )
      v30 = ((int)v29 + 1) >> 1;
    v31 = (float)(v23 * (float)v28) + (float)(v9 * (float)v30);
    if ( v25 >= 4 )
      v32 = -1;
    else
      v32 = 1;
    v33 = (float)v32 * v31;
    v34 = v26 & 3;
    if ( v26 < 0 && (v26 & 3) != 0 )
      v34 = (int)v34 - 4;
    v35 = v34 == 1;
    v36 = ((_BYTE)v26 + 1) & 3;
    if ( (int)v26 + 1 < 0LL && (((_BYTE)v26 + 1) & 3) != 0 )
      v36 = (int)v36 - 4;
    v37 = (int)v36 >> 1;
    if ( v36 < 0 )
      v37 = ((int)v36 + 1) >> 1;
    if ( v26 >= 4 )
      v38 = -1;
    else
      v38 = 1;
    v39 = (float)v38 * (float)((float)(v23 * (float)v35) + (float)(v9 * (float)v37));
    v40 = (float *)&v42[64 * (_DWORD)i];
    *v40 = (float)((float)(v21 + 0.0) + (float)(v33 * v20)) - (float)(v39 * v15);
    v40[1] = (float)((float)(v8 + 0.0) + (float)(v39 * v20)) + (float)(v33 * v15);
    v40[2] = v10;
    v40[6] = v22;
    v40[8] = (float)((a2 & 0xFF000000) >> 24);
    v40[9] = (float)((a2 & 0xFF0000u) >> 16);
    v40[10] = (float)(unsigned __int8)((unsigned __int16)(a2 & 0xFF00) >> 8);
    v40[11] = (float)(unsigned __int8)a2;
  }
  dword_887300(1, 0);
  if ( a3 != 0 && (unsigned __int8)a2 == 255 )
    *(_QWORD *)(v5 - 21528) |= 0x80uLL;
  result = dword_887310(4, (int)v42, 10);
  if ( a3 != 0 && (unsigned __int8)a2 == 255 )
    *(_QWORD *)(v5 - 21528) &= ~0x80uLL;
  return result;
}


// func_00365f00  addr 0x00365f00  window 1152B
__int64 __usercall sub_365F00@<$v0>(
        __int64 a1@<$a0>,
        int a2@<$a1>,
        int a3@<$a2>,
        unsigned __int16 a4@<$a3>,
        int a5@<$a4>,
        float a6@<$f12>,
        float a7@<$f16>)
{
  int v7; // $gp
  int v11; // $s2
  int v12; // $s6
  int v13; // $s7
  int v14; // $fp
  int v15; // $s1
  int v16; // $s0
  int v17; // $s5
  float v18; // $f22
  int v19; // $f20
  __int64 v20; // $a0
  __int64 v21; // $a1
  __int64 v22; // $a2
  __int64 v23; // $a3
  float v24; // $f21
  float v25; // $f20
  __int64 i; // $s1
  float *v27; // $s0
  float v28; // $f0
  float v29; // $f27
  float v30; // $f25
  __int64 v31; // $a0
  __int64 v32; // $a1
  __int64 v33; // $a2
  __int64 v34; // $a3
  float v35; // $f0
  float v36; // $f27
  float v37; // $f21
  float v38; // $f23
  __int64 result; // $v0
  float v41; // [sp+E0h] [-1990h]
  unsigned __int8 v42; // [sp+E8h] [-1988h]
  float v43[1632]; // [sp+F0h] [-1980h] BYREF

  v41 = *(float *)&a1;
  v42 = a2;
  v11 = HIBYTE(a3);
  v12 = BYTE2(a3);
  v13 = BYTE1(a3);
  v14 = (unsigned __int8)a3;
  v15 = HIBYTE(a2);
  v16 = BYTE2(a2);
  v17 = BYTE1(a2);
  v18 = *(float *)&a1;
  v19 = dword_8872F8;
  sub_457120(a1);
  if ( a4 == 0 || a4 >= 0x65uLL )
    nullsub_8((unsigned int)aShdmiscC, 571);
  v43[0] = v41;
  v43[1] = v24;
  v25 = *(float *)&v19 - a6;
  v43[2] = v25;
  v43[8] = (float)v42;
  v43[9] = (float)v17;
  v43[10] = (float)v16;
  v43[11] = (float)v15;
  for ( i = 0; a4 >= i; i = (int)i + 1 )
  {
    v27 = &v43[16 * (_DWORD)i];
    v28 = sub_44B7B0(v20, v21, v22, v23);
    v27[16] = (float)(v18 + 0.0) + (float)(v30 * (float)(v29 * v28));
    v35 = sub_44B610(v31, v32, v33, v34);
    v27[17] = (float)(v37 + 0.0) + (float)(a7 * (float)(v36 * v35));
    v27[18] = v25;
    v27[24] = (float)v14;
    v27[25] = (float)v13;
    v27[26] = (float)v12;
    v27[27] = (float)v11;
    v27[6] = v38;
  }
  dword_887300(1, 0);
  if ( a5 != 0 )
    *(_QWORD *)(v7 - 21528) |= 0x80uLL;
  result = dword_887310(5, (int)v43, a4 + 2);
  if ( a5 != 0 )
    *(_QWORD *)(v7 - 21528) &= ~0x80uLL;
  return result;
}

