/* Generated by tools/ida_headstart.py -- Hex-Rays (IDA Pro 9.4) pseudocode.
 *
 * REFERENCE ONLY. This is not valid C and is never compiled: IDA's pseudo
 * types (__int64, _DWORD, _$F0 register aliases) are not MWCC input, and a
 * raw `__asm { ... }` block below is Hex-Rays declining to model an Emotion
 * Engine instruction it does not understand (FPU multiply-accumulate chains,
 * or a rare single op like mfthc1/pcpyld). Everything else in a function
 * usually decompiles correctly -- control flow, hardware MMIO addresses
 * (rendered as MEMORY[0x...]), struct layout. Translate an asm island by
 * hand using the measured b210 rules in docs/matching.md; do not guess.
 *
 * Regenerate: python3 tools/ida_headstart.py --report <verify.json>
 */

// func_003742b0  addr 0x003742b0  window 864B
__int64 __fastcall sub_3742B0(int a1)
{
  __int64 v2; // $v1
  __int64 v3; // $s3
  __int64 v4; // $s2
  __int64 v5; // $s1
  __int64 v6; // $v0
  int *v7; // $s4
  __int64 v8; // $s1
  __int64 v9; // $v0
  __int64 v10; // $v0
  __int64 v11; // $s2
  __int64 v12; // $s1
  __int64 v13; // $v0
  int *v14; // $s4
  __int64 v15; // $v0
  __int64 i; // $s1
  int v18; // [sp+6Ch] [-4h] BYREF

  v2 = *(int *)(a1 + 127724);
  if ( v2 == 2 )
    return 1;
  if ( v2 == 1 )
  {
LABEL_21:
    for ( i = 0; i < 3; i = (int)i + 1 )
    {
      if ( *(_DWORD *)(a1 + 4 * i + 127660) != 0 && sub_46A750() == 0 )
        return 0;
    }
    sub_454BD0(*(int *)(a1 + 127720));
    *(_DWORD *)(a1 + 127720) = 0;
    *(_DWORD *)(a1 + 127724) = 2;
    return 1;
  }
  if ( *(_DWORD *)(a1 + 127724) == 0 && sub_4553C0(*(int *)(a1 + 127720)) != 0 )
  {
    v3 = 0;
    v4 = 0;
    while ( v4 < 9 )
    {
      v5 = sub_455EA0(*(int *)(a1 + 127720), v3, (int)&v18);
      nullsub_7((unsigned int)aBtlshuffledraw, 257);
      v6 = dword_8873F4(1, v18, 0x40000);
      v7 = (int *)(a1 + 4 * v4 + 127672);
      *v7 = v6;
      if ( v6 == 0 )
        nullsub_8((unsigned int)aBtlshuffledraw, 258);
      sub_43F810(*v7, v5, v18);
      v4 = (int)v4 + 1;
      v3 = (int)v3 + 1;
    }
    v8 = 0;
    while ( v8 < 3 )
    {
      v9 = sub_455EA0(*(int *)(a1 + 127720), v3, 0);
      v10 = sub_46AF60(v9);
      *(_DWORD *)(a1 + 4 * v8 + 127660) = v10;
      if ( v10 == 0 )
        nullsub_8((unsigned int)aBtlshuffledraw, 265);
      v8 = (int)v8 + 1;
      v3 = (int)v3 + 1;
    }
    v11 = 0;
    while ( v11 < 3 )
    {
      v12 = sub_455EA0(*(int *)(a1 + 127720), v3, (int)&v18);
      nullsub_7((unsigned int)aBtlshuffledraw, 271);
      v13 = dword_8873F4(1, v18, 0x40000);
      v14 = (int *)(a1 + 4 * v11 + 127708);
      *v14 = v13;
      if ( v13 == 0 )
        nullsub_8((unsigned int)aBtlshuffledraw, 272);
      sub_43F810(*v14, v12, v18);
      v11 = (int)v11 + 1;
      v3 = (int)v3 + 1;
    }
    v15 = sub_455EA0(*(int *)(a1 + 127720), v3, 0);
    sub_36D230(v15);
    *(_DWORD *)(a1 + 127724) = 1;
    goto LABEL_21;
  }
  return 0;
}


// func_00374d20  addr 0x00374d20  window 1744B
__int64 __fastcall sub_374D20(int a1)
{
  int v1; // $gp
  int v3; // $v1
  int v4; // $s1
  float v5; // $f1
  float v6; // $f0
  __int64 v7; // $s3
  __int64 v8; // $s5
  __int64 v9; // $s6
  __int64 v10; // $s7
  __int64 v11; // $s2
  __int64 v12; // $s0
  float v13; // kr00_4
  float v14; // $f2
  float v15; // $f1
  float v16; // $f0
  __int64 v17; // $v0
  __int64 v18; // $v0
  float v19; // $f1
  unsigned __int8 v20; // $v1
  float v21; // $f0
  float v22; // $f20
  float v23; // $f1
  unsigned __int8 v24; // $v1
  float v26; // [sp+A0h] [-40h]
  float v27; // [sp+A4h] [-3Ch]
  float v28; // [sp+A8h] [-38h]
  float v29; // [sp+ACh] [-34h]
  float v30[4]; // [sp+B0h] [-30h] BYREF
  __int64 v31; // [sp+C0h] [-20h] BYREF
  float v32; // [sp+C8h] [-18h]
  float v33[4]; // [sp+D0h] [-10h] BYREF

  v3 = *(_DWORD *)(a1 + 127752);
  v4 = a1 + 232 * v3 + 120480;
  v5 = *(float *)(a1 + 232 * v3 + 120508);
  v6 = *(float *)(a1 + 232 * v3 + 120512);
  v33[0] = *(float *)(a1 + 232 * v3 + 120504);
  v33[1] = v5;
  v33[2] = v6;
  v26 = *(float *)(a1 + 232 * v3 + 120596);
  v27 = *(float *)(a1 + 232 * v3 + 120600);
  v28 = *(float *)(a1 + 232 * v3 + 120604);
  v29 = *(float *)(a1 + 232 * v3 + 120608);
  if ( (*(_WORD *)(a1 + 127732) & 0x40LL) != 0 )
    v7 = *(int *)(a1 + 127652);
  else
    v7 = *(int *)(a1 + 127648);
  v8 = sub_378240(v7);
  v9 = sub_378250(v7);
  v10 = sub_378500(v7);
  v11 = sub_3E0F80();
  v12 = *(int *)(sub_457120() + 4);
  v13 = (float)((float)((float)(v27 * v27) + (float)(v26 * v26)) + (float)(v28 * v28)) + (float)(v29 * v29);
  v14 = v26 * (float)(2.0 / v13);
  v15 = v27 * (float)(2.0 / v13);
  v16 = v28 * (float)(2.0 / v13);
  *(float *)v11 = 1.0 - (float)((float)(v27 * v15) + (float)(v28 * v16));
  *(float *)(v11 + 4) = (float)(v26 * v15) + (float)(v16 * v29);
  *(float *)(v11 + 8) = (float)(v28 * v14) - (float)(v15 * v29);
  *(float *)(v11 + 16) = (float)(v26 * v15) - (float)(v16 * v29);
  *(float *)(v11 + 20) = 1.0 - (float)((float)(v28 * v16) + (float)(v26 * v14));
  *(float *)(v11 + 24) = (float)(v27 * v16) + (float)(v14 * v29);
  *(float *)(v11 + 32) = (float)(v28 * v14) + (float)(v15 * v29);
  *(float *)(v11 + 36) = (float)(v27 * v16) - (float)(v14 * v29);
  *(float *)(v11 + 40) = 1.0 - (float)((float)(v26 * v14) + (float)(v27 * v15));
  *(_DWORD *)(v11 + 48) = 0;
  *(_DWORD *)(v11 + 52) = 0;
  *(_DWORD *)(v11 + 56) = 0;
  *(_DWORD *)(v11 + 12) = 3;
  sub_3E0C90(v11, (int)v33, 2);
  v17 = sub_3E9700(v12);
  sub_3E0E20(v11, v17, 2);
  dword_887300(6, 0);
  dword_887300(8, 0);
  dword_887300(20, 2);
  sub_3F6440(3, 464891);
  sub_3F6440(2, 68);
  if ( (*(_WORD *)(a1 + 127732) & 0x20LL) != 0 )
  {
    v18 = sub_36BE00();
    dword_887300(1, v18);
    sub_410420(v9, 4, v11, 3);
    sub_4106A0(4);
  }
  sub_378280(v7, *(unsigned __int8 *)(v4 + 216));
  if ( (*(_WORD *)(a1 + 127732) & 0x80LL) != 0 )
  {
    v31 = qword_64EA38;
    v32 = flt_64EA40;
    sub_3E0870(v11, (int)&v31, 1);
  }
  dword_887300(1, v10);
  sub_410420(v8, 4, v11, 3);
  sub_4106A0(4);
  if ( (*(_WORD *)(a1 + 127732) & 0x10LL) != 0 )
  {
    sub_3F6440(3, 464897);
    sub_3F6440(2, 72);
    *(_WORD *)(a1 + 127730) = (*(unsigned __int16 *)(a1 + 127730) + 1) % 60;
    v19 = (float)(255.0 * (float)(1.0 - sub_44B610())) / 2.0;
    if ( v19 >= 2147483600.0 )
      v20 = (int)(float)(v19 - 2147483600.0);
    else
      v20 = (int)v19;
    sub_378280(v7, v20);
    sub_410420(v8, 4, v11, 3);
    sub_4106A0(4);
  }
  if ( (*(_WORD *)(a1 + 127732) & 0x100) != 0 )
  {
    ++*(_WORD *)(a1 + 127730);
    v21 = sub_373CB0(1);
    v22 = v21;
    if ( *(unsigned __int16 *)(a1 + 127730) >= 0x14uLL )
      *(_WORD *)(a1 + 127732) &= ~0x100u;
    v23 = 255.0 * (float)(1.0 - v21);
    if ( v23 >= 2147483600.0 )
      v24 = (int)(float)(v23 - 2147483600.0);
    else
      v24 = (int)v23;
    sub_378280(v7, v24);
    v30[0] = (float)(*(float *)(v1 - 31732) * v22) + 1.0;
    v30[1] = v30[0];
    v30[2] = 1.0;
    sub_3E0A90(v11, (int)v30, 1);
    sub_410420(v8, 4, v11, 3);
    sub_4106A0(4);
  }
  return sub_3E0F40(v11);
}


// func_003753f0  addr 0x003753f0  window 1024B
__int64 __fastcall sub_3753F0(__int64 a1)
{
  __int64 v1; // $s1
  int v2; // $gp
  __int64 v4; // $s2
  __int64 i; // $s3
  int v6; // $s5
  __int64 v7; // $s0
  __int64 result; // $v0
  float v9; // $f2
  __int64 v10; // $a2
  __int64 v11; // $a1
  int v12; // $v1
  float v13; // $f20
  float v14; // $f0
  __int64 j; // $s0
  _DWORD v16[30]; // [sp+A0h] [-80h]
  _BYTE v17[4]; // [sp+118h] [-8h] BYREF
  _BYTE v18[4]; // [sp+11Ch] [-4h] BYREF

  sub_34F1E0();
  v18[0] = -1;
  v18[1] = -1;
  v18[2] = -1;
  if ( (*(_WORD *)(a1 + 127732) & 1LL) != 0 )
    v4 = sub_378530(*(int *)(a1 + 127748), *(int *)(a1 + 127740));
  else
    v4 = *(int *)(a1 + 127748);
  for ( i = 0; i < v4; i = (int)i + 1 )
  {
    if ( (*(_WORD *)(a1 + 232 * i + 120480) & 2LL) != 0 )
    {
      if ( (*(_WORD *)(a1 + 127732) & 2LL) == 0 )
        sub_374A10(a1, i);
      v6 = a1 + 232 * i;
      v7 = (int)a1 + 4016 * (int)i;
      sub_36DDA0(v7, v6 + 120504);
      sub_36DE20(v7, v6 + 120596);
      v18[3] = *(_BYTE *)(v6 + 120696);
      sub_36DE40(v7, (int)v18);
      if ( i != *(_DWORD *)(a1 + 127752) )
      {
        v16[(_DWORD)i] = v7;
        sub_3766F0((int)a1 + 127564, (unsigned int)sub_374CF0);
      }
    }
  }
  result = sub_376800((int)a1 + 127564, 1);
  qmemcpy(v17, " @", 2);
  v17[2] = -1;
  v17[3] = -1;
  v9 = 1.0;
  v10 = *(int *)(a1 + 127748);
  v11 = *(int *)(a1 + 127740);
  if ( v11 == 4 || v11 == 3 )
  {
    v13 = 0.0;
  }
  else
  {
    if ( v11 == 2 )
    {
      LODWORD(v10) = (int)v10 / 3;
      v1 = *(unsigned __int16 *)(a1 + 127442);
      v9 = *(float *)(v2 - 32400);
    }
    else if ( v11 == 1 )
    {
      v12 = (int)v10 >> 1;
      if ( v10 < 0 )
        v12 = ((int)v10 + 1) >> 1;
      LODWORD(v10) = v12;
      v1 = *(unsigned __int16 *)(a1 + 127442);
    }
    else if ( *(_DWORD *)(a1 + 127740) == 0 )
    {
      v1 = *(unsigned __int16 *)(a1 + 127442);
    }
    if ( v1 < 0 )
      v14 = (float)(((unsigned int)v1 >> 1) | v1 & 1) + (float)(((unsigned int)v1 >> 1) | v1 & 1);
    else
      v14 = (float)(int)v1;
    v13 = v9 * (float)((float)(0.5 * v14) / (float)(int)v10);
  }
  if ( v13 > 0.0 )
  {
    for ( j = 0; j < v4; j = (int)j + 1 )
    {
      if ( (*(_WORD *)(a1 + 232 * j + 120480) & 2LL) != 0 )
      {
        sub_375A70(a1, j);
        result = sub_3768E0(a1, j, 2, (int)v17);
      }
    }
  }
  return result;
}


// func_00375b40  addr 0x00375b40  window 528B
__int64 __fastcall sub_375B40(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __int64 result; // $v0
  __int64 v9; // $v1
  float v10; // $f7
  float v11; // $f6
  float v12; // $f5
  float v13; // $f3
  float v14[4]; // [sp+60h] [-30h] BYREF
  float v15; // [sp+70h] [-20h] BYREF
  float v16; // [sp+74h] [-1Ch]
  float v17; // [sp+78h] [-18h]
  float v18; // [sp+7Ch] [-14h]
  __int64 v19; // [sp+80h] [-10h] BYREF
  float v20; // [sp+88h] [-8h]

  v19 = qword_64EA48;
  v20 = flt_64EA50;
  result = sub_378530(*(int *)(a1 + 127748), *(int *)(a1 + 127740));
  if ( a2 >= result )
    result = nullsub_8((unsigned int)aBtlshuffledraw, 1001);
  v9 = *(_DWORD *)(a1 + 232 * a2 + 120488) == 3
    || *(_DWORD *)(a1 + 232 * a2 + 120488) == 0
    || *(unsigned __int16 *)(a1 + 232 * a2 + 120588) >= (__int64)*(unsigned __int16 *)(a1 + 232 * a2 + 120590);
  if ( v9 != 0 )
  {
    sub_3DC740((int)&v15, (int)&v19, 0);
    v10 = *(float *)(a1 + 232 * a2 + 120604);
    v11 = *(float *)(a1 + 232 * a2 + 120596);
    v12 = *(float *)(a1 + 232 * a2 + 120600);
    v13 = *(float *)(a1 + 232 * a2 + 120608);
    v14[3] = (float)(v13 * v18) - (float)((float)((float)(v12 * v16) + (float)(v11 * v15)) + (float)(v10 * v17));
    v14[0] = (float)((float)((float)((float)((float)(v12 * v17) - (float)(v10 * v16)) + 0.0) + (float)(v15 * v13)) + 0.0)
           + (float)(v11 * v18);
    v14[1] = (float)((float)((float)((float)((float)(v10 * v15) - (float)(v11 * v17)) + 0.0) + (float)(v16 * v13)) + 0.0)
           + (float)(v12 * v18);
    v14[2] = (float)((float)((float)((float)((float)(v11 * v16) - (float)(v12 * v15)) + 0.0) + (float)(v17 * v13)) + 0.0)
           + (float)(v10 * v18);
    return sub_3760F0(a1, a2, a3, a4, 0, (int)v14);
  }
  return result;
}


// func_00375f00  addr 0x00375f00  window 160B
__int64 __fastcall sub_375F00(int a1, int a2)
{
  int v2; // $s2
  __int64 result; // $v0

  v2 = a1 + 232 * a2;
  sub_370410(v2 + 120492);
  *(_DWORD *)(v2 + 120484) = 5;
  result = sub_370A80(v2 + 120588);
  *(_DWORD *)(v2 + 120488) = 3;
  return result;
}


// func_003768e0  addr 0x003768e0  window 4176B
__int64 __fastcall sub_3768E0(__int64 a1, __int64 a2, char a3, _BYTE *a4)
{
  int v4; // $gp
  float v5; // $f20
  __int64 v9; // $s2
  __int64 result; // $v0
  float v11; // $f23
  float v12; // $f22
  _BYTE *v13; // $s4
  _BYTE *v14; // $s3
  float v15; // $f20
  float v16; // $f24
  __int64 v17; // $s2
  float v18; // $f21
  float v19; // $f23
  float v20; // $f1
  char v21; // $v1
  float v22; // $f2
  char v23; // $v1
  char v24; // $v1
  char v25; // $v1
  float v26; // $f20
  float v27; // $f21
  __int64 i; // $s0
  float *v29; // $v1
  float *v30; // $v0
  __int64 v31; // $a1
  float *v32; // $a0
  float v33; // $f5
  float v34; // $f4
  float v35; // $f3
  float v36; // $f1
  float v37; // $f1
  __int64 v38; // $a1
  float *v39; // $a0
  float v40; // $f5
  float v41; // $f4
  float v42; // $f3
  float v43; // $f1
  float v44; // $f1
  __int64 v45; // $a1
  float *v46; // $a0
  float v47; // $f5
  float v48; // $f4
  float v49; // $f3
  __int64 v50; // $a1
  float *v51; // $a0
  float v52; // $f5
  float v53; // $f4
  float v54; // $f3
  _BYTE *v55; // $s4
  _BYTE *v56; // $s3
  char v57; // $v1
  char v58; // $s7
  float v59; // $f24
  float v60; // $f22
  __int64 v61; // $s2
  float v62; // $f21
  float v63; // $f24
  float v64; // $f25
  __int64 v65; // $s0
  float v66; // $f23
  float v67; // $f22
  float *v68; // $a1
  float *v69; // $a0
  float v70; // $f4
  __int64 v71; // $v1
  float v72; // $f2
  float v73; // $f1
  float v74; // $f0
  float v75; // $f5
  float v76; // $f11
  float v77; // $f16
  float v78; // $f15
  float *v79; // $v0
  float v80; // $f10
  float v81; // $f9
  float v82; // $f14
  float v83; // $f7
  float v84; // $f6
  float v85; // $f7
  float v86; // $f7
  float v87; // $f6
  int v88; // $v0
  float v89; // $f23
  _BYTE *v90; // $s4
  _BYTE *v91; // $s3
  char v92; // $v1
  char v93; // $s7
  float v94; // $f24
  float v95; // $f22
  __int64 v96; // $s2
  float v97; // $f22
  float v98; // $f0
  float v99; // $f21
  __int64 v100; // $s0
  float v101; // $f1
  float v102; // $f24
  float v103; // $f23
  float v104; // $f22
  float *v105; // $a1
  float *v106; // $a0
  float v107; // $f4
  __int64 v108; // $v1
  float v109; // $f3
  float v110; // $f2
  float v111; // $f1
  float v112; // $f0
  float v113; // $f5
  float v114; // $f11
  float v115; // $f16
  float v116; // $f15
  float *v117; // $v0
  float v118; // $f10
  float v119; // $f9
  float v120; // $f14
  float v121; // $f7
  float v122; // $f6
  float v123; // $f7
  float v124; // $f7
  float v125; // $f6
  _DWORD v126[3]; // [sp+B0h] [-EA0h] BYREF
  int v127; // [sp+BCh] [-E94h]
  int v128; // [sp+C0h] [-E90h]
  int v129; // [sp+C4h] [-E8Ch]
  int v130; // [sp+C8h] [-E88h]
  int v131; // [sp+D0h] [-E80h]
  int v132; // [sp+D4h] [-E7Ch]
  int v133; // [sp+D8h] [-E78h]
  int v134; // [sp+E0h] [-E70h]
  int v135; // [sp+E4h] [-E6Ch]
  int v136; // [sp+E8h] [-E68h]
  _DWORD v137[64]; // [sp+F0h] [-E60h] BYREF
  _BYTE v138[1520]; // [sp+1F0h] [-D60h] BYREF
  _BYTE v139[1520]; // [sp+7E0h] [-770h] BYREF
  float v140; // [sp+DD0h] [-180h]
  float v141; // [sp+DD4h] [-17Ch]
  float v142; // [sp+DD8h] [-178h]
  float v143; // [sp+DE0h] [-170h]
  float v144; // [sp+DE4h] [-16Ch]
  float v145; // [sp+DE8h] [-168h]
  float v146; // [sp+DF0h] [-160h]
  float v147; // [sp+DF4h] [-15Ch]
  float v148; // [sp+DF8h] [-158h]
  float v149; // [sp+E00h] [-150h]
  float v150; // [sp+E04h] [-14Ch]
  float v151; // [sp+E08h] [-148h]
  float v152; // [sp+E10h] [-140h]
  float v153; // [sp+E14h] [-13Ch]
  float v154; // [sp+E18h] [-138h]
  float v155; // [sp+E20h] [-130h]
  float v156; // [sp+E24h] [-12Ch]
  float v157; // [sp+E28h] [-128h]
  float v158; // [sp+E30h] [-120h]
  float v159; // [sp+E34h] [-11Ch]
  float v160; // [sp+E38h] [-118h]
  float v161; // [sp+E40h] [-110h]
  float v162; // [sp+E44h] [-10Ch]
  float v163; // [sp+E48h] [-108h]
  float v164; // [sp+E50h] [-100h]
  float v165; // [sp+E54h] [-FCh]
  float v166; // [sp+E58h] [-F8h]
  float v167; // [sp+E60h] [-F0h]
  float v168; // [sp+E64h] [-ECh]
  float v169; // [sp+E68h] [-E8h]
  float v170; // [sp+E70h] [-E0h]
  float v171; // [sp+E74h] [-DCh]
  float v172; // [sp+E78h] [-D8h]
  float v173; // [sp+E80h] [-D0h]
  float v174; // [sp+E84h] [-CCh]
  float v175; // [sp+E88h] [-C8h]
  float v176; // [sp+E90h] [-C0h]
  float v177; // [sp+E94h] [-BCh]
  float v178; // [sp+E98h] [-B8h]
  float v179; // [sp+EA0h] [-B0h]
  float v180; // [sp+EA4h] [-ACh]
  float v181; // [sp+EA8h] [-A8h]
  float v182; // [sp+EB0h] [-A0h]
  float v183; // [sp+EB4h] [-9Ch]
  float v184; // [sp+EB8h] [-98h]
  float v185; // [sp+EC0h] [-90h]
  float v186; // [sp+EC4h] [-8Ch]
  float v187; // [sp+EC8h] [-88h]
  float v188; // [sp+ED0h] [-80h]
  float v189; // [sp+ED4h] [-7Ch]
  float v190; // [sp+ED8h] [-78h]
  float v191; // [sp+EE0h] [-70h]
  float v192; // [sp+EE4h] [-6Ch]
  float v193; // [sp+EE8h] [-68h]
  float v194; // [sp+EF0h] [-60h]
  float v195; // [sp+EF4h] [-5Ch]
  float v196; // [sp+EF8h] [-58h]
  float v197; // [sp+F00h] [-50h]
  float v198; // [sp+F04h] [-4Ch]
  float v199; // [sp+F08h] [-48h]
  float v200; // [sp+F10h] [-40h]
  float v201; // [sp+F14h] [-3Ch]
  float v202; // [sp+F18h] [-38h]
  float v203; // [sp+F20h] [-30h]
  float v204; // [sp+F24h] [-2Ch]
  float v205; // [sp+F28h] [-28h]
  float v206; // [sp+F30h] [-20h]
  float v207; // [sp+F34h] [-1Ch]
  float v208; // [sp+F38h] [-18h]
  float v209; // [sp+F40h] [-10h]
  float v210; // [sp+F44h] [-Ch]
  float v211; // [sp+F48h] [-8h]

  v9 = a3;
  if ( a3 >= 3LL )
    nullsub_8((unsigned int)aBtlshuffledraw, 1502);
  v133 = 1065353216;
  v129 = 1065353216;
  v126[0] = 1065353216;
  v128 = 0;
  v126[2] = 0;
  v126[1] = 0;
  v132 = 0;
  v131 = 0;
  v130 = 0;
  v136 = 0;
  v135 = 0;
  v134 = 0;
  v127 |= 0x20003u;
  sub_3F6440(2, 72);
  sub_3F6440(3, 464897);
  dword_887300(20, 1);
  dword_887300(6, 1);
  result = dword_887300(8, 0);
  if ( *(_DWORD *)(a1 + 232 * a2 + 120484) == 6 )
  {
    v12 = (float)(unsigned __int8)a4[3] * (float)((float)*(unsigned __int8 *)(a1 + 232 * a2 + 120696) / 255.0);
    switch ( v9 )
    {
      case 2LL:
        v88 = sub_457120();
        sub_3E9700(*(int *)(v88 + 4));
        v90 = v139;
        v91 = v138;
        if ( v12 >= 2147483600.0 )
          v92 = (int)(float)(v12 - 2147483600.0);
        else
          v92 = (int)v12;
        v93 = v92;
        v94 = 0.0;
        v95 = v89 / 21.0;
        v96 = 0;
        while ( v96 < 21 )
        {
          sub_3764B0(a1, a2, (int)&v137[3 * v96]);
          v94 = v94 - v95;
          v90[12] = *a4;
          v90[13] = a4[1];
          v90[14] = a4[2];
          v90[15] = 0;
          v90[48] = *a4;
          v90[49] = a4[1];
          v90[50] = a4[2];
          v90[51] = v93;
          v91[12] = *a4;
          v91[13] = a4[1];
          v91[14] = a4[2];
          v91[15] = v93;
          v91[48] = *a4;
          v91[49] = a4[1];
          *((_WORD *)v91 + 25) = (unsigned __int8)a4[2];
          v96 = (int)v96 + 1;
          v90 += 72;
          v91 += 72;
        }
        v97 = 0.5 * sub_36DE70((int)a1 + 4016 * (int)a2);
        v98 = sub_36DEB0((int)a1 + 4016 * (int)a2);
        v100 = 0;
        v101 = *(float *)(v4 - 32232);
        v102 = v101 * v97;
        v103 = *(float *)(v4 - 31992) * (float)(0.5 * v98);
        v104 = v101 * (float)-v97;
        while ( v100 < 2 )
        {
          if ( v100 == 1 )
          {
            v99 = v104;
            v5 = v103;
          }
          else if ( v100 == 0 )
          {
            v99 = v102;
            v5 = v103;
          }
          v105 = (float *)v139;
          v106 = (float *)v138;
          v107 = 1.0;
          v108 = 0;
          v109 = *(float *)(v4 - 31736);
          v110 = *(float *)&qword_60A0E0;
          v111 = *((float *)&qword_60A0E0 + 1);
          v112 = flt_60A0E8;
          v113 = *(float *)(v4 - 31740);
          while ( v108 < 21 )
          {
            v114 = v110 * (float)(v109 * v107);
            v115 = v111 * (float)(v109 * v107);
            v116 = v112 * (float)(v109 * v107);
            v117 = (float *)&v137[3 * v108];
            v118 = *v117;
            v119 = v117[1];
            v120 = v117[2];
            v149 = (float)(v114 + *v117) + v99;
            v150 = (float)(v115 + v119) + v5;
            v151 = v116 + v120;
            v121 = v150;
            v122 = v151;
            *v105 = v149;
            v105[1] = v121;
            v105[2] = v122;
            v146 = v99 + v118;
            v147 = v5 + v119;
            v148 = v120;
            v123 = v147;
            v105[9] = v146;
            v105[10] = v123;
            v105[11] = v120;
            v143 = v99 + v118;
            v144 = v5 + v119;
            v145 = v120;
            *v106 = v143;
            v106[1] = v5 + v119;
            v106[2] = v120;
            v140 = (float)(v118 - v114) + v99;
            v141 = (float)(v119 - v115) + v5;
            v142 = v120 - v116;
            v124 = v141;
            v125 = v142;
            v106[9] = v140;
            v106[10] = v124;
            v106[11] = v125;
            v107 = v107 + v113;
            v108 = (int)v108 + 1;
            v105 += 18;
            v106 += 18;
          }
          sub_410420((int)v139, 42, (int)v126, 2);
          sub_4106A0(4);
          sub_410420((int)v138, 42, (int)v126, 2);
          sub_4106A0(4);
          v100 = (int)v100 + 1;
        }
        break;
      case 1LL:
        v55 = v139;
        v56 = v138;
        if ( v12 >= 2147483600.0 )
          v57 = (int)(float)(v12 - 2147483600.0);
        else
          v57 = (int)v12;
        v58 = v57;
        v59 = 0.0;
        v60 = v11 / 21.0;
        v61 = 0;
        while ( v61 < 21 )
        {
          sub_3764B0(a1, a2, (int)&v137[3 * v61]);
          v59 = v59 - v60;
          v55[12] = *a4;
          v55[13] = a4[1];
          v55[14] = a4[2];
          v55[15] = 0;
          v55[48] = *a4;
          v55[49] = a4[1];
          v55[50] = a4[2];
          v55[51] = v58;
          v56[12] = *a4;
          v56[13] = a4[1];
          v56[14] = a4[2];
          v56[15] = v58;
          v56[48] = *a4;
          v56[49] = a4[1];
          *((_WORD *)v56 + 25) = (unsigned __int8)a4[2];
          v61 = (int)v61 + 1;
          v55 += 72;
          v56 += 72;
        }
        sub_36DE70((int)a1 + 4016 * (int)a2);
        v63 = 0.5 * sub_36DEB0((int)a1 + 4016 * (int)a2);
        v65 = 0;
        v66 = -v64;
        v67 = -v63;
        while ( v65 < 4 )
        {
          switch ( v65 )
          {
            case 3LL:
              v62 = v66;
              v5 = v67;
              break;
            case 2LL:
              v62 = v64;
              v5 = v67;
              break;
            case 1LL:
              v62 = v66;
              v5 = v63;
              break;
            case 0LL:
              v62 = v64;
              v5 = v63;
              break;
            default:
              break;
          }
          v68 = (float *)v139;
          v69 = (float *)v138;
          v70 = 1.0;
          v71 = 0;
          v72 = *(float *)&qword_60A0E0;
          v73 = *((float *)&qword_60A0E0 + 1);
          v74 = flt_60A0E8;
          v75 = *(float *)(v4 - 31740);
          while ( v71 < 21 )
          {
            v76 = v72 * (float)(3.0 * v70);
            v77 = v73 * (float)(3.0 * v70);
            v78 = v74 * (float)(3.0 * v70);
            v79 = (float *)&v137[3 * v71];
            v80 = *v79;
            v81 = v79[1];
            v82 = v79[2];
            v161 = (float)(v76 + *v79) + v62;
            v162 = (float)(v77 + v81) + v5;
            v163 = v78 + v82;
            v83 = v162;
            v84 = v163;
            *v68 = v161;
            v68[1] = v83;
            v68[2] = v84;
            v158 = v62 + v80;
            v159 = v5 + v81;
            v160 = v82;
            v85 = v159;
            v68[9] = v158;
            v68[10] = v85;
            v68[11] = v82;
            v155 = v62 + v80;
            v156 = v5 + v81;
            v157 = v82;
            *v69 = v155;
            v69[1] = v5 + v81;
            v69[2] = v82;
            v152 = (float)(v80 - v76) + v62;
            v153 = (float)(v81 - v77) + v5;
            v154 = v82 - v78;
            v86 = v153;
            v87 = v154;
            v69[9] = v152;
            v69[10] = v86;
            v69[11] = v87;
            v70 = v70 + v75;
            v71 = (int)v71 + 1;
            v68 += 18;
            v69 += 18;
          }
          sub_410420((int)v139, 42, (int)v126, 2);
          sub_4106A0(4);
          sub_410420((int)v138, 42, (int)v126, 2);
          sub_4106A0(4);
          v65 = (int)v65 + 1;
        }
        break;
      case 0LL:
        v13 = v139;
        v14 = v138;
        v15 = *(float *)(v4 - 31744) * v12;
        v16 = 0.0;
        v17 = 0;
        while ( v17 < 21 )
        {
          sub_3764B0(a1, a2, (int)&v137[3 * v17]);
          v16 = v16 - v19;
          v13[12] = *a4;
          v13[13] = a4[1];
          v13[14] = a4[2];
          v20 = v12 * v18;
          if ( (float)(v12 * v18) >= 2147483600.0 )
            v21 = (int)(float)(v20 - 2147483600.0);
          else
            v21 = (int)v20;
          v13[15] = v21;
          v13[48] = *a4;
          v13[49] = a4[1];
          v13[50] = a4[2];
          v22 = v15 * v18;
          if ( (float)(v15 * v18) >= 2147483600.0 )
            v23 = (int)(float)(v22 - 2147483600.0);
          else
            v23 = (int)v22;
          v13[51] = v23;
          v14[12] = *a4;
          v14[13] = a4[1];
          v14[14] = a4[2];
          if ( v22 >= 2147483600.0 )
            v24 = (int)(float)(v22 - 2147483600.0);
          else
            v24 = (int)v22;
          v14[15] = v24;
          v14[48] = *a4;
          v14[49] = a4[1];
          v14[50] = a4[2];
          if ( v20 >= 2147483600.0 )
            v25 = (int)(float)(v20 - 2147483600.0);
          else
            v25 = (int)v20;
          v14[51] = v25;
          v17 = (int)v17 + 1;
          v13 += 72;
          v14 += 72;
        }
        sub_36DE70((int)a1 + 4016 * (int)a2);
        v26 = 0.5 * sub_36DEB0((int)a1 + 4016 * (int)a2);
        for ( i = 0; i < 4; i = (int)i + 1 )
        {
          v29 = (float *)v139;
          v30 = (float *)v138;
          switch ( i )
          {
            case 3LL:
              v50 = 0;
              while ( v50 < 21 )
              {
                v51 = (float *)&v137[3 * v50];
                v52 = *v51;
                v173 = v27 + *v51;
                v53 = v51[1] - v26;
                v174 = v53;
                v54 = v51[2];
                v175 = v54;
                *v29 = v173;
                v29[1] = v53;
                v29[2] = v54;
                v170 = v52;
                v171 = v53;
                v172 = v54;
                v29[9] = v52;
                v29[10] = v53;
                v29[11] = v54;
                v167 = v52;
                v168 = v53;
                v169 = v54;
                *v30 = v52;
                v30[1] = v53;
                v30[2] = v54;
                v164 = v52 - v27;
                v165 = v53;
                v166 = v54;
                v30[9] = v164;
                v30[10] = v53;
                v30[11] = v54;
                v50 = (int)v50 + 1;
                v29 += 18;
                v30 += 18;
              }
              break;
            case 2LL:
              v45 = 0;
              while ( v45 < 21 )
              {
                v46 = (float *)&v137[3 * v45];
                v47 = *v46;
                v185 = v27 + *v46;
                v48 = v26 + v46[1];
                v186 = v48;
                v49 = v46[2];
                v187 = v49;
                *v29 = v185;
                v29[1] = v48;
                v29[2] = v49;
                v182 = v47;
                v183 = v48;
                v184 = v49;
                v29[9] = v47;
                v29[10] = v48;
                v29[11] = v49;
                v179 = v47;
                v180 = v48;
                v181 = v49;
                *v30 = v47;
                v30[1] = v48;
                v30[2] = v49;
                v176 = v47 - v27;
                v177 = v48;
                v178 = v49;
                v30[9] = v176;
                v30[10] = v48;
                v30[11] = v49;
                v45 = (int)v45 + 1;
                v29 += 18;
                v30 += 18;
              }
              break;
            case 1LL:
              v38 = 0;
              while ( v38 < 21 )
              {
                v39 = (float *)&v137[3 * v38];
                v40 = *v39 - v27;
                v197 = v40;
                v41 = v39[1];
                v198 = v41 - v26;
                v42 = v39[2];
                v199 = v42;
                v43 = v198;
                *v29 = v40;
                v29[1] = v43;
                v29[2] = v42;
                v194 = v40;
                v195 = v41;
                v196 = v42;
                v29[9] = v40;
                v29[10] = v41;
                v29[11] = v42;
                v191 = v40;
                v192 = v41;
                v193 = v42;
                *v30 = v40;
                v30[1] = v41;
                v30[2] = v42;
                v188 = v40;
                v189 = v26 + v41;
                v190 = v42;
                v44 = v189;
                v30[9] = v40;
                v30[10] = v44;
                v30[11] = v42;
                v38 = (int)v38 + 1;
                v29 += 18;
                v30 += 18;
              }
              break;
            case 0LL:
              v31 = 0;
              while ( v31 < 21 )
              {
                v32 = (float *)&v137[3 * v31];
                v33 = v27 + *v32;
                v209 = v33;
                v34 = v32[1];
                v210 = v34 - v26;
                v35 = v32[2];
                v211 = v35;
                v36 = v210;
                *v29 = v33;
                v29[1] = v36;
                v29[2] = v35;
                v206 = v33;
                v207 = v34;
                v208 = v35;
                v29[9] = v33;
                v29[10] = v34;
                v29[11] = v35;
                v203 = v33;
                v204 = v34;
                v205 = v35;
                *v30 = v33;
                v30[1] = v34;
                v30[2] = v35;
                v200 = v33;
                v201 = v26 + v34;
                v202 = v35;
                v37 = v201;
                v30[9] = v33;
                v30[10] = v37;
                v30[11] = v35;
                v31 = (int)v31 + 1;
                v29 += 18;
                v30 += 18;
              }
              break;
            default:
              break;
          }
          sub_410420((int)v139, 42, (int)v126, 2);
          sub_4106A0(4);
          sub_410420((int)v138, 42, (int)v126, 2);
          sub_4106A0(4);
        }
        break;
      default:
        break;
    }
    sub_3F6440(2, 68);
    return sub_3F6440(3, 464891);
  }
  return result;
}


// func_00377930  addr 0x00377930  window 1248B
__int64 __fastcall sub_377930(int a1, int a2, __int64 a3, unsigned __int8 *a4, __int64 a5)
{
  float v10; // $f20
  float v11; // $f1
  float v12; // $f0
  float v13; // $f22
  __int64 v14; // $s1
  float v15; // kr00_4
  float v16; // $f2
  float v17; // $f1
  float v18; // $f0
  float v19; // $f21
  __int64 i; // $s0
  float *v21; // $a0
  float v22; // $f23
  float v24; // [sp+70h] [-160h]
  float v25; // [sp+74h] [-15Ch]
  float v26; // [sp+78h] [-158h]
  float v27; // [sp+7Ch] [-154h]
  float v28[3]; // [sp+80h] [-150h] BYREF
  float v29; // [sp+8Ch] [-144h]
  float v30; // [sp+90h] [-140h]
  int v31; // [sp+94h] [-13Ch]
  float v32; // [sp+98h] [-138h]
  float v33; // [sp+9Ch] [-134h]
  int v34; // [sp+A0h] [-130h]
  float v35; // [sp+A4h] [-12Ch]
  float v36; // [sp+A8h] [-128h]
  int v37; // [sp+ACh] [-124h]
  _BYTE v38[264]; // [sp+B0h] [-120h] BYREF
  float v39[4]; // [sp+1B8h] [-18h] BYREF
  __int64 v40; // [sp+1C8h] [-8h] BYREF

  v10 = 1.0 / *(float *)(sub_457120() + 128);
  if ( a3 != 0 )
  {
    v11 = *(float *)(a3 + 4);
    v12 = *(float *)(a3 + 8);
    v39[0] = *(float *)a3;
  }
  else
  {
    v11 = *(float *)(232 * a2 + a1 + 120508);
    v12 = *(float *)(232 * a2 + a1 + 120512);
    v39[0] = *(float *)(232 * a2 + a1 + 120504);
  }
  v39[1] = v11;
  v39[2] = v12;
  v24 = *(float *)(232 * a2 + a1 + 120596);
  v25 = *(float *)(232 * a2 + a1 + 120600);
  v26 = *(float *)(232 * a2 + a1 + 120604);
  v27 = *(float *)(232 * a2 + a1 + 120608);
  v13 = sub_36DE70(a1 + 4016 * a2) / 2.0;
  sub_36DEB0(a1 + 4016 * a2);
  v14 = sub_3E0F80();
  sub_457120();
  v15 = (float)((float)((float)(v25 * v25) + (float)(v24 * v24)) + (float)(v26 * v26)) + (float)(v27 * v27);
  v16 = v24 * (float)(2.0 / v15);
  v17 = v25 * (float)(2.0 / v15);
  v18 = v26 * (float)(2.0 / v15);
  *(float *)v14 = 1.0 - (float)((float)(v25 * v17) + (float)(v26 * v18));
  *(float *)(v14 + 4) = (float)(v24 * v17) + (float)(v18 * v27);
  *(float *)(v14 + 8) = (float)(v26 * v16) - (float)(v17 * v27);
  *(float *)(v14 + 16) = (float)(v24 * v17) - (float)(v18 * v27);
  *(float *)(v14 + 20) = 1.0 - (float)((float)(v26 * v18) + (float)(v24 * v16));
  *(float *)(v14 + 24) = (float)(v25 * v18) + (float)(v16 * v27);
  *(float *)(v14 + 32) = (float)(v26 * v16) + (float)(v17 * v27);
  *(float *)(v14 + 36) = (float)(v25 * v18) - (float)(v16 * v27);
  *(float *)(v14 + 40) = 1.0 - (float)((float)(v24 * v16) + (float)(v25 * v17));
  *(_DWORD *)(v14 + 48) = 0;
  *(_DWORD *)(v14 + 52) = 0;
  *(_DWORD *)(v14 + 56) = 0;
  *(_DWORD *)(v14 + 12) = 3;
  sub_3E0C90(v14, (int)v39, 2);
  v28[0] = v13;
  v28[1] = v19;
  v28[2] = 0.0;
  v29 = -v13;
  v30 = v19;
  v31 = 0;
  v32 = v13;
  v33 = -v19;
  v34 = 0;
  v35 = v29;
  v36 = v33;
  v37 = 0;
  for ( i = 0; i < 4; i = (int)i + 1 )
  {
    sub_3E42A0((int)v39, (int)&v28[3 * i], v14);
    sub_3717E0((int)v39, (int)&v40);
    v21 = (float *)&v38[64 * (_DWORD)i];
    *(_QWORD *)v21 = v40;
    v21[2] = v22;
    v21[8] = (float)*a4;
    v21[9] = (float)a4[1];
    v21[10] = (float)a4[2];
    v21[11] = (float)a4[3];
    v21[6] = v10;
  }
  dword_887300(1, 0);
  if ( a5 != 0 && a4[3] == 255 )
    sub_364C50();
  dword_887310(4, (int)v38, 4);
  if ( a5 != 0 && a4[3] == 255 )
    sub_364C70();
  return sub_3E0F40(v14);
}


// func_00377eb0  addr 0x00377eb0  window 800B
__int64 __fastcall sub_377EB0(__int64 a1, __int64 a2)
{
  int v2; // $gp
  __int64 v3; // $ra
  __int64 v6; // $s1
  __int64 v7; // $s0
  __int64 i; // $a1
  float *v9; // $v0
  int v10; // $a0
  float v11; // $f1
  float v12; // $f0
  char *v13; // $v0
  __int64 j; // $a1
  float *v15; // $v0
  int v16; // $a0
  float v17; // $f1
  float v18; // $f0
  char *v19; // $v0
  _QWORD v21[2]; // [sp+0h] [-B0h] BYREF
  __int64 v22; // [sp+30h] [-80h]
  int v23; // [sp+40h] [-70h]
  int v24; // [sp+44h] [-6Ch]
  int v25; // [sp+48h] [-68h]
  int v26; // [sp+4Ch] [-64h]
  int v27; // [sp+50h] [-60h]
  int v28; // [sp+54h] [-5Ch]
  int v29; // [sp+58h] [-58h]
  int v30; // [sp+5Ch] [-54h]
  float v31; // [sp+60h] [-50h] BYREF
  float v32; // [sp+64h] [-4Ch]
  int v33; // [sp+68h] [-48h]
  float v34; // [sp+6Ch] [-44h]
  float v35; // [sp+70h] [-40h]
  int v36; // [sp+74h] [-3Ch]
  float v37; // [sp+78h] [-38h]
  float v38; // [sp+7Ch] [-34h]
  int v39; // [sp+80h] [-30h]
  float v40; // [sp+84h] [-2Ch]
  float v41; // [sp+88h] [-28h]
  int v42; // [sp+8Ch] [-24h]
  float v43; // [sp+90h] [-20h]
  float v44; // [sp+94h] [-1Ch]
  float v45; // [sp+98h] [-18h]
  float v46; // [sp+A0h] [-10h]
  float v47; // [sp+A4h] [-Ch]
  float v48; // [sp+A8h] [-8h]

  v22 = v3;
  nullsub_7((unsigned int)aBtlshuffledraw, 1900);
  v6 = dword_8873F4(1, 576, 0x40000);
  if ( v6 == 0 )
    nullsub_8((unsigned int)aBtlshuffledraw, 1901);
  v7 = sub_451FC0(a1, (unsigned int)aBattleShuffleA, 18, 0, 0, (unsigned int)sub_377E10, (unsigned int)sub_377E60, v6);
  if ( v7 == 0 )
    nullsub_8((unsigned int)aBtlshuffledraw, 1911);
  sub_3781D0(v7, a2);
  sub_378260(v7, 255, 255, 255, 0);
  v31 = -30.0;
  v32 = *(float *)(v2 - 31776);
  v33 = 0;
  v27 = 1065222144;
  v23 = 0;
  v34 = 30.0;
  v35 = v32;
  v36 = 0;
  v28 = 0;
  v24 = 0;
  v37 = v31;
  v38 = -v32;
  v39 = 0;
  v29 = 1065222144;
  v25 = 1059389440;
  v40 = 30.0;
  v41 = v38;
  v42 = 0;
  v30 = 0;
  v26 = 1059389440;
  for ( i = 0; i < 4; i = (int)i + 1 )
  {
    v9 = &v31 + 3 * i;
    v46 = *v9;
    v47 = v9[1];
    v48 = v9[2];
    v10 = v6 + 36 * i;
    v11 = v47;
    v12 = v48;
    *(float *)(v10 + 288) = v46;
    *(float *)(v10 + 292) = v11;
    *(float *)(v10 + 296) = v12;
    *(_BYTE *)(v10 + 300) = -1;
    *(_BYTE *)(v10 + 301) = -1;
    *(_BYTE *)(v10 + 302) = -1;
    *(_BYTE *)(v10 + 303) = -1;
    v13 = (char *)v21 + 4 * i;
    *(_DWORD *)(v10 + 316) = *((_DWORD *)v13 + 20);
    *(_DWORD *)(v10 + 320) = *((_DWORD *)v13 + 16);
  }
  v31 = 30.0;
  v32 = *(float *)(v2 - 31776);
  v33 = 0;
  v27 = 1065222144;
  v23 = 0;
  v34 = -30.0;
  v35 = v32;
  v36 = 0;
  v28 = 0;
  v24 = 0;
  v37 = 30.0;
  v38 = -v32;
  v39 = 0;
  v29 = 1065222144;
  v25 = 1059389440;
  v40 = v34;
  v41 = v38;
  v42 = 0;
  v30 = 0;
  v26 = 1059389440;
  for ( j = 0; j < 4; j = (int)j + 1 )
  {
    v15 = &v31 + 3 * j;
    v43 = *v15;
    v44 = v15[1];
    v45 = v15[2];
    v16 = v6 + 36 * j;
    v17 = v44;
    v18 = v45;
    *(float *)(v16 + 432) = v43;
    *(float *)(v16 + 436) = v17;
    *(float *)(v16 + 440) = v18;
    *(_BYTE *)(v16 + 444) = -1;
    *(_BYTE *)(v16 + 445) = -1;
    *(_BYTE *)(v16 + 446) = -1;
    *(_BYTE *)(v16 + 447) = -1;
    v19 = (char *)v21 + 4 * j;
    *(_DWORD *)(v16 + 460) = *((_DWORD *)v19 + 20);
    *(_DWORD *)(v16 + 464) = *((_DWORD *)v19 + 16);
  }
  return v7;
}


// func_00378280  addr 0x00378280  window 640B
void __fastcall sub_378280(int a1, char a2)
{
  int v2; // $gp
  int v3; // $a0
  float v4; // $f6
  float v5; // $f5
  __int64 i; // $a1
  __int64 v7; // $a4
  int v8; // $a2
  float v9; // $f4
  int v10; // $a2
  float v11; // $f4
  _BYTE *v12; // $a7
  float v13; // $f0
  char v14; // $a2
  float v15; // $f0
  char v16; // $a2
  float v17; // $f0
  int v18; // $a2

  v3 = *(_DWORD *)(a1 + 56);
  *(_BYTE *)(v3 + 287) = a2;
  if ( *(_DWORD *)(v3 + 4) != 0 )
  {
    v4 = *(float *)(v2 - 31992);
    v5 = *(float *)(v2 - 32232);
  }
  else
  {
    v4 = 0.0;
    v5 = 0.0;
  }
  for ( i = 0; i < 4; i = (int)i + 1 )
  {
    v7 = 3 - (int)i;
    v8 = (int)v7 >> 1;
    if ( v7 < 0 )
      v8 = ((int)v7 + 1) >> 1;
    v9 = (float)v8;
    v10 = (3 - (_BYTE)i) & 1;
    if ( v7 < 0 && ((3 - (_BYTE)i) & 1) != 0 )
      v10 -= 2;
    v11 = (float)((float)(1.0 + 0.0) - (float)(v4 * (float)v10)) - (float)(v5 * v9);
    v12 = (_BYTE *)(v3 + 36 * i);
    v13 = (float)*(unsigned __int8 *)(v3 + 284) * v11;
    if ( v13 >= 2147483600.0 )
      v14 = (int)(float)(v13 - 2147483600.0);
    else
      v14 = (int)v13;
    v12[300] = v14;
    v15 = (float)*(unsigned __int8 *)(v3 + 285) * v11;
    if ( v15 >= 2147483600.0 )
      v16 = (int)(float)(v15 - 2147483600.0);
    else
      v16 = (int)v15;
    v12[301] = v16;
    v17 = (float)*(unsigned __int8 *)(v3 + 286) * v11;
    if ( v17 >= 2147483600.0 )
      v18 = (int)(float)(v17 - 2147483600.0);
    else
      LOBYTE(v18) = (int)v17;
    v12[302] = v18;
    v12[303] = *(_BYTE *)(v3 + 287);
    v12[444] = -1;
    v12[445] = -1;
    v12[446] = -1;
    v12[447] = *(_BYTE *)(v3 + 287);
  }
}

