/*
 * Generated by tools/ghidra_headstart.py -- Ghidra decompiler output.
 *
 * REFERENCE ONLY. This is not valid C and is never compiled.
 *
 * Ghidra pseudo-types (`undefined1 [16]`, `undefined4`, `code *`, `uint`,
 * `ulong`) and its `FUN_xxxxxxxx` / `DAT_xxxxxxxx` naming are decompiler
 * artifacts -- translate them into the project's own conventions
 * (s8/u8/s16/u16/s32/u32/s64/u64/f32 and the real func_xxxxxxxx names)
 * before writing any source.
 *
 * Why this corpus exists: Ghidra's Emotion Engine support models the PS2's
 * 128-bit register file and VU0 macro-mode ops (you will see
 * `undefined1 auVar [16]` and intrinsics like `_sqc2(...)`), where Hex-Rays
 * emits an opaque `__asm { }` island that hides the surrounding dataflow.
 * For ordinary integer code the Hex-Rays corpus in docs/ida_headstart is
 * usually the easier read. Use whichever is clean for your target; when both
 * are, cross-check them against each other and against the retail
 * disassembly from build/RECON_dis.py.
 *
 * Regenerate: python3 tools/ghidra_headstart.py --report <verify json>
 */


// func_001eca10  addr 0x001eca10  window 976B
int FUN_001eca10(int param_1,int param_2)

{
  undefined4 uVar1;
  bool bVar2;
  long lVar3;
  long lVar4;
  int iVar5;
  int iVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  float fVar10;
  float fStack_8;
  float fStack_4;
  
  iVar7 = 0;
  iVar8 = *(int *)(iGpffffb3ac + 0x318);
  do {
    if ((iVar8 == 0) || (iVar7 != 0)) {
      return iVar7;
    }
    for (iVar5 = 0; iVar5 < 4; iVar5 = iVar5 + 1) {
      iVar6 = iVar8 + iVar5 * 0x130;
      if (((0.0 < *(float *)(iVar6 + 0x1c)) && (iVar9 = iVar6 + 8, iVar9 != param_1)) &&
         (iVar9 != param_2)) {
        fStack_8 = *(float *)(iVar6 + 0x10) - *(float *)(param_1 + 8);
        fStack_4 = *(float *)(iVar6 + 0x14) - *(float *)(param_1 + 0xc);
        fVar10 = (float)FUN_003e41b0(&fStack_8);
        if (1.0 <= fVar10) {
          fStack_8 = *(float *)(iVar6 + 0x10) - *(float *)(param_2 + 8);
          fStack_4 = *(float *)(iVar6 + 0x14) - *(float *)(param_2 + 0xc);
          fVar10 = (float)FUN_003e41b0(&fStack_8);
          if (1.0 <= fVar10) {
            iVar6 = iVar8 + iVar5 * 0x130;
            uVar1 = *(undefined4 *)(iVar6 + 0x18);
            iVar6 = iVar6 + 8;
            lVar3 = FUN_001ecde0(iVar6,uVar1,param_1 + 8);
            lVar4 = FUN_001ecde0(iVar6,uVar1,param_2 + 8);
            if (lVar3 == lVar4) {
              bVar2 = false;
            }
            else {
              lVar3 = FUN_001ecde0(param_1 + 8,param_2 + 8,iVar9);
              lVar4 = FUN_001ecde0(param_1 + 8,param_2 + 8,uVar1);
              if (lVar3 == lVar4) {
                bVar2 = false;
              }
              else {
                bVar2 = true;
              }
            }
            if (bVar2) {
              iVar7 = 1;
              break;
            }
          }
        }
      }
    }
    if (iVar7 == 0) {
      if ((((*(float *)(param_1 + 8) <= *(float *)(iVar8 + 8)) ||
           (*(float *)(param_1 + 0xc) <= *(float *)(iVar8 + 0xc))) ||
          ((*(float *)(iVar8 + 0x268) <= *(float *)(param_1 + 8) ||
           (*(float *)(iVar8 + 0x26c) <= *(float *)(param_1 + 0xc))))) &&
         (((*(float *)(param_2 + 8) <= *(float *)(iVar8 + 8) ||
           (*(float *)(param_2 + 0xc) <= *(float *)(iVar8 + 0xc))) ||
          ((*(float *)(iVar8 + 0x268) <= *(float *)(param_2 + 8) ||
           (*(float *)(iVar8 + 0x26c) <= *(float *)(param_2 + 0xc))))))) {
        for (iVar5 = 0; iVar5 < 4; iVar5 = iVar5 + 1) {
          iVar6 = iVar8 + (iVar5 + 1U & 3) * 0x130 + 8;
          iVar9 = iVar8 + iVar5 * 0x130 + 8;
          lVar3 = FUN_001ecde0(iVar9,iVar6,param_1 + 8);
          lVar4 = FUN_001ecde0(iVar9,iVar6,param_2 + 8);
          if (lVar3 == lVar4) {
            bVar2 = false;
          }
          else {
            lVar3 = FUN_001ecde0(param_1 + 8,param_2 + 8,iVar9);
            lVar4 = FUN_001ecde0(param_1 + 8,param_2 + 8,iVar6);
            if (lVar3 == lVar4) {
              bVar2 = false;
            }
            else {
              bVar2 = true;
            }
          }
          if (bVar2) {
            iVar7 = 1;
            break;
          }
        }
      }
    }
    iVar8 = *(int *)(iVar8 + 0x4cc);
  } while( true );
}

